### ISSUE TITLE
TypeScript definition file

### ISSUE THREAD

**Issue by tvq** [marionettejs/backbone.marionette#1037]
It would be extremely nice, if the TypeScript definition file was up to date. 
( https://github.com/borisyankov/DefinitelyTyped/tree/master/marionette )

**Comment by tinymammothdesign** [comment]
+1 to Type Definitions!

**Comment by corford** [comment]
+1 from me for a TS definition file

**Comment by ryanluker** [comment]
+1

**Comment by agwidarsito** [comment]
Is anyone working on this? Perhaps a few of us can commit (pun intended) and get it developed between us?

**Comment by thejameskyle** [comment]
The definitely typed people seem to be doing a better job than anyone on the Marionette team would be able to do. I'd rather leave it up to them.

**Comment by samccone** [comment]
I agree, this is the best place to look
https://github.com/borisyankov/DefinitelyTyped/blob/master/marionette/marionette.d.ts

**Comment by ildarnm** [comment]
+1
