### ISSUE TITLE
Marionette custom build

### ISSUE THREAD

**Issue by yamsellem** [marionettejs/backbone.marionette#1118]
Marionette is branded as a “collection of common design and implementation patterns”.

While it is a "all or nothing" download for the moment, allowing to download separate parts (including their dependencies) — like twittter.bootstrap does — would be a wonder.

**Comment by jshthornton** [comment]
I +1 this idea.
To me I intend to use a lot of micro libraries to build a web application.
For instance I might use Virtual DOM for templating, Immutables and Stores (LokiJS) for models and collections, and PubSub.js for the event bus.

But something that Marionette is unrivaled at is a great View system.

**Comment by yamsellem** [comment]
@jshthornton If you like small libraries with one purpose, you may take a look to [Ampersand](http://ampersandjs.com). It shares the common patterns of Marionette, but with a component state of mind (and it trades Marionette's deprecated Controller & Module for a useful State).

**Comment by stephanebachelier** [comment]
@yamsellem interesting ;)
Le mar. 30 juin 2015 à 11:32, amsellem yves <notifications@github.com> a
écrit :
