### ISSUE TITLE
rethink marionette router

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#1177]
Currently the Marionette Router is lacking in multiple ways
- No filters
  - before
  - after
  - around?
- Single controller limitation
  - pre route controller
- No concept of state decoupled from the URL

For marionette to continue to grow this is going to be a critical problem that we need to solve.

Take a peak at this https://github.com/angular-ui/ui-router for a great example of what a router should do.

Previous Issues:
- #259 for filters
- #773 for better controller methods
- #62 nested and inherited routes (angular ui style)

**Comment by newtonianb** [comment]
ping @brian-mann message from Apr 15, 2014, that all sounds incredible! is it ready to show?

**Comment by urosgruber** [comment]
@brian-mann any news on this gistm even if it's just WIP.
