### ISSUE TITLE
Rename `render:collection` => `render:children`

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#1309]
Because you're rendering the children not the collection

**Comment by ianmstew** [comment]
See https://github.com/marionettejs/backbone.marionette/pull/2730#issuecomment-139792426.  I argue that `render` should 1:1 imply `render:children` and therefore eliminate the necessity for it altogether.  Same with `destroy` and `destroy:children`.  I don't see the value add of discriminating between rendering the entire view and rendering its children once without a CompositeView (#2268).

**Comment by paulfalgout** [comment]
I think I am in agreement..  Particularly about making the destroy
private..  But we would need to absolutely commit to axing composite
view..  What does composite view do that can't be done with collection view
and replace El?

**Comment by ianmstew** [comment]
The _only_ thing that I'm aware a CompositeView does that a nested CollectionView has difficulty doing is possibly re-rendering the entire CompositeView on `reset` (#2719).

**Comment by ianmstew** [comment]
Fixed by #2730
