### ISSUE TITLE
Tests Cleanup

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#1447]
**Current Progress:**

> Checked = Merged
> Linked = Opened PR
> Unlinked = Unstarted 

- [x] [appRouter](https://github.com/marionettejs/backbone.marionette/pull/1412)
- [x] [application.appRegions](https://github.com/marionettejs/backbone.marionette/pull/1397)
- [x] [application](https://github.com/marionettejs/backbone.marionette/pull/1411)
- [x] [behaviors](https://github.com/marionettejs/backbone.marionette/pull/1413)
- [x] [bindEntityEvents](https://github.com/marionettejs/backbone.marionette/pull/1414)
- [x] [callbacks](https://github.com/marionettejs/backbone.marionette/pull/1415)
- [x] [collectionView.attachToDOM](https://github.com/marionettejs/backbone.marionette/pull/1416)
- [x] [collectionView.emptyView](https://github.com/marionettejs/backbone.marionette/pull/1417)
- [x] [collectionView.itemViewOptions](https://github.com/marionettejs/backbone.marionette/pull/1418)
- [x] [collectionView.reset](https://github.com/marionettejs/backbone.marionette/pull/1419)
- [ ] collectionView
- [x] [commands](https://github.com/marionettejs/backbone.marionette/pull/1420)
- [x] [compositeView-childViewContainer](https://github.com/marionettejs/backbone.marionette/pull/1462)
- [x] [compositeView.onBeforeRender](https://github.com/marionettejs/backbone.marionette/pull/1422)
- [ ] compositeView
- [x] [controller](https://github.com/marionettejs/backbone.marionette/pull/1423)
- [x] [destroyingViews](https://github.com/marionettejs/backbone.marionette/pull/1424)
- [x] [getOption](https://github.com/marionettejs/backbone.marionette/pull/1425)
- [x] [itemView](https://github.com/marionettejs/backbone.marionette/pull/1460)
- [ ] layoutView.dynamicRegions
- [ ] layoutView
- [x] [mixinUnderscoreCollection](https://github.com/marionettejs/backbone.marionette/pull/1426)
- [ ] module
- [ ] module.stop
- [x] [normalizeMethods](https://github.com/marionettejs/backbone.marionette/pull/1427)
- [x] [onDomRefresh](https://github.com/marionettejs/backbone.marionette/pull/1428)
- [x] [precompiledTemplateRendering](https://github.com/marionettejs/backbone.marionette/pull/1429)
- [ ] region
- [ ] regionManager
- [x] [renderer](https://github.com/marionettejs/backbone.marionette/pull/1431)
- [x] [requestResponse](https://github.com/marionettejs/backbone.marionette/pull/1432)
- [x] [sortedViews](https://github.com/marionettejs/backbone.marionette/pull/1463)
- [x] [templateCache](https://github.com/marionettejs/backbone.marionette/pull/1433)
- [x] [templateHelpers](https://github.com/marionettejs/backbone.marionette/pull/1438)
- [x] [triggerMethod](https://github.com/marionettejs/backbone.marionette/pull/1439)
- [x] [unbindEntityEvents](https://github.com/marionettejs/backbone.marionette/pull/1453)
- [x] [view.entityEvents](https://github.com/marionettejs/backbone.marionette/pull/1454)
- [x] [view](https://github.com/marionettejs/backbone.marionette/pull/1455)
- [x] [view.triggers](https://github.com/marionettejs/backbone.marionette/pull/1457)
- [x] [view.uiBindings](https://github.com/marionettejs/backbone.marionette/pull/1458)
- [x] [view.uiEventAndTriggers](https://github.com/marionettejs/backbone.marionette/pull/1459)

---

**Please, no one touch this checklist except me.**

**Comment by samccone** [comment]
anyone interested in picking this up we are so so close

**Comment by thejameskyle** [comment]
Closing this as part of cleaning out old issues. Feel free to reopen this.
