### ISSUE TITLE
CollectionView Automatic Rendering should support the `unshift` method.

### ISSUE THREAD

**Issue by bgaillard** [marionettejs/backbone.marionette#1475]
The CollectionView documentation explains that each time an attached collection `add`, `remove`, `reset` method is called the view is updated. 

I encounter problems on collections where the elements are added at the beginning of the collection (this is very frequent when you have to display comments like the Facebook Comment Widget, when somebody add a comment its added at the beginning). 

Each time I add an item in my collection using the Backbone [`unshift`](http://backbonejs.org/#Collection-unshift) method the CollectionView add the associated ItemView after the already rendered ItemViews. 

I think it would be great to also have Automatic Rendering with the `unshift` method.

**Comment by vernondegoede** [comment]
@ahumphreys87 Has this ever been released? At the moment I don't see `unshift` support anywhere. I checked both `master` and `next` branch.

**Comment by ahumphreys87** [comment]
It should be caught by the default add event

**Comment by vernondegoede** [comment]
This doesn't seem to be the case. For now, I'm using the following piece of code to update my view, but the view doesn't get rendered. I need to call `render()` manually on the view which renders everything instead of just the added items.

My code:
```
// The collection of productListView is 
this.productsListView.collection.addVariants(variants.toJSON());
```

```
Entities.VariantCollection = Backbone.Collection.extend({
  addVariants: function (variants, position) {
    if (variants.length > 0) {
      // Add variants as first items to our collection
      this.unshift(variants);

      // Emit a custom event signaling items have been added.
      // Useful for not responding to add until all items have been added.
      this.trigger('add:completed', this);
    }
   }
});
```

**Comment by scott-w** [comment]
How are you instantiating `productsListView` and binding `productsListView.collection`? You need to either:

1. Bind it on instantiation `new ProductsListView({collection: myCollection});`
2. Bind it in the `constructor` method for your view.
