### ISSUE TITLE
Uncaught ViewDestroyedError: Cannot use a view thats already been destroyed

### ISSUE THREAD

**Issue by massimopalmieri** [marionettejs/backbone.marionette#1510]
I'm trying to update to version 2.0.1, I don't know if I'm doing something wrong or it's just a bug. My view looks more or less like this:

```
MyView = Marionette.ItemView.extend({
    template: '#my-template',

    events: {
        'click .btn': 'save'
    },

    save: function () {
        this.collection.each(function (model) {
            model.save({
                start: 'date...',
                end: 'another date...'
            });
        });
    }
});
```

When I click on the `.btn` I get this error `Uncaught ViewDestroyedError: Cannot use a view thats already been destroyed`, but the view is still there, it's not been destroyed.

**Comment by wuservices** [comment]
@massimopalmieri I was having a similar error and .listenTo fixed it for me. Thanks!

**Comment by leandronsp** [comment]
👍 `@listenTo` thanks a lot
