### ISSUE TITLE
View/Behavior constructor/initialize order

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#1579]
Right now View/Behavior constructor/initialize methods run in this order:
- Behavior::constructor
- Behavior::initialize
- View::constructor
- View::initialize

I think this would be the ideal order:
- Behavior::constructor
- View::constructor
- Behavior::initialize
- View::initialize

https://github.com/marionettejs/backbone.marionette/blob/master/src/marionette.view.js#L19-L23
https://github.com/marionettejs/backbone.marionette/blob/master/src/marionette.behavior.js#L28

``` js
// View::constructor
if (_.isObject(this.behaviors)) {
  new Marionette.Behaviors(this); // < calls Behavior::initialize
}

Backbone.View.apply(this, arguments);
```

I think we should remove the explicit initialize call and add it to the the wrapped methods list:

``` diff
// marionette.behavior.js
- this.initialize.apply(this, arguments);

// marionette.behaviors.js
 Behaviors.wrap(view, behaviors, [
+  'initialize',
   'bindUIElements', 'unbindUIElements',
   'delegateEvents', 'undelegateEvents',
   'behaviorEvents', 'triggerMethod',
   'setElement', 'destroy'
 ]);
```

**Comment by MeoMix** [comment]
Hey,

It doesn't look like this change ever landed? I'm trying out v3 right now and I'm not able to access "el" from a behavior's initialize.

**Comment by paulfalgout** [comment]
@marionettejs/marionette-core we might want to consider this.

How about:

```js
const View = Backbone.View.extend({

  constructor(options) {
    this.render = _.bind(this.render, this);
    
    // no longer a need for this
    // this._setOptions(options);

    monitorViewEvents(this);

    const viewInitialize = this.initialize;
    this.initialize = function() {
      this._initBehaviors();
      this._initRegions();
      viewInitialize.apply(this, arguments);
    };

    Backbone.View.prototype.constructor.call(this, this.options);

    this.initialize = viewInitialize;

    this.delegateEntityEvents();
  },
```

**Comment by paulfalgout** [comment]
😿 
So nope:

```js
var View = Backbone.View = function(options) {
    this.cid = _.uniqueId('view');
    _.extend(this, _.pick(options, viewOptions));

// For this to work we need to call _initBehaviors here.

    this._ensureElement();
    this.initialize.apply(this, arguments);
  };
```

Otherwise the `events` hash isn't correct for `_ensureElement`

I don't think there's a great way to do this.. however you can use `getOption` in `v3` in a behavior `initialize` and that should get you the passed in option or the one on the definition.

@MeoMix thoughts?

**Comment by jgerigmeyer** [comment]
Is there a recommended answer to @MeoMix's question (https://github.com/marionettejs/backbone.marionette/issues/1579#issuecomment-200581247)? That is, for a `behavior` to do something initially that requires access to the `view.el`?

**Comment by paulfalgout** [comment]
I think the best way to handle this is for the behavior to wait for a render event.  The place where the behavior needs to initialize in the view for this to work is in the middle of the backbone view constructor.. so barring removing dependence on Backbone.View entirely, I don't see a solution where this works in `initialize`
