### ISSUE TITLE
CollectionView / CompositeView should have an optional filter method

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#1596]
Collections have a comparator, and we now respect that in the view layer. However the next most common tasks for lists is to filter / reduce the set of results shown to the user.

There are currently several strategies, such as resetting with a new collection, using a third party plugin like backbone filtered collection, or to hack into `addChildView`.

We should provide a formal way for people to do this to remove the burden from the developer.

```js
Marionette.CollectionView.extend({
  filter/omit/where: function(model, ChildView, index) {
    return true / false
  }
})
```

* https://github.com/marionettejs/backbone.marionette/issues/183
* https://github.com/marionettejs/backbone.marionette/issues/835

**Comment by cmaher** [comment]
Resolved by #1596

**Comment by betovelandia** [comment]
Just saved my day with this, thanks @cmaher

**Comment by samccone** [comment]
its a dream

**Comment by jackocnr** [comment]
Loving this feature guys, thanks! Some feedback for my particular use case:

1) I feel like I need some kind of re-filter option for when I change a model in such a way that would affect the filtering. So currently we automatically update the collectionView for adding and removing models from the collection, but if you change an attribute on a model that would mean that it would get filtered differently, nothing happens. One workaround is to re-render the whole collectionView but I'd rather not do that. The workaround I'm currently using is to remove the model from the collection and then re-add it.

2) I'd like to be able to display a count at the top of the collectionView. One flexible way to solve this would be to make the filtered models available to the view instance e.g. `onRender: function() { this.filteredModels.length... }`

**Comment by MaffooBristol** [comment]
This is cool, but why's this feature not also implemented in CompositeViews?

**Comment by paulfalgout** [comment]
@MaffooBristol I would assume this works for `CompositeView` as a `CompositeView` just extends the `CollectionView`

**Comment by samccone** [comment]
yep it works just find in CompositeViews

https://github.com/tastejs/todomvc/blob/master/examples/backbone_marionette/js/TodoMVC.TodoList.Views.js#L81-L106

**Comment by MaffooBristol** [comment]
Oh god I needed to upgrade my version of Marionette. I'm a :lemon:, sorry

**Comment by samccone** [comment]
hey no problem :fish:
