### ISSUE TITLE
RegionManager addRegion should allow regionClass with options

### ISSUE THREAD

**Issue by jfairbank** [marionettejs/backbone.marionette#1609]
In PR #1602, I thought of a use case for `Region.buildRegion` where I would expect this to work:

```javascript
var app = new Marionette.Application();

var FooRegion = Marionette.Region.extend({
  el: '#foo-region'
});

app.addRegions({
  fooRegion: {
    regionClass: FooRegion,
    fooOption: 'bar'
  }
});

this.app.fooRegion instanceof FooRegion; //=> true
this.app.fooRegion.options.fooOption;    //=> 'bar'
```

When I made sure that adding a region like that would work in `buildRegion` and ran my new test for it, I discovered it in fact did not work and my `fooRegion` just equaled the object I passed into `addRegions`.  I dug deeper and discovered that `RegionManager#addRegion`, which `addRegions` eventually calls in the stack, does not work as intended if the region configuration object does not include a `selector` property ([reference](https://github.com/marionettejs/backbone.marionette/blob/v2.0.1/src/marionette.regionManager.js#L44-L50)).

All that to say, I feel this should be a supported way to define a region for Application (and LayoutView too).

**Comment by webmustang** [comment]
Add this feature to docs, please

**Comment by paulfalgout** [comment]
which part?  It is a little outdated.. RegionManager is gone and Application only has a single region now.. and it currently doesn't take a Region definition like regions on a View.  https://github.com/marionettejs/backbone.marionette/issues/2955
