### ISSUE TITLE
Issue with Browserify: "Cannot read property 'Deferred' of undefined "

### ISSUE THREAD

**Issue by lsimoneau** [marionettejs/backbone.marionette#1719]
`require`ing Marionette in a browserify build results in that error when the page is loaded. It seems like `Backbone.$` is undefined, so I've tried to work around it (I've seen this done in a few places):

``` coffee
Backbone = require('backbone')
Backbone.$ = require('jquery')

require('backbone.marionette')
```

But this still gives me the same error, and I'm not sure why. It must have worked for some other people at some point, since there are examples of this exact code elsewhere online: https://github.com/monzou/backbone.marionette.example/blob/master/app/src/vendor.coffee

Anyone familiar with this have any ideas what I might be doing wrong? Or has something changed that makes this not work anymore?

**Comment by rossfishkind** [comment]
For anyone viewing this thread as of June 18, 2015, the issue has been resolved with an update to Marionette v2.4.2.

**Comment by samccone** [comment]
👍

**Comment by paulfalgout** [comment]
Some clarification here is that it is v2.4.2 in combination with backbone 1.2.x
