### ISSUE TITLE
Create all of the jsdoc Files

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#1756]
#### Classes
- [x] application  (@jasonLaster)
- [ ] approuter {[stubbed version](https://github.com/ChetHarrison/backbone.marionette/commit/7fc36349e05b6850f71f57f5db6d870861dd700f)}
- [ ] behavior   {has a template}
- [ ] collectionview    {has a template} (@joshbedo)
- [ ] compositeview    {has a template}
- [x] controller (@benfenton)
- [x] itemview    {has a template} (@bendman)
- [x] layoutview (@jdaudier)
- [ ] module {[stubbed version](https://github.com/ChetHarrison/backbone.marionette/commit/7fc36349e05b6850f71f57f5db6d870861dd700f)}
- [ ] object (@fabiii21)
- [x] region (@jasonLaster)
- [x] regionManager (@jdaudier)
- [ ] view {has a template} (@jdaudier)

#### Functions
- [x] helpers (@moimikey)
- [ ] renderer
- [x] bindEntityEvents (@moimikey)
- [ ] domRefresh
- [x] triggermethod (@moimikey)
- [ ] templatecache
- [ ] behaviors
- [ ] callbacks

Nice docs for inspiration: https://github.com/PharkMillups/beautiful-docs

**Comment by samccone** [comment]
globbing #1757 in here

**Comment by samccone** [comment]
globbing #1973 in here

**Comment by samccone** [comment]
globbing #1927 in here

**Comment by samccone** [comment]
globbing #1941 in here

**Comment by samccone** [comment]
globbing #1942 in here

**Comment by paulfalgout** [comment]
This is on the backburner.. if someone wants to champion it again for v3, let's reopen it.
