### ISSUE TITLE
Can't use debugger statements when developing

### ISSUE THREAD

**Issue by joshbedo** [marionettejs/backbone.marionette#1786]
I was just working on my first issue to get my toes wet and noticed when you run `grunt watch` it complains about debugger breakpoints and gives the following message

```
Running "jshint:marionette" (jshint) task

   src/marionette.collectionview.js
    147 |    debugger;
             ^ Forgotten 'debugger' statement?

>> 1 error in 21 files
Warning: Task "jshint:marionette" failed. Use --force to continue.
Aborted due to warnings.
```

I think it would be great if the `grunt` and `grunt watch` command ignored debugger statements because i consider that part of the development process. Then when you run `grunt production` it checks for debugger statements and throws that error. This would allow you to use it for development but ensure that it doesn't get pushed out into the codebase. I personally like to walk through tests/code and see how things are working as well as output functions to see how things are connected so i find debugger really helpful. 

Any thoughts?

**Comment by c0debreaker** [comment]
This is awesome @r34ch ! It worked for me. :)

/*jshint -W087 */
