### ISSUE TITLE
Marionette.deprecate

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#1792]
Exhilarated by his day of hacking with fellow Marionetters at the offices of the Hook and of the Loop, and a glass or two of wine, @thejameskyle was prepared to stay up all through the night slaving away on ways of improving the framework for all.

He thought and he thought, and he thought some more. He spoke to his dear friend @jasonLaster about how much the `App.module` method overloading "sucked". And then it came to him!

Deprecation warnings! Of course! A perfect way of informing their community inline how they should be preparing their apps for future breaking changes.

```js
Marionette.deprecate('x will be replaced by y soonerishingly.', testCase);
```
Brilliant! But what would this output? Ah, yes! A nice stack trace of course!
```
DEPRECATION: x will be replaced by y soonerishingly.
    at myPublicMethod (http://example.com/app.js:52:16)
    at _myPrivateMethod (http://example.com/app.js:56:5)
    at http://example.com/app.js:60:3
    at window.onload (http://example.com/app.js:61:2) 
```

The people saw this, and oh how they wanted it. They cried out, "But @thejameskyle, that must be incredibly difficult to do!"

@thejameskyle Smiled at them and said, "Oh dear child, fear not, for I have the solution."

```js
Marionette.deprecate = function(message, test) {
  if (test === undefined || !test) {
    var error = new Marionette.Error({
      name: 'DEPRECATION',
      message: message
    });
    error.captureStackTrace(Marionette.deprecate);
    console.warn(error.stack);
  }
};
```

> See [Demo](http://jsfiddle.net/thejameskyle/7c7sLrev/).

Cordially,
@thejameskyle

**Comment by megawac** [comment]
I think we should start creating 3 builds:

- Debug: has stuff like `deprecate` and other logging
- Production
- Production Minified

**Comment by jmeas** [comment]
That's 6 builds when we have core and bundled :(

**Comment by jasonLaster** [comment]
i agree - i think debug could be dev, but yea. that'd be nice

**Comment by paulfalgout** [comment]
@samccone this issue is open on 2.4 but I guess the PR already made it in 2.3
