### ISSUE TITLE
v3.0.0 Plan

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#1796]
Because v3 is a long ways away, and given that we're still not sure exactly what will land in it, the current discussion around that release will be had in [**a Google doc**](https://docs.google.com/document/d/1Sx1YE2SJg-NGSGsd8mELf3wpywI-UyOvCkufbm6klOw/edit#). This cleans up Github issues that are aren't actionable at this time.

Once the release nears and we begin to solidify our plans we'll migrate back to Github issues.

**Comment by jasonLaster** [comment]
Here's a trello board for ongoing work:
https://trello.com/b/oN61mg80/board
