### ISSUE TITLE
Feature Request: Feature Flags

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#1814]
#### Idea

Allow people to opt-in to testing out new features before they are officially released by putting the features behind flags that are attached to a global object.

#### Motivation

It'd be nice to be able to get feedback on features before officially releasing them. Feature flags would allow us to get that feedback, but because of their opt-in heavy warning nature people won't expect the APIs to be stable.

---

I've been thinking about this for a little while, and I think it'd be very useful.

Feature flagging API src:
```js
Marionette.FEATURES = _.extend({
    FEATURE_ONE   : false,
    FEATURE_TWO   : false,
    FEATURE_THREE : false
}, root.MARIONETTE_FEATURES);
// ^^^^ `window` or `global` depending on environment

Marionette.FEATURES.isEnabled = function(name) {
    return !!Marionette.FEATURES[name];
};
```

How it should be used in Marionette code:
```js
if (Marionette.FEATURES.isEnabled('FEATURE_ONE')) {
    Marionette.CoolNewFeature = function() {
        console.log('A CRAZY COOL NEW FEATURE!!!');
    }
}
```

In order to turn features on or off, they can do the following:
```html
<script>
  window.MARIONETTE_FEATURES = {
      FEATURE_ONE: true
  };
</script>
<script src="marionette.js"></script>
<script src="app.js"></script>
```
or
```js
global.MARIONETTE_FEATURES = {
  FEATURE_ONE: true
};
var Marionette = require('marrionette');
var App = require('app');
```

Which will then allow them to use the latest and greatest before it is officially released, knowing that the API could very likely change.
```js
Marionette.CoolNewFeature();
// >> A CRAZY COOL NEW FEATURE!!!
```

> See [Demo](http://jsfiddle.net/thejameskyle/7mydzfe7/).

What do you guys think?

**Comment by cmaher** [comment]
resolved by #2315
