### ISSUE TITLE
Improve CollectionView API: accept ChildView as a function and make getChildView private

### ISSUE THREAD

**Issue by paulovieira** [marionettejs/backbone.marionette#1846]
Many properties accept two forms for its value: 

1) as a direct object; 
2) as a function (which is executed at runtime and returns an object that will override the value for that property).

For instance:

* `events` (for any view type)
* `templateHelpers` (for any view type)
* `regions` (for LayoutView)

The second form is very useful and in my opinion should be generalized as much as possible.

In `CollectionView` we have a similar feature for `childView`, but instead of accepting the two forms we have to use another property if we want to define it as a function: `getChildView`.

```javascript
MyCV = M.CollectionView.extend({
    childView: SpringView,

    getChildView: function(child){
        if(child.get("season")==="summer"){ return SummerView; }

        return WinterView;
    }
});
```

Note that in the above snippet the `childView` property will never be used (because `getChildView` was overriden, and it doesn't use `this.childView`). In practice, by overriding `getChildView` we are also overriding `childView` (in the sense that the only reference to `this.childView` is inside `getChildView`)

The API would be more consistent if we could define `childView` also as function:

```javascript
MyCV = M.CollectionView.extend({
    childView: function(child){
        if(child.get("season")==="summer") { return SummerView; }

        return WinterView;
    }
});
```

or 

```javascript
var myCV = new MyCV({
    childView: function(){
        if(child.get("season")==="summer"){ return SummerView; }

        return WinterView;
    }
});
```

The `getChildView` method would still make sense, but I think it would be better as a private method:

```javascript
    _getChildView: function(child) {
        var childView = this.getOption('childView');
  
        if (!childView) {
            throwError('A "childView" must be specified', 'NoChildViewError');
        }
  
        // <new-stuff>
        if(childView.prototype instanceof Backbone.View){ 
            return childView; 
        }
        else if(_.isFunction(childView)){
            return childView(child)
        }
        else{
            throwError('...');
        }
        // </new-stuff>
    }
```
We can also make this backwards compatible by keeping `getChildView` as a public method. Nothing would change for those who are overriding it. But ideally, instead of overriding `getChildView` we should be defining `childView` as a function. It would make the API cleaner.

I can submit a PR if there is interest in going on with this idea.

**Comment by samccone** [comment]
@paulfalgout would you like to open a PR to implement getChildView? still very open to this feature

**Comment by paulfalgout** [comment]
I think @samccone meant @paulovieira

**Comment by samccone** [comment]
oops yep @paulovieira *

**Comment by paulovieira** [comment]
Ah ah, too many pauls around here :-) Sure thing, I'll give it a try over the next days. 

But to be clear: my ideia for v3 would be have a simplified API by removing the `getChildView` method and adding the logic directly into the `childView` property (which could either be a view class or a function that returns a view class). In other words, the role currently played by `getChildView` would be played instead by `childView`. This would make the API coherent with other parts of the library (read the first paragraph of issue for more details)

Yes, this is quite a breaking change for many apps, but it's simple to upgrade: it's only a matter of renaming `getChildView` to `childView`(could be done automatically with the upgrade script).

**Comment by paulfalgout** [comment]
Merged into next
