### ISSUE TITLE
beforeClose and stopping close being called

### ISSUE THREAD

**Issue by dominicglenn** [marionettejs/backbone.marionette#186]
I'm not entirely sure if the functionality already exists in Marionette, but the ability to either have beforeClose stop a view being closed, or a separate method to handle this would be useful.

The use case for this would be unsaved models etc, if you are about to close an ItemView that has unsaved changes made to the model, you'd be able to prompt the user if they want to cancel the close operation since the model is unsaved.

**Comment by rally25rs** [comment]
I think the common use case for this would be having a main navbar/header that has links in it, for example href="#/" to go "Home"

Then the app is currently on an ItemView, perhaps at "#/myitem"

If I click the Home link I need to prompt the user to save the data on their ItemView if it has changes.
There seems to be no built-in way to do this in Backbone or Marionette.

The route, controller, and view all have no way to cancel the navigation action based on the result of a confirm("discard your changes?") call.

**Comment by JHereu** [comment]
Is there any update on this issue?

**Comment by rafde** [comment]
This was resolved to closed.
