### ISSUE TITLE
CompositeView::childViewOptions does not get a model

### ISSUE THREAD

**Issue by JustBlackBird** [marionettejs/backbone.marionette#1873]
I'm trying to update from 1.x branch to 2.x but there is a problem. It seems that `CompositeView::childViewOptions` method does not get a model anymore. At the same time the documentation [here](http://marionettejs.com/docs/v2.2.0/marionette.collectionview.html#collectionviews-childviewoptions) says that it should accept a model. Is this a bug or is documentation wrong or may be I've missed something?

**Comment by samccone** [comment]
this has been released @JustBlackBird let me know if you are still running into issues

**Comment by JustBlackBird** [comment]
It seems that everything is fine. Thank you @samccone, @jmeas
