### ISSUE TITLE
Alias Backbone objects on Marionette

### ISSUE THREAD

**Issue by jamesplease** [marionettejs/backbone.marionette#1899]
``` js
Marionette.Model = Backbone.Model;
Marionette.Collection = Backbone.Collection;
Marionette.extend = Backbone.Model.extend;
Marionette.History = Backbone.History;
Marionette.history = Backbone.history;
```

Why not? This way people can just use the `Marionette` object and not even worry about Backbone.

This will tidy up people's code, and I think it makes Marionette _feel_ more standalone, and less like an extension.

If we do this, we might also consider renaming `Marionette.View` to `Marionette.BaseView`, or something.

**Comment by jmeas** [comment]
nvm i think this is a bad idea as well
