### ISSUE TITLE
Accessing childViewContainer from within a behavior?

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#1909]
Hiya,

I have a Behavior which is applied to several different types of CompositeView. One of the requirements of the Behavior is to work upon the given CompositeView's childViewContainer after the CompositeView emits the appropriate event.

    // Behavior:
    this.view.ui.childContainer.height(height);

Currently, each CompositeView assigns its childViewContainer to a UI element using a consistent, generic naming convention.

For instance:

    var StreamView = Backbone.Marionette.CompositeView.extend({
        childViewContainer: '@ui.childContainer',
        ui: {
            childContainer: '#stream-listItems'
        }
    }

This allows the Behavior to access "this.view.ui.childContainer" to do its needed work.

This seems inappropriate because the childContainer is not necessarily referenced in the CompositeView nor should the CompositeView need to know that a specific variable name must be used for an unreferenced UI element.

Am I approaching this incorrectly? Thoughts?

**Comment by samccone** [comment]
@MeoMix can you just call `getChildViewContainer` ?
https://github.com/marionettejs/backbone.marionette/blob/master/src/composite-view.js#L147

**Comment by MeoMix** [comment]
@samccone Maybe... but a few questions (that method looks pretty odd):

- getChildViewContainer expects a second parameter, childView, but that parameter does not appear to be used in the method. Is that a mistake?
- The method, while prefixed with 'get', actually affects the state of the view by caching the container as containerView.$childViewContainer. While OK in itself I am worried about calling this method after resetChildViewContainer has been called. It is unclear why the cached childViewContainer needs to be deleted and I feel like I would be introducing a bug into my code if I restore the cached object.

Thoughts?

**Comment by samccone** [comment]
1. yep we do not use it .. but we list it since it is called here
https://github.com/marionettejs/backbone.marionette/blob/master/src/composite-view.js#L133 ... debatable if it is good but meh

2. yep it sure does mutate state, that is no good, alas this is some OG marionette code :( I think you should be fine thought, the delete is just old defensive code not really needed.

**Comment by MeoMix** [comment]
Why not just remove the delete so I don't have to call a method and can just grab my property since it won't have been cleaned up after render? :p

**Comment by samccone** [comment]
:smile: :+1:

**Comment by samccone** [comment]
@MeoMix 

i told you it was OG

5cd35a28

**Comment by jasonLaster** [comment]
@MeoMix nice idea. Mind filing a new ticket about the delete. Also welcome a PR from you.

**Comment by MeoMix** [comment]
Is it something that should be slated for 3.x?

**Comment by jasonLaster** [comment]
hmm - not sure. it could be minor if it affects nobodies implementation...

**Comment by jasonLaster** [comment]
deleted in favor of fixing $childViewContainer as the discussion suggests

https://github.com/marionettejs/backbone.marionette/issues/2488
