### ISSUE TITLE
Thoughts on implementing Marionette Warnings?

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#1910]
Hiya,

I think it's fair to say that Marionette is incredibly flexible and people use it in a plethora of interesting scenarios. As such, strictly enforcing error conditions isn't always the best idea because it can become a hindrance when a developer has a scenario which is outside of normal use cases. This fact was seen quite recently in #1861.

That said, I think that there should still be the possibility of some hand-holding through a warning system. Perhaps warnings would be opt-in with a debug flag being set.

The first use case which comes to my mind is when refactoring a view. On more than one occasion I have had a UI object with cached references to nothing. For example:

    //  OLD:
    //  Template:
       <div class='buttons'></div>
    //  View:
       ui: { buttons: '.buttons' }

    //  NEW:
    //  Template:
       <div class='buttons-fancy'></div>
    //  View:
       ui: { buttons: '.buttons', fancyButtons: '.buttons-fancy }

It would be nice if Marionette could warn me and let me know that no elements were found for the ui.buttons selector. Maybe it's intended, but maybe it was just old code which was refactored out.

I'm sure there are lots of other scenarios where a little guidance could go a long ways in cleaning up people's code. What do you guys think?

**Comment by ahumphreys87** [comment]
I kinda think we should put together a separate debug library for this - something that you'll only include during development. This way we avoid bloating the main library.

Either that or could this belong in inspector? @jasonLaster what you think?

**Comment by jasonLaster** [comment]
I feel like another lib could go out of date. Maybe inspector maybe inline ala react Dev checks
