### ISSUE TITLE
Improve jsdoc

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#1927]
#### Additional Functionality
- [ ] Function Bodies --- Show the source, file, and line number for each function (#1757)
- [ ] Parse Events -- Parse class events with jsdoc descriptions and examples
- [ ] Notes section -- Some content in the API doesn't fit the regular pattern, for example 
- [ ] Add parent field -- Classes should have a parent field so that we can get parent functions
- [ ] Ancestor fields -- Get ancestor protected and public properties, functions, and events
- [ ] Lint for yaml whitespace -- It's really helpful to have strict whitespacing for syntax highlighting, build tools, and general consistency.

#### Cleanup
- [ ] change `jsdoc` extension to `yaml` --- This will help reduce confusion and improve editor whitespace and syntax support
- [ ] move constructor field to functions --- Currently `constructor` is a top level field, I think we should nest it inside functions because it is a class function. We can pull it to the top level in the build phase or www.

**Comment by samccone** [comment]
moving to #1756
