### ISSUE TITLE
ItemView.tagName breaks template abstraction.

### ISSUE THREAD

**Issue by richburdon** [marionettejs/backbone.marionette#1930]
The requirement that ItemView declares a tagName seems to me to break the requirement of separation of code and layout. In the simple example below all of the template code is in HTML script blocks EXCEPT for the <tr> tag, forcing the implementation of template logic into layout PLUS code. E.g., if I need to add attributes to each item row this has to be done in code. Worse, if I want to change my layout (template), I need to understand (and change) the code.

An alternative would be to allow ItemView to adopt the root element of its template as the container (i.e., specify <tr> in the item view template).

```
var ItemView = Backbone.Marionette.ItemView.extend({
  template: '#template-item',
  tagName: 'tr' // <- WHY CAN'T I DECLARE THIS IN MY TEMPLATE?
});

var ListView = Backbone.Marionette.CompositeView.extend({
  template: '#template-list',
  childView: ItemView,
  childViewContainer: 'table'
});

<script type="text/template" id="template-list">
  <table></table>
</script>

<script type="text/template" id="template-item">
  <td><%= title %></td>
</script>
```

**Comment by rjsteinert** [comment]
Alas, my Google Fu has brought me here. The proposal that @richburdon made solves what Ian Williams describes as "<DIV> Hell", and boy can I relate. When working on a team, the folks that are writing the CSS/templates and the folks that are writing the JS are not always the same people, nor should they be. I myself am not an expert in CSS/SASS/LESS/etc. and prefer to leave that up to the experts who know how to build Style Guides. What @richburdon describes is a convenience and certainly something that could be abstracted into separate library, but I encourage those who are actively mainting Marionette ( @jmeas thankyou!) to consider 1) how great it is to separate markup and code and 2) how not having this ability in Marionette looks to people coming from other communities or comparing Marionette to other frameworks such as Angular.
