### ISSUE TITLE
Build jsdoc static analysis tool

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#1941]
This issue was started in #1756 by @ChetHarrison

We should build a tool that helps automate some of the `jsdoc` work involved with documentation:
1. generate yaml for new classes / utility functions
2. lint existing api for missing functions, parameters, properties, events
3. add function bodies to api

The work is being done in this repo: https://github.com/ChetHarrison/jsdoccer

**Comment by samccone** [comment]
moving to THE JSDOCCER issue #1756
