### ISSUE TITLE
Add "before:detach" / "detach" events?

### ISSUE THREAD

**Issue by paulovieira** [marionettejs/backbone.marionette#1964]
#1957 adds the "before:attach"/"attach" events for the tree view that is placed in the DOM (using region's `show`). One common case for this event is to activate 3rd party plugins located deep in the view tree and that must be started only after the view is in the DOM.

Should we add "before:detach" / "detach" events as well? These might be necessary to shut down those plugins.

In principle it could (and should) be done on the view's "destroy". But if `preventDestroy` is true, `beforeDestroy`/`destroy` will not be fired.

**Comment by marcusstenbeck** [comment]
+1

I was looking for this functionality today.

**Comment by jasonLaster** [comment]
@ianmstew feel brave enough?

**Comment by ianmstew** [comment]
@jasonLaster Sounds like a fun one :p  Sure, v2.5 or v3.0.0?  I can do some preliminary research to check which makes sense from LOE side (v3.0.0 refactoring might give us some advantages, for example).

**Comment by paulfalgout** [comment]
Closed by https://github.com/marionettejs/backbone.marionette/pull/2850
