### ISSUE TITLE
Adding behavior pattern to controllers

### ISSUE THREAD

**Issue by farias-r7** [marionettejs/backbone.marionette#1975]
My understanding is that the Behavior pattern in views allows some nice cocern/mixin style patterns to be used. 

It would be cool if this functionality was extended to marionette controllers. Right now we are using Cocktail.js and the mixin patterns introduced by @brian-mann in our controllers and marionette behaviors in our views. It would be nice to be consistent between controllers and views.

Any thoughts from the community on such a request?

**Comment by jasonLaster** [comment]
Closing this PR as it's more of a discussion around mixin's, which is happening with Metal
