### ISSUE TITLE
Regions: Allow a View to replace the Region's element in the DOM

### ISSUE THREAD

**Issue by trezy** [marionettejs/backbone.marionette#1976]
## The Issue

Currently Marionette enforces the idea that a `Region` should be an element which exists in the DOM that will wrap the `View`s that are displayed inside of it. The `View`s, similarly, are forced to have a parent element. This means that to utilize Marionette's awesome `Region`s we're forced to have two elements wrapping a view. That kinda sucks.

## The Solution[s]

We could manually render the `View` without using `Region`s but that's dumb. The concept of `Region`s is marvelous and wonderful. Having to completely bypass it just to avoid an extra tag is silly.

``` javascript
var app = Backbone.Marionette.Application;

app.aView = new Backbone.Marionette.ItemView();

app.addInitializer(function () {
  $('.foo').html(function(){
    app.aView.render();
  });
});
```

Alternatively, we could extend the `Region` class to allow a view to replace the `Region`'s element. This could be a simple option passed through in the `Region`'s `options` object.

``` javascript
var app = Backbone.Marionette.Application;

var awesomeRegion = Backbone.Marionette.Region({
  el: '#foo'
  replaceElement: true
});

var thingyView = Backbone.Marionette.ItemView({
  tagName: 'section'
  className: 'thingy'
});

app.addRegions({
  foo: awesomeRegion
});
```

This way we could point the region to an arbitrary element that exists in the page as a placeholder - in this case, `<div id=foo />` - then when we call `app.foo.show(ThingyView);` we could replace the `Region`'s element with the `View`'s element. When we destroy the `View` we would need to replace it with the original element, too.

## Conclusion

A Marionette `Region` should be a target for content, not a content wrapper. The `View` should dictate what content is shown and how that markup is handled.

**Comment by ajambrovic** [comment]
I have a similar issue, I'm trying to render a table, where `<thead>` and `<tbody>` are my regions. Inside the `<tbody>` region I want to render a collectionView of `<tr>` but I end up with an unnecessary collectionView container element (by default a `<div>`). I've tried setting the `tagName` and `id` attributes, but what I get is a `<tbody>` tag inside another `<tbody>` tag.

**Comment by ahumphreys87** [comment]
@ajambrovic you should take a look at CompositeView - I use them for this
scenario all the time

**Comment by ajambrovic** [comment]
@ahumphreys87 I've looked at the documentation for the CompositeView, but in that example, the `thead' element is hardcoded - that's why I used the LayoutView with the two regions so I don't see how I could use the CompositeView instead of the LayoutView and still have dynamic `thead' (in this scenario, the `thead' element could also change on re-render so I'd like to delegate it's management to e.g. regions instead of handling it myself).

**Comment by JSteunou** [comment]
with a composite view `thead` could contain your model and `tbody` your collection.

Add some `modelEvents` to manually update the `thead` (or auto via backbone.stickit)`

**Comment by paulfalgout** [comment]
@ahumphreys87 this is solved by https://github.com/marionettejs/backbone.marionette/pull/2625 ?

**Comment by ahumphreys87** [comment]
It is indeed :dancer:

**Comment by trezy** [comment]
Yup, sorry for not responding. Definitely closed and I'm so happy it is. :-D

**Comment by nucleartide** [comment]
@ajambrovic I'm facing your exact problem right now with `<thead>` and `<tbody>`. I want `<thead>` to contain an ItemView, and `<tbody>` to contain a CollectionView, but I can't work around CollectionView's wrapping div, which will mess up the table rendering. The only solution I can imagine is to do some manual rendering and destroying:

```javascript
module.exports = LayoutView.extend({
  // ...

  onAttach: function() {
    var tbody = this.$el.find('tbody')[0];

    this.collectionView = new CollectionView({
      el: tbody,
      collection: new Collection(...)
    });

    this.collectionView.render();
  },

  onDestroy: function() {
    this.collectionView.destroy();
  }
});
```

I see that #2625 provides a `replaceElement` option for `show()`, but in the meantime I'm going with my solution above. Hopefully it doesn't leak memory. D:

**Comment by JSteunou** [comment]
That's why `CompositeView` is awesome! You can create a view with table > tbody and specify tbody as `childrenContainer` ;)
