### ISSUE TITLE
Deprecate Marionette.Deferred

### ISSUE THREAD

**Issue by cmaher** [marionettejs/backbone.marionette#1982]
With the deprecation and eventual removal of `Marionette.Callbacks`, Marionette is entirely synchronous. `Marionette.Deferred` was added to configure the thenable implementation used by callbacks. We should deprecate it now and remove it in v3, or if v3 requires asynchronous behavior, I think it would be better to name it to `Marionette.Promise`, defaulting to the native Promise implementation.

I'm not sure this is the best candidate for `Marionette.Deprecate` because we would have to deprecate `Marionette.Deferred = myDeferred`.

**Comment by samccone** [comment]
gona say this is done
