### ISSUE TITLE
[Request] Pass childView as parameter to getChildViewContainer

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#1983]
In CompositeView, `getChildViewContainer` is public and can be overwritten, but receives only the `containerView` as parameter. It could be convenient to add the `childView` as a second parameter.

**Use case:**
If some wants to make a `CompositeView` which can render a collection of items in a two columns layout, he can do that by having 2 `childViewContainer`. By overwriting `getChildViewContainer` he could decide in which column the `childView` should go.

**Comment by samccone** [comment]
fixed  in 50aca9665db44e8d7d766d16b7c6f5d39541679f
