### ISSUE TITLE
CollectionView exhibits incorrect behavior after resortView with overridden addChild method

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2021]
Alright, this is a legitimate bug and I am stoked to have figured it out! :D

So, I've got a CollectionView which has overridden its addChild method as described by the docs: http://marionettejs.com/docs/marionette.collectionview.html#collectionviews-addchild

For this example, I will use a very simple case:

	Backbone.Marionette.CollectionView.extend({
	  addChild: function(child, ChildView, index){
		var denyAdd = this.el.scrollTop > 0 && index === 0;
		if (!denyAdd) {
		  Backbone.Marionette.CollectionView.prototype.addChild.apply(this, arguments);
		}
	  }
	});

The CollectionView will not render its first child if the view has been scrolled down at all. Fair enough, yeah?

So, the CollectionView is scrolled down a bit and its collection is sorted. Sorting the collection causes the CollectionView to call its _renderChildren method. _renderChildren nukes the child views and calls 'showCollection' which looks like:

	// Internal method to loop through collection and show each child view.
	showCollection: function () {
		var ChildView;
		this.collection.each(function (child, index) {
			ChildView = this.getChildView(child);
			this.addChild(child, ChildView, index);
		}, this);
	},

Since we've overridden addChild -- our implementation will be called first while iterating over the collection. Since scrollTop is greater than 0, the first model in the collection is not added as a child view. **BUT INDEX IS STILL INCREMENTED**

_renderChildren completes. The view looks good externally, but, internally, Babysitter has an array of children whose index starts at 1 **instead of 0**.

Now, the user scrolls back up to the top of the CollectionView, scrollTop is 0. CollectionView's addChild method is called with the first model in the collection. An attempt is made to insert the collection at the top of the CollectionView, at index 0. addChild calls _updateIndices, increments all the children indexes (so now the starting index is 2), and the _insertBefore method **fails to find the appropriate index.** As such, it append the ChildView at the end of the CollectionView, but with an index of 0.

I propose that the docs mention that you probably need to override showCollection if you're overriding addChild because really bad things can happen. Or, showCollection needs to get a lot smarter about anticipating overridden addChild and check to see if a child was actually inserted at the index. If not, don't increment the index.

And here's a helpful picture: http://i.imgur.com/ikmxQ8M.png -- You can see in the third table that there is no view with index 0 :(

**Comment by cmaher** [comment]
mmm, would a `filter` work in this case @MeoMix ?

**Comment by MeoMix** [comment]
I think the new version of Marionette definitely changes things a bit, but I haven't had the time to revisit it just yet.

**Comment by ahumphreys87** [comment]
@MeoMix I'd be interested to see if adding a `filter` caters for your use case here. It's sounds pretty much like what we built it for :)

**Comment by ahumphreys87** [comment]
Closing as this should be fixed with `filter`. @MeoMix feel free to reopen if the issue still remains
