### ISSUE TITLE
Adopt Backbone.Boilerplate

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2039]
@tbranyen suggested today that we could move Boilerplate over to the Marionette org. It's a popular project with a good following, but it hasn't been maintained lately.

Talking to @tbranyen, his vision for the future of the Boilerplate aligns well with the changes I'd like to see in it, and go hand-in-hand with the work we're doing in Marionette.

He suggested we take it over and make it more Marionette-centric.

Thoughts?

Edit: Linkage https://github.com/backbone-boilerplate/backbone-boilerplate

**Comment by samccone** [comment]
Any interest in this from anyone? @jmeas @thejameskyle  ?

**Comment by thejameskyle** [comment]
With the work @jmeas has been doing on es6-boilerplate and me on wires, I think we will have something better.

**Comment by samccone** [comment]
K will close.
