### ISSUE TITLE
{preventDestroy: true} does not seem to work properly...

### ISSUE THREAD

**Issue by thisissami** [marionettejs/backbone.marionette#2046]
Hi All,

I've been getting into Marionette recently and have begun building the front end system for a platform that I've been hired to create. I've ran into what I presume is a bug with Marionette, and wanted to check in here.

In my app, I have a div with id `main`. This is set up to be a region for my app. In this region, I show a `LayoutView`. This layout view contains a region, which contains an `ItemView`. When this view is clicked, the entire `main` layout is replaced with a new `ItemView`, with the `{preventDestroy: true}` attribute passed in. This new `ItemView`, when clicked, returns the original `LayoutView` to the `main` region. 

However, the original `LayoutView` no longer exists when I bring it back to my `main` region. Perhaps of interest, it is only destroyed after the click in the second `ItemView`, when the code to bring back to original `LayoutView` is ran. 

Here is the HTML:

```HTML
        <div id="main"></div>
		<script type="text/template" id="template1">
			HELLO HELLO HELLO
			<div id="test"></div>
		</script>
		<script type="text/template" id="template2">
			CLICK HERE TO SWITCH VIEWS
		</script>
		<script type="text/template" id="template3">
			CLICK HERE TO GO BACK
		</script>
```

And here is my JavaScript code that I run: 

```JavaScript
	var MatchManager = new Marionette.Application();
	MatchManager.addRegions({
		main: '#main',
	});
	window.runTest = function(){
		MatchManager.layoutView = Marionette.LayoutView.extend({
			template: '#template1',
			regions: {
				test: '#test'
			},
			onShow: function(){
				this.test.show(new MatchManager.itemView());
			},
		});

		MatchManager.itemView = Marionette.ItemView.extend({
			template: '#template2',
			events: {
				'click': 'switch'
			},
			switch: function(){
				MatchManager.main.show(new MatchManager.itemView2(), {preventDestroy: true});
			}
		})

		MatchManager.itemView2 = Marionette.ItemView.extend({
			template: '#template3',
			events: {
				'click': 'back'
			},
			back: function(){
				MatchManager.main.show(MatchManager.layout);
			}
		});

		MatchManager.originalLayout = new MatchManager.layoutView();
		MatchManager.main.show(MatchManager.originalLayout);
	}

	MatchManager.start();
```

This feels like a major bug. I might be doing something wrong, but I don't think I am. Can anybody here confirm one way or another?

**Comment by ahumphreys87** [comment]
@jmeas do you remember which PR this was?

@thisissami have you tried your code with 2.3?

**Comment by paulfalgout** [comment]
I believe this is the same as https://github.com/marionettejs/backbone.marionette/issues/2415

Essentially the preventDestroy is working, but when you subsequently re-show the layout it will re-render it which rebuilds its regions which will then destroy the child views.

I'm closing this and referencing: https://github.com/marionettejs/backbone.marionette/issues/1263 which contains what would be a fix for this issue.
