### ISSUE TITLE
Region#_destroyView should call onBeforeDestroy and onDestroy on non-Marionette Views

### ISSUE THREAD

**Issue by cmaher** [marionettejs/backbone.marionette#2051]
CollectionView (among others) uses `triggerMethodOn` to ensure that `onBeforeDestroy` and `onDestroy` on the view being destroyed (if those methods exist), in order to be consistent with how other parts of Marionette work.

**Comment by paulfalgout** [comment]
This is resolved here: https://github.com/marionettejs/backbone.marionette/pull/2704
