### ISSUE TITLE
Accidentally collided with Marionette methods -- should I just work around it?

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2052]
I wrote code which looks like this:

	var MyCollectionView = Backbone.Marionette.CollectionView.extend({
		template: _.template(''),
		
		collectionEvents: {
			'add': '_onCollectionAdd',
			'remove': '_onCollectionRemove',
			'reset': '_onCollectionReset'
		},

		_onCollectionAdd: function(model, collection){
			console.log('MyCompositeView _onCollectionAdd is running.');
		},
		
		_onCollectionRemove: function(model, collection){
			console.log('MyCompositeView _onCollectionAdd is running.');
		},
		
		_onCollectionReset: function(collection){
			console.log('MyCompositeView _onCollectionAdd is running.');
		}
	});

I thought it was pretty slick. I have been trying to enforce a naming standard for my event handlers such that they correspond to the triggering object. However, this code breaks horribly because CollectionView already uses an _onCollectionAdd and _onCollectionRemove. _onCollectionReset is unused, though.

You can imagine my confusion when I saw that my Behaviors were working OK, but that the same code on the CollectionView itself was breaking.

For now, I'm just going to work around it by naming my functions something else... _onMyCollectionAdd and _onMyCollectionRemove, but I'll admit it's still pretty fragile because collectionEvents in a Behavior will work fine with _onCollectionAdd.

Any thoughts on this? Is this an issue with my function naming conventions? Or could Marionette be doing more to use less-generic names for something so easily collided with?

**Comment by cmaher** [comment]
We should keep this in mind as we move into v3. Some of Marionette's internal methods are very much names that users can come up with on their own. I'm also throwing in `_mn_methodName` as a suggestion.

**Comment by ahumphreys87** [comment]
Im :-1: for changing the convention here. As @rhubarbselleven pointed out - this is also how Backbone identify private methods.

Maybe this should be a feature for Inspector, we could warn when a private function is overridden via `extend`.

thoughts @marionettejs/marionette-core

**Comment by jasonLaster** [comment]
@ahumphreys87 the inspector could definitely work. 

I'm also :-1: devs should look at their parent classes...

**Comment by MeoMix** [comment]
Could I please have a suggestion on how to adjust my app's naming conventions if this change is not going to occur?

    collectionEvents: {
        'add': '_onCollectionAdd',
        'remove': '_onCollectionRemove',
        'reset': '_onCollectionReset'
    },

This seems like the obvious choice of function names. I could change it to whatever type of Collection is being used, i.e:

    collectionEvents: {
        'add': '_onPlaylistItemsAdd',
        'remove': '_onPlaylistItemsRemove',
        'reset': '_onPlaylistItemsReset'
    },

but it would be nice to keep the view as dumb as possible -- it doesn't need to know that it's working on a given type of collection... just that it is working on a collection.

Plus, I think there's a reason that I'm colliding with Marionette. We both chose the 'correct'/'expected' naming convention for the function. It feels weird to say that Marionette is going to take precedent over external use.

Furthermore, I have to worry about scenarios which aren't technically broken right now but could very easily be broken in the future.

For instance, Marionette does not leverage an '_onCollectionReset' event handler. Instead, it calls render directly:

    this.listenTo(this.collection, 'add', this._onCollectionAdd);
    this.listenTo(this.collection, 'remove', this._onCollectionRemove);
    this.listenTo(this.collection, 'reset', this.render);

So, it's perfectly valid for me to create a collectionEvents which looks like:

    collectionEvents: {
        'reset': '_onCollectionReset'
    },

but I feel like this is incredibly high risk. All it takes is Marionette needing to perform a step in addition to rendering and using _onCollectionRender to wrap both those steps. I'm not convinced this would even be considered a breaking change since render would still be called. So, I think it's possible to collide with user's naming conventions, unintentionally, quite easily.

I think it's the job of a framework to do its job as quietly and seamlessly as possible. It's not too difficult to use a naming convention which doesn't have a high likelihood of being stumbled into. 

I think that saying Marionette should not change because of Backbone's current implementation is valid and I will admit that I have collided with BB's private methods in the past to much confusion. Personally, I feel that Marionette is a much more lively project that is being actively iterated upon and it's frustrating to consider limitations just for the sake of adhering to a less actively maintained project.

**Comment by paulfalgout** [comment]
Not that this solves the issue specifically, but why are you using `_onCollectionAdd` and not `onCollectionAdd`

**Comment by MeoMix** [comment]
I prefix methods which are private / are not referenced outside the given module with an underscore. Isn't that common practice?

Here's an example file: https://github.com/MeoMix/StreamusChromeExtension/blob/71b3fc39bb9434ab2d639cfcf9c1baa7ce6a9ef2/src/js/foreground/view/search/searchView.js#L60

**Comment by paulfalgout** [comment]
I don't know that `onEvent` methods are generally _ privatized in the same way..  I mean you would never call `onRender` outside of the module.  
In the world of `triggerMethod` it is very hard to maintain any sort of consistency with `_onEvent` methods.. most event handlers belonging to the module would probably not be _'d  
The reason the _s are in `Mn` for these events in particular is so that you don't attempt to override them.. not so you don't call them directly.

**Comment by MeoMix** [comment]
In my mind, onRender is not prefixed with _ because it has references outside of the current module. Marionette hooks into onRender and thus we know that, when modifying onRender, we need to look outside of just this file to ensure changes aren't breaking.

By contrast, I know that when I'm changing a method that is prefixed with '_' that it's safe to do a find/replace on the current file and that's it.

Maybe I'm just struggling to cope with the fact that there's no private/protected/public concept in js. :) Your point does make sense and I do see the difference in my usage of '_' versus Marionette. However, I do think that it's nice to make a distinction between public and private methods and I'm not aware of a more clear way to provide that distinction.

**Comment by ianmstew** [comment]
I suspect I haven't ran into this because I see "on" as the naming convention for _any_ event handler, including my own.  I wouldn't collide with Marionette "on" methods in a rename because I wouldn't choose a name like "onShow" in order to avoid confusion.  I do see what you mean, though, about there being no _absolute_ privacy within `Backbone.extends()` properties.  Coming from Java land, I've gone through the same anguish, but ultimately favor Javascript's flexibility :)

**Comment by MeoMix** [comment]
What do you usually name your event handlers? :)
