### ISSUE TITLE
Marionette Components / Bundles

### ISSUE THREAD

**Issue by bgaillard** [marionettejs/backbone.marionette#2054]
Hi, this issue is created to complement the following comment : https://github.com/marionettejs/backbone.marionette/issues/2026#issuecomment-61487073. 

**The problem**
In each application we create with Marionette (we often use Twitter Bootstrap) we develop the same components again and again and again... 

For example several of our apps uses : 
 * OK/Cancel modal boxes
 * Breadcrumbs
 * Select components (with Twitter Bootstrap select for example)
 * Pagination components
 * Etc.

Today  : 
 * Its very hard to find ready to use Marionette components
 * We would like to share some of the Marionette components we develop but we have no guides to explain us how to create a component "the Marionette way"

**The idea**
The idea would be to propose a Marionette Component / Bundle structure developers could use to create reusable / sharable / ready-to-use components. 

As it will be inevitably opinionated this would be a separate project with for example : 
 * A yeoman generator to quickly start the dev of a new component
 * A grunt/gulp task to test, minify, package the component
 * Instructions to organize files and directories
 * Instructions to manage events (with a Backbone.Radio channel for example)
 * How to specify inputs / outputs, how to define an interface for the component
 * How to install and use a component in an existing Marionette app
 * Etc.

Do you think it would be a good idea ?

**Comment by ahumphreys87** [comment]
I dont think this is something that should go into marionette core. By the sounds of it @bgaillard you are looking for a set of opinions on how to build marionette apps and a way of creating your "boilerplate" code. You should take a look at Marionette Wires: https://github.com/thejameskyle/marionette-wires/

It doesn't have the yeoman generator you mentioned but its certainly a tool I'd be interested in seeing for that project.

Regarding https://github.com/jfairbank/marionette.component this lib seems like a combo of what we are discussing for modules/sub-apps/router changes in v3 which are documented in other issues
