### ISSUE TITLE
Allow for custom sorting in a CollectionView

### ISSUE THREAD

**Issue by cpjolicoeur** [marionettejs/backbone.marionette#2056]
I'm working on a sample implementation to show as an example, but wanted to open a ticket to start a discussion and see if there was other interest in this.

It would be a nice feature to be able to pass a custom sort option to a CollectionView.  By default, a CollectionView of course keeps its children view rendered in the same sort order as the underlying collection.

In my use case, I need to render the same collection in a few places in my app, but sorted differently in each place.  My current solutions are to clone the original collection and then do manual work to keep the two collections in sync related to model changes, but each collection having its own sort comparator.  Or, In the collection views themselves, I can override the `attachHtml` method to insert the DOM where I want depending on how that view wants to sort things.

It would be nice to be able to pass a custom sort comparator to a collection view and have it use that for its children view sorting or default to the collection sort if no custom sort option is provided.

I'm not fully sure the implications or implementation details on this yet, as I'm still working through it but I'm curious if there is any input on something like this or if there is an existing agreed-upon preferred solution.

**Comment by samccone** [comment]
merged, will go out with 2.4
