### ISSUE TITLE
Marionette classes should have a cid field

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2059]
It's common practice to check a View or Model's `cid` field when debugging. The `cid` field is also an important way to hyperlink objects in the Inspector. e.g click on a view and jump to the UI pane and that view's info panel. 

While working on the inspector, I found that many of Marionette's classes do not have a cid field. This should be relatively easy to add:

Classes in need of a cid
- [x] Object
- [ ] Controller
- [ ] Module
- [x] Application
- [x] Behavior

**Comment by paulfalgout** [comment]
Related: https://github.com/marionettejs/backbone-metal/issues/2

**Comment by SauloSilva** [comment]
All, regions and region-manager also extend from Object too.

**Comment by ahumphreys87** [comment]
Fixed with #2524. Controller is gone as is Module
