### ISSUE TITLE
add support for views with dynamic ids to the UI hash

### ISSUE THREAD

**Issue by acidreign** [marionettejs/backbone.marionette#2067]
When adding views with dynamic ids there is no good way to add the id to the selector in the UI hash.

I tried a bunch of different things to get this to work including initializing/changing the UI hash inside the initialize() function but nothing seemed to work.

I ended up patching _buidUIElements() to add the elements id to the selector if it exists:
```javascript
  _bindUIElements: function() {
    if (!this.ui) { return; }

    // store the ui hash in _uiBindings so they can be reset later
    // and so re-rendering the view will be able to find the bindings
    if (!this._uiBindings) {
      this._uiBindings = this.ui;
    }

    // get the bindings result, as a function or otherwise
    var bindings = _.result(this, '_uiBindings');

    // empty the ui so we don't have anything to start with
    this.ui = {};

    // bind each of the selectors
    var id = (this.id) ? '#'+this.id+' ' : '';
    _.each(_.keys(bindings), function(key) {
      var selector = id+bindings[key];
      this.ui[key] = this.$(selector);
    }, this);
  },
```
Is there a better way to handle this or is it a legitimate issue?

**Comment by RomanKapitonov** [comment]
any news? I need a kind of this functionality either. 

As a valid case for this consider using a list of elements that can be marked as active with CSS .active class. So the ui hash should look as follows

``` coffee
ui: 
  activeElement: '.active'
```

Then if you have a behavior that is referencing that ui hash the active element will actually never change automatically unless you set it explicitly.

That would be really nice thing to have

**Comment by paulfalgout** [comment]
The UI hash updates on the view's 'render' so that the look-up is cached.  If it had to do the look up every time you accessed the UI or worse if the DOM changed outside of a 'render', then there's not much point in using the UI hash at all.  In that case just use `this.$('.active')`  If you want to use the UI hash reliably the only thing that should add the class to the view is the 'render' of the view and not any form of `$.addClass`

**Comment by RomanKapitonov** [comment]
@paulfalgout 
Sounds reasonable, ended up changing the UI hash in a setAsActive method on element click. Thanks for your explanation

**Comment by samccone** [comment]
:+1:
