### ISSUE TITLE
Support Underscore 1.7

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2072]
Underscore 1.7 included breaking changes...

> pauses to let the laughter subside

...with the `_.template` method. Right now Marionette doesn't support 1.7, but we should for v3, I think. What needs to get done to support that?

Maybe some updates to the `Renderer` + docs (ref: #2019)?

**Comment by samccone** [comment]
changed my mind @megawac if people want to use 1.7 they should look at the template api for underscore since it is not like 

Marionette.Template .. it is _.template
