### ISSUE TITLE
Marionette cannot work with Browserify

### ISSUE THREAD

**Issue by commenthol** [marionettejs/backbone.marionette#2074]
See thread on [Stackoverflow](http://stackoverflow.com/questions/21070737/cant-get-marionette-working-with-browserify).

Marionette does not work with Browserify as jQuery, Wreqr and BabySitter is currently not attached to Backbone. 

The piece of code in charge...

**src/build/marionette.core.js Line 8**

``` javascript
  } else if (typeof exports !== 'undefined') {
    var Backbone = require('backbone');
    var _ = require('underscore');
    var Wreqr = require('backbone.wreqr');
    var BabySitter = require('backbone.babysitter');
    /* Wreqr and Babysitter are required but not handled to Marionette as 
        Backbone.Wreqr, Backbone.BabySitter */
    module.exports = factory(root, Backbone, _); 
  } else {
```

Will issue a PR to fix this behaviour.

**Comment by ad-lebedev** [comment]
Hi all!

Have a problem with browserify and marionette -- trying to build vendors bundle but got this error:
```bash
Cannot find module 'backbone.wreqr' from '.../client/src/vendor/backbone.marionette/lib/core'
Cannot find module 'backbone.babysitter' from '.../client/src/vendor/backbone.marionette/lib/core'
```
I've checked, there are no 'core' directories in both packages. 
Marionette was installed with bower, just ```bower install backbone.marionette```

**Comment by ad-lebedev** [comment]
Sorry for disturbing! =(
I found the reason of this error. It was not a marionette issue, but just a problem of my browserity gulp task.
I use ```bower-resolve``` to determine packages for browserification based on bower.json file content. But there was no backbone.wreqr and backbone.babysitter there.

I'm sorry, one more time!

**Comment by paulfalgout** [comment]
no problem!  Thanks for reporting on your findings!
