### ISSUE TITLE
CollectionView sort only available as an option

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2076]
You can only pass `sort` as an option, not as a class prop.

```js
var MyCv = Mn.CollectionView.extend({
  sort: false
});

// sort is true
var myCv = new MyCv();
```

The cause is [this weird code](https://github.com/marionettejs/backbone.marionette/blob/master/src/marionette.collectionview.js#L20)

**Comment by paulfalgout** [comment]
Ah this is fixed here I believe:  https://github.com/marionettejs/backbone.marionette/pull/2263

**Comment by samccone** [comment]
that it was, good spot @paulfalgout
