### ISSUE TITLE
Adding behavior-like pattern to Regions

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2077]
This issue is similar to https://github.com/marionettejs/backbone.marionette/issues/1975

**I think there is a better case for Regions having something like behaviors than controllers or objects.**

For my projects use case we've extended Region classes on a few occasions.  Sometimes we want to animate something in or out.  We also have a region that when given a view, centers the view within the region, darkens the background, and destroys the view if a click occurs outside the view shown.  (essentially make any view a modal by showing it in the modal region)

**I've found I use custom regions to do two things mostly.** 

1. Intercept the show or empty and do something with the view on the way in or out.  
2. Handle DOM events / add additional styling to views shown with the region.

We haven't yet run into a particular situation in which case we've needed more than one custom region behavior, but it certainly isn't inconceivable, and much like pattern issues that arose with using mixins with views, the same issues would occur here.

However one thing I believe that sets region behaviors apart from view behaviors is that in most cases when using view behaviors you're adding a behavior to a view that has other responsibilities.  For regions, at least in my limited perspective on the use case, most custom regions are exclusively region behaviors.  So in a world where region behaviors existed, many custom regions would simply be configuring region behaviors.

**My suggestion would be to allow region behavior configuration at the manager level** (probably in addition to allowing behavior configuration on a custom region)
```
var rm = new Marionette.RegionManager();

// With an object literal
var regions = rm.addRegions({
  main: '#main-content',
  navigation: {
    selector: '#navigation',
    regionClass: MyNavRegion
  },
  side: {
    selection: '#side',
    // regionClass: Marionette.Region,
    regionBehaviors: {
      animateIn: {
        'type': 'fadeIn'
      },
      watchScroll: { }
    }
  }
});
```

**Comment by jasonLaster** [comment]
I'm :-1: on this proposal for a couple reasons...

+ regions are already very complicated
+ pro users customize regions. it's not a common feature at all
+ people who are pro's can use a form of composition to add behaviors to many regions

@paulfalgout you put a lot of thought into this, so I don't want to dismiss the idea casually. thoughts?

**Comment by paulfalgout** [comment]
Yeah.  While I do think the value of regions is underrated, I didn't realize how under-utilized they were until the discussions of removing them entirely.  Also even in my use of them various combinations of region "behaviors" seem more limited.  Some sort of mixin strategy, via metal, or even just homegrown is easy enough.
