### ISSUE TITLE
Ability to prompt user for confirmation when navigating away

### ISSUE THREAD

**Issue by frozenspider** [marionettejs/backbone.marionette#2089]
(This seems to be asked already: https://github.com/marionettejs/backbone.marionette/issues/186)
Could you please add a way for us to stop user from navigating away from the page if it has unsaved changes? In plain old application, we could use `window.onbeforeunload`, but it doesn't work with single-page app.

Right now people seems to use a bunch of dirty hacks for this:
* Overriding `router.navigate` - https://paydirtapp.com/blog/backbone-in-practice-dirty-object-handling/
* Intercepting link clicks - http://stackoverflow.com/a/9876710/466646
* Hacking into `Backbone.History.loadUrl` - http://stackoverflow.com/a/9873637/466646, http://stackoverflow.com/a/24535463/466646, etc.
* Some event and interceptor magic - https://christinemdraper.wordpress.com/2014/09/06/confirm-before-navigating-away-from-unsaved-edits-using-javascript-and-backbone/

I think a clean and standard solution would be nice

**Comment by rally25rs** [comment]
+1 this seems like basic SPA behavior. I was surprised that there was no way to cancel navigation in Backbone or Marionette.

**Comment by jmeas** [comment]
@rally25rs, it is definitely surprising without the context of the history of Backbone's router. @jashkenas intends/intended for the Backbone Router to be used as an object that sets up the initial state of the application, and *not* one that handles transitions between your application's state after it has been set up. Consequently features like canceling routing will **necessarily** be a hack to add in.

Routers like Backbone's stem from the jQuery days of development, but recent routers have moved to more powerful patterns, resembling something like a nested state machine. That's just a fancy way of saying that they focus on the **state** of your application at any given time, and, more specifically, transitions between those states. So you get nice fancy hooks for async transitions, canceling transitions, redirecting, and all of the things people want in a router.

Some examples are Ember's router, Angular's UI-Router, and React's router. I'm working on a new router for the Backbone world that's inspired by these two implementations, but will be much faster & much smaller than the alternatives. It's possible that it will one day find its way into Marionette.

Until then, tho'...ya just gotta figure it out! I'd still recommend BaseRouter as a starting point tho'.

**Comment by ahumphreys87** [comment]
This feature request is covered in #2092
