### ISSUE TITLE
ViewDestroyedError in recursive composite view

### ISSUE THREAD

**Issue by eyaleizenberg** [marionettejs/backbone.marionette#2116]
Hi,
I have a 'tree' like structure of models and views:
A flow view (process and list view inherit from it) can have more flow views as child views. A flow view can also have an item view as a child view called task view (inherits from activity flow).

Clicking the edit button in the activity calls a popup which upon closing sets some variables on the activity (in this case Task). This calls the "render" method on that itemview. This works fine for me.

If I edit the composite view and then try to edit the item view again, upon closing the popup I get this:
Uncaught ViewDestroyedError: View (cid: "view162") has already been destroyed and cannot be used.

I have tried everything on this issue:
https://github.com/marionettejs/backbone.marionette/issues/1510

But nothing helps. Here are the main files:
https://gist.github.com/eyaleizenberg/e36cf461f6da81912476

Thanks a lot!

**Comment by paulfalgout** [comment]
Stale issue.  Closing @eyaleizenberg if you're still running into issues https://gitter.im/marionettejs/backbone.marionette is an invaluable resource.
