### ISSUE TITLE
Bizarre issue when initiating Composite Views

### ISSUE THREAD

**Issue by thisissami** [marionettejs/backbone.marionette#2117]
Here is this bizarre thing that I have come across. The following code works (where `this` is a `LayoutView`, `results` is a valid region, `col` is a valid collection, `LeaderboardResult` is a valid `ItemView` definition, and the template referred to is valid and contains a single ul element):

```
                this.results.show(new Marionette.CompositeView({
                    collection: col,
                    model: new Backbone.Model({type: 'Team'}),
                    childView: LeaderboardResult,
                    childViewContainer: 'ul',
                    template: '#leaderboardsTemplate',
                }));
```

The following code (with all the above definitions remaining the same), does not work:

```
                this.results.show(new TournamentListResults({
                    collection: col,
                    model: new Backbone.Model({type: 'Team'})
                }));

                    //elsewhere in the code
        var TournamentListResults = Marionette.CompositeView.extend({
            childView: LeaderboardResult,
            childViewContainer: 'ul',
            template: '#leaderboardsTemplate',
        });
```

Is there any reason for this being the functionality? I want to be able to reuse the composite view in several locations, and would rather have more concise code by being able to use the variable `TournamentListResults`.

**Comment by mix3d** [comment]
I don't know if I'm digging up an old issue here, but I had the same problem. What ended up fixing it, was by having the childView class extended/defined BEFORE the definition of the CompositeView class. Perhaps the runtime tries to extend the class before the Itemview is defined, therefore using itself as a fallback?  It might be further convoluted when combined with RequireJS, as I am using, but I thought it might be worth noting that the order of operations made a difference for me.

**Comment by Vanuan** [comment]
Why "model" is a model instance while "childView" is a class? This is a design problem. This really should be a string "childViewClassName".
