### ISSUE TITLE
Naming inconsistency between child view attribute and event prefix

### ISSUE THREAD

**Issue by johanalkstal** [marionettejs/backbone.marionette#2121]
I noticed that the child view attribute for `CollectionView`/`CompositeView` is camel cased like `childView:`, while child view events are prefixed with `childview` in lower case.

I think this needs to be fixed to be consistent. I've tripped on this a couple of times causing bugs when I've camel cased the event prefix.

**Comment by SauloSilva** [comment]
+1 
I also agree that currently exists this inconsistency.
I did [pull-request](https://github.com/marionettejs/backbone.marionette/pull/2185), to fix it.

**Comment by samccone** [comment]
this was merged!

**Comment by SauloSilva** [comment]
@samccone thanks man :D
