### ISSUE TITLE
Investigate first class support for virtual DOM

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2126]
I think this is very possible to support within marionette.
https://github.com/Matt-Esch/virtual-dom

#### Avenues of Investigate

* VDOM templating
* VDOM view render override
* VDOM nesting (think regions, layoutview's)

**Comment by samccone** [comment]
Hi @ram-you 
You can use this virtual DOM implementation https://github.com/tiagorg/Marionette.VDOMView right now!

**Comment by ram-you** [comment]
Thanks @samccone . I'll make a try.

**Comment by jmeas** [comment]
@ram-you, keep in mind that that is still a prototype, and only an ItemView implementation. @samccone @tiagorg would you say that it's ready for production?

**Comment by tiagorg** [comment]
Hey guys, I am going to publish it to npm and release a new version, I am
just finishing fixing some tests for CollectionView / CompositeView

I've found out that the VDOM always requires a parent node, so when the
template is not wrapped by a sole DOM element the approach doesn't work,
for instance when the template has more than one root element as
"<a>one</a><b>two</b>" or no elements at all as "single text"

So I am trying to wrap whatever is coming with a fake element and then
leaving it out of the real DOM, but that broke just a couple of other tests
which I believe I've found a solution last night

So please bare with me for a while and this should be operational very soon
:)

**Comment by samccone** [comment]
@jmeas I would say the itemView replacement is very much ready and we have proven that with our work on porting the test suite from BB, and Marionette over

but like anything new there is always a level of risk :)

**Comment by ram-you** [comment]
@jmeas This is just for internal testing until it is integrated into the official version of Marionette.

**Comment by samccone** [comment]
@ram-you I am fairly confident that this will never be a part of the official core lib, however I forsee it becoming a 'blessed" marionette core+ lib

**Comment by ram-you** [comment]
@samccone 
It is a pity. 
It could however deter those who think migrate to other frameworks because of the virtual-DOM (React for example).

**Comment by tiagorg** [comment]
@samccone @jmeas thanks for the "blessed" :) - BTW I would like to ask your blessing again as soon as I commit the changes I'm working on right now, I would really appreciate a code review...

In order to make the code reusable throughout ItemView and CompositeView I am now creating a mixing an using _.extend on regular Marionette's ItemView and CompositeView and the VDOM feature will be enabled/disabled through a property. I am about to check it in and I would like to know what you guys think about it :)

**Comment by tiagorg** [comment]
@ram-you I will let you know as soon as version 0.1.0 is released on NPM then please be more than welcome to try it out :)

**Comment by andrewvy** [comment]
Shouldn't the view template always default to be wrapped in a single div, could that be used as the parent node?

**Comment by tiagorg** [comment]
We've tried replacing ```this.el``` for the VDOM element itself but it didn't work on cases where ```el``` is provided during the instantiation - on that case a real DOM element would get replaced with a Virtual one and that broke many Backbone.js View tests....

So that is why we are trying to create a VDOM element from the template and appending it to ```this.el```...

**Comment by tiagorg** [comment]
Howdy!

I have finally released it on npm, yaay! At https://www.npmjs.com/package/marionette-vdom

I've also renamed the repo to ```marionette-vdom``` to be more consistent with the other packages over there.

The current version is 0.1.0-pre and I'm planning to release 0.1.0 as soon as I write more test cases for edge scenarios: https://github.com/tiagorg/marionette-vdom

Thanks very much everyone for the contribution so far, specially @samccone @megawac and @jmeas.

And @ram-you please feel free to start using it, it should go by doing ```npm install marionette-vdom``` :)

**Comment by tiagorg** [comment]
Going forward guys I would really appreciate if I could get some code review from you. @megawac has done some today and it has been great :)

Specially about the way I'm approaching using a mixin and parameter. If you think there is a better way, please let me know :+1:

**Comment by samccone** [comment]
Going to close... @tiagorg killed it with this one!
https://github.com/tiagorg/marionette-vdom

**Comment by tiagorg** [comment]
Only with a handy help from @samccone ;)

**Comment by JSteunou** [comment]
Well done guys!

**Comment by aMarCruz** [comment]
+1
and please, please, give us template transpilers, something like this:
https://github.com/Bobris/Bobril/tree/master/examples/jsx
or this
https://github.com/trueadm/t7

cc @samccone @Matt-Esch

**Comment by aMarCruz** [comment]
Latest FF already has native support for ES6 tagged templates, you can see running t7.js example w/o ES6->ES5 transpiler, Chrome soon... or using Babel, Typescript 1.5, etc.

**Comment by trueadm** [comment]
@aMarCruz t7.js is now supported natively in Chrome too. :)

Other good news is that Microsoft Edge (out next month) will also have support and so will Safari 9 (out later this year with iOS 9 and the new OS X).

**Comment by JSteunou** [comment]
You mean `Template String`, not `t7.js`.

**Comment by trueadm** [comment]
Sorry, to clarify t7.js (for in-browser compilation) depends on `template strings` and `template tags` – both ES6 features are available in the browsers I mentioned above.
