### ISSUE TITLE
Add `onDomRefresh` to list of deprecated features

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2128]
For v2.3

**Comment by jasonLaster** [comment]
So, i seem to remember a reason we can't do this?

**Comment by paulfalgout** [comment]
No I think we can do it.  And it is probably worth it.  

https://github.com/marionettejs/backbone.marionette/issues/2299  Reintroduce a simplified onDomRefresh
https://github.com/marionettejs/backbone.marionette/pull/2281 Refactor onDomRefresh

Related:
https://github.com/marionettejs/backbone.marionette/issues/2287 Move _isRendered and _isShown flags to respective views

**Comment by scott-w** [comment]
From what I can see, `dom:refresh` is no longer deprecated in v3?

**Comment by paulfalgout** [comment]
correct it is improved.  I think this can just go away
