### ISSUE TITLE
Deprecate RegionManager in v2.3 (removal in v3)

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2129]
RegionManager exists because both LayoutViews and Applications use them. We're removing Regions from app, so RegionManager could reasonably be merged directly into the LayoutView, saving us some LoC, such as [this craziness](https://github.com/marionettejs/backbone.marionette/blob/master/src/marionette.layoutview.js#L142-L161) and [this craziness](https://github.com/marionettejs/backbone.marionette/blob/master/src/marionette.layoutview.js#L53-L81). We don't *need* any of that bloat.

If we're concerned about getting rid of the entire class, or making LayoutView too big, then it should at least become a mixin, so that we don't have these unnecessary [proxy methods](https://github.com/marionettejs/backbone.marionette/blob/master/src/marionette.layoutview.js#L74-L76) that were the cause of many-an-issue in the period of 2.x in situations where the APIs didn't line up.

Down the road, I can see CompositeView getting rid of its custom Region-like code (childViewContainer...what the heck?) and using the same logic that the LayoutView does. So maybe a mixin makes more sense.

My long-term vision is that we have two types of views: View and CollectionView. The CollectionView would be unchanged, but the View would effectively just be a LayoutView, allowing you to nest child views indefinitely. To create a CompositeView, you would create a single Region and a render a CollectionView in there.* There could even be a new CompositeView class, if we wanted, that hid all of this rearranging from the end user, but exposed the *same exact API*. So it would be a transparent update (tho' still breaking technically). This would cut the codebase of the views by a huge amount...like 25% or more, I would wager.

\* If you're particularly familiar with these APIs, you'll know that you can't simply replace the `childViewContainer` with a region. The reason being that a Region + CollectionView adds two wrapper elements, whereas a `childViewContainer` only wraps the collection once. How do we fix this incompatibility? https://github.com/marionettejs/backbone.marionette/issues/1976!

**Comment by jcrben** [comment]
Was regionManager actually deprecated? The docs don't say anything about that. http://marionettejs.com/docs/v3.0.0-pre.2/marionette.regionmanager.html

**Comment by paulfalgout** [comment]
The v3 docs are definitely a WIP. It wasn't a documented deprecation until https://github.com/marionettejs/backbone.marionette/blob/next/docs/marionette.regionmanager.md#marionetteregionmanager

But they're removed in v3.  Do you use it directly?

**Comment by jcrben** [comment]
Thanks! No, don't use it directly.
