### ISSUE TITLE
Add `items` to CompositeView?

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2131]
An ItemView can accept either a model or a collection, but it isn't intended to have both. When a model is passed in, that model is available in the template. When a collection is included, that collection is available in the template under the variable `items`.

A CompositeView is like an ItemView in that it has a template and accepts both a model and a collection. However, the collection is not made available in the template.

Should it be?

Ref [#2127(comment)](https://github.com/marionettejs/backbone.marionette/issues/2127#issuecomment-66798521)

**Comment by ahumphreys87** [comment]
Im gonna close this as we're pushing ahead for 3.0 and we're gonna deprecate `CompositeView` anyway
