### ISSUE TITLE
Mn.$ & Mn._

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2139]
I like Angular's approach to DOM manipulation and functional programming helpers. It provides the bare minimum set that it needs for the internal library to function, and nothing more.

In the case of DOM manipulation, there's a little 'jqLite' object available at `Angular.$`. Need all of jQuery or Zepto or whatever? Just pull it in and replace Angular.$.

In the case of functional methods, they just attach them directly to the Angular object.

It's a lot easier to make the case for $ than it is _, so I'll start there. Backbone doesn't depend on jQuery, and this has caused us a lot of problems in the past. 

===

I wish there was a save as draft version cuz im tired of typing this. Gonna hit submit and finish it l8r

**Comment by megawac** [comment]
Thought about this a bit and started implementing. I feel like the MVP for a `$lite` implementation is

- IE>8 support
- promises (A+ not that jquery nonsense)
- `.ajax()` implementation
- `ready()`
- selector engine exposing
    - next, find, eq, children, after, parent
- events
- Several of the dom methods
   - css
   - empty
   - remove
   - hide/show
   - toggle + attr/class
   - attr
   - prop
   - val
   - append/prepend
   - html
   - text
   - detach
- ~~getScript~~

I also want to have nodejs support via jsdom and cheerio

**Comment by samccone** [comment]
just to be clear, if we just a custom DOM lib we are now taking all the responsibility of making sure this all works. With jquery we do not have to worry about that. Just something to think about

**Comment by megawac** [comment]
We don't need to create a dom lib and thats not what I'm going for with
this. jsdom will be the engine for node +cheerio and document +
sizzle/slick/qwery will be the selector engine for the browser

**Comment by samccone** [comment]
:+1:

**Comment by capricube** [comment]
Hi, i'm little late to this discussion but doesn't https://github.com/akre54/Backbone.NativeView remove the jquery dependency from backbone? ﻿﻿From Mn's point of view there are only a few jquery methods missing.

**Comment by ahumphreys87** [comment]
@megawac did you get anywhere with this? This is conflicting with #2300 - @marionettejs/marionette-core should we nail down what we wanna do here?

**Comment by ahumphreys87** [comment]
Im actually working on a Marionette.Native plugin which makes use of https://github.com/akre54/Backbone.NativeView and https://github.com/akre54/Backbone.Fetch. It's quite close now and I think the plugin route is the correct way for us now with v3. We have abstracted a lot of the `$` usage so it can be overriden.
