### ISSUE TITLE
CollectionView: use childViewOptions.template cause emptyView to use childView template

### ISSUE THREAD

**Issue by blacroix** [marionettejs/backbone.marionette#2142]
If I define a childViewOptions with a template field for custom childView templates the emptyView gets the childView's template.

See:

````
// get the emptyViewOptions, falling back to childViewOptions
    var emptyViewOptions = this.getOption('emptyViewOptions') ||
                          this.getOption('childViewOptions');
````

Line 205-206 of *marionette.collectionview.js*

Last version of Marionnette.

**Comment by paulfalgout** [comment]
Stale issue.  Closing @blacroix if you're still running into issues https://gitter.im/marionettejs/backbone.marionette is an invaluable resource.
