### ISSUE TITLE
Global templateContext

### ISSUE THREAD

**Issue by jamesplease** [marionettejs/backbone.marionette#2164]
Template helpers are just extra data added to the data available in your template. There should be an easy way to configure global template helpers.

@jakobdamjensen implemented this recently in his app by modifying the templateHelpers prop on the View prototype. This isn't ideal because future views would need to `_.extend(View.prototype.templateHelpers, myTemplateHelpers)`, which should not be necessary.

There should just be a way to specify global template helpers. I'm thinking a possibility would be adding them to the Renderer object.

``` js
Mn.Renderer = {
  // global template helpers
  templateHelpers: {}
};
```

Then we would mix that in [here](https://github.com/marionettejs/backbone.marionette/blob/master/src/view.js#L46-L53).

//cc @jakobdamjensen

**Comment by bgaillard** [comment]
@jmeas  :+1: :+1: :+1:  This feature is definitly a must have, we need it in almost all our Marionette projects.

Because it "seems to be very simple" to implement and does not break the APIs it could be great to have it in a 2.5 version of Marionette (is this version scheduled ?). 

I know their is a discussion to rename `templateHelpers` into `templateContext` https://github.com/marionettejs/backbone.marionette/issues/2166 for Mn 3.X.

So for version 2.5 we could keep `templateHelpers` and change this name into `templateContext` for version 3.X ? 

```javascript
// Version 2.5
Mn.Renderer.templateHelpers = { ... };
// In Marionette View code
mixinTemplateHelpers = function(target) {
    target = target || {};
    var templateHelpers = this.getOption('templateHelpers');
    templateHelpers = Mn._getValue(templateHelpers, this);
    target = _.extend(target, Marionette.Renderer.templateHelpers); // Only one line added
    return _.extend(target, templateHelpers);
};

// Version 3.X
Mn.Renderer.templateContext = { ... };
// In Marionette View code
mixinTemplateContext = function(target) {
    target = target || {};
    var templateContext = this.getOption('templateContext');
    templateContext = Mn._getValue(templateContext, this);
    target = _.extend(target, Marionette.Renderer.templateContext);
    return _.extend(target, templateContext);
};
```

Temporarily in Mn 2.4.X we add this in our projects to make it work.
```javascript
/**
 * Function used to overwrite the "standard" Marionette `Marionette.View.mixinTemplateHelpers(target)` method to be 
 * able to use global template helpers.
 * 
 * @param {Object} target The data to mixin (i.e where to attach additional template helper methods).
 */
Mn.View.prototype.mixinTemplateHelpers = function(target) {
    target = target || {};
    var templateHelpers = this.getOption('templateHelpers');
    templateHelpers = Mn._getValue(templateHelpers, this);
    target = _.extend(target, Mn.Renderer.templateHelpers); // Only one line added
    return _.extend(target, templateHelpers);
};
```

**Comment by jasonLaster** [comment]
@bgaillard this could be a PR for the `next` branch. I think people would like something if it doesn't break APIs

**Comment by ianmstew** [comment]
We do not currently have a `2.5` scheduled so that we avoid pushing off `3.0` further, but if there's enough support for a `2.5` we can cherry-pick off of `next`.

**Comment by Seebiscuit** [comment]
Any traction here recently? I was once working on this and wouldn't mind revisiting. However, I'm not a unit testing expert (read, I know sh*t about unit testing) so if someone would be interesting in partnering in testing include a mention.

Would this be on `3.0` or before?

cc @paulfalgout

**Comment by paulfalgout** [comment]
I think it'd be on `templateContext` for `3.x`  If you get this started we can look at the unit testing.

**Comment by paulfalgout** [comment]
@Seebiscuit any luck?

**Comment by Seebiscuit** [comment]
@paulfalgout What do you think of @bgaillard idea above? Maybe he'd like to make the PR? 

Looks reasonable.

**Comment by paulfalgout** [comment]
I don't actually know why we necessarily want to add it to the renderer.  I think it could live in its own module in `v3`
The implementation looks good, though I think it can be done in a single `_.extend(target, globalTemplateContext, templateContext)`

**Comment by Seebiscuit** [comment]
How would we initially set the `globalTemplateContext`? I think it lends itself to a standalone module. Mainly because I feel we should use a setter of some sort. This is more stylistical, rather than functional. But exposing globalTemplateContext feels wrong.

I'm also thinking `mixinTemplateHelpers` should be in the closure of `Mn.View` and be invoked in the constructor. 

I'm swamped, but I'll try to slap a PR together soon. @paulfalgout should I sub the PR and sorry about tests later?

**Comment by paulfalgout** [comment]
This might be a terrible idea.. but we could define something on the `Marionette.View.constructor`  so that you'd call `Marionette.View.setTemplateContext({  myGlobalContext: 'foo' });`  So it wouldn't be something you'd extend on any particular view.

Not sure about the `mixingTemplateHelpers` in the constructor.. seems like that'd have to happen each `render`

**Comment by Seebiscuit** [comment]
The first point is not totally horrendous. After all, `globalTemplateContext` is a `View`-specific property , albeit not specific to any one view) so there's some sense to make it available to the `Mn.View`. On the other hand, positioning the setter in `View` tends to encourage setting the `globalTemplateContext` from any view instance. That may be hard to debug.

Although it may be a pain in practice, I'm an advocate of having a high level location for the setter. What I'm thinking is something along the lines of placing a reference to the `globalTemplateContext` module at the root (`Mn.templateContext`). So you would use the setter like:

```
Mn.templateContext.set(...);
```

Of course, the trade-off is the we pollute the root with `View`-specific functionality. So, I can go both ways on this. And maybe we're back to `Mn.Renderer.globalTemplateContext`...

And now that you mention it, 'Doh!', of course you want to `mixinTemplateHelpers` in the `render`, I can see the `templateHelpers` being modified in between renders.

**Comment by paulfalgout** [comment]
Ah so I was thinking of using it more statically like..
```js
Marionette.View = Backbone.View.extend({
  functionsAvailabletoViewInstances: function() {}
}, {
  setTemplateContext: function(context) {}
});

// so that
const MyView = Marionette.View.extend({
  onRender() {
    this.setTemplateContext // undefined
  }
});

// to set the global template context you'd call
Marionette.View.setTemplateContext({});
```
Although now that I've written that out.. `CollectionView` isn't a `View`.. so that'd be 2 interfaces for the same thing.  :disappointed:

**Comment by paulfalgout** [comment]
Actually now that I think about it, particularly since `CompositeView` is deprecated, `CollectionView` has no use for `templateContext` so it absolutely makes sense for it to only be available off of `Marionette.View`

**Comment by reidcooper** [comment]
Bump, interested in having a parent view with a set of templateHelpers that will be inherited by all views that extend from it.

**Comment by paulfalgout** [comment]
So there seems to be some varying opinions on how this should be addressed and any solution provides some sort of perf hit when it may not be used in general.
When situations like this arise it's probably best to leave this to individual configuration or 3rd party plugins provided adequate hooks are provided to implement the functionality.
In this case, `mixinTemplateContext` should meet the requirements
```js
mixinTemplateContext(serializedData) {
    const templateContext = _.result(this, 'templateContext');
    if (!templateContext) { return serializedData; };
    if (!serializedData) { return templateContext; };
    return _.extend({}, serializedData, templateContext);
  }
```
where you could easily
```js
const originalMixinTC = View.prototype.mixinTemplateContext;
View.prototype.mixinTemplateContext = function() {
  const templateContext = originalMixinTC.apply(this, arguments);
  return _.defaults(templateContext, myGlobalTC);
}
```

So I'll add this to the v4 docs and if anyone feels strongly against this suggestion, we can revisit.
