### ISSUE TITLE
isDestroyed and isRendered need to be made private with a public accessor method.

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2170]
https://github.com/marionettejs/backbone.marionette/pull/2138#issuecomment-68226080

**Comment by ahumphreys87** [comment]
shouldn't this wait till v3? it's breaking if people are using `view.isRendered` or `view.isDestroyed`.

**Comment by cmaher** [comment]
Definitely breaking, and `isRendered ` was added specifically by user request.
