### ISSUE TITLE
Hogan.js

### ISSUE THREAD

**Issue by ram-you** [marionettejs/backbone.marionette#2173]
Hi and happy new year.
I find that using Hogan.js is better than Handlebars in term of size and speed. Can someone help me integrate Hogan.js along with Marionette ?
Thank you.

**Comment by jmeas** [comment]
Precompile your templates, and it will just work (you should be recompiling!). Otherwise, look into overriding [this method](https://github.com/marionettejs/backbone.marionette/blob/master/src/template-cache.js#L93) on the `templateCache` object. Marionette's compile logic is there.
