### ISSUE TITLE
Major branch tests do not pass

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2179]

**Comment by jmeas** [comment]
#2138 broke major branch, so I dropped the commit.

**Comment by duncanbeevers** [comment]
@jmeas What failures are you seeing?

![screen shot 2015-01-07 at 8 19 35 am](https://cloud.githubusercontent.com/assets/7367/5646857/f6cc3c7a-9645-11e4-8868-019c475f011b.png)

**Comment by duncanbeevers** [comment]
Opened #2182 applying to `major`
