### ISSUE TITLE
Add isRendered to views

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2180]
Added in #2138, but it broke major (#2179), so I dropped the commit. We need to redo the PR, making sure it passes before merging.

**Comment by jmeas** [comment]
This will be resolved by #2182 

===

In reply to [this comment](https://github.com/marionettejs/backbone.marionette/issues/2179#issuecomment-69027330)

> @jmeas What failures are you seeing?

None after I dropped the commit, but the tests were failing in yesterday's version of major branch, which was something along the lines of 6 behind and 2 ahead of master (those 2 being your commit + the merge). When I dropped your commits the tests passed, so I dropped 'em and rebased and all was well.

**Comment by samccone** [comment]
fixed
