### ISSUE TITLE
Doc links in each readme are 404s

### ISSUE THREAD

**Issue by alpacalips** [marionettejs/backbone.marionette#2190]
The links to the 'View the new docs' are 404s

Reference: https://github.com/marionettejs/backbone.marionette/commit/a1a492e3630ed22f2aa2af2ece0509aabb306065#diff-5415d2a99ad5528e202f6d699e40da9a

**Comment by SauloSilva** [comment]
@alpacalips @samccone [fixed](https://github.com/marionettejs/backbone.marionette/pull/2191/files)

**Comment by alpacalips** [comment]
I could be wrong but I think the intention is to show the current docs when the version is omitted from the url. Otherwise, the readme files would require updates on every version bump.

**Comment by samccone** [comment]
:+1: fixed cross stream, thanks for the issue and the work guys! Appreciate it a bunch :)

https://github.com/marionettejs/marionettejs.com/commit/f19583abf8a5872f92bdbcf9821fa05df4dd8d78

**Comment by SauloSilva** [comment]
@samccone really the best way to do Thanks guys.
