### ISSUE TITLE
Add a Marionette inspector console.log

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2193]
React does this, and I think it is a nice idea.

cc @jasonLaster @jdaudier

**Comment by jasonLaster** [comment]
So does ember and other dudes. I don't think we're ready yet for that.

My take on this is that when the Inspector is 1.0 we can do that. or when I get power hungry... whichever comes first.

**Comment by samccone** [comment]
kk

**Comment by jmeas** [comment]
Can someone explain this issue/feature/thing to me in more detail? :open_mouth:

**Comment by thejameskyle** [comment]
@jmeas For an example: http://emberjs.com/guides/understanding-ember/debugging/#toc_log-router-transitions

**Comment by jasonLaster** [comment]
oh actually - was thinking something different. inspector logging makes a lot of sense and you should add some tickets to the inspector project for that too...

@samccone - I thought you were saying that we should add a `console.log("Marionette Inspector: use that shit")` promo.

**Comment by samccone** [comment]
yep that is what i was saying @jasonLaster

**Comment by thejameskyle** [comment]
Oh, uh how do I put this... no.

**Comment by samccone** [comment]
mind explaining @thejameskyle I think it is a nice thing, and obviously react and angular agree at some degree (with a wayyy less robust inspector than @jasonLaster and team has built). The motivation in my mind was to improve developer experience by letting them know we have this amazing tool they can use to make their lives easier.

**Comment by jmeas** [comment]
Both of these are great ideas, I think!

A dev tools console log is a great way for us to market the inspector. If @jasonLaster thinks we should hold off a bit before doing that, then that's fine. I'd love to see it added one day, though.

@thejameskyle, how come you're so against it?

**Comment by thejameskyle** [comment]
If we add it the first thing people will ask is how to turn it off.

**Comment by megawac** [comment]
I think its fine if we start doing `debug` builds in which we include `error` and `deprecate`, otherwise I'd be against it

**Comment by jmeas** [comment]
Ohhh...You know what...I was thinking this would be for the website, and not Marionette itself.

**Comment by samccone** [comment]
it is already on the website actually
