### ISSUE TITLE
behaviors should be able to be passed in as options to a generic view class

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2195]
```js
new Marionette.ItemView({
  behaviors: {
    fooBehavior: {}
  },
  model: zapModel
});
```

This should be a simple tweak to this line here
https://github.com/marionettejs/backbone.marionette/blob/master/src/behaviors.js#L21

any thoughts or objections from anyone?

**Comment by jmeas** [comment]
I can't come up with any compelling reason why they shouldn't be able to be passed as options, so I'm cool with the change.

One thing to think about is that Behaviors are effectively mixins. Do we want our mixins to be used to define classes, or should they work as properties that can be used to *configure* a pre-existing class? For whatever reason, I tend to think of them more like the former, but, again, I don't see any issues by letting them be passed in an as option.

Perhaps the *only* thing I can think of is that it might put us on a slippery slope of what can be passed in as options. For better or worse, Backbone doesn't let you customize *everything* about a Class via options. Take `view`, for instance. You can't pass a `template` in as an option to a view.

If we become more lenient in what we accept as options, people might ask us to go all the way with it. Shrug. This possibility isn't enough to make me want to avoid this change, though. Unless anyone has any more thoughts on the above, I say we make the change.

**Comment by jasonLaster** [comment]
I like it. It passes my, could I see myself wanting this test! This could be especially nice if you're setting up behavior options:



options,behaviors.dropdown.multiSelect = true
show(new view(options))

**Comment by ahumphreys87** [comment]
moving to #2386
