### ISSUE TITLE
How about Views contaner view?

### ISSUE THREAD

**Issue by isergey** [marionettejs/backbone.marionette#2199]
Hi! 
Marionette have ItemView (for rendering model), CollectionView (for rendering collection), CompositeView (for rendering collection plus some info), LayoutView (for containing views in regions). How about ViewsContainer (name for example) for containing views (as LayoutView ) and rendering them without regions and collections? 

```javascript
var viewsContainer = new Marionette.ViewsContainer([
  new ItemView({..}),
  new LayoutView({..})
]);
```
When it is rendering, html will looks as this:
```html
<div> //viewsContainer element
  <div></div> //ItemView el
  <div></div> //LayoutView el
</div>
```

**Comment by jmeas** [comment]
Hey @isergey, you've identified two things here: a problem, and a possible solution.

Re: the problem

Being unable to manually place child views next to one another is one that we're aware of. The solution we've been discussing involves letting regions' elements [be swapped for their view's element](https://github.com/marionettejs/backbone.marionette/issues/1976). This has already been done in the wild over in [minionette](https://github.com/jridgewell/minionette), and it seems to work great. //cc @jridgewell

Re: the solution

Although there aren't plans to add a ViewsContainer to Marionette at the moment, I can see the utility to the API. In fact, your ViewsContainer API reminds me of Ember's [ContainerView](http://emberjs.com/api/classes/Ember.ContainerView.html). Is that where you got the idea? Perhaps one day we can implement that.

What do you think about the ability to swap a region's elements?

**Comment by jmeas** [comment]
Oh, another thing that I forgot to mention is that we've been discussing is the idea of a Multiregion, which is **very** similar to the ContainerView.

**Comment by jridgewell** [comment]
In Minionette terms, this _can_ be achieved using custom `#template()` and dynamically adding regions. I wouldn't recommend it, though.

In Marionette terms, it seems like you're asking for a MultiRegion. Are you creating a dynamic number of subviews that you want to render? If not, is there anything wrong with just using normal regions?

**Comment by isergey** [comment]
Thanks to all!
The idea with ContainerView came from the fact that I do not want to allocate the region in separate DOM element. Also, I want to be able to store an any number of sub views, which is not limited by the number of elements in the template.

**Comment by jridgewell** [comment]
> The idea with ContainerView came from the fact that I do not want to allocate the region in separate DOM element.

As @jmeas said, Minionette achieves this by swapping the region's element with the subview's as opposed to Marionette appending the subview to the region's el.

> Also, I want to be able to store an any number of sub views, which is not limited by the number of elements in the template.

This is MultiRegion territory. I've never had this use case myself, outside of rendering a collection of models which is better handled by a `CollectionView`.

**Comment by thejameskyle** [comment]
> This is MultiRegion territory. I've never had this use case myself

On the app I'm working on we have a PageView class which is used across routes which always contains a number of subviews called ModUnits (blame @toekneestuck for that name). These ModUnits need to be displayed in a particular order but also don't belong to any collection.

We could create an arbitrary Collection and stuff them in a CollectionView, but all of the childViews would be different subclasses of the original ModUnit. It also would be creating a lot of extra code to hack around the framework.

We could subclass PageView for each individual page and add in regions for the Views before inserting them, but this creates duplicated code to again hack around the framework.

Right now we ended up making a much larger PageView class which can accept config to do some hacky stuff to get the behavior we want.

**Comment by jridgewell** [comment]
> PageView class which is used across routes

> always contains a number of subviews called ModUnits. These ModUnits need to be displayed in a particular order

It's a new `PageView` for each route, correct? Regions are just there to allow it's subview to be swapped with something else later. If that's not needed, wouldn't just `$#append` take care of this?

> Right now we ended up making a much larger PageView class which can accept config to do some hacky stuff to get the behavior we want.

I don't want to sound like I'm debating your code, I'm just genuinely interested. It seems like MultiRegions are a real need, and I've never run into it. Could you post sample code of the solution you ended up with?

**Comment by thejameskyle** [comment]
> It's a new PageView for each route, correct?

Not necessarily... there's a lot of complexity around it. 

> Regions are just there to allow it's subview to be swapped with something else later.

That would happen in a lot of places if we were actually regions, right now we are not because they don't do what we would need.

> wouldn't just $#append take care of this?

I believe it comes down to something similar to that. I wish there was an API around this though, especially so we could use the Marionette Inspector.

> I don't want to sound like I'm debating your code, I'm just genuinely interested.

I don't think any of us are happy with it, so no worries. 

> It seems like MultiRegions are a real need, and I've never run into it. Could you post sample code of the solution you ended up with?

I could, but it's very over-engineered atm so it'd be difficult to pull out into a small demo. It'd be easier just to create one. So here you go: http://jsbin.com/kuwux/1/edit?js,output

**Comment by isergey** [comment]
Hi all!
I found this http://justspamjustin.github.io/BossView/ . This is similar to what I said at the beginning of the discussion. Maybe it should be included in the standard library?

**Comment by ahumphreys87** [comment]
@isergey i think this can be accomplished now in Mn 3.0.

Views can now replace the regions element when shown. So you could have a View with 2 regions, with child views shown in each one, setting `replaceEl` to true. This will give you the desired markup above.

http://marionettejs.com/docs/master/marionette.collectionview.html#tables-using-marionette-3

This is an example with 1 child, but it should give you an idea.

**Comment by isergey** [comment]
Hello from future :) How I can make, for example, toolbar with dynamically adding buttons? It's look like this:
```javascript
new ToolbarView().add(new ButtonView('Open')).add(new ButtonView('Close'))
``` 

I understand that the need to manually implement this behavior . But it is very often the case that must be solved to create a desktop like interfaces . I think this may be necessary to provide " out of the box "

**Comment by paulfalgout** [comment]
```js

**Comment by paulfalgout** [comment]
alternatively
```js
const ToolbarView = Mn.CollectionView.extend({ sort: false });
new ToolbarView().addChildView(new ButtonView('Open')).addChildView(new ButtonView('Close'));
```
