### ISSUE TITLE
Resolver pattern

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2207]
Right now we have a resolver for Behaviors called `behaviorsLookup`. Resolvers allow you to access global objects from anywhere in the application by key.

For instance:

`resolve('something');` => returns whatever object is associated with the key

At the moment our Behaviors resolver throws an error by default. I have three suggestions for our resolvers:

1. Standardize the API
2. Never throw an error by default. Create conventions.
3. Consider using it in other places

Ember uses this pattern all over the place. While I don't think that we need it all over the place, I can see us using it for Behaviors and Templates. Here's one idea for what this could look like:

```js
Marionette.resolveTemplate(templateName) {
  return Marionette.templates[templateName];
}

Marionette.resolveBehavior(behaviorName) {
  return Marionette.behaviors[behaviorName];
}
```

There's a lot more to say about this, but I figured I'd put these thoughts down in an issue for now :thought_balloon:

**Comment by jfairbank** [comment]
I'll admit I initially had not been a fan of this pattern, at least not pulling from some global app object (i.e. `myApp.Behaviors`). I always preferred pulling in the behaviors I desired and using `behaviorClass`, but that syntax does get tiring. I think I have warmed up to this pattern more. If we standardized this and maybe even leveraged Radio requests, then that could be really nice.

**Comment by jmeas** [comment]
> If we standardized this and maybe even leveraged Radio requests, then that could be really nice.

That's a really cool idea.

**Comment by thejameskyle** [comment]
I disagree with using this for behaviors, this is the api I would want to see: #2214

**Comment by cmaher** [comment]
So this is basically a service locator, which is basically dependency injection. From my experience, string-based DI in JS doesn't work too well, because it separates your code from your dependencies.  I'd much rather inject via known dependencies than mystery strings. I have a very simple type-based [dependency injector](https://github.com/cmaher/capacitor/blob/master/lib/injector.js) I've been using in capacitor that ensures dependencies are loaded before requested. I'm not sure I see the need to officially support a stringly-typed service locator.

**Comment by ahumphreys87** [comment]
I'm :+1: for this.

**Comment by paulfalgout** [comment]
So personally I don't think Marionette needs to support this.  For the most part people are probably using (hopefully) some other form of `import` `require` etc and aren't registering elements on a global object.  However it seems trivial to implement a pattern like this on your own, outside of Marionette if you wanted to.

I'd vote to close this 👎

**Comment by scott-w** [comment]
I'm also :-1: on this. I'm not a fan of `behavioursLookup` at all and I much prefer to do it with import/require. I think JavaScript has some good answers to the library problem nowadays and we have them reasonably well documented.

**Comment by paulfalgout** [comment]
Anyone disagrees, comment here and we can reopen.
