### ISSUE TITLE
onAttach documentation clarity

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2208]
The phrasing of the following statement, [found here](http://marionettejs.com/docs/marionette.view.html#view-attach--onattach-event), could use some work:

> Because the attach event is only fired when the view is a child of the document, it is a requirement that the Region you're showing it in be a child of the document at the time that you call show.

The statement seems to imply that if a user calls "region.show" before the region is a child of the document then Marionette will throw an error. In reality, the onAttach event will not fire for the child view being shown until the region becomes a child of the DOM.

**Comment by samccone** [comment]
@MeoMix would you like to open a PR?
