### ISSUE TITLE
Write documentation link test

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2211]
we always have broken links, which is stupid. A small program that downloads the pages and tests the links for 200s would catch this.

**Comment by megawac** [comment]
Is that true on the new site as well?

**Comment by samccone** [comment]
yeah that is fixed, I think Jason is more talking about the internal doc links that we have in the repo

**Comment by jasonLaster** [comment]
Yup

**Comment by peterblazejewicz** [comment]
Do you mean functional tests? TryGhost uses Phantom/Casper for quick tests of these kind:
https://github.com/TryGhost/Ghost/blob/master/core/test/functional/routes/frontend_test.js
More general example from Casper:
https://gist.github.com/n1k0/4509789

**Comment by samccone** [comment]
going to move this to the www repo
