### ISSUE TITLE
Region.show fails _ensureElement in onRender when regionClass is defined.

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2213]
I'm able to successfully call region.show in onRender when I'm using a simple region. If I define a regionClass then it errors in _ensureElement.

Link to fiddle: http://jsfiddle.net/MeoMix/gscnvsob/

	var MyView = Marionette.LayoutView.extend({
		template: _.template('<div id="workingRegion"></div><div id="brokenRegion"></div>'),    
		
		regions: {
			workingRegion: '#workingRegion',
			brokenRegion: {
				el: '#brokenRegion',
				regionClass: Marionette.Region
			}
		},
		
		onRender: function(){
			this.workingRegion.show(new Marionette.ItemView({ template: false }));
			this.brokenRegion.show(new Marionette.ItemView({ template: false }));
		}
	});

	(new MyView()).render();

**Comment by MeoMix** [comment]
Just kidding. I need to use selector instead of el, apparently.

**Comment by samccone** [comment]
:dog: :+1:
