### ISSUE TITLE
Behaviors api

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#2214]
@jmeas mentioned using resolvers for behaviors in #2207 which got me thinking to the api.

I believe we've all agreed in the past that the current `behaviorsLookup` is generally not very good and we all use `behaviorClass` instead.

Well based on my ideas in #2202, I would like to propose the following:

```js
import FormBehavior from '../behaviors/form';
import ModalBehavior from '../behaviors/modal';

export default var LoginForm = View.extend({
  behaviors: {
    form: FormBehavior,
    modal: ModalBehavior
  },

  form: [{
    type: 'text',
    attr: 'username'
  }, {
    type: 'password',
    attr: 'password'
  }],

  modal: {
    overlay: true,
    size: 'large',
    speed: 100
  }
});
```

What this does it first take a map of names to behavior classes:
```js
behaviors: {
  form: FormBehavior,
  modal: ModalBehavior
}
```
Using their names to pass them options in an api that makes sense to them and doesn't need to be cluttered with `behaviorClass`. 

```js
form: [{
  type: 'text',
  attr: 'username'
}, {
  type: 'password',
  attr: 'password'
}],

modal: {
  overlay: true,
  size: 'large',
  speed: 100
}
```

We can even change our events api to work around these names:
```js
view.trigger('modal:open');
view.on({
  'form:invalid': () => view.trigger('modal:shake'),
  'form:valid': () => view.trigger('modal:close')
});
```

The great thing about this is that it leaves the naming up to the user. If I want to use `FooBehavior` but already have a `foo` property, I can call it `bar` and have everything work seamlessly.

**Comment by jmeas** [comment]
lgtm

**Comment by jasonLaster** [comment]
We discussed this api early on. Ultimately decided against it because it was one extra step. I do think it's nice though. 

Maybe we make the options key more specific. So instead of form, it's formOptions. That way it's clearer. Think childViewOptions.

**Comment by thejameskyle** [comment]
@jasonLaster Not sure about `formOptions`. I don't like the idea of us creating keys via manipulating strings (`triggerMethod` already drives me slightly crazy) and there's no associated `form` object. (ie. `childViewOptions` is to `childView` as `formOptions` is to...?).

**Comment by jfairbank** [comment]
> Maybe we make the options key more specific. So instead of form, it's formOptions. That way it's clearer. Think childViewOptions.

Yes, I think some way to denote what is being defined. That would ease the mental burden a little more. I don't know about the previous API that had been discussed, but what if all the options where wrapped in `behaviorOptions: { ... }`? It's a little more to type, but I'm not a fan of just defining keys that you have to remember are associated with a given behavior. That may require users to juggle naming if they wanted to define some custom properties on a view too.

**Comment by thejameskyle** [comment]
The problem with `behaviorOptions` is that it's not extensible, it requires extra work to subclass an object with defined `behaviorOptions`.

```js
var ModalBehavior = Behavior.extend({...});
var FormBehavior = Behavior.extend({...});

var ModalView = View.extend({
  behaviors: {
    modal: ModalBehavior
  },

  behaviorOptions: {
    modal: {
      // ...
    }
  }
});

var FormModalView = ModalView.extend({
  behaviors: _.extend({}, ModalView.prototype.behaviors, {
    modal: ModalBehavior
  }),

  behaviorOptions: _.extend({}, ModalView.protoype.behaviorOptions, {
    modal: _.extend({}, ModalView.prototype.behaviorOptions.modal, {
      // ...
    }),
    form: {
      // ...
    }
  })
});
```

The further away from that we can get the better. I don't yet see a way of eliminating the `behaviors` object, but I'd certainly like to.

Behaviors in its current form isn't at all object-oriented and mixins are _significantly_ better and simpler.

**Comment by jasonLaster** [comment]
Meh. Straw man arg. I'd just use a function in the subclass instead of that ugly extend business. But yea fooOptions, barOptions where foo and bar would probably rarely be overriden and extended.
