### ISSUE TITLE
Marionette.bindEntityEvents docs are misleading

### ISSUE THREAD

**Issue by okitu** [marionettejs/backbone.marionette#2215]
Hi there,

is just read the docs for Marionette.bindEntityEvents.

http://marionettejs.com/docs/v2.3.0/marionette.functions.html#marionettebindentityevents

the parameter description for the 'entitiy' say

*The second parameter is the entity (Backbone.Model or Backbone.Collection)
to bind the events from.*

But actually, the entity can be any object, that implements Backbone.Events.
Or am i missing something?

**Comment by jmeas** [comment]
Thanks @okitu! You're absolutely right. Would you have time to make a PR to fix this mistake? The docs are in this repository under the `docs` folder.

**Comment by okitu** [comment]
Done =)

**Comment by samccone** [comment]
this has been fixed :dancer:
