### ISSUE TITLE
Remove Behaviors in favor of Mixins

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#2216]
For the reasons I outline [here](https://github.com/marionettejs/backbone.marionette/issues/2214#issuecomment-70541866) I believe this is worth discussing. I know @jasonLaster will want to kill me, but here goes anyways. 

---

Behaviors (in their current form) are not subclass-able and therefore not object-oriented enough to make sense in larger applications.

```js
var ModalBehavior = Behavior.extend({...});
var FormBehavior = Behavior.extend({...});

var ModalView = View.extend({
  behaviors: {
    modal: {
      behaviorClass: ModalBehavior,
      // options...
    }
  }
});

var FormModalView = ModalView.extend({
  behaviors: _.extend({}, ModalView.prototype.behaviors, {
    modal: _.extend({}, ModalView.prototype.behaviors.modal, {
      // additional options...
    }),
    form: {
      behaviorClass: FormBehavior,
      // options...
    }
  })
});

var LoginView = FormModalView.extend({
  behaviors: _.extend({}, FormModalView.prototype.behaviors, {
    modal: _.extend({}, FormModalView.prototype.behaviors.modal, {
      // additional options...
    }),
    form: {
      behaviorClass: FormModalView.prototype.behaviors.form.behaviorClass,
      // overwrite options...
    }
  })
});
```

This is absurd when you compare it to the accepted alternative:

```js
var ModalMixin = Behavior.extend({...});
var FormMixin = Behavior.extend({...});

var ModalView = View.extend({
  modal: {
    // options...
  }
}).mixin(ModalMixin);

var FormModalView = ModalView.extend({
  modal: _.extend({}, ModalView.prototype.modalOptions, {
    // additional options...
  }),
  form: {
    // options...
  }
}).mixin(FormMixin);

var LoginView = FormModalView.extend({
  modal: _.extend({}, FormModalView.prototype.modal, {
    // additional options...
  }),
  form: {
    // overwrite options...
  }
});
```

Behaviors are not well defined, confusing, and specific to Marionette. Mixins are an accepted computer science concept which is used in lots and lots of applications across languages and frameworks.

**Comment by jmeas** [comment]
:+1:

**Comment by jasonLaster** [comment]
Not sure if you're proposing changing the way behaviors are setup or the underlying behavior :)

Now. WRT to CS I think the OO ppl are fine w/ multiple delegation schemes. Wouldn't want to anger the gods.

**Comment by megawac** [comment]
If only `_.create` did a deep merge of properties -- you goofed it @thejameskyle https://github.com/jashkenas/underscore/pull/1907!

```js
var FormModalView = ModalView.extend({
  behaviors: _.create(ModalView.prototype.behaviors, {
    modal: {
      // additional options...
    },
    form: {
      behaviorClass: FormBehavior,
      // options...
    }
  })
});
```

*sigh*

**Comment by thejameskyle** [comment]
> If only `_.create` did a deep merge of properties -- you goofed it @thejameskyle

_Pfff_, don't pretend that wouldn't be rejected.

**Comment by megawac** [comment]
It wouldn't have stood a chance

**Comment by jasonLaster** [comment]
Let's discuss the merits / implementation details of mixins in a new issue. Realistically well want to add them and get community weigh in before taking the axe to behaviors

**Comment by thejameskyle** [comment]
> Let's discuss the merits / implementation details of mixins in a new issue. 

I mean they already exist if you define them as POJO's like Backbone.Events... Which is already enough IMO to have this discussion.

**Comment by jasonLaster** [comment]
I think we first want to implement the mixin function. Just doing a shallow extend tight?

**Comment by thejameskyle** [comment]
This is what I do: https://github.com/marionette-wires/wires-metal/blob/master/src/wires-metal.js#L196-L200

Note that `_wrapAll` is a shallow extend that implements `this._super()`.

**Comment by bzalasky** [comment]
I agree with Jason that it makes more sense to implement the mixin
functionality first. I'm about to go train a new team that's inheriting a
Marionette project I built, and a significant portion of the the session
will involve discussing the direction that Marionette is heading in...
maintaining support for behaviors is essential for us right now, as ripping
them to replace them with mixins is a waste of time from a business
perspective, and would put us on a track of avoiding future updates (for
the time being) on this project.

- Ben
