### ISSUE TITLE
Discuss adding new mixin patterns 

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2218]
this has come up several times, issue links coming, but I believe it's time add some more mixin utilities. 

Three that I know of are: deep merge, advice.js or functional mixins, and _wrapAll w/ super.  

I look forward to see how people want to proceed. They all of their merits to me. 

_wrapAll: https://github.com/marionette-wires/wires-metal/blob/master/src/wires-metal.js#L196-L200 Note that _wrapAll is a shallow extend that implements this._super().

**Comment by thejameskyle** [comment]
- I think we can implement a basic version of advice js as a separate lib (which I would definitely like).
- I'm afraid of the incompatibilities of introducing a deep merge.
- I wrote _wrapAll/super so I think it's the greatest thing ever and you should all use it.

**Comment by paulfalgout** [comment]
So a utility that is particularly useful for manually mixing in other functionality is `Marionette._getValue` but it's private.  Any reason why that isn't a public utility?

**Comment by ahumphreys87** [comment]
i think this is solved with metal? Closing as will be fixed with #2426
