### ISSUE TITLE
CompositeView: onRender is called before _initialEvents

### ISSUE THREAD

**Issue by kamijean47** [marionettejs/backbone.marionette#2219]
When using CompositeView, it seems that ` onRender ` is called before ` _initialEvents `, so whenever i add models to the collection inside the ` onRender `, they are not rendered, because the collection is empty during initialization, and the collection is already populated before the events are delegated.

If there's a way maybe its better to have ` render ` -> `_initialEvents ` -> ` onRender `, i guess.

I just had this issue when i updated to v2.3.1

**Comment by samccone** [comment]
@kamijean47 What version were you on previously?

**Comment by kamijean47** [comment]
@samccone i had v1.1.0 before

**Comment by ahumphreys87** [comment]
related to #2016 just needs docs to explain the change in behaviour
