### ISSUE TITLE
Add application child view shortcut methods

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2220]
LayoutView is getting some new view shortcut methods (`getChildView`, `showChildView`) #2145. We should add these shortcuts to Application to be consistent in 2.x.  I believe there are plans to deprecate region managing responsibilities in Applications in 3.x, but for 2.x consistency it'd be nice to have.

**Comment by jmeas** [comment]
I could see us going either way on this. I am a bit hesitant of us adding new functionality onto deprecated features, even if it does make it more consistent. What do others think?

**Comment by paulfalgout** [comment]
I think at this point the `next` branch is dictating that this isn't going to happen.  @jasonLaster ?

**Comment by jasonLaster** [comment]
ageed
