### ISSUE TITLE
Proposal for LoadingView for CollectionView/CompositeView

### ISSUE THREAD

**Issue by sobrinho** [marionettejs/backbone.marionette#2221]
We have seen this issue before (#1108, #878, #645, #510, #469, #416) so it's definitely a need.

I'm thinking in the simplest approach possible: when the collection fires `request` marionette renders the loading view.

We don't need nothing besides that because the first render will continue as before (empty if there is no item, item view if there is items).

What we have so far:

``` javascript
Marionette.CompositeViewWithLoading = Marionette.CompositeView.extend({
  _initialEvents: function () {
    Marionette.CompositeView.prototype._initialEvents.apply(this, arguments);

    this.once("render", function () {
      if (this.collection) {
        this.listenTo(this.collection, "request", this._renderLoading);
        this.listenTo(this.collection, "sync", this.render);
      }
    });
  },

  _renderLoading: function () {
    this.startBuffering();

    this.closeChildren();
    this.closeEmptyView();

    this.showLoading();

    this.endBuffering();
  },

  showLoading: function () {
    var LoadingView = this.getLoadingView();

    if (LoadingView) {
      var model = new Backbone.Model();
      this.addItemView(model, LoadingView, 0);
    }
  },

  getLoadingView: function () {
    return Marionette.getOption(this, "loadingView");
  }
});
```

I'm concerned about the render after the sync but it's needed because we need to render the empty view after a sync which returns nothing for an already empty collection (I didn't find a way to detect that specific situation yet).

Would be great to have this feature somehow in marionette instead of implementing it as a plugin or something else.

I think what we need:

- [ ] Avoid the double render due to the `sync` listener
- [ ] Improve the implementation (code style, parity with the concept of empty view i.e.: closeLoadingView)
- [ ] Makes it compatible to most recent (this code was implemented for 1.8.8)
- [ ] Makes it work on collection view too

What you guys think?

**Comment by paulfalgout** [comment]
First thanks for raising the issue.

I'm :-1:  on a loading view being in Marionette.  This is best served with something in something like https://github.com/MarionetteLabs/marionette-cookbook or perhaps it's own extension library.  This may be related to a common pattern, but it's opinionated as to how to show a preloader, when there are other legitimate ways to solve this problem.. 

Plus there are other scenarios it doesn't address: 
What if CompositeView requires both the collection and the model to have loaded, or maybe just the model?   

Perhaps your collection is a portion of data coming back from a bigger XHR that is not tied directly to the collection sync, but the collection gets reset once the xhr is successful.

I think it's fine that a solution like this doesn't cover all of the cases, but I believe for that reason it's not a core-library kind of functionality.

**Comment by thejameskyle** [comment]
This will be easy to solve with Route-objects.

:-1:

**Comment by jmeas** [comment]
@sobrinho, you're right that this is a common problem. As @thejameskyle points out, we're working to solve this exact thing with a system that works outside of the view itself.It'll be great!

For now, I agree with @paulfalgout that this doesn't belong in core given all of the different possibilities. Come hang out on Gitter if you'd like to talk to folks to learn how they might approach this in the current library.

For now, I'm gonna close this. But thanks for raising the issue!

**Comment by sobrinho** [comment]
What you mean with route-objects?

**Comment by jmeas** [comment]
We're working on a new routing abstraction. Instead of associating callbacks with your routes, you can associate Objects. These Objects are called Routes. Routes are great because they provide you all sorts of abstractions to do the common things you might want to do when you route: redirect, fetch data, show a loading view.

**Comment by sobrinho** [comment]
Well, it won't help in my case, we don't use backbone routes at all.

I ended using this behaviour, kudos to @samuelsimoes, which does what we need:

``` javascript
CollectionLoadIndicator = Marionette.Behavior.extend({
  collectionEvents: {
    request: "showLoadingElement",
    sync: "hideLoadingElement"
  },

  initialize: function () {
    this.model = new Backbone.Model;
    this.boilerplate = Marionette.ItemView.extend(this.options);
  },

  showLoadingElement: function () {
    this.view.startBuffering();

    this.view.closeChildren();
    this.view.closeEmptyView();

    this.loadingView = this.view.addItemView(this.model, this.boilerplate, 0);

    this.view.endBuffering();
  },

  hideLoadingElement: function () {
    this.view.removeChildView(this.loadingView);

    delete this.loadingView;

    this.view.checkEmpty();
  }
});
```

**Comment by jmeas** [comment]
> Well, it won't help in my case, we don't use backbone routes at all.

You might be surprised! We're planning for our routers to manage *application state*, independent of whether or not you're encoding that state into a URL. If you've got something loading, then you've likely got some state in the app.

**Comment by yamsellem** [comment]
Is there some code/docs on those exciting new routing objects/abstraction?
