### ISSUE TITLE
Destroying a collection view shows an empty view before it "died"

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#2223]
Destroying a collection view (manually or because of a region.empty) call a check for empty and could trigger a show empty view, which can be unwanted.

**Comment by samccone** [comment]
@JSteunou would you be able to put together a jsfiddle showing this behavior?

**Comment by JSteunou** [comment]
Hard to demonstrate, I cannot add a console.log or debugger statement inside marionette in a jsfiddle.

I had a bug due in part to https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L437 lately, because I'm using models on my own, sort of super Backbone.Model, and emptying a region containing a collection view tried to show an empty view which use a new Backbone.Model by default. I spotted this because I override view render and it was calling a non existing method on the model because it was not a model of my own but a Backbone.Model

**Comment by ahumphreys87** [comment]
closing in favour of #2313 

@JSteunou we have been discussing this issue a bit more over there, feel free to offer your input.

**Comment by JSteunou** [comment]
Good call, did not see it.
