### ISSUE TITLE
_getValue fails in IE8

### ISSUE THREAD

**Issue by craigjennings11** [marionettejs/backbone.marionette#2225]
When testing my app in IE8, I noticed an error coming from `_getValue()`. It appears that if you pass `undefined` to `apply()` as the second parameter, IE8 errors out:

![image](https://cloud.githubusercontent.com/assets/1683368/5967669/304de8b8-a7d5-11e4-8707-925241f6d749.png)

This is also discussed here: http://stackoverflow.com/questions/11112950/function-apply-causing-jscript-object-expected-error-in-ie

Since there are many instances where `_getValue` is called without a 3rd parameter, this case will come up often.

**Comment by samccone** [comment]
fixed in v2.3.2
