### ISSUE TITLE
Is view options as a function useful?

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2229]
This line in the base `Marionette.View` https://github.com/marionettejs/backbone.marionette/blob/master/src/view.js#L12
lets you pass options as a function.  Neat feature, except that the options function is passed to the `Backbone.View`

Backbone doesn't process the function, so if you use options as a function none of the view options such as model or collection would be applied to the view.
http://backbonejs.org/docs/backbone.html#section-128

If `Backbone.View` isn't given the result of the option function, is it a useful feature?

**Comment by jmeas** [comment]
I think that this behavior should be removed.

**Comment by paulfalgout** [comment]
Yeah I think you're right.

It looks like this may have worked with Backbone 1.0.0 https://github.com/jashkenas/backbone/blob/1.0.0/backbone.js#L1087

But since options are no longer attached by Backbone, it no longer gets the result of options before picking the viewOptions  https://github.com/jashkenas/backbone/blob/1.1.0/backbone.js#L988

**Comment by ahumphreys87** [comment]
fixed with #2263

**Comment by paulfalgout** [comment]
Yeah kinda fixed...  it works now in all cases.. so it was a bug fix for v2, though I think it might be better if it was removed.  It's a fairly confusing, fairly useless feature.
