### ISSUE TITLE
underscore dependency version

### ISSUE THREAD

**Issue by silistri** [marionettejs/backbone.marionette#2230]
Hello 

Backbone is now working with underscore 1.7.0 but marionette is still linked with underscore 1.6.0.
Is that intentional or just an oversight?

Thank you

backbone - package.json 
 "dependencies"  : {
    "underscore"  : ">=1.6.0"
  },

marionette - package.json 
  "dependencies": {
    "backbone.babysitter": "^0.1.0",
    "backbone.wreqr": "^1.0.0",
    "backbone": "1.0.0 - 1.1.2",
    "underscore": "1.4.4 - 1.6.0"
  },

**Comment by jmeas** [comment]
Thanks for the report, @silistri! Underscore does not follow semver, and 1.7.0 included a breaking change. Marionette, on the other hand, only includes breaking changes for major releases, so we will be updating to 1.7 when v3 comes out.

**Comment by silistri** [comment]
thank you very much!

**Comment by jmeas** [comment]
Noprob :+1:

**Comment by le0pard** [comment]
Hello. 

Looks like version 1.8.x revert broken `_.extend` command workflow from 1.7.x. Is is possible right now to use underscore 1.8.2 with marionette?

P.S. I updated my marionette app (2.4.0) with underscore 1.8.2 and it still work correctly.
