### ISSUE TITLE
childEvents not supported in behavior.. other options? Is this an oversight? Am I dumb?

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2235]
My goal is for a behavior attached to a CollectionView to be able to know which ChildView was just interacted with by the user. It does not appear that this is currently possible.

Here's an example: http://codepen.io/Meo/pen/XJaGxo

And here's the code I'm trying:
```js
	var CollectionViewBehavior = Marionette.Behavior.extend({
	  //  Does NOT run:
	  childEvents: {
		'do:stuff': function(args){
		  console.log('Model to do stuff on:', args.model);
		}
	  }
	});

	var ChildViewBehavior = Marionette.Behavior.extend({
	  triggers: {
		'click': 'do:stuff'
	  }
	});

	var MyChildView = Marionette.ItemView.extend({
	  template: _.template('MyChildView - click me!'),
	  behaviors: {
		ChildViewBehavior: {
		  behaviorClass: ChildViewBehavior
		}
	  }
	});

	var MyCollectionView = Marionette.CollectionView.extend({
		childView: MyChildView,
		behaviors: {
		  CollectionViewBehavior: {
			behaviorClass: CollectionViewBehavior
		  }
		},
		//  Does run:
		childEvents: {
		  'do:stuff': function(args){
			console.log('This totally works, but is not in a behavior to do stuff on:', args.model);
		  }
		}
	});

	var myCollectionView = new MyCollectionView({ collection: (new Backbone.Collection([{}]))});
	$('body').append(myCollectionView.render().el);
```
Am I missing something? I get that Behaviors should be generic, so I think it makes sense that they don't support childEvents, but it leaves me thinking I have to do one of a few hacky workarounds to make this work.

Thoughts?

**Comment by samccone** [comment]
So yeah makes sense that is does not work

There would need to be a change in this method
https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L454

to enable proxying to behaviors, I am not sure if it would be a good idea to add this complexity to the collectionView implementation or not... perhaps worth an investigation tho

**Comment by jasonLaster** [comment]
well i don't know. triggerMethod should proxy to all behaviors...

**Comment by samccone** [comment]
right it does, @MeoMix wants to use the childEvents hash instead of 

```
onChildViewClick: function(){}
```

inside his behavior

this line here is the "problem"
https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L469

**Comment by MeoMix** [comment]
Err @samccone -- is there an alternate syntax which is supported? You seem to be alluding that I can use an onEventName: function(){ }, but I've tried:

   onDoStuff: function(){ },
   onChildViewDoStuff: function(){}

etc.. and none of those appear to work in the behavior, either?

**Comment by ahumphreys87** [comment]
Closing as this seems to be working correctly @MeoMix to allow the `onChildViewDoStuff` casing example to work you could set `childEventPrefix` on the `CollectionView` to `childView` - it defaults to `childview` which is why `view` is always lower case.

**Comment by lococo--0** [comment]
@ahumphreys87 @MeoMix 
Does it means `onChildviewDoStuff` is useful in all behavior? 

But it seems that `onChildviewDoStuff` in my LayoutView can be invoked, no work in the behavior of the LayoutView.

**Comment by fraserharris** [comment]
This is quite a "gotcha".  It makes no sense (from an external API consumer perspective) that childEvents are the odd ducks that don't trigger in behaviors...
