### ISSUE TITLE
Blog post examples broken.

### ISSUE THREAD

**Issue by trusktr** [marionettejs/backbone.marionette#2238]
@derickbailey Just wanted to point out that some of the examples in your [blog](http://lostechies.com/derickbailey/2012/04/05/composite-views-tree-structures-tables-and-more/) are broken and probably easy to fix for the world to benefit from. :+1:

**Comment by samccone** [comment]
Hi @trusktr @derickbailey is no longer involved in the day to day of Marionette. your best bet to get this resolved is to ping him on twitter of leave a comment on the blog post.

thanks for the :eyes:
