### ISSUE TITLE
Documentation: CollectionView / CompositeView sort rerender

### ISSUE THREAD

**Issue by bazineta** [marionettejs/backbone.marionette#2247]
At present, the CollectionView and CompositeView documentation speaks to the view re-rendering on a collection 'reset' event, but does not speak to it re-rendering on a 'sort' event.  In that the views do re-render on 'sort', it would be helpful to document this.

Additionally, given the relative functions of these two classes, it should be made clear that CompositeView completely re-renders on sort, rather than just re-rendering the child view container.

While completely re-rendering in CollectionView is obvious, I think that it's less so in CompositeView, and so it'd not be unexpected that only the CompositeView's childViewContainer would be re-rendered, when in fact the opposite is true.

**Comment by samccone** [comment]
> but does not speak to it re-rendering on a 'sort' event. In that the views do re-render on 'sort', it would be helpful to document this.

@bazineta  currently collectionViews and compositeViews do not rerender on 
https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L82

**Comment by samccone** [comment]
@bazineta would you like to open a PR to improve the documentation here?

**Comment by bazineta** [comment]
Sure, will do so.

**Comment by samccone** [comment]
hey @bazineta any word on the PR here?

**Comment by ahumphreys87** [comment]
@bazineta do you have time for this PR?

**Comment by bazineta** [comment]
@ahumphreys87 I do, but given the extreme amount of flux and open issues in the associated views at present, was holding off until the smoke clears somewhat.

**Comment by ahumphreys87** [comment]
It would be cool to get this change out in 2.4.2 which will fix the reverse ordering issue you reported.

Most other issues surround what will happen with CompositeView in v3 which we hope will be next release after 2.4.2 were going all out to make that happen.

**Comment by ahumphreys87** [comment]
fixed with #2514
