### ISSUE TITLE
ItemView ui hash does not work when using element IDs

### ISSUE THREAD

**Issue by guyht** [marionettejs/backbone.marionette#2248]
In following code

```coffee-script
# Setup steps view
    View = Marionette.ItemView.extend (

        # Pre-rendered
        template: false

        # Base element
        el: '#steps'

        # Setup ui
        ui: (
            step1: '#step-1'
            step2: '#step-2'
            step3: '#step-3'
        )

# Set step on render
        onRender: ->
              @ui.step1.removeClass 'complete'

)
```

@ui.step1 returns null.  This is because on bind, marionette attempts to find the element using the following selector $('#steps #step-1') which is invalid (two ids).   When a ui element is referenced by ID, the selector should not contain the base el (i.e. $('#step-1'))

**Comment by samccone** [comment]
A selector with two ids is a valid selector (css and in JS)
http://jsfiddle.net/0j3rqdg6/1/

can you attach a JSFIDDLE that shows this bug please.

**Comment by samccone** [comment]
:+1:

**Comment by guyht** [comment]
:wink:

**Comment by samccone** [comment]
![](https://s.yimg.com/cd/diminuendo/1.0/original/0ce11856aef17620a76a35988141f0daf1d966f5.gif)
