### ISSUE TITLE
LayoutView => ItemView PR path

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2251]
:skull: Farewell, LayoutView!

There are two PRs that need to happen for the LayoutView to be merged into ItemView

- [x] 1. Rename Marionette.View to Marionette.AbstractView #2252
- [x] 2. Migrate LayoutView code into Marionette.ItemView #2253

**Comment by blikblum** [comment]
Hi, i've been following Marionette closely for sometime and have a concern about increased resource usage / performance with this change and i'd like to hear the opinion of more experienced JS/Mn devs.

One of the most common usage of ItemView is render list items (or table rows), as advertised in the site. Such situations almost always does not need the LayoutView / region features.

But with the proposed changes, each view used to render list items (and it can be many) will run the code path that initializes regions at initialization and at rendering without any benefit.

Any thoughts?

**Comment by thejameskyle** [comment]
@blikblum I don't see any reason there would be a noticeable perf impact with this change. Aside from that I've been working on some improvements to the view layer for awhile that will greatly improve perf.

**Comment by jmeas** [comment]
@blikblum, thanks for the interest in the project! You're right – there might be some slight loss of performance here given the current implementation of LayoutView that naively instantiates the RegionManager. With that said, I don't think it will be too noticeable. As @thejameskyle mentioned, we're working on optimizations that will make it pretty much negligible. And you can be sure that we'll run perf tests to compare the old behavior with the new.

**Comment by stephanebachelier** [comment]
I follow @blikblum regarding any performance issue. Migrating Layout to ItemView will make all itemview memory footprint bigger which might be an issue. 
I use Marionette mainly for mobile application so I'm very concerned with performance.

**Comment by jmeas** [comment]
We'll make sure the performance won't change in any noticeable way. Wait for the perf tests if you're concerned!

**Comment by jmeas** [comment]
A discussion on performance is being had over at #2267

**Comment by jmeas** [comment]
Solved by #2253
