### ISSUE TITLE
Override behavior ui with view ui

### ISSUE THREAD

**Issue by stephanebachelier** [marionettejs/backbone.marionette#2266]
Don't know if it's only me, by I don't like how the `ui` is initialized for a behavior. It you looks [here](https://github.com/marionettejs/backbone.marionette/blob/master/src/behaviors.js#L52) you can see that the ui is built by extending the view.ui and then the behavior.ui

```
        // Construct an internal UI hash first using
        // the views UI hash and then the behaviors UI hash.
        // This allows the user to use UI hash elements
        // defined in the parent view as well as those
        // defined in the given behavior.
        var ui = _.extend({}, viewUI, behaviorUI);
```

I think it breaks the idea of the behavior being small reusable unit of code, that a view use and can override. IMO it should be written the opposite which is : 

```
var ui = _.extend({}, behaviorUI, viewUI);
```

This will solve an issue that I faced, where the behavior ui define a default ui element that the view may want to override which is not possible with the existing form.

An example:

```
// close icon behavior
var CloseIconBehavior = Marionette.Behavior.extend({
  events: {
    'click @ui.closeIcon': 'closeView'
  },

  ui: {
      closeIcon: '.icon-close'
    };
  },

  closeView: function () {
    this.view.destroy();
  }
});

// the view
Marionette.ItemView.extend({
  ui: {
     closeIcon: '.icon-cancel'
  },

  behaviors: {
    iconClose: {
      behaviorClass: CloseIconBehavior
    }
  }
});
```

In the example above the `CloseIconBehavior.closeView` will never be called because the `CloseIconBehavior` will bind the click event to `click .icon-close` and not `.icon-cancel`.

Using my proposed approach it will "behave" correctly.

As I use really a lot the behaviors for my applications, - they are really powerful! -, this is a major pain.

See PR #2308

**Comment by jasonLaster** [comment]
Hmm. Interesting point. I think I dig it

**Comment by stephanebachelier** [comment]
@jasonLaster I can add more explanations if you need. I've seen some issues about some core developers not really liking behaviors, but after digging into it, I find they are a really powerful tool.
I use them a lot in two mobile applications and they are some kind of smart tools.

**Comment by jasonLaster** [comment]
In
