### ISSUE TITLE
The path to remove CompositeView

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2268]
CompositeView's name is indicative of its true self: it's a mashup of LayoutView ([now ItemView](https://github.com/marionettejs/backbone.marionette/pull/2253)) and CollectionView.

But it lives a strange existence. It extends from CompositeView, and then re-creates much of the functionality that Regions provide to wrap the collection in a template. This is unnecessary code bloat.

As part of our mission to get down to 2 views, the CompositeView can simply go away without any loss of functionality. In addition, we will end up with a more consistent implementation, as all manual nesting of views will be done with the Region API.

To get there, though, we need to update Regions a bit to support the same functionality as the childViewContainer.
1. [x] Allow region element to be a placeholder https://github.com/marionettejs/backbone.marionette/issues/1976
2. [x] Delete CompositeView from the code
3. [x] Write upgrade guide. Maybe create a small library that polyfills the change, exposing the same surface area as the CompositeView itself.

That's it!

Original discussions:
https://github.com/marionettejs/backbone.marionette/issues/290 https://github.com/marionettejs/backbone.marionette/issues/1584

**Comment by jmeas** [comment]
[Minionette](https://github.com/jridgewell/minionette) provides an awesome region swap strategy. We should draw inspiration from there. //cc @jridgewell.

**Comment by jasonLaster** [comment]
@cmaher brave enough to take a stab at some of this?

**Comment by ahumphreys87** [comment]
Im gonna take this one!

**Comment by ahumphreys87** [comment]
Note: we are only deprecating in 3.0.0 ready for removal in 4

**Comment by paulfalgout** [comment]
I think we should write and prove the upgrade guide and _then_ remove the code :-)

**Comment by paulfalgout** [comment]
https://gist.github.com/paulfalgout/1826e3324d004e2b5f50c28e75fcce06
It's not 100% parity, but it's pretty close.. there's also plenty of edge-cases we wouldn't necessarily want to support, but this should cover 99% of use cases.
Could also copy the _renderTemplate into this so as not to use a private function..

Here's an alternate version that support less features, but doesn't pull from the prototypes: https://gist.github.com/paulfalgout/e55bb0813e2d45e4cbc42801f2d9412a
notably the 2nd version could easily support regions as well

**Comment by rafde** [comment]
@marionettejs/marionette-core Is this still part of the plan? I am on the fence because of weird cases like https://github.com/marionettejs/backbone.marionette/issues/3150

**Comment by paulfalgout** [comment]
I'm not sure we should keep around an entire API for edge cases when #3150 can be solved like so:
```js
// Mn v2  https://jsfiddle.net/ag5eqstL/

const List = Mn.CompositeView.extend({
  el: '#container',
  template: '#list',
  childViewContainer: 'table',
  childView: Item,
  onRender () {
  	$('#container-code').text(this.$el.html());
  }
});

// Mn v3  https://jsfiddle.net/ag5eqstL/1/

const List = Mn.NextCollectionView.extend({
  el: '#container',
  initialize() {
    this.templateView = new Marionette.View(_.pick(this, ['el', 'template']));
  },
  template: '#list',
  childViewContainer: 'table',
  childView: Item,
  onBeforeRender() {
    this.templateView.render();
    this.$container = this.$(this.childViewContainer);
  },
  attachHtml(collectionView, els) {
    this.appendChildren(this.$container, els);
  },
  onRender () {
  	$('#container-code').text(this.$el.html());
  },
  onBeforeDestroy() {
    this.templateView.destroy();
  }
});
```

Note in v3.4 this'll change slightly:
```js
attachHtml(els) {
  this.Dom.appendChildren(this.$container, els);
}
```

**Comment by paulfalgout** [comment]
Or https://gist.github.com/paulfalgout/00738a248920dd04a4fc6fa52b755723
```js
import MakeComposite from 'make-composite';

const List = Mn.NextCollectionView.extend({
  initialize() {
   MakeComposite()
  },
  el: '#container',
  template: '#list',
  childViewContainer: 'table',
  childView: Item,
  onRender () {
  	$('#container-code').text(this.$el.html());
  }
});
```

**Comment by rafde** [comment]
Cool. Planning on doing some easy-medium stuff regarding helping the project some.

**Comment by JSteunou** [comment]
Maybe publish the `make-composite` as a Marionette plugin?

**Comment by paulfalgout** [comment]
I'm certainly open to someone doing that 😸

**Comment by blikblum** [comment]
I changed my idea about this. Initially i was all for removing it. But after porting some apps to v3, trying to replace composite by collection view, i realized that the amount of work / code necessary to replace by collection view is not worth the trouble. 

With, hopefully, tree shaking enabled in v4, the code size will not be a problem for those not using it.

So at this time i'm inclined of keep CompositeView on top of NextCollectionView (@paulfalgout demoed in gitter two implementations)

**Comment by scott-w** [comment]
Is there a way to bring the `NextCollectionView` and `CompositeView` a bit closer together perhaps? Perhaps making it so the CollectionView can take a template and optional `childViewContainer` would be a step in the direction people need?

On that note, does `NextCollectionView` listen to `modelEvents`?

**Comment by paulfalgout** [comment]
One of the major pain points of CompositeView in the past was that it frequently dictated how CollectionView could be updated and in general made the library harder to maintain.  Additionally it added a lot more API surface area, and testing.. I do think maybe there is a simple way to add this functionality back, but it should be ideally without needing much inheritance or additional API

**Comment by blikblum** [comment]
I think implementations like the below should be good enough, handling just most common cases:

https://gist.github.com/paulfalgout/e55bb0813e2d45e4cbc42801f2d9412a

https://gist.github.com/paulfalgout/1826e3324d004e2b5f50c28e75fcce06

**Comment by paulfalgout** [comment]
I much prefer https://gist.github.com/paulfalgout/e55bb0813e2d45e4cbc42801f2d9412a as an option.  Allows changes to the view code apart from concerns with the collectionview.

**Comment by paulfalgout** [comment]
@scott-w 

> On that note, does NextCollectionView listen to modelEvents?

Yep.

**Comment by JSteunou** [comment]
If I understood well, the best would be either as a Module inside Marionette hoping for treeshaking or as Module outside Marionette as a plugin, but maintained by @marionettejs/marionette-core and with a minimum impact on CollectionView API to not be a drag again?

**Comment by JSteunou** [comment]
Maybe simpler then to keep it inside, well tested & documented

**Comment by scott-w** [comment]
So if I understand correctly, you're thinking that, instead of managing `template: ...`, you can attach a `View` and `childViewContainer` selects something inside the newly-rendered view?

**Comment by paulfalgout** [comment]
I think we could possibly support `template` and `childViewContainer` directly, but under-the-hood it'd just be spinning up a view that shares the `el`

**Comment by paulfalgout** [comment]
Some initial messing around with the code and I'm feeling less confident about this being a good idea.  If it's not complicated in one area it is complicated in another..  we can get _close_ to right very easily.. like it's pretty easy with some examples like above to cover particular use-cases, but for a "CompositeView" to cover the edge cases is very difficult.

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/pull/3433 possible replacement
