### ISSUE TITLE
Create Marionette.Utils

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#2275]
```js
Marionette.Utils = new Marionette.Mixin({
  getOption: function() {},
  triggerMethod: function() {},
  triggerMethodOn: function() {},
  bindEntityEvents: function() {},
  unbindEntityEvents: function() {},
  // others?
});
Marionette.Class.mixin(Marionette.Utils);
```

Then:
- Remove top level methods (eg. `Marionette.getOption`)
- Remove proxy methods (eg. `Marionette.proxyGetOption`)
- Remove from classes (eg. `Marionette.View.prototype.getOption`) (will already exist in prototype chain)

**Comment by jasonLaster** [comment]
hmm - I like the idea of namespacing. I'd like to hold off on `Mixin` until we lock down the behavior. I'd like to leave the door open for a more powerful mixin pattern closer to Ember's mixins which don't clobber the object prototype.

**Comment by thejameskyle** [comment]
@jasonLaster Want to create an issue over in metal for that?

**Comment by jasonLaster** [comment]
sure

**Comment by paulfalgout** [comment]
I think this is going to be taken care of by what is added to the base Marionette.Class.

**Comment by jasonLaster** [comment]
Hmm, probably. But I'd like to see Utils namespaced as well so they're not on Marionette itself.

**Comment by jasonLaster** [comment]
They're now in their own files and will be modularized soon
