### ISSUE TITLE
Make everything a class

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#2276]
Some of our classes are extending from Backbone's, some from Marionette.Object, and others are just implementing all the normal class features themselves.

**Comment by jasonLaster** [comment]
Sam did a good job to consolidate our classes now we have views and objects. 

Next step add metal

**Comment by jasonLaster** [comment]
closing this card. We can revisit making everything a Metal Class when we add metal or somethign like it.
