### ISSUE TITLE
Marionette Application needs to have a router associated with it

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2280]
API TBD

**Comment by thejameskyle** [comment]
```js
import {Application} from 'marionette';
import Router from './router';

export default Application.extend({
  router: Router
});
```

**Comment by jmeas** [comment]
I dig that API, but there's one thing to note...if we end up serializing our regions into an object that the Router can then use a resolver pattern on, then there will need to be a way for the router to know about the app's rootElement.

**Comment by thejameskyle** [comment]
```js
Marionette.Application = Marionette.Class.extend({
  constructor: function() {
    this.theRouter = new this.router({
      theEl: this.rootEl
    });
  }
});
```

**Comment by jmeas** [comment]
@thejameskyle, that works, but it seems like unnecessary boilerplate, y'know? Like nobody would ever configure that any differently. It'd be great if that could be the default somehow.

**Comment by jasonLaster** [comment]
James' checka that's the App.

**Comment by jmeas** [comment]
> James' checka that's the App.

oic :+1:

**Comment by thejameskyle** [comment]
wat

**Comment by paulfalgout** [comment]
`Marionette.Application` is now reusable, and I am not convinced that Marionette needs to bundle a router.  There seem to be a handful of 3rd party routers that are viable and coupling a router, while simpler, is introducing an option that may not be super productive.  I'm more interested in seeing a handful of examples for how to use a few router options.  @marionettejs/marionette-core  ?

**Comment by paulfalgout** [comment]
Closing due to comments over on https://github.com/marionettejs/backbone.marionette/issues/2092
