### ISSUE TITLE
Move _isRendered and _isShown flags to respective views

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2287]
After the removal of `onDomRefresh` only `CompositeView` needs the `_isRendered` flag and only the `CollectionView` needs `_isShown`.

Both of these flags could be set and managed in their respective views.

`CollectionView` has `_onShowCalled' https://github.com/marionettejs/backbone.marionette/pull/2262/files#diff-091acc5f607e2622bd6cabf705443fffR115

And `CompositeView` has a `render` function.

**Comment by samccone** [comment]
:+1:

**Comment by paulfalgout** [comment]
Anyone have concerns with needing these flags for other things.  Skimmed issues and https://github.com/marionettejs/backbone.marionette/issues/1952 seemed like a possible candidate.

Essentially Backbone's `setElement` is unbinding / rebinding events if you call `setElement` on an already rendered view, but Marionette is not resetting the `ui` hash.  

`bindUIElements` can be added to `setElement` but it's not really useful for the general use case of `setElement` before the first `render`  Seems like we'd want something related to this in the overridden `setElement` in `AbstractView`:

```
if (!this._isRendered) {
  this.bindUIElements();
}
```

**Comment by paulfalgout** [comment]
I'm not certain how useful this is any longer.. now that it's essentially just `View` and `CollectionView`  perhaps each view needs to have these handled differently, but I think we're finding many of the "children" responsibilities of knowing and proxying statuses from parents to children are the same or very similar.  If onDomRefresh functionality is handled at the AbstractView level, maybe these flags should be as well.

**Comment by paulfalgout** [comment]
Closed by https://github.com/marionettejs/backbone.marionette/pull/2850
