### ISSUE TITLE
Remove selector key for region definitions

### ISSUE THREAD

**Issue by jfairbank** [marionettejs/backbone.marionette#2289]
We support `el` and `selector`. We should just use `el`. Recommend PR after `Region` mixin is added.

``` js
var MyView = Marionette.ItemView.extend({
  regions: {
    foo: {
      selector: '#foo',
      regionClass: MyRegionClass
    }
  }
};

// should be

var MyView = Marionette.ItemView.extend({
  regions: {
    foo: {
      el: '#foo',
      regionClass: MyRegionClass
    }
  }
};
```

**Comment by thejameskyle** [comment]
:+1:

**Comment by jmeas** [comment]
:+1:

**Comment by samccone** [comment]
:+1:

**Comment by instanceofpro** [comment]
:+1:

**Comment by jmeas** [comment]
:+1:

**Comment by jmeas** [comment]
:+1:

**Comment by jfairbank** [comment]
:+1:

**Comment by samccone** [comment]
![](http://i.imgur.com/8DgP4.jpg)

**Comment by thejameskyle** [comment]
![](http://media0.giphy.com/media/wTzPSxZBqSove/giphy.gif)

**Comment by samccone** [comment]
![](http://cdn0.dailydot.com/uploaded/images/original/2013/3/7/uj7beoj.gif)

**Comment by buob** [comment]
![article-1283511293727-0b0681d5000005dc-493565_466x380](https://cloud.githubusercontent.com/assets/986404/6066582/22eafa0a-ad3c-11e4-9b3b-beabef74133f.jpg)

**Comment by scott-w** [comment]
Chasing turtles here - did this ever get resolved?

**Comment by paulfalgout** [comment]
@scott-w selector is still in the code, but we can break it for v4

**Comment by scott-w** [comment]
:+1:

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/pull/3465
