### ISSUE TITLE
Rename showChildView and getChildView

### ISSUE THREAD

**Issue by jfairbank** [marionettejs/backbone.marionette#2291]
It makes sense to move these methods to the `Region` mixin. One downside is if you want to use the mixin in a `CollectionView`. These method names will make it confusing really quick.

I don't love them, but something like `showInRegion` and `getRegionView` could work. Ideas for better names?

**Comment by samccone** [comment]
it is still TBD if collectionViews can have regions.. and or templates.

I think we are leaning on the side of having the above ^ so yes we need to figure out a better naming convention for those helper methods

**Comment by jasonLaster** [comment]
Yep the mixin will help, but not convinced the names are bad. Their intention is clear

**Comment by jfairbank** [comment]
@jasonLaster I'm not saying these names are *bad*. Their intention is definitely clear. The problem is that `CollectionVIew` obviously already has a notion of children views.

If we're going to support `CollectionView` being able to include the region mixin, then this nomenclature is going to be confusing, especially to newcomers. I can see someone expecting these methods to work with the children views. (Granted, down the road this might be a nonissue if we roll some master enumerable region thing, where `CollectionView's` children views are a managed region list.)

I'm trying to avoid any mental burden we might put on developers now while we have the opportunity. This is a major release, so we can change these names now. That won't be possible as a minor release if we discover these names don't work once we've released v3.

---

The other option is to leave these as specific `ItemView` methods and not make them a part of the mixin. Then, we don't have to rename them. But, I do like the convenience of `showChildView`.

**Comment by jasonLaster** [comment]
oh shit - that's a great point @jfairbank.

**Comment by jmeas** [comment]
I think we can resolve this by talking about the long-term vision for Regions and CollectionViews. We should have a mtg about it.

**Comment by jasonLaster** [comment]
making it 3.x so that we can do this with the regionify work

**Comment by rafde** [comment]
[request granted](https://github.com/marionettejs/backbone.marionette/blob/5f5e74b7936a35f3f0aebad20079434241360d06/src/mixins/regions.js#L183)
