### ISSUE TITLE
Simplify bindEntityEvents

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2292]
[All of this bloat](https://github.com/marionettejs/backbone.marionette/blob/master/src/bind-entity-events.js#L18-L107) could maybe become as small [as this](https://github.com/jmeas/puppets/blob/v0.0.1/src/utilities.js#L37-L54)? The Puppets version doesn't support space-separated names, so I suppose I'd have to add that in, but it shouldn't be too hard!

**Comment by thejameskyle** [comment]
:+1:
