### ISSUE TITLE
Support a parentEl type property on classes that mixin Regions

### ISSUE THREAD

**Issue by jfairbank** [marionettejs/backbone.marionette#2294]
Now in v3 `ItemView` we call `_buildRegions` before delegating to `RegionManager` to add regions. This method adds some default options for each region created.

```js
_buildRegions: function(regions) {
  var defaults = {
    regionClass: this.getOption('regionClass'),
    parentEl: _.partial(_.result, this, 'el')
  };

  return this.regionManager.addRegions(regions, defaults);
}
```

For the mixin to work with `ItemView`, we will need to support some property for telling the mixin we want to use a `parentEl`. We already support `regionClass` on the `ItemView` prototype (and as an option thanks to \*shudder\* `getOption`). I propose we support `regionParentEl` or `regionOptions: { regionClass, regionParent }`. Either option can also be a function for determining their values at runtime.

Downsides to `regionOptions` are inheritance or code duplication issues when you want to change only one of those inner properties.

We could make some assumptions and support `regionParentEl` being `true` too. The mixin would then check for a `this.el` property on the class that has mixed it in.

We will have to provide some type of convention for this to avoid the couple bugs with regions in `LayoutView` we discovered last year.

**Comment by ianmstew** [comment]
Is this still an issue in the re-envisioned `3.0` that contains only two views, View and CollectionView, both extending AbstractView?

**Comment by paulfalgout** [comment]
with the removal of `regionManager`, I don't think this is a thing.
