### ISSUE TITLE
Marionette should be built w/ babel (6to5) boilerplate principles

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2296]
Ember and Lodash are built w/ these principles. We have two experts on the matter here @jmeas, @thejameskyle. There would be several benefits:
+ module-based build strategy (think imports on the top, export on the bottom)
+ module resolution `import CollectionView from 'backbone.marionette/source/collection-view'`
+ es6 features

There would be one significant downside:
+ we would be es5 compliant, which means that those who want to support es3 for ie8 need a shim

I'll leave it to the pros to outline an implementation strategy:
+ refactor
+ build tools
+ package management

What do y'all think?

**Comment by jmeas** [comment]
https://github.com/marionettejs/backbone.marionette/issues/2250

**Comment by samccone** [comment]
@jasonLaster I don't want to drop ie8 support because we use ES6. If we are going to use things that need polyfills then we need to bake them into the core lib.

**Comment by jasonLaster** [comment]
Reasonable

**Comment by samccone** [comment]
that said, we can use es6, @thejameskyle alluded to the fact that we can simply avoid certain es6 things that need polyfills

**Comment by paulfalgout** [comment]
I am unfortunately tied to IE8 for quite a while   :skull:

**Comment by jmeas** [comment]
I think that it's fine if we support IE9 out of the box, with IE8 support if you include an ES5 shim. It's 2015, and more and more people make applications that don't need to support legacy browsers.

**Comment by jasonLaster** [comment]
Reopening Bc this is where the convo is. 

I don't think ie8 should be a blocker. I'm tied to ie8 :poop:s.com is optimized for it.

**Comment by samccone** [comment]
Pretty much every project we do here needs ie8 support, and marionette just working in IE8 is a really great thing. 

That said, I agree @jmeas it should not hold us back, we just need to make sure that we give people the polyfill that they need.

**Comment by instanceofpro** [comment]
We can use autopolyfiller https://github.com/azproduction/autopolyfiller. It scans code and applies only required polyfills.

**Comment by jmeas** [comment]
> marionette just working in IE8 is a really great thing.

Yup. This won't change.

> That said, I agree @jmeas it should not hold us back, we just need to make sure that we give people the polyfill that they need.

It isn't our job to supply the polyfill – [it already exists](https://github.com/es-shims/es5-shim).

Using 6to5 is simple; we tell our users that if they're supporting IE9, then they're good. And if they're using IE8, then they need to include the shim. The shim and sham together are only 20kb, which isn't such a bad compromise given what we're getting out of the change, I think.

**Comment by jasonLaster** [comment]
Yea, I agree it's kinda lame there's an additional step for ie8 work, but I can see why we don't want to add the bloat by default.

**Comment by samccone** [comment]
I would love to understand what the es6 transpiler does that break ie8, and then we can further this discussion. I was under the impression that if we simply did not use certain features os es6 we would be ok.

**Comment by jmeas** [comment]
> I was under the impression that if we simply did not use certain features os es6 we would be ok.

There are certain features that we must avoid; otherwise no shim or sham could ever make it work in IE8.

> I would love to understand what the es6 transpiler does that break ie8

The name of the transpiler says it best: 6*to5*. It's not 6to3. [Ref](http://kangax.github.io/compat-table/es5/) (click "Show obsolete browsers")

**Comment by bzalasky** [comment]
I'm surprised to hear how much IE8 support is still going on. Both of the
enterprise projects I've worked on in the last year only support back to
IE9. Are you all working in the consumer space or enterprise?

**Comment by samccone** [comment]
@bzalasky I am working in both. IE8 is still a real concern for most projects here

**Comment by paulfalgout** [comment]
Healthcare

**Comment by thejameskyle** [comment]
Can we move the discussion about whether or not to support IE8 elsewhere? There are plenty of things we can use 6to5 for that supports IE8 perfectly, so that discussion is irrelevant.

**Comment by samccone** [comment]
yep :+1: good call @thejameskyle
