### ISSUE TITLE
Is there a way to have a Root LayoutView create all of the regions from its template when it's el is assigned to an existing element?

### ISSUE THREAD

**Issue by dschissler** [marionettejs/backbone.marionette#2298]
I'm trying to get my project off on a good start by removing version 2.3 deprecated features.

I have a HTML like this:

```
<body>
<div id="application"></div>
...scripts
</body>
```

I'm not using Application regions and instead I'm creating a RootView from the LayoutView class.  I'm passing in `#application` as the selector.

I want the RootView to add three regions from its template but its not doing this because the element already exists.  I've been working on the backend for months and before in my R&D setup I was able to get everything going becaue the Application object was starting everything off with already defined regions.  Since the RootView is a level up I want it to be able to create the initial regions.

Is there some Marionette way to do this without resorting to `@$el.html(templateStuff)` on the `onRender` event?

**Comment by dschissler** [comment]
Dang.  It looks like it is working now.  I must have just needed a few minute break.

**Comment by samccone** [comment]
:+1:
