### ISSUE TITLE
Reintroduce a simplified onDomRefresh

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2299]
We are in the process of removing https://github.com/marionettejs/backbone.marionette/pull/2281

As mentioned there, the spirit of `onDomRefresh` may be useful.. essentially:
```
onAttach: function(){
  this.doSomething();
  this.on('render', this.doSomething);
}
```
Also, it should work with the view being detached from a region, then reattached

**Comment by jmeas** [comment]
What I'm thinking is:

1. CollectionView triggers `onAttach` to the child views
2. all views have `this.on('attach', this.attachRefreshListener);`, which starts the listener
3. the listener is removed when the view is destroyed or removed from a region

**Comment by samccone** [comment]
yep @jmeas sounds perfect

**Comment by jmeas** [comment]
I can add it if we want. @marionettejs/marionette-core whatcha think?

**Comment by samccone** [comment]
:+1: :+1:

**Comment by paulfalgout** [comment]
Closed by https://github.com/marionettejs/backbone.marionette/pull/2850
