### ISSUE TITLE
Set jquery as a dependency of Marionette

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2300]
It is silly that we still use backbone's $ for a jquery ref. It not only makes using tools like requirejs, and browserfiy hard, it is a pretty terrible anti-pattern. Lets be the responsible party here and set the dependency.

**Comment by jmeas** [comment]
The problem with Backbone.$ is about to be resolved. They're going to set it as a dep. Does that change your opinion @samccone?

**Comment by samccone** [comment]
Last backbone release is a year old atm so I don't want to wait any longer

**Comment by thejameskyle** [comment]
> The problem with Backbone.$ is about to be resolved. 

Until that PR is merged let's not assume anything.

**Comment by paulfalgout** [comment]
I think this is not an issue with Bb `1.2` now.  If still outstanding, please re-open.
