### ISSUE TITLE
onRoute should get named arguments rather than array

### ISSUE THREAD

**Issue by spenoir** [marionettejs/backbone.marionette#2311]
onRoute accepts `name, path, arguments`. Arguments is an array of named arguments without any names. It would be more useful it if were an object hash with named keys rather than an array.

cheers.

**Comment by jmeas** [comment]
Yup. This comes upstream from Backbone, which uses the `0...n` argument signature for everything. It makes for a *terrible* API, and nobody likes it.

Use [BaseRouter.](https://github.com/jmeas/backbone.base-router)
