### ISSUE TITLE
Migrate away from Babysitter

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2312]
We unanimously agree that Babysitter is no good. We can move toward removing it **now** by proxying its features directly onto the collection view.

- [ ] Add length to the collectionView.
- [ ] Add those findBy methods to the collectionView
- [ ] Make a plan for a more general [enumerable object](http://emberjs.com/api/classes/Ember.Enumerable.html) that we can use in Regions, CollectionViews, and any time we need a list

This issue extends into breaking-compatibility territory, but for now I want to focus on backwards-compatible solutions toward us getting rid of Babysitter.

**Comment by samccone** [comment]
:+1: :+1:

**Comment by jasonLaster** [comment]
Yup. The babysitter spirit will always be with us. Actually think it was a great first version for what it does.

**Comment by bazineta** [comment]
It'd be nice to have the third option, i.e., an enumerable object, which allows for implementation of CollectionView-esque things using a tested implementation.  For example, I've got a drag and drop dashboard view that uses BabySitter today, and it was easy to instrument with Inspector as a result.

Thus, at least in my case, I think it'd be nice to say 'if you want an inspectable view that manages subviews in some unusual manner, use one of these enumerable objects to manage the subviews, and Inspection will be yours, oh yes.....'

**Comment by ianmstew** [comment]
https://github.com/joefitter/backbone.enumerable/blob/master/src/backbone.enumerable.js
