### ISSUE TITLE
Provide APIs for rendering templates directly

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2317]
Not every bit of HTML needs complex event handling. Region, and other APIs, should be able to render templates directly.

**Comment by jasonLaster** [comment]
I think we can do better here as well. This is what we've got now:

```js
this.showChildView('footer', new Marionette.View({
  template: footerView,
  model: footerModel
}));
```

I think we could do something like:

```js
this.showContent('footer', footerTemplate, footerModel)
```

In this case, something like region events is nice for binding event handlers and what not...

**Comment by samccone** [comment]
what about...

```js
this.renderInto('footer', {model: foo, template: Bar})
```

**Comment by jasonLaster** [comment]
yea, I like that @samccone

**Comment by thejameskyle** [comment]
If we add this I would prefer it just cast a template into a view. It's not expensive, it keeps the region api clean, and it ensures that there are no incompatibilities.

**Comment by samccone** [comment]
"cast a template into a view" not sure whatcha mean?

**Comment by thejameskyle** [comment]
```js
renderInto(region, options) {
  var view = new View(options);
  this.getRegion(region).show(view);
}
```

**Comment by samccone** [comment]
yep exactly

**Comment by denar90** [comment]
What if instead of adding new API method just extend `showChildView` functionality. My proposal is pass View class instead of instance
```
showChildView(name, View = Mn.View, ...args) {
    const region = this.getRegion(name);
    return region.show(new View(args));
 }
```
But it look like breaking change.
