### ISSUE TITLE
(doc) customize page titles + missing favicon

### ISSUE THREAD

**Issue by mindrones** [marionettejs/backbone.marionette#2321]
If you open many tabs of the documentation it's difficult to find the one you're looking for, because tabs tend to shrink and you can't see the most interesting part of the title:
`<title>marionette.application - Marionette.js Docs</title>`

Also, the only page showing the Marionette logo as favicon is http://marionettejs.com/

It would be nice to have like:
- [Application](http://marionettejs.com/docs/v2.3.2/marionette.application.html) page title: `Application`
- [Region](http://marionettejs.com/docs/v2.3.2/marionette.region.html) page title: `Region`
- and so on...

If the favicon gets fixed there's probably no need to specify a `Marionette.js Docs` in the title.

**Comment by samccone** [comment]
hi @mindrones we have a repo and issue tracker for the www
https://github.com/marionettejs/marionettejs.com

would you mind reopeneing there?

**Comment by samccone** [comment]
ps thanks for this awesome issue :)

**Comment by mindrones** [comment]
Ah I see! Sure I'll reopen there sorry for the noise :)
