### ISSUE TITLE
I'd like to have an ability use one view with two regions

### ISSUE THREAD

**Issue by extempl** [marionettejs/backbone.marionette#2322]
For example, search results for different elements which shown with certain screen resolution. 
Now I need to initialize new view with different logic for second region.

**Comment by samccone** [comment]
hey @extempl you should take a look at LayoutView class http://marionettejs.com/docs/v2.3.2/marionette.layoutview.html

it does just what you want.

For future questions like this, it is best to refer to ask in the chat room
https://gitter.im/marionettejs/backbone.marionette/
