### ISSUE TITLE
When rendering an ItemView in Region of LayoutView, ItemView's "click" event triggers on LayoutView as well.

### ISSUE THREAD

**Issue by dogonthehorizon** [marionettejs/backbone.marionette#2323]
Greetings,

Per @jmeas 's direction, I'm filing a report here to see if we can get to the bottom of this puzzling issue.

Let's get the basics out of the way:
  - Backbone: 1.1.2
  - Marionette: 2.3.1
  - Underscore: 1.7.0
  - jQuery: 2.1.3
  - Operating System: OSX 10.9.5
  - Browsers: Chrome 40.0.2214.111 (64-bit) && Firefox 35.0

The gist of the issue is, when I've bound click events to both a LayoutView and an ItemView that is rendered in a Region of that same LayoutView, the ItemView's click event takes precedence. I've tried various levels of specificity for both event hashes (e.g. "click .button.alert.kv-item" in the ItemView) with no luck.

Each time I attempt to click on the LayoutView's element ("click .close"), the ItemView's event is fired and encounters the following error: `Uncaught TypeError: Cannot read property 'stopPropagation' of undefined`. This error is being thrown inside of the `destroy` method that I have defined for the ItemView's event handler.

Here's a minimal example of the code that triggers this behavior. The selectors for these events are mutually exclusive:

```javascript
var LV = Backbone.Marionette.LayoutView.extend({
 
    template: tpl,
 
    className: "md-content",
 
    regions: {
        "content": "#md-guts"
    },
 
    events: {
        "click .close": "closeModal"
    },
 
    closeModal: function(event) {
        event.stopPropagation();
        event.preventDefault();
 
        Radio.channel("modal").command("destroy");
    }
```

```javascript
var IV = Backbone.Marionette.ItemView.extend({
 
    template: tpl,
 
    events: {
        "click .kv-item": "destroy"
    },
 
    destroy: function(event) {
        event.stopPropagation();
        event.preventDefault();
 
        console.log("removing this item!");
    }
});
```

Any direction as to where the issue might lie? I'd be happy to provide more context after some code cleanup if it's necessary.

**Comment by samccone** [comment]
@dogonthehorizon mind throwing this into a jsfiddle or something

**Comment by dogonthehorizon** [comment]
Well, it seems that my choice of function in the `ItemView` was causing the strange behavior. Changing the event handler's name from `destroy` to `removeItem` seems to have resolved the issue.

Thanks to @paulfalgout for pointing me in that direction!

**Comment by paulfalgout** [comment]
:tada:

**Comment by samccone** [comment]
:boom:
