### ISSUE TITLE
Add api for binding an object to a radio channel

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2324]
Radio is a fantastic eventbus that we should make as easy to use as possible from within Mn. The api, I have in mind is `bindToChannel`, with some great defaults for things like Routes and Application

```js
var FormService = Marionette.Class.extend({
  logChannel: {
    'event info' :'onInfo'
  },

  formChannel: {
    'event invalid': 'onInvalid',
    'command submit' : 'submitForm'
  },

  initialize: function() {
    this.bindToChannel('log', this.logChannel);
    this.bindToChannel('form', this.formChannel);
  }
})
```

```js
headerRoute = Marionette.Route.extend({
  channel: {
    'command user:show' : 'userShow'
  }
});
```

**Comment by jasonLaster** [comment]
maybe types could be `on`, `reply`, `comply` instead of event, command, request

**Comment by thejameskyle** [comment]
Why not have something like:

```js
Whatever.extend({
  channelName: 'whatever',
  reply: {
    'foo': 'foo'
  },
  comply: {
    'bar': 'bar'
  }
});
```

**Comment by jasonLaster** [comment]
@thejameskyle definitely an option, my thought there is that it's actually kinda common to listen to multiple channels... so i like a flatter api there... also with the api for radio pretty set, i feel confident you can follow the pattern "type event"

**Comment by thejameskyle** [comment]
What about the inverse then:

```js
Class.extend({
  requests: {
    'myChannel foo': 'onFoo'
  },
  commands: {
    'myChannel bar': 'onBar'
  }
});
```

**Comment by jfairbank** [comment]
@thejameskyle I like that a little better for avoiding calling `this.bindToChannel`, but what do we call events? This wouldn't work on a view if we used `events` as the key.

**Comment by jasonLaster** [comment]
@thejameskyle - weird i'm surprised you're not a fan of grouping by channel.

```
channelName: { '(event|command|request) event': 'handler', ... }
```

feels a lot like the inspector radio view here:

![](http://f.cl.ly/items/3i233A2G250N2027341V/Image%202015-02-12%20at%206.22.00%20PM.png)

**Comment by jmeas** [comment]
I'm :+1: for this **if** we end up bundling Radio with Marionette v3.

**Comment by thejameskyle** [comment]
>  like that a little better for avoiding calling this.bindToChannel, but what do we call events? This wouldn't work on a view if we used events as the key.

@jfairbank I'm not sure this should be on every object anyways.

**Comment by jasonLaster** [comment]
Hmm, I do see the benefit of doing no or one bond with that api. Maybe radioEvents, radioCommands, radioRequests. 

@jmeas I think there will be other uses for Radio, but this is a really big way I want to market using Mn.

**Comment by jmeas** [comment]
I talked to @jasonLaster and I'm cool adding Radio in v3.

**Comment by paulfalgout** [comment]
Seems like it might be

```js
Class.extend({
  listenTo: {
    'myChannel baz': 'onBaz'
  },
  replyTo: {
    'myChannel foo': 'onFoo'
  },
  complyTo: {
    'myChannel bar': 'onBar'
  }
});
```
os `obj`, `event`, `handler` are the arguments for `listenTo`

And possibly:
```js
Class.extend({
  channel: 'myChannel'
  listenTo: {
    'baz': 'onBaz'
  },
  replyTo: {
    'foo': 'onFoo'
    'dogeChannel wow': 'onWow'
  },
  complyTo: {
    'bar': 'onBar'
  }
});
```

**Comment by jmeas** [comment]
:+1:

**Comment by paulfalgout** [comment]
Nice thought me, except `listenTo` is conflicting with `Backbone.Events`  :disappointed:

**Comment by jmeas** [comment]
Ha :P Completely missed that.

**Comment by jasonLaster** [comment]
@paulfalgout I liked that api as well. I guess this one runs into the same problem as `requests`,`commands`,`events`.

**Comment by paulfalgout** [comment]
Yeah :sob:   I am playing with some similar functionality on something we're building..

Anyone have better naming ideas..  to not halt the project I switched to `listensTo` `repliesTo` compliesTo`   Don't love it.

**Comment by jasonLaster** [comment]
heh - i don't mind that.

**Comment by paulfalgout** [comment]
I just know I'm going to type `listenTo` a bunch instead of `listensTo`, but it does work..  was also thinking of how we could use the term "radio" somehow to be explicit, but it gets wordy.

**Comment by jasonLaster** [comment]
radioEvents, radioCommands, radioRequests could be nice. 

I like events, modelEvents, childEvents, radioEvents side-by-side

**Comment by jmeas** [comment]
:+1: @jasonLaster

**Comment by paulfalgout** [comment]
Yeah I like that

**Comment by thejameskyle** [comment]
Using the `'channel event'`-style seems inconsistent with Backbone.View events where it is `'event element'`.

**Comment by jasonLaster** [comment]
I think the key is context specific. ModelEvents is just event or events and that's fine.

**Comment by jasonLaster** [comment]
Oops hit the wrong button.

**Comment by cmaher** [comment]
`'event channel`' would be weird. I think it's better to stay consistent with Radio's api: `Radio.comply('channel', 'event')`

**Comment by jasonLaster** [comment]
Yea, that's the conclusion I came to as well. I think it's more important for Radio's api to be consistent than our xEvents apis.

events, modelEvents, childEvents, radioEvents are all awesome way of doing event binding in a declarative fashion. I don't think the keys themselves need to be too consistent. 

I think this reads well! 

```js
radioEvents: {
  'app start': 'onAppStart',
  'app finish': 'onAppFinish',
  'books start': 'onBooksStart',
  'books finisht': 'onBooksFinish',
}
```

I've been thinking a lot about this event story for 3.0 and i'm really excited. Especially when our basic Marionette View in 3.0 will support regions

**Comment by thejameskyle** [comment]
It still seems weird to me to have multiple channels like that

**Comment by paulfalgout** [comment]
I kind of agree..  but it might be specific to my use case.

I'm much more likely to want
```js
channelName: 'books',
radioEvents: {
  'start': 'onBooksStart',
  'finish': 'onBooksFinish'
}
```

but it's not a stretch for me to consider something like:

```js
channelName: 'books',
radioEvents: {
  'app start': 'onAppStart',
  'app finish': 'onAppFinish', 
  'start': 'onBooksStart',
  'finish': 'onBooksFinish'
}
```

but it is moderately confusing / magical..

Perhaps we just end up with some `bindToChannel` helper that we use to build `radioEvents` to `this.channelName` and with which you could build your own `radioBookEvents` if need be?

**Comment by jridgewell** [comment]
I think the only one not suggested yet:

```javascript
radio: {
    channelName: {
        'eventName': 'method', // defaults to event
        'commandName command': 'other',
        'requestName request': 'another'
    }
}
```

**Comment by benmccormick** [comment]
I'm :+1: for the radioEvents, radioCommands,radioRequests  and `channel event` syntax.  I think this would make Marionette.Object a lot more useful too.

**Comment by thejameskyle** [comment]
If someone wants to throw an implementation together over in https://github.com/thejameskyle/marionette-wires maybe that'd give us something better to discuss the api with.

**Comment by rhubarbselleven** [comment]
Just throwing this one in here: https://github.com/jmeas/backbone.event-spec

In reading this, I'm thinking about consistency in event naming and that it should flow through from existing practices

**Comment by jasonLaster** [comment]
Yup would love to see this in wires.

**Comment by benmccormick** [comment]
So this isn't quite usable yet, but I threw together a Gist to mix this api in on Mn.Object.

It uses ES6 and is set up for my project (so it imports marionette as 'marionette' rather than 'backbone.marionette' among other small irregularities), so would need a bit of work to be chopped into a PR or used on other people's projects.  It also only supports Mn.Object because that was the use-case I was interested in and supporting more types is a pain since this requires overriding constructors.  

But I think its enough to show what this would involve

https://gist.github.com/benmccormick/0948b37c75107a42b07e

also to be clear this is using the syntax that @jasonLaster suggested:

```
radioEvents: {
  'app start': 'onAppStart',
  'app finish': 'onAppFinish',
  'books start': 'onBooksStart',
  'books finisht': 'onBooksFinish',
},

radioCommands: {
  'app doFoo': 'makeFooHappen',
},

radioRequests: {
  'resources bar': 'getBar',
},
```

I have a bunch of "service modules" in my app that just listen to a radio command and then either return a resource or execute a command (this is how I show toaster messages and log errors to the server for instance).  Right now they're just standalone modules, but I would definitely make them Mn.Objects using this API if it ships.

**Comment by jfairbank** [comment]
I've been playing with this by implementing something similar at work. So far I'm liking the idea of something like:

```js
var MyObject = BaseObject.extend({
  channelNames: ['foo', 'bar', 'baz'],

  // or radioEvents
  channelEvents: {
    'foo save:user': '_savedUser',
    'bar start': '_startedBar'
  },

  channelCommands: {
    'foo delete:user': '_deleteUser'
  },

  initialize() {
    this.getChannel('foo') === Radio.channel('foo');
  },

  _savedUser() {
    this.channelCommand('bar', 'stop');
    this.channelTrigger('baz', 'save:user');
  },

  ...
});
```

So, it's basically a similar API to what has already been suggested for handlers as well as some helpers like `channelCommand`, `channelTrigger`, `channelRequest`, and `getChannel`. Using the helpers has grown on me instead of grabbing a channel at the top of a module or using the Radio API directly. That somewhat decouples the idea of what event bus is driving these channels underneath.

**Comment by jasonLaster** [comment]
Cool Jeremy!

What does channelNames do?

**Comment by jfairbank** [comment]
`channelNames` is for declaring the channels to use with the object. Internally, it's placing references to each declared channel in `channelNames` on a `this.channels` object. So, basically: `this.channels.foo = Radio.channel('foo')`.

**Comment by benmccormick** [comment]
I just tossed together an initial PR to show what this might look like in terms of changes: #2431

The big part of course is that it requires Mn to be aware of Radio at all, either as a hard (BB -> _ style) or soft (BB -> $) dependency.
