### ISSUE TITLE
Publish triggerMethod as a separate module

### ISSUE THREAD

**Issue by cmaher** [marionettejs/backbone.marionette#2327]
I know some of us don't actually like the name 'triggerMethod', but whatever it ends up being called should still be a separate module. It fits the node mentality of small packages doing one thing well, and it would make it easier for other BB plugin authors to take advantage of it.

An added benefit of making it separate is that the idea of lifecycle events can catch on in other plugins as well, spreading the style and ideas of Marionette.

**Comment by samccone** [comment]
yes please, I need this for module.. and actually require all of marionette for this one method!

**Comment by samccone** [comment]
https://github.com/marionettejs/marionette.module/blob/master/src/module.js#L139

**Comment by jmeas** [comment]
> and it would make it easier for other BB plugin authors to take advantage of it.

True. Do we want to tho?

Every other day my opinion on triggerMethod swaps from 'OMG WORST THING EVER' to 'such a clever, useful utility.' I'm rly undecided on it.

@brian-mann, I'm curious, what are your thoughts on triggerMethod these days?

**Comment by cmaher** [comment]
I would really like it in backbone.hoard (https://github.com/cmaher/backbone.hoard/issues/35). `triggerMethod` gives YOU the power to decide how you want to extend components.  Do you want to capture events? Do you want to call some methods? do you want to do both? It also really helps you nail down a lifecycle and declaratively hook into it.

**Comment by jasonLaster** [comment]
@cmaher - just do it. we won't sue you

**Comment by jasonLaster** [comment]
meh - shouldn't close cause it's still *open* technically :P

**Comment by cmaher** [comment]
You know, we sometimes don't want to externalize things, so I wanted to check :dancer:

**Comment by jasonLaster** [comment]
Oh didn't think of this as an extract. I think I'm still plus one though.

**Comment by paulfalgout** [comment]
I'm closing this for now.  If someone wants to champion it, we can relook at it and reopen.. I personally am enjoying less library dependencies in v3
