### ISSUE TITLE
Add JSCS

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2329]
It will ensure that the code is a bit more consistent.

**Comment by jmeas** [comment]
I'm just now setting this up on my projects. For the most part, my coding style mirrors what we use in Marionette. I haven't tested this too thoroughly yet, but [this .jscsrc](https://gist.github.com/jmeas/abfa49cb177deb0694b8) could be a good place to start.

**Comment by samccone** [comment]
@jmeas how does this differ from jshint?

**Comment by jmeas** [comment]
JSHint = lint things that affect code behavior
JSCS = lint code style

At the moment, JSHint has a slew of style rules, like quote style. But @rwaldron pointed out in an issue that they are actively working on removing these in future versions of JSHint.

**Comment by ahumphreys87** [comment]
I found the link: http://jshint.com/blog/jshint-3-plans/

**Comment by samccone** [comment]
:+1:

**Comment by stackptr** [comment]
eslint bills itself as a more extensible linter than jshint, though I'm sure you all are aware of it. eslint works pretty well in my projects, though it is not limited to either style nor errors.

**Comment by benmccormick** [comment]
Worth noting that the jshint3 blog post is from 2013.  They may still be doing that some day, but it has been a loooong time coming.

**Comment by jmeas** [comment]
> They may still be doing that some day, but it has been a loooong time coming.

True, true. Even so, the fact remains that JSHint offers a very small number of style-related rules -- especially compared to JSCS.

This is more about using both of them to their full advantage. JSCS is amazing when it comes to style-related rules, and JSHint is great when it comes to the rest of it.

ESLint is another option, but I'd only want to consider it if it's trivial to get a system as powerful as the jshint+jscs combo. I don't think it's worth our time writing our own plugins for eslint.

**Comment by benmccormick** [comment]
Cool :+1: If you see value in JSCS, go for it.  If this was just "JSHint is going away" driven, I'd say you might be overthinking.

**Comment by jmeas** [comment]
> If this was just "JSHint is going away" driven, I'd say you might be overthinking.

Ah, right, right. Yeah I'm thinking that's just an added bonus.

To give an example, JSCS can force you to write this:

```js
function() {}
```

and not any of these:

```js
function () {}
function (){}
function(){}
```

I mean we usually catch these in PRs, but it'd be cool to have a linter check it for us.

**Comment by stephanebachelier** [comment]
:+1:

**Comment by ahumphreys87** [comment]
done via #2378
