### ISSUE TITLE
Collection trigger before:show on children only when buffering

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#2333]
Future added children *just* have `show` triggered

**Comment by paulfalgout** [comment]
Is this solved in 2.4?  I think it was here:  https://github.com/marionettejs/backbone.marionette/commit/ec6ef5932180bc4e84cd8315106792695c7c0b60

**Comment by JSteunou** [comment]
I dont know I'm still with 2.3 :(

**Comment by paulfalgout** [comment]
I'm closing this as I believe it is solved in 2.4, we can certainly reopen if not.
