### ISSUE TITLE
TemplateCache.loadTemplate does not work for empty existing templates

### ISSUE THREAD

**Issue by kachkaev** [marionettejs/backbone.marionette#2347]
Some templates may be intentionally left blank for various design reasons (e.g. some stuff can be unavailable for certain user languages). Current implementation of [TemplateCache.loadTemplate function](https://github.com/marionettejs/backbone.marionette/blob/2b900bba24d74c6c0cffad2740e07df69a15cc20/src/template-cache.js#L76) fails to consider empty templates as valid ones and throws an error. The reason for this is in relying on the length of the template's html:

```js
loadTemplate: function(templateId) {
    var template = Backbone.$(templateId).html();
    if (!template || template.length === 0) {
        throw new Marionette.Error({
            name: 'NoTemplateError',
            message: 'Could not find template: "' + templateId + '"'
        });
    }
    return template;
},
```

The problem can be avoided with this simple fix:

```js
loadTemplate: function(templateId) {
    var $template = Backbone.$(templateId);
    if (!$template.length) {
        throw new Marionette.Error({
            name : 'NoTemplateError',
            message : 'Could not find template: "' + templateId + '"'
        });
    }
    return $template.html();
},

```

**Comment by ianmstew** [comment]
@kachkaev This looks like a great candidate for the next patch release, `2.4.3`.  Would you care to open a PR against `patch`?  There are some possible caveats/edge cases around empty templates, but I think it would be easier to discuss once we have some code and a test case.

**Comment by ianmstew** [comment]
@ahumphreys87 Is the fix merged into `patch` yet?

**Comment by paulfalgout** [comment]
Yep it's in `patch` here: https://github.com/marionettejs/backbone.marionette/commit/81519ef36810a02076afa8a5d4d2718d380e36de
