### ISSUE TITLE
Add cross browser testing.

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2353]
@megawac I know you are doing this for Backbone and Underscore, mind giving it a go on this repo?

**Comment by megawac** [comment]
Where's QUnit?!!

**Comment by samccone** [comment]
Nooooooooo

**Comment by samccone** [comment]
but really, ping @megawac any interest in dropping some knowledge on this front for us? I know you setup the basic stuff on backbone, would love to have some help on this if you can find the time :)

thanks

**Comment by ahumphreys87** [comment]
Im guessing this will involve bringing karma back in? It provides a simple saucelabs plugin.

**Comment by megawac** [comment]
Grunt-saucelabs may work as well. I spent about an hr trying to get it
working but ran into some issues with the build steps (@sam and I were
supposed to figure this out a couple weeks ago. May look at it again
sometime this week, my schedule has calmed a bit
