### ISSUE TITLE
Investigate how we can provide a nightly build off of next and master

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2360]
This would be a really nice thing, and I think we can figure out how to get this working :)
anyone have thoughts about it? Pro or con?

**Comment by jasonLaster** [comment]
Yea, definitely pretty cool. Would be a fun blog opportunity too.

I could see some combination of github hooks + aws cron + S3, with a simple download link on the website.

**Comment by paulfalgout** [comment]
@denar90 any interest or know how in doing this?  You seem to be our devops guy lately :-D

**Comment by denar90** [comment]
This can be handy since we rerun site build each commit in master.

**Comment by paulfalgout** [comment]
Sooooooo Travis just added cron jobs.  Seems like a nightly build would be much easier with this:  https://docs.travis-ci.com/user/cron-jobs/

**Comment by denar90** [comment]
I've run several tests and started doubt on it purpose. Make it for `next` have no sense, maybe for using integration tests, but in another hand we want to run them during every PR which makes cron jobs not needed. Other than that, cron jobs are only for pushing stuff into branch directly not for PR's...
Doing it for `master`. I don't know... If we pushing some changes there it's not a problem redeploying site after every push. Spending time for this just to save some travis jobs will be waisting a time.

Guys I might misunderstood travis cron work, so please don't hesitate to correct me.

**Comment by paulfalgout** [comment]
If someone wants to champion this, let's reopen it.
