### ISSUE TITLE
Marionette - framework - performance slow over the time

### ISSUE THREAD

**Issue by shekarraos** [marionettejs/backbone.marionette#2361]
We developed iOS hybrid app using Phonegap plugin and Backbone framework with Marionette JS plugin. Our clients will use this for employees to sign-in/sign-out and this app will always open and running 24X7.

App works fine on fresh install for 1 week and app performance starts degrading after 1 week like below

Screen rendering very slow
Keyboard response is slow
If we continuously use it for 1 month, app hangs... we have kill it OR
restart iPad, then it works fine.
We thought webview is holding cache if app continuously running, we have implementented clearing webview cache by using phonegap plugin, still no luck.

Will there be any issues if we continuously run the app 24X7 ?

Is backbone framework creating any issues like cache all models data over the time ??

I have looked at heap profile Chrome dev tools, I could see few detached html elements.

I did use Backbone debugger tool,  I dont see Models are getting destroyed... Model objects are always increasing.

Its really useful if anybody can help on this.

**Comment by thejameskyle** [comment]
> App works fine on fresh install for 1 week and app performance starts degrading after 1 week like below

Can't tell if :trollface:

**Comment by samccone** [comment]
@shekarraos this is going to be basically impossible for us to debug without a reduced test case of your code that exhibits the problem. Can you provide us a sample of code that will make your memory issue happen?

**Comment by jmeas** [comment]
Closing. @shekarraos, these are called memory leaks. While it's not impossible that there is a memory leak in Marionette, it is most likely in your application code.

> Will there be any issues if we continuously run the app 24X7 ?

If you have memory leaks, yes.

> Is backbone framework creating any issues like cache all models data over the time ??

No. But there is currently a memleak in the `listenToOnce` method, so you should definitely refrain from using that.

I'm going to close this because, as @samccone pointed out, it is virtually impossible for us to do anything for you without more information. I encourage you to do more investigating. If you come up with something more concrete, then we would be happy to help.

**Comment by stephanebachelier** [comment]
@shekarraos you should profile your application using Xcode instruments tools. As pointed by @jmeas you need to check for memory leaks. 
But they are many causes that can make your app slowing down:
- are you cleaning the dom
- every event listener should be removed. I suppose you know that. You may have some conditions that prevent event listeners to be removed. DOM events, Backbone events
- pay attention to any scrolling handler that might not be removed
- remove images is sometimes not really sufficient and it can retains lots of memory
