### ISSUE TITLE
Issue getting regions using the regionManager

### ISSUE THREAD

**Issue by coldfumonkeh** [marionettejs/backbone.marionette#2362]
i ran the following code in my application and was receiving errors as the get() method was not defined

    var rm = new Backbone.Marionette.RegionManager();
    var regions = rm.addRegions({
      'modal': ModalRegion
    });
    regions.get('modal');

I think there is either an issue with the addRegions method and how it manages the regions, or the docs just need updating. Either way it was a problem.

**Comment by samccone** [comment]
you are calling get on the return value of addRegions,

you will want to call `get` on your regionManager instance, `rm` in your case.

**Comment by coldfumonkeh** [comment]
@samccone I did that too, and the same result and error.

**Comment by coldfumonkeh** [comment]
And isn't what I posted above the same as the code mentioned in the docs? 

```
    var rm = new Marionette.RegionManager();
    var region = rm.addRegion("foo", "#bar");
    var regions = rm.addRegions({
      baz: "#baz",
      quux: "ul.quux"
    });
    regions.get('baz').show(myView);
```

**Comment by samccone** [comment]
@coldfumonkeh try this

```js
   var rm = new Marionette.RegionManager();
    var region = rm.addRegion("foo", "#bar");
    var regions = rm.addRegions({
      baz: "#baz",
      quux: "ul.quux"
    });
    rm.get('baz').show(myView);
```

If the docs are incorrect would you mind opening a PR and we can get that in ASAP.
good catch :)
