### ISSUE TITLE
IE8 doesn't have Array.prototype.indexOf

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2363]
:disappointed: 

So https://github.com/marionettejs/backbone.marionette/blob/v2.4/src/collection-view.js#L98 fails.

We'll need to resort to `_.indexOf`

**Comment by samccone** [comment]
Fixed!

**Comment by sentientnebula** [comment]
Isn't about time to start thinking about dropping support for IE8?  Even Microsoft is set to abandon it soon.

**Comment by jmeas** [comment]
> Isn't about time to start thinking about dropping support for IE8? Even Microsoft is set to abandon it soon.

Unfortunately, clients dictate this. Many developers still work for clients that require IE8.

With that said, I think that it's reasonable if Marionette moved over to using ES5 features that [have polyfills](https://github.com/es-shims/es5-shim). I'll open an issue.
