### ISSUE TITLE
Adopt ES5 features with polyfills

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2364]
Marionette supports IE8 out of the box. This is great, but things are slowly moving toward a time when the majority of people will be supporting IE9+.

With this in mind, we may want to start taking advantage of ES5 features that [have shims](https://github.com/es-shims/es5-shim).

The user story goes from:

> Marionette supports IE8 out of the box!

to:

> Marionette supports IE9+ out of the box! Use the ES5 shim if you need to support IE8.

**Comment by cmaher** [comment]
I'm all for this (with proper docs) in v3.

**Comment by samccone** [comment]
i really want to see what complexity we drop by losing IE8 support before we go this way

**Comment by cmaher** [comment]
Related to the discussion in #2296.

Considering IE8 is scheduled for end-of-life by 2016, I don't think we still need to actively support it in the core code when 

1. Microsoft won't be supporting it
2. Really good shims exist that we can direct people toward

**Comment by devel-pa** [comment]
Unfortunately, as in http://www.theie8countdown.com/ still 10% of users use this browser. Talking about corporate it goes to 25% . Indeed sucks.
As I'm using anyway es5-shim, and I think it should be added for any serious project, I think the support for IE8 should be dropped, but the code should be still compatible with the shim library (there are few things there that can't be shimmed correctly).
Documentation must point to that in the most verbose way.
For sure the drop of support doesn't have to be the only purpose, but by the performance and usability improvement, less complexity and shorter codebase.
As of ES6 I am very excited about it, but still a very exotic thing for today. As it have to be compiled anyway to ES5 my humble opinion is to be postponed for version 4 or 5 of Marionette. No real advantage for today, and, if you want to use ES6 on your project Marionette is not staying in the way. Tested with babel and works flawless.

**Comment by sentientnebula** [comment]
theiecountdown.com data is two years old.  Things have changed drastically since then, including Microsoft's announcement that they will be dropping all support--including security updates--for IE8 this coming January.  I don't think it makes a lot of sense to continue supporting a browser that's been EOLed by Microsoft itself--especially if sticking to features with existing shims available.  Even the most bureaucratic corporate sloths are finally having their hands forced at this point.

**Comment by jmeas** [comment]
I'm going to open this back up...but please only add relevant comments that add to this discussion. @devel-pa, ES6 has **nothing** to do with this thread, and the rest of your comment just reiterated the opening message.

**Comment by devel-pa** [comment]
@jmeas Sorry for that, next time I'll shut up and stand back.

**Comment by cmaher** [comment]
The linked discussion talks about ES6 and necessitating ES5 polyfills for IE8, so I can see how that confusion could come about.

**Comment by samccone** [comment]
> Unfortunately, as in http://www.theie8countdown.com/ still 10% of users use this browser. Talking about corporate it goes to 25% . Indeed sucks.
As I'm using anyway es5-shim, and I think it should be added for any serious project, I think the support for IE8 should be dropped, but the code should be still compatible with the shim library (there are few things there that can't be shimmed correctly).

great point @devel-pa 


> For sure the drop of support doesn't have to be the only purpose, but by the performance and usability improvement, less complexity and shorter codebase.

I agree.

The primary concern for me is that, sometimes it is nice just to have a lib work without a polyfill. Like I sad before I would like to see the wins that we can get by dropping IE8 support before we decide on doing it.

**Comment by JSteunou** [comment]
Now that old IE are gonna be dropped this month and Mnv3 is ES6 maybe this issue can be closed.

**Comment by paulfalgout** [comment]
Technically I believe we are still supporting ES3.  But I dunno if dropping IE8 support will change our code base at all.

**Comment by paulfalgout** [comment]
I think this is safe to close.  I don't know that we're introducing anything requiring a shim and we don't spend too much time worrying about it either way..  We can deal with it if it comes up as an issue.
