### ISSUE TITLE
Add alternative array syntax for Behaviors

### ISSUE THREAD

**Issue by benmccormick** [marionettejs/backbone.marionette#2366]
As I've started to use Behaviors more, I've noticed that the current syntax for binding Behaviors to Views is optimized for a namespace based method of storing Behaviors.  As somebody who uses a module system (AMD and ES6 modules in my case), and uses several Behaviors that don't accept options, I end up writing extra code every time.  Specifically in situations like this

```javascript
import * as Mn from 'marionette';
import * as ValidationBehavior from 'behaviors/validation';
import * as KeymapBehavior from 'behaviors/keymap';
import * as WarnOnDestroyBehavior from 'behaviors/warn';

let ExampleView = Mn.LayoutView.extend({
    behaviors: {
        validation: {
            behaviorClass: ValidationBehavior,
        },
        keymap: {
            behaviorClass: KeymapBehavior
        },
        warn: {
           behaviorClass: WarnOnDestroyBehavior,
           message: 'Are you sure you want to delete this?'
        }
    },
});

export default ExampleView
```

So in this case validation, keymap, and warn are all unnecessary names that aren't used and don't need to be anything in particular.  They're basically just boilerplate/fluff.  I also have to keep typing behaviorClass and the object syntax even though classes are my primary way of defining behaviors, and I often don't need additional options.  It would be much nicer if I could write that code like this instead:

```javascript
import * as Mn from 'marionette';
import * as ValidationBehavior from 'behaviors/validation';
import * as KeymapBehavior from 'behaviors/keymap';
import * as WarnOnDestroyBehavior from 'behaviors/warn';

let ExampleView = Mn.LayoutView.extend({
    behaviors: [ValidationBehavior, KeymapBehavior, {
      behaviorClass: WarnOnDestroyBehavior,
      message: 'Are you sure you want to delete this?'
    }],
});

export default ExampleView
```

Instead of a big object and a bunch of boilerplate, I just pass the Behaviors as an array that accepts either a Behavior class, or an object that is defined the same way Behaviors are defined now.  So I avoid the unnecessary keys, and Behaviors that don't receive options can avoid all of the boilerplate altogether.

I'm happy to whip up a PR for this, I just wanted to get feedback first.  Note I'm proposing this as an additional syntax, not a breaking change.

**Comment by jasonLaster** [comment]
So, my hesitation here is that behavior name is nice for readability and the inspector.

**Comment by benmccormick** [comment]
If you use modules, you can create a nice readable name for the class.  And this would be an alternate syntax, not the only choice.  I can see the point about the inspector though, it would probably be hard to pull in the className rather than the key.

FWIW a version of the array syntax actually works today

```javascript
import * as Mn from 'marionette';
import * as ValidationBehavior from 'behaviors/validation';
import * as KeymapBehavior from 'behaviors/keymap';
import * as WarnOnDestroyBehavior from 'behaviors/warn';

let ExampleView = Mn.LayoutView.extend({
    behaviors: [{ behaviorClass: ValidationBehavior }, {
      behaviorClass: KeymapBehavior }, {
      behaviorClass: WarnOnDestroyBehavior,
      message: 'Are you sure you want to delete this?'
    }],
});

export default ExampleView
```

**Comment by Anachron** [comment]
I would argue that not naming your Behavior somethingBehavior but rather (Is)Closeable, (Is)Draggable, HasTooltip, HasModel etc is more clear.

**Comment by MasterLambaster** [comment]
@jasonLaster I'd use that alternative syntax to apply multiple behaviours of the same class. Right now you can do that only by creating behaviour class aliases

**Comment by benmccormick** [comment]
@Anachron sure, thats what is nice about modules.  You can name it whatever makes sense to you and your team.
