### ISSUE TITLE
CompositeView reorderOnSort ignores childViewContainer

### ISSUE THREAD

**Issue by bazineta** [marionettejs/backbone.marionette#2367]
Using a CompositeView with:

```
childViewContainer: 'tbody'
reorderOnSort: true
```
Moves the children outside of the table element on the first sort.  The sort is performed properly; the elements just aren't in the table afterward.  Issue appears to be that the reordering is being performed by the base CollectionView, not the CompositeView.

**Comment by samccone** [comment]
Good find @bazineta , would you be able to put together a jsfiddle

**Comment by bazineta** [comment]
I can try a jsfiddle.  Is there a basic one that's used as a basis for such things?

**Comment by samccone** [comment]
sure @bazineta use this as a base
http://jsfiddle.net/9847c0vL/1/

**Comment by bazineta** [comment]
http://jsfiddle.net/enwwk9je/1/

**Comment by thejameskyle** [comment]
Okay, it's just that it doesn't respect `childViewContainer` at all, not something related specifically to `<tbody>`.

**Comment by samccone** [comment]
fixed in minor, will come out with 2.4.1
