### ISSUE TITLE
v2.4.0 : attachHtml   error

### ISSUE THREAD

**Issue by ram-you** [marionettejs/backbone.marionette#2370]
Hi, have this error when updated to 'v2.4.0':
Cannot read property 'splice' of undefined
The undefined is: collectionView._bufferedChildren

I'm using a CompositeView.
Thank you for help.

**Comment by samccone** [comment]
Hi @ram-you would you mind putting together a JSFiddle or testcase for us to help debug?

you can use this as a base
http://jsfiddle.net/9847c0vL/1/

**Comment by ram-you** [comment]
Hi @samccone, this is the JSFiddle, just added 
```javascript
   initRenderBuffer: function () {
            this.elBuffer = document.createDocumentFragment();
        }
```
http://jsfiddle.net/4n7p3emf/1/

**Comment by hacfi** [comment]
@ram-you You’re overwriting the `initRenderBuffer` method which initializes _bufferedChildren: 
https://github.com/marionettejs/backbone.marionette/blob/master/lib/backbone.marionette.js#L2162

Change it to

```js
            initRenderBuffer: function () {
                this._bufferedChildren = [];
                this.elBuffer = document.createDocumentFragment();
            }
```

and everything works fine.

**Comment by ram-you** [comment]
Thank you @hacfi 
Works.
Please remove the 'unsolved' and 'bug' labels.

**Comment by hacfi** [comment]
As you created the bug you can just click the Close issue button at the bottom.
