### ISSUE TITLE
[2.4.0] Layout as item view

### ISSUE THREAD

**Issue by devel-pa** [marionettejs/backbone.marionette#2371]
A LayoutView that is a childeView of a CompositeView when onBeforeShow is triggered the regions elements are not available and all showChildView fails with: 
"Uncaught Error: An "el" .css-class must exist in DOM"

**Comment by samccone** [comment]
@devel-pa can you put together a JSfiddle for us to help debug

**Comment by devel-pa** [comment]
http://jsfiddle.net/uzkuvwfy/16/

Finally i could reproduce it when pushing an element in the collection.

Thanks, 
Paul

**Comment by paulfalgout** [comment]
I believe this is getting resolved here: https://github.com/marionettejs/backbone.marionette/pull/2434  Let me know if it doesn't look like a fix.
