### ISSUE TITLE
When a subview is rendered the parent view is destroyed

### ISSUE THREAD

**Issue by victorwpbastos** [marionettejs/backbone.marionette#2374]
I have a view with a table. When the user clicks on a table row a modal is rendered in another region. When the modal view is rendered the table view is destroyed. I realized that this is happening in all the versions since version `2.0.3`. All the versions until `2.0.2` are fine.

**Comment by jmeas** [comment]
This is pretty vague, @victorwpbastos. And it's unlikely that this is in the Marionette library itself. Can you create an isolated gist reproducing the problem?

**Comment by samccone** [comment]
This is related to the 2.0.3 release
https://github.com/marionettejs/backbone.marionette/releases/tag/v2.0.3

> Destroying a view outside of its region will now cause the region to remove its reference to that view.

**Comment by samccone** [comment]
@victorwpbastos I would love it if you could put together a JSFiddle to show us your use case, and we can provide some more help.

**Comment by paulfalgout** [comment]
Closing until there can be more info provided.
