### ISSUE TITLE
Destroying a Region should empty it as well (v3)

### ISSUE THREAD

**Issue by cmaher** [marionettejs/backbone.marionette#2379]
Currently, destroying a region will call `Marionette.Object#destroy`, which triggers events and stops listening.  It makes a lot of sense to also `empty` the region, thus destroying the contained view.  Some people might be depending on the current behavior, so this should be scheduled for whatever Region-type-thing we have in v3.

**Comment by ahumphreys87** [comment]
im :+1: for this for consistency, maybe `reset` is a better option over `empty` though, it does a bit more destroying! :boom:

**Comment by ahumphreys87** [comment]
fixed with #2869
