### ISSUE TITLE
Internal Documentation Linking

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#2380]
It would be great if the internal documentation linked to other sections/pages to get more information.

For example, in [CollectionView childview event bubbling](http://marionettejs.com/docs/v2.4.0/marionette.collectionview.html#childview-event-bubbling-from-child-views) I would like a link to the documentation for [triggers](http://marionettejs.com/docs/v2.4.0/marionette.view.html#viewtriggers). For new users, I think it can greatly speed up the understanding when you read documentation out of order.

**Comment by jasonLaster** [comment]
That's a great idea. I'd happily merge some PRs that added more links / more contextual information!

As a side note, doc PRs are the best. More ppl read docs than code and there are tons of ways to improve them!

**Comment by samccone** [comment]
:+1: @scott-w any interest in PR'ing some of this in?

**Comment by scott-w** [comment]
@samccone I'll get a few ideas in shortly :)
