### ISSUE TITLE
Add possibility to changing default Behavior during View initialization.

### ISSUE THREAD

**Issue by vovchok** [marionettejs/backbone.marionette#2386]
That would be cool to add the possibility to change Behavior during View initialization. It gives us the flexibility to initialize a view with the different kinds of behavior. The following changes will add the desired result.

In the src/view.js

``` javascript
this._behaviors = Marionette.Behaviors(this);
```

replace to

``` javascript
this._behaviors = Marionette.Behaviors(this,  this.getOption('behaviors'));
```

and in the src/behavior.js

``` javascript
if (!_.isObject(view.behaviors)) {
```

replace to

``` javascript
if (!_.isObject(view.behaviors) && _.isEmpty(behaviors)) {
```

Example of usage:

``` javascript
var Behaviors = {};

Mn.Behaviors.behaviorsLookup = function() {
    return Behaviors;
};

var DefaultBoxBehavior = Mn.Behavior.extend({
    ui: {
        box: ".box"
    },
    events: {
        "click @ui.box": "onClick"
    },
    onClick: function() {
        console.log("default behavior");
    }
});
Behaviors.DefaultBoxBehavior = DefaultBoxBehavior;

var NewBoxBehavior = Mn.Behavior.extend({
    ui: {
        box: ".box"
    },
    events: {
        "click @ui.box": "onClick"
    },
    onClick: function() {
        console.log("new behavior");
    }
});
Behaviors.NewBoxBehavior = NewBoxBehavior;

var BoxView = Mn.ItemView.extend({
    template: '<div class="wrapper"><a href="#" class="box">Click me</a></div>',
    behaviors: {
        DefaultBoxBehavior: {}      
    }
});

// default 
var befaultBox = new BoxView();
befaultBox.render().$el.appendTo("body");

// new
var newBox = new BoxView({
    behaviors: {
        NewBoxBehavior: {}      
    }
});
newBox.render().$el.appendTo("body");
```

**Comment by jasonLaster** [comment]
good call. Would be happy to :+1: a pr

**Comment by adorsk** [comment]
Another use case to consider for this is updating behaviors on view instance that has already been created.

For example, something like this (referring to @wovchok 's example above)
````
// default 
var befaultBox = new BoxView();
befaultBox.render().$el.appendTo("body");

// new
var newBox = new BoxView();

// Update behaviors on existing newBox instance.
newBox.updateBehaviors({NewBoxBehavior: {}})
````

I'll take a look into this.

**Comment by adorsk** [comment]
Placeholder note, re: behavior cascades.

As I'm working on this, I'm realizing that I don't understand how grouped (nested?) behaviors should interact.

The current behavior is that nested behaviors are treated as a flat list. If the same behavior is included multiple times in a view's behavior tree, then only the first behavior closest to the tree node is instantiated.

This could be potentially confusing, as a behavior might be defined with one set of options in one place, but be overridden in another. It's not clear to me how whether options should merge together.

For example, say we something like this (in rough pseudocode):

````
var FooBehavior = Marionette.Behavior.extend();
var BarBehavior = Marionette.Behavior.extend({
  behaviors: {
   foo: {flavor: 'chocolate', topping: 'nuts'}
  }
});

var MyView = Marionette.View.extend({
  behaviors: {
   foo: {flavor: 'vanilla'},
   bar: {}
  }
});

````

**Comment by ianmstew** [comment]
@jasonLaster Any thoughts on this?

**Comment by samccone** [comment]
> The current behavior is that nested behaviors are treated as a flat list. If the same behavior is included multiple times in a view's behavior tree, then only the first behavior closest to the tree node is instantiated.

This seems wrong.. @adorsk what is supposed to happen is both should be instantiated, would you be able to put together a test case for us?

**Comment by paulfalgout** [comment]
@marionettejs/marionette-core after looking into this and https://github.com/marionettejs/backbone.marionette/issues/2538 some more I believe we should close these issues.
At first glance this was interesting and seemed quite useful, but looking into the implementation made it less than ideal.

Essentially behaviors add their events and triggers at the same time as the view's events/triggers get added as part of `delegateEvents`

We can't reasonably remove or add a behavior after the events have been delegated without first undelegating and redelegating the events.  That is bad news 🐻 s.  

Fortunately `behaviors` can be defined as a function and you can use `getOption` inside that function, so just like `events` or `triggers` you can customize what behaviors are added during the initialization (this issue), and for #2538 while it might not be as clean, the use cases can be resolved by having the behaviors always set up, but with a flag of some sort they should bail out of their handlers if the behavior is not "enabled"  While that isn't quite as clear as add/remove, it's not unrealistic and won't hide poor performing re-delegations.

I'm going to close this for now, but we can reopen if someone has an issue with it.
