### ISSUE TITLE
reorderOnSort: true only works once when reversing collection order

### ISSUE THREAD

**Issue by bazineta** [marionettejs/backbone.marionette#2387]
When using
```
reorderOnSort: true
```
in a collection or composite view, the reordering will only work once when reversing the order of a collection.  Problem is here:

https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L179

Basically, this is running the list of models in the collection against the BabySitter's view of things.  The first time one changes the comparator such that the model order in the collection is reversed and sorts, we'll land here and the model order will be compared against the BabySitter's view of things.  They won't match, and so the view will be reordered.

However, nothing in the BabySitter has changed at this point.  If we then change the comparator again, once again reversing the order and sorting, we're once again back here, but now the model order matches what the BabySitter regards as correct.  As a result, orderChanged will be undefined; so far as the BabySitter is concerned, the model order and the view order are identical, so there's nothing to do.

Thus, one can reverse the sort order of a collection once, but subsequently, the view will remain unchanged.

**Comment by ahumphreys87** [comment]
Nice find @bazineta :+1:

**Comment by jgerigmeyer** [comment]
Just to clarify, this bug doesn't exist only when reversing the collection specifically. It's any time the collection returns to the original order.

**Comment by samccone** [comment]
:clap: great bug heh we knew there would be issues fun fun stuff

@jgerigmeyer @bazineta any takers on a PR?

**Comment by ahumphreys87** [comment]
Just discovered with @mezod that if you use `viewComparator` this is a workaround for this issue

**Comment by mezod** [comment]
Yeah, I don't seem to have this bug. I can switch from sortByDate to sortByDateReverse to Custom in any pattern indefinately!

**Comment by cmaher** [comment]
resolved by #2455
