### ISSUE TITLE
Provide a standard mechanism for tweaking collection/compositeView HTML output before attaching to DOM.

### ISSUE THREAD

**Issue by sentientnebula** [marionettejs/backbone.marionette#2388]
Example use case:  A View similar to a bowling score sheet with a couple of twists.

A standard bowling score sheet can be easily represented by a sheetView CompositeView containing a collection of gameView rows.  Each gameView, in turn can be represented by a CompositeView consisting of a playerName, a Collection of sets, and a total box.

The twists:  Number of sets is variable, and the width of the score sheet adjusts to fit user device display size and/or user preference.  This is done by setting maxSetsPerRow low enough to not exceed the constraints on the sheet width.  If the actual number of sets per game exceed maxSetsPerRows the sets wrap within their container to form multiple “subrows” per game and extra empty sets are injected as needed to ensure everything divides out evenly and grid remains nicely aligned.  There is no totals box to worry about.

So what is the problem?  In Theory, there is no problem, and in practice there is USUALLY no problem.  At standard 100% zoom there is no problem on any target browser, but certain combinations of device/browser/custom-zoom-level create a 1px rounding error that make the grid render less than perfectly.

The  solution:
Fortunately, all you need to do to prevent this rounding error is to wrap a div around each of the “subrows” that occur when setsPerGame > maxSetsPerRow.

In Marionette 2.3.2 and prior, I achieved this by overriding attachHtml, buffering the setView childViews into a div node until once each maxSetsPerRow iteration, at which point I appended the div node (div-wrapped set of childViews) in place of a childView.

My app broke after upgrading to Marionette 2.4 because attachHtml now passes the childView to attachBuffer, which in turn passes it to _buildBuffer.  buildBuffer wants to extract the node itself from  a childView's el itself rather than taking a node directly.  In addition to overriding attachHTML, I also had to override _buildBuffer to append plain b rather than b.el in order for it to work.

I didn't like this because it was starting to feel a bit convoluted.  Then I thought, with the code changes in 2.4, wouldn't it be better to remove the attachHTML override, let childViews buffer normally, and then apply custom logic at buffer building time?  So I just overrode _buildBuffer and nothing else, and it feels like a much cleaner solution.

The only problem is that the underscore in _buildBuffer implies that it is a private internal function for use by attachBuffer, and not something that should be overridden.

Prior to Marionette 2.4 attachHtml has been a popular point of override for applying custom logic.  2.4 makes overriding attachHtml a bit more problematic.  Creating custom buffer builder logic is a cleaner solution in some situations.  I think think _attachBuffer should be renamed to attachBuffer, or some other mechanism created to allow for custom logic to be applied to  collection/composite HTML output before attachment.

**Comment by ahumphreys87** [comment]
@sentientnebula couldn't this be achieved in your template? or by changing the template using `getTemplate` when `maxSetsPerRows` per row is exceeded?

**Comment by sentientnebula** [comment]
If it was just a matter of adding a conditional div to the template, I'd say yes.

There is, however, no limit on total sets per game, and on a small display, maxSetsPerRow could be as low as 3.  In a gameView with a collection of 24 sets, displayed at the narrowest sheet width setting, there would be 7 “row” breaks (8 “rows”).  I put “rows” in quotes because gameView doesn't care how the sets end up being arranged to fit a particular display.  I just inject the hard div “rows” at buffer building time to help out the rendering engines.

Injecting wrappers in _buildBuffer is an extremely straight forward process.  I'm not sure how you'd accomplish the same thing in the gameView template without a few contortions.

**Comment by sentientnebula** [comment]
Sorry to confuse matters.  I kept referring to _createBuffer as _buildBuffer.

_createBuffer is the correct function name.

**Comment by ahumphreys87** [comment]
@sentientnebula forgive me, I think Im missing something - would you mind putting together a gist?

**Comment by sentientnebula** [comment]
Concise version:
 
What:  Group childViews before dropping them into the childViewContainer.
Example:  24 childViews, maxSetsPerRow = 8   
Standard:  24 spans dropped into childViewContainer
Modified:   3 divs (containing 8 spans each) dropped into childViewContainer

```
_createBuffer: function(collectionView) {
  var elBuffer = document.createDocumentFragment(),
    childViewSubContainer, column, rowLength = this.maxSetsPerRow;

  _.each(collectionView._bufferedChildren, function(b, index) {      
    column = index % rowLength + 1;
    if (column == 1) {
      childViewSubContainer = document.createElement('div');
    }
    childViewSubContainer.appendChild(b.el);
    if (column == rowLength) {
      elBuffer.appendChild(childViewSubContainer);
	}
  });
  return elBuffer;
}
```

Why:  To prevent potential rendering glitches (1px rounding errors) when displaying at certain zoom-levels.

Under most circumstances, both versions display exactly the same.  The modified version is bullet-proofed against edge-case rendering scenarios.

**Comment by ahumphreys87** [comment]
@sentientnebula this functionality would be achieved using the same logic in `getTemplate` and using an alternative template.

Please let us know if you need help debugging this.

**Comment by sentientnebula** [comment]
Are you suggesting I create an infinite number of templates?   I'm not sure what purpose calling getTemplate would serve when the combinations are endless.  Screen size, view size, and amount of content are all completely dynamic.  It's not simply a matter of exceeding a fixed limit or not.

**Comment by ahumphreys87** [comment]
If you override `attachBuffer` is there anything preventing you from manipulating the buffer that is passed to it? I think that would be an alternative to `getTemplate`

**Comment by sentientnebula** [comment]
Currently, in 2.4.1, you can easily override attachBuffer and call your own customCreateBuffer in place of calling _createBuffer with optimal performance, because the buffer only gets created once.  Your patch calls _createBuffer a step earlier and sends the result to attachBuffer.  Continuing to call  customCreateBuffer from attachBuffer would result in the buffers being created twice and the first one ignored.

Manipulating the already constructed buffer in attachBuffer, would only solve the needless performance hit of creating the buffer twice if doing so was a fast operation.  Due to the nature of the underlying string manipulations involved, doing so would likely be even slower than just recreating the buffer a second time, which is, obviously, less performant than only creating the buffer once.  The code would also be messier.

Renaming _attachBuffer to attachBuffer and making it an approved override point would solve all these issues.  Right now I am overriding _createBuffer and it is working perfectly.  I just don't like overriding a method marked as private.   This suggests that it is for Marionette's internal use only, and that there is no good reason to override it, which there clearly is--unless you want to take a performance hit for no good reason.

What is your objection to renaming _createBuffer to createBuffer?

**Comment by theseyi** [comment]
@sentientnebula I have a similar issue with the new internal implementation of attachHtml, (which is really a misnomer now, since no html is attached or manipulated in the method), however, did #2496 solve the issue you describe here? or are you still using your custom implementation of overriding _createBuffer? Thanks

**Comment by theseyi** [comment]
@ahumphreys87
