### ISSUE TITLE
Set Region.$el to expected values during initialization?

### ISSUE THREAD

**Issue by trusktr** [marionettejs/backbone.marionette#2389]
If I `console.log(this.someRegion.$el)`, from inside a `LayoutView` during the `LayoutVIew`'s initialization, I see that `this.someRegion.$el[0]` is `undefined`, which can cause unexpected results when people are wish to use `$el` during initialization code.

`console.log(this.someRegion.getEl(this.someRegion.el))` returns the expected result in `LayoutView.prototype.initialize` (at which point regions have been initialized, but not necessarily having shown anything, so `this.someRegion.$el` isn't ready).

Maybe `Region.prototype._ensureElement` needs to be called at some point before `Region.prototype.show`, like in the constructor, to ensure that `$el` is available for classes that extend Region by the time their overriden `Region.prototype.initialize` is called?

**Comment by trusktr** [comment]
I updated the original comment. I'd wrongly though that `$el[0]` was the `document` when in fact `$el[0]` is simply `undefined`, and the `context` of `$el` is `document` (which can also lead to unexpected results, and that might be better changed as well.

**Comment by trusktr** [comment]
Here's an example of `initialize` in a view that extends LayoutView, using requestAnimationFrame to wait for the regions to be ready:

```js
  /**
   * @override
   */
  initialize: function () {
    $(window).on('scroll', _.bind(this._windowScrollHandler, this));

    // Wait for regions to be ready, then trigger a window scroll event.
    requestAnimationFrame(_(function frame() {
      if (!this.region1.getEl(this.region1.el).length ||
          !this.region2.getEl(this.region2.el).length ||
          !this.region3.getEl(this.region3.el).length) {

        requestAnimationFrame(frame.bind(this));
      }
      else {
        // finally, all regions have a gettable el, so
        $(window).trigger('scroll');
      }
    }).bind(this));
  },
```

Alternatively, here's the same thing waiting for `$el` of each region:

```js
  /**
   * @override
   */
  initialize: function () {
    $(window).on('scroll', _.bind(this._windowScrollHandler, this));

    // Wait for regions to be ready, then trigger a window scroll event.
    requestAnimationFrame(_(function frame() {
      if (!this.region1.$el.length ||
          !this.region2.$el.length ||
          !this.region3.$el.length) {

        requestAnimationFrame(frame.bind(this));
      }
      else {
        // finally, all regions have a gettable el, so
        $(window).trigger('scroll');
      }
    }).bind(this));
  },
```

The first example will always fire sooner than the second example because `getEl` will return a `Backbone.$` object at some point in time after the initial constructor call before but before `getEl` itself has been used internally to set `Region.$el`. The second method looks cleaner, but has the downside that `$el` might never have a length greater than `0` if the `show` method of a Region is never called (for example, if we render a view in the Region's supposed element and the Region has no idea), and `this._windowScrollHandler` in my example will fail if it relies on such a Region's `$el`.

Is there a better way to do what I'm doing? Is there anything I should avoid doing in favor of something else in order to be able to rely on a Region's `$el` for a window scroll (or similar) event?

**Comment by paulfalgout** [comment]
There are quite a bit of issues around when layouts are rendered and when regions are available.

This does seem not quite ideal though.  What is the concerns of `_windowScrollHandler` in relation to the regions and layout?

**Comment by trusktr** [comment]
@paulfalgout `_windowScrollHandler` just needs to do something to some DOM whenever the user scrolls, but the $el reference isn't available yet. `initialize` might be a bad place to do this. I'm betting `onRender` of each subview would be much better, `_.after(3, _windowScrollHandler)`.
