### ISSUE TITLE
CollectionView documentation

### ISSUE THREAD

**Issue by Ky6uk** [marionettejs/backbone.marionette#2390]
Documentation for CollectionView should be improved. Here is missing some events: `before:render:empty`
`render:empty`
`before:remove:empty`
`remove:empty`

**Comment by samccone** [comment]
@Ky6uk thanks for the note, would you like to open a PR adding this. It would be very much appreciated.

**Comment by Ky6uk** [comment]
@samccone ya. I would wrote it, but my english is not perfect. :)

**Comment by jasonLaster** [comment]
@Ky6uk go for it. Get the OSS commit ;)
