### ISSUE TITLE
How to test complex marionette applications

### ISSUE THREAD

**Issue by RomanKapitonov** [marionettejs/backbone.marionette#2391]
I've been developing a pretty big and complex application using marionette and the approach described in [these](http://www.backbonerails.com/series) screencasts. So far i've come to a point where i am afraid to change anything without breaking existing functionality. There is a list of libraries for testing client side applications and jasmine is among the most popular ones. However i could not find any good tutorial or guide on how to test marionette applications.

With all that in mind perhaps we should consider adding a detailed guide on how to test marionette applications using jasmine (as far as it's the alpha and omega in client side application testing).
How do you test your applications?

**Comment by quentindemetz** [comment]
I use:
- mocha and chai for unit testing my views
- casperjs with sinonjs for integration testing

**Comment by paulfalgout** [comment]
I also use mocha and chai for unit testing.

You might also check out:
http://karma-runner.github.io/0.12/index.html
http://pioneerjs.com/
http://www.cypress.io/ (coming soon)

And come chat with everyone over on http://gitter.im/marionettejs/backbone.marionette to see how they're doing it.
