### ISSUE TITLE
sort() calls render on CompositeView

### ISSUE THREAD

**Issue by mezod** [marionettejs/backbone.marionette#2392]
Hello,

I have a composite view representing a list that has a header with 2 icons to change the type of sort. When I click on an icon, I expect two things:

1. To style the clicked icon as to show which sort is selected
2. Sort the collection

I am doing it like so:
```js
     dateCreatedSort: function(e){
		    	console.log("column:datecreatedsort");
		    	var column = this.columnId;

		    	$('#'+column+'-column span').removeClass("selected");
	    		$('#'+column+'-column span.dateCreatedSort')
	    			.addClass("selected dateCreatedSortInverse")
	    			.removeClass("dateCreatedSort");

		    	this.options.viewComparator = function(model) { 
		    		return (new Date(model.get('dateCreated'))).getTime(); 
		    	};
		    	
		    	this.collection.sort();
      }
```
If I go step by step in the console, I can see that the styles are properly changed, then the sort is executed successfully (the collection is sorted) but for some reason the view is re-rendered and thus, the styling is overwritten by the default. I am not actively rerendering the view.

I am using Marionette 2.4.1 so it's not the issue related with the ChildViewContainer that was fixed for this version.

The complete code can be found here: https://github.com/mezod/multikanban/blob/master/app/scripts/apps/kanban/show/show_view.js#L319

Any ideas on why could the view be rerendered?

**Comment by ahumphreys87** [comment]
@mezod are you using the `reorderOnSort` option? I thought you were based on our chat in gitter but I cant see it in you code. http://marionettejs.com/docs/v2.4.1/marionette.collectionview.html#collectionviews-reorderonsort

If you aint using that option then the default behaviour is to rerender if the order has changed.

**Comment by mezod** [comment]
No, I wasn't using the reorderOnSort option. This fixes this issue, thank you @ahumphreys87 !

**Comment by samccone** [comment]
heh still a bug tho!

**Comment by mezod** [comment]
Come on man, it's the first time I close an issue in my life and you take 5 secs to reopen it, hahah joking :P Why is this still a bug though? If I understood correctly, it is normal behaviour that the CompositeView rerenders on sort when reorderOnSort isn't set, right?

**Comment by ahumphreys87** [comment]
It is the default behaviour but it relates to this open PR: #2325

Which is that a CompositeView should only render its children rather than the full view on a sort.

**Comment by samccone** [comment]
ah yes yes sorry keep getting our future versions and this mixed up!
