### ISSUE TITLE
Annotated source header bug?

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/backbone.marionette#2393]
This shouldn't be a header, right?

![image](https://cloud.githubusercontent.com/assets/1666031/6475060/910542d2-c1d4-11e4-9b7c-4145782167b8.png)

**Comment by samccone** [comment]
yes

**Comment by jdaudier** [comment]
https://github.com/marionettejs/backbone.marionette/blob/master/src/layout-view.js#L55-L56

**Comment by samccone** [comment]
yeah needs a `\`

**Comment by jdaudier** [comment]
Do we even need `#2134:` part?

**Comment by samccone** [comment]
eh debatable

**Comment by jdaudier** [comment]
is that referring to a PR? don't see other comments with references to PRs

**Comment by samccone** [comment]
yep it is a ref to the issue, no need I suppose for it

**Comment by thejameskyle** [comment]
I would actually prefix that with "Issue #"

**Comment by jdaudier** [comment]
is it possible to link to the issue?  or do we think people will search for it?

**Comment by samccone** [comment]
sure it is just markdown @jdaudier

**Comment by jdaudier** [comment]
cool

**Comment by thejameskyle** [comment]
Looks like this was fixed

**Comment by jdaudier** [comment]
Still need to be fixed

![image](https://cloud.githubusercontent.com/assets/1666031/6597727/ddf7b420-c7d4-11e4-8749-9ad02bba1537.png)

**Comment by samccone** [comment]
because we have not deployed, the annotated source is built based on the tags, thus it will be like this until the next release and forever like this on this version.

**Comment by jdaudier** [comment]
so we don't rebuild the annotated source constantly but just once when we do a release?

**Comment by samccone** [comment]
Every deploy we do rebuild, however we build based on tags, so that they are snapshots in time
