### ISSUE TITLE
CollectionView attachBuffer not invoked internally as documented

### ISSUE THREAD

**Issue by dkurucz** [marionettejs/backbone.marionette#2395]
Line 2171 invokes attachBuffer with only one parameter (this), while the documentation notes that this should have a second parameter as well, the buffer itself.  It is no longer possible to add the children in the overridden method without manually constructing the buffer out of _bufferedChildren.  Not sure if this is a new design, but this was working correctly in 2.0.1.  Thanks!

**Comment by dkurucz** [comment]
please see proposed solution at https://github.com/marionettejs/backbone.marionette/pull/2396

**Comment by ahumphreys87** [comment]
fixed via #2503
