### ISSUE TITLE
Dependency issues in Node

### ISSUE THREAD

**Issue by FishbaitHarry** [marionettejs/backbone.marionette#2397]
- Backbone works fine in Nodejs, it doesn't depend on jquery and doesn't list it in package.json
 - Backbone.Marionette depends on Backbone and does list it in package.json
 - Backbone.Marionette depends on jquery (or a similar library), but does not list it in package.json
 - The line: `Marionette.Deferred = Backbone.$.Deferred;` throws an error in Nodejs environment regardless of whether jquery is available or not, because Backbone doesn't require it and doesn't provide it.

Possible solution: when Marionette detects being in CommonJS environment, it should probably require jquery explicitly. What do you think about it?

**Comment by samccone** [comment]
See for the jquery dependency
https://github.com/marionettejs/backbone.marionette/issues/2300

For how to use in commonjs (browserify) see https://github.com/marionettejs/marionette-integrations/tree/master/browserify
