### ISSUE TITLE
Investigate first class ractive support

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2398]
https://github.com/ractivejs/ractive

Worth looking into what the combination would look like at least, or what would be involved.

**Comment by Forbin** [comment]
Very exciting! Would like to see what your initial thoughts are and rough timeline.

**Comment by rogovdm** [comment]
+1 to excitement

**Comment by samccone** [comment]
Hey @Forbin @rogovdm  this is just a ticket, anyone that is interested I would love to see any experiments or whatnot. I am guessing the final result will be something like the awesome work 
@tiagorg did here: 
github.com/tiagorg/Marionette.VDOMView

**Comment by rafde** [comment]
This issue feels a bit dated. @paulfalgout : safe to close?

**Comment by paulfalgout** [comment]
I dunno. Guess so. Seems like first class ______ support is a better objective. @blikblum has already done quite a bit of research into this kind of thing. Maybe we can close this and the idom ticket and any related one to open up a more general one regarding renderers and dom differs. Kind of two related issues with dozens of combinations of solutions.
