### ISSUE TITLE
Adding regex to AppRouters appRoutes hash

### ISSUE THREAD

**Issue by cjroebuck** [marionettejs/backbone.marionette#24]
Hi Derick, I need to add a regex to the appRoutes hash. Is there a clean way to do this using AppRouter, previously with Backbones Router I just did `this.route <regex>,<name>,<callback>`

as in http://documentcloud.github.com/backbone/#css(pre%3Anth-child(167))

Im trying to figure out how to put my regex into the AppRouter so that its `processAppRoutes` function can deal with it properly..

**Comment by neptunian** [comment]
When i use the initialize function because I need a regex route, the method is called using 'options.controller.someMethod' as suggested. But inside the 'someMethod' function, 'this' does not refer to the correct object.  So i cannot reference other methods using 'this' in my Controller object.

**Comment by yellowcap** [comment]
@neptunian this comes late and I add this here for future reference. I had the same problem and was able to bind the controller to `someMethod` using underscorejs `_.bindAll(options.controller,  'someMethod')`
