### ISSUE TITLE
accessing router options from the appRoutes callback

### ISSUE THREAD

**Issue by newtonianb** [marionettejs/backbone.marionette#2401]
I'm using Marionette.SubRouter which extends from Marionette.AppRouter. Marionette.SubRouter allows me to pass parameter object when instantiating the router. My issue is I'm trying to get ahold of that object from within my callback ``myPath``. Inside my ``appRoutes`` callback this refers to the API object. How can I do this?

```
(in a different module)
new App.MyApp.Router("prefix", {myvar: 'test'})
```

```
API =
  myPath: ->
   # debugger  # how can I access options here
class MyApp.Router extends Marionette.SubRouter
  controller: API
  initialize: (options) ->
    { @myvar } = options
  appRoutes:
    "my-path" : "myPath"
```

**Comment by samccone** [comment]
Hi @newtonianb please ask this in https://gitter.im/marionettejs/backbone.marionette/ or on stackoverflow

We try to keep the issue tracker for bugs and or feature requests. Thanks!

**Comment by newtonianb** [comment]
Sorry will do thanks

**Comment by samccone** [comment]
no worries :+1:
