### ISSUE TITLE
childTriggers or childProxy

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2404]
On a view, `events` has a sister hash `triggers` for conveniently converting DOM events into view events.  Thanks to @jasonLaster's #2316, we are now uniformly dealing with `childEvents` across all views with children.  I propose a sibling hash to _childEvents_ called `childTriggers`.  _childTriggers_ would be a logical parallel to _triggers_ in that it converts child events to "my own" view events.

The logical parallel is nice, but the real value of _childTriggers_ would be the ability to declaratively proxy child events, in other words give the ability to bubble, or deeply link, events through views more than 2 levels deep.  This solution would avoid any unintended or complicated side effects of "auto proxying" the way DOM nodes do, and would serve as a more elegant solution to #2341 than we have today while prioritizing zero magic over automation.  I imagine the PR would apply childTriggers to _all_ views implementing _childEvents_.

Example:

Instead of
```js
childEvents: {
  activate: function () { this.triggerMethod(‘activate’); }
}
```

We would have
```js
childTriggers: {
  activate: 'activate'
}
```

Or even
```js
childProxy: {
  activate: true
}
```

**Comment by ahumphreys87** [comment]
I like the idea of providing this, however the issue I have is that when you listen for these events you have no way of telling whether the event is a `childEvent` or an `event`.

Maybe we append `child:` to the event name? So:

```
childTriggers
  activate: 'activate'
}

this.listenTo(view, 'child:activate', function() {
  // called when the childTrigger activate is fired
});
```

@marionettejs/marionette-core thoughts?

**Comment by jasonLaster** [comment]
@ahumphreys87 agreed. I'd think that `childTriggers` use a similar `childPrefix` or whatever for that reason

**Comment by ianmstew** [comment]
Thanks for commenting, @ahumphreys87 .

If childTriggers is defined on a view, the developer is explicitly choosing the event name to be re-fired on the view.  This is exactly how the _triggers_ hash works; the power to choose the event name is completely in the hands of the developer, and because the developer is defining it there are no surprises.

For example, if I cause event collisions like so using the plain triggers hash, the fault is my own:

```js
triggers: {
  'click': 'render'
}
```

I am making a recommendation with parallel logic for _childTriggers_.  The developer should have the same power and responsibility of _triggers_, except in the scope of child event rather than DOM events.

If I shoot myself in the foot with the following, the responsibility is mine.

```js {
childTriggers: {
  'activate': 'render'
}
```

My concern with prepending "child" is that power is removed from the developer in naming events, and we end up with the problem that childEvents itself solves: a potential for "child:child:child:event".

**Comment by ahumphreys87** [comment]
@ianmstew I'm :+1: for this feature, it makes sense. Im with @jasonLaster and think we should keep consistent with `childEvents` and use `childEventPrefix`

**Comment by ianmstew** [comment]
Ahhh, I missed that reference to the existing use for `childViewEventPrefix`.  Yes, it definitely makes sense to use it for `childTriggers`.

I think I was also confused on another point.  Using the `childViewEventPrefix` would still provide the ability to write my example code, because within the `childTriggers` hash the prefix is implied.

**Comment by ianmstew** [comment]
The only question I have left is the API.  The `triggers` hash follows this format:

```js
triggers: {
  'domEvent': 'viewEvent'
}
```

It makes sense for `childTriggers` to follow an analogous format:

```js
childTriggers: {
  'childEvent': 'viewEvent'
}
```

Do you think extra sugar would be appropriate, mapping a value of "true" to a reflection of the key value, where this:

```js
childTriggers: {
  'childEvent': true
}
```

implies this?

```js
childTriggers: {
  'childEvent': 'childEvent'
}

**Comment by ahumphreys87** [comment]
@ianmstew I like what your trying to do here. However  this case I feel having the extra sugar for `true` may confuse matters a bit - I'd don't think this would be expected behaviour,  for me reading the code it's much more readable if the event thats triggered is rewritten in front of me. This is just my opinion though. @marionettejs/marionette-core thoughts?

**Comment by paulfalgout** [comment]
Yep I'm :-1: on the `true` sugar too.

So with this.. `View.triggers` uses `triggerMethod` exclusively when triggering.  Are we expecting that it would catch only `triggerMethod` triggers as well, or it would also catch `Backbone.View.trigger`?

Currently the layout `childEvents` only works with `triggerMethod`, but https://github.com/marionettejs/backbone.marionette/issues/2464 is opened to change that.  However `childEvents` does work with `trigger` on a `CollectionView`

And although we could have the same API for `View` and `CollectionView` I'd imagine the implementation might be relatively different.. particularly dependent on #2464?

**Comment by ianmstew** [comment]
@ahumphreys87 @paulfalgout I was on the fence about that, thanks for your feedback.  I'm with you that the keystrokes saved probably isn't worth creating a new pattern.  Maybe if it were "childProxy" instead of "childTriggers" that would make more sense, but I do prefer the "childTriggers" parallel to "childEvents".

@paulfalgout My gut says it should work with any `trigger`, and I would like to see it fall in line with #2464.  Thanks for pointing out the difference.  Are you both comfortable with my moving forward with `childTriggers` support for both `triggerMethod` and `Backbone.View.trigger`?

**Comment by paulfalgout** [comment]
I would prefer seeing, both.  Not sure if the methods of proxying between `childEvents` on `CollectionView` and `LayoutView`.. err.. `View` can be generalized and reused here or not, but hopefully there's some form of sane consolidation that can be done.

**Comment by ianmstew** [comment]
That would definitely be nice.  I'll be on the lookout for consolidation opportunity as I proceed.

**Comment by jasonLaster** [comment]
2 cents. Let's move ahead with childTriggers 

Supporting trigger is a different ticket. We should do that too tho!

**Comment by ianmstew** [comment]
K, like it.  Keep `childTriggers` completely parallel to `childEvents` and only support `triggerMethod` at first.  After doing so, create a parallel ticket to #2464 or expand it to cover `trigger` for `childTriggers`.

**Comment by paulfalgout** [comment]
So I've recently encountered a couple of instances in which bubbling an event up was useful outside of a view.  I'm wondering if the bulk of this could be done in a util that could also be applied to object such that something like
```js
myObject.listenTo(myView, 'some:event', function(arg1, arg2){
  this.triggerMethod('some:event', arg1, arg2);
});
```
could just be:
```js
myObject.proxyEvent(myView, 'some:event');
```
or possibly even something like:
```js
myObject.proxyEvent(myView, 'some:event', 'viewPrefix:');
```
Then if it supported a hash, `childTriggers` would simply be an internal use of this util much like `collectionEvents` uses `bindEntityEvents`

**Comment by jasonLaster** [comment]
that could be nice. like bindEntityEvents but a little different...

**Comment by ianmstew** [comment]
@paulfalgout I'm loving it.  I cannot wait to get this in, along with #2464.  My bubbling looks like this right now (worse if there are multiple event arguments):

```js
childEvents: {
  'show:settings-modal': function () { this.triggerMethod('show:settings-modal'); },
}
```

Could be this:

```js
childTriggers: {
  'show:settings-modal': 'show:settings-modal'
}
```

Instead of a view prefix, maybe an optional event name rewrite more like childTriggers?

**Comment by ianmstew** [comment]
I just thought of something.  One way `childTriggers` should probably differ from `triggers` is that `triggerMethod(eventName, view, model, collection)` would not be useful.  We'll want to proxy the original event's arguments exactly.  I think this makes sense because we are simply proxying view events, not converting DOM events to view events.

**Comment by megawac** [comment]
:+1:

Do we want to support the `all` event or what should we do in that case. It will require special handling in either case

(does this have to be on v3 exclusively or picked on to 2 as well)
