### ISSUE TITLE
modelEvents and collectionEvents fire twice when set as a function

### ISSUE THREAD

**Issue by mbmufffin** [marionettejs/backbone.marionette#2405]
Like the title says, I'm seeing `modelEvents` and `collectionEvents` fire twice for a given view when shown. The `events` hash does not fire twice when set as a function.

Here is a JSFiddle that demonstrates what I'm talking about: http://jsfiddle.net/M5J8Q/1712/

If you inspect the console logs, you'll see that the log in the `modelEvents` function fires twice, while other functions fire once.

Is this the expected behavior?

**Comment by infiniteluke** [comment]
I would say it's expected.

modelEvents get grabbed during event delegation. Apparently backbone calls undelegateEvents inside of delegateEvents. Both are overriden in Marionette and end up grabbing the modelEvents through getOptions.
(https://github.com/jashkenas/backbone/blob/52973d31068d6c3fcf6bbb5042d93ee1496e9896/backbone.js#L1226)

It looks like the only reason Backbone would do this is to cover the case where multiple views are attached to the same el.(https://github.com/jashkenas/backbone/blob/52973d31068d6c3fcf6bbb5042d93ee1496e9896/backbone.js#L1244)

**Comment by paulfalgout** [comment]
This has been solved in major here: https://github.com/marionettejs/backbone.marionette/commit/19b73f0ced209e1aaabc038c145b574c34aeac23

**Comment by samccone** [comment]
:+1: flagging with major and closing
