### ISSUE TITLE
proxyChildEvents should allow empty childViewEventPrefix

### ISSUE THREAD

**Issue by honi** [marionettejs/backbone.marionette#2417]
proxyChildEvents could check if childViewEventPrefix is empty or undefined before appending it to the rootEvent:
https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L580

This would allow to proxy child events without a prefix. If childViewEventPrefix is empty, the current behavior is that proxied events are appended just a ":" which doesn't make much sense.

If you consider this a valid use case I can prepare a proper PR.

**Comment by jasonLaster** [comment]
I do. Thanks @honi. Glad you're using them!

**Comment by paulfalgout** [comment]
So why is this a valid use case?  Wouldn't you get n+1 renders when a collection view renders?  And if one childview destroyed, it would proxy it up, and collectionview would trigger as if it destroyed which would then call empty on the collectionview's region..  seems like a can-o-worms?

**Comment by jasonLaster** [comment]
It's a huge can-o-worms. Didn't think it through Paul. 

Happy to re-open if there's a good counter argument.

**Comment by honi** [comment]
hmm.. good point.

My use case is that I'm using a CollectionView to easily create many views which I would otherwise create individually. So I wanted to capture the child events as if the CollectionView didn't exist. 

But then again, appending ```childview:``` when registering the listener isn't such a big deal.

**Comment by jasonLaster** [comment]
:) my thought too. Guess we can't have nice things
