### ISSUE TITLE
Consider supporting displayName

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2425]
`displayName` is a non-standard way of naming functions.  This is useful for determining what class an instantiated object comes from.  Particularly useful for the inspector https://github.com/marionettejs/marionette.inspector/issues/98, however it would be useful for debugging in general..  It is however not fully supported by any browser other than firefox, many debugging tools support it to some extent.

It was purposefully avoided in coffeescript so I imagine it would not end up in backbone.
https://github.com/jashkenas/coffeescript/issues/1767

However it is fully supported in JSX and react.
https://github.com/facebook/react/pull/799

It would be super easy to implement, with almost 0 cost to anything.  Thoughts?

**Comment by jasonLaster** [comment]
I like it. Will ping the chrome devtools group and see what they think

**Comment by paulfalgout** [comment]
devtools guys may very well say to use `function.constructor.name` over `displayName`

But in the case of the react devtools, they use both:
https://github.com/facebook/react-devtools/blob/e47bccd514121574c95fcfc80f4bf2b3e5bb91ca/injected/InjectedScriptHost.js#L47

**Comment by jasonLaster** [comment]
chromium devtools:
https://code.google.com/p/chromium/issues/detail?id=17356

**Comment by samccone** [comment]
lets do it :)

**Comment by Lbatson** [comment]
hey all. I was going to look into this as I'm wanting to start to contribute, however I've had the same issue on both my computers getting an error with `npm install`. I've tried `npm cache clean` and removing `~/.npm` and still have an issue when trying to install off of `master`. Any help with this would be appreciated as I'd like to take a stab at working on this issue. Here's the full debug output. Thanks

    npm ERR! Darwin 14.1.0
    npm ERR! argv "node" "/Users/Lance/.nvm/v0.10.32/bin/npm" "install"
    npm ERR! node v0.10.32
    npm ERR! npm  v2.7.6
    npm ERR! path /Users/Lance/Projects/backbone.marionette/node_modules/grunt-lintspaces/node_modules/editorconfig/bin\editorconfig
    npm ERR! code ENOENT
    npm ERR! errno 34

    npm ERR! enoent ENOENT, chmod '/Users/Lance/Projects/backbone.marionette/node_modules/grunt-lintspaces/node_modules/editorconfig/bin\editorconfig'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent`

**Comment by eth0lo** [comment]
I see the benefit with this, nevertheless why introduce that when [Function.name](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Function/name) serves a similar propose, and is considered in the standard

**Comment by denar90** [comment]
Can we do it automatically? Found babel [plugin](https://www.npmjs.com/package/babel-plugin-transform-react-display-name) just for react 😞

**Comment by paulfalgout** [comment]
I think browsers are making this less and less important.  We can reopen if someone want to champion it.

**Comment by bmeurer** [comment]
As pointed out earlier in this thread, the "name" property on `Function` instances was made configurable in ES6 as a standard replacement for "displayName". We're dropping support for "displayName" in Chrome with M90 (https://bit.ly/devtools-function-displayName-removal).

**Comment by samccone** [comment]
Thanks @bmeurer for the input on this :) 👋  everyone else
