### ISSUE TITLE
When a CollectionView is shown by a Region, its children's before:render is never fired

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2428]
Consider the following nested structure:

```js
var ChildView = Marionette.LayoutView({
  regions: {
    grandchild: '.js-grandchild'
  },
  // never called
  onBeforeShow: function () {
    // never shown
    this.showChildView('grandchild', new GrandChildView());
  }
});

var ChildrenView = Marionette.CollectionView({
  childView: ChildView
});

var TopLayout = Marionette.LayoutView.extend({
  regions: {
    children: '.js-children'
  },
  onBeforeShow: function () {
    var childrenView = new ChildrenView();
    this.showChildView('children', childrenView);
  }
});
```

When a CollectionView is rendered by a Region, the Region calls [_view.render()_](https://github.com/marionettejs/backbone.marionette/blob/1b2222e2cf61e70fc2f8a513894b334c59867485/src/region.js#L90) before [triggering _show_](https://github.com/marionettejs/backbone.marionette/blob/1b2222e2cf61e70fc2f8a513894b334c59867485/src/region.js#L134).  A CollectionView's _render()_ method ultimately calls _\_triggerBeforeShowBufferedChildren()_ before returning, which [checks _\_isShown_](https://github.com/marionettejs/backbone.marionette/blob/1b2222e2cf61e70fc2f8a513894b334c59867485/src/collection-view.js#L59).  The problem is that _\_isShown_ is only set when [_show_ is fired](https://github.com/marionettejs/backbone.marionette/blob/1b2222e2cf61e70fc2f8a513894b334c59867485/src/dom-refresh.js#L33), which hasn't yet.  Thus, before:render is never fired on the instances of ChildView.

**Comment by ianmstew** [comment]
When trying to figure out why _before:show_ is broken on ChildView instances but not _show_, I found this:

https://github.com/marionettejs/backbone.marionette/blob/1b2222e2cf61e70fc2f8a513894b334c59867485/src/collection-view.js#L31
https://github.com/marionettejs/backbone.marionette/blob/1b2222e2cf61e70fc2f8a513894b334c59867485/src/collection-view.js#L115-L117

It appears _show_ is propagated after the fact, but there isn't a similar consideration for _before:show_.

**Comment by ahumphreys87** [comment]
fixed with #2463

**Comment by ianmstew** [comment]
@ahumphreys87 @jasonLaster We should tag this v2.4.2 and cherry-pick #2463 from `next` like we're doing with the attach/beforeAttach PR.  I think people (incl me) will appreciate having this fixed sooner rather than later.

**Comment by jasonLaster** [comment]
Yup
