### ISSUE TITLE
App with router and 1 Module with its own router?

### ISSUE THREAD

**Issue by elgubenis** [marionettejs/backbone.marionette#2430]
Hi,

I am trying the following:
I have one Marionette.App and in the initialize of it im initializing a Router,
after that im using Backbone.history.start with pushState true,
now i have a route in this router which is cars* when this route is triggered (via cars or cars/add etc.)
then a Module is started, this module is initializing a new Router (just for that module i hoped) and it has its own cars and cars/add routes, but now the "App-Router" is not triggering anymore any cars* route.. but i would like that behavior to control the stop and start of my modules, maybe not the best idea but i think thats the only part missing, re-attach the 1st Routers routes (after Module stop)

**Comment by elgubenis** [comment]
i know that the AppRouter is not intended to solve these kind of purposes, but i would like to use it anyway, it almost works.. the only thing missing is that the first initialized Routers routes get overriden by the Router(s) initialized after..

**Comment by paulfalgout** [comment]
Please join us in the https://gitter.im/marionettejs/backbone.marionette for discussions such as these.

That said, I personally don't setup routers on start/stop, but the routers are always available and determine what should start/stop.  However you might also want to check out https://www.youtube.com/watch?v=F32QhaHFn1k or one of the other router related videos on the marionette youtube channel.
