### ISSUE TITLE
Unnecessary recursive view call

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2438]
In [this block of code](https://github.com/marionettejs/backbone.marionette/blob/c5115b0f52b4ca0bf09d0da9581e50fee73dd3c0/src/region.js#L116-L127), `displayedViews = this._displayedViews(view);` is called twice.  I don't see how the `view` display hierarchy can change between calls, so the second seems to be unnecessary.  Am I missing something?  If not, I'll submit an PR to optimize.

Edit: The only reason the view display hierarchy might change is if the developer overrides `attachHtml(view)` and does something to `view` besides attaching html (uses the method improperly).  Do we want to protect ourselves from this, or is it better to optimize here?

**Comment by jasonLaster** [comment]
I think we did this because you might not do `before:attach` and do `attach`. 

maybe add check for using displayedViews if it's not empty?

**Comment by ianmstew** [comment]
Good point.  That check would make it safe.  I like clean code and adding the extra check isn't as clean.  But saving another recursive call could be worth it...  What do you think?

**Comment by jmeas** [comment]
This is necessary and intentional. Change it, and you'll see that the tests fail. 

> The only reason the view display hierarchy might change is if the developer overrides attachHtml(view)

Not true. `onBeforeAttach` provides an opportunity to render sub views.

**Comment by ianmstew** [comment]
I see your point about rendering sub views in onBeforeAttach.  I did not consider that, but it is certainly a logical possibility.

Within that scenario, I noticed there is an opportunity for descendant views to fire onAttach without ever firing onBeforeAttach, so even with both traversals in place there isn't a guarantee that the total event lifecycle will be correct.  This could be a discussion in a separate issue, but I'm not sure if this qualifies as an issue.  What do you think?

**Comment by jmeas** [comment]
> Within that scenario, I noticed there is an opportunity for descendant views to fire onAttach without ever firing onBeforeAttach

Can you elaborate on this?

**Comment by ianmstew** [comment]
Here's what I had in mind.  It's definitely not a simple scenario, so I wouldn't be surprised if it went unnoticed indefinitely.

Suppose `region` is attached to the dom in the process of showing `childLayout`.  `region.show()` will reach this point:

- `if (attachedRegion && triggerBeforeAttach)` true
  - collect `childLayout` and its descendant view references, which do not yet contain `grandchildLayout`
  - fire onBeforeAttach on `childLayout` and its descendant view references

Suppose within `childLayout#onBeforeAttach` `childLayout` creates `grandchildLayout` and shows it, `childLayout.region.show()` will reach this point:

- `if (attachedRegion && triggerBeforeAttach)` false
  - skip: collect `grandchildLayout` and its descendant view references
  - skip: fire onBeforeAttach on `grandchildLayout` and its descendant view references

Since `region` has already collected the descendant view references for `childLayout` which do not include `grandchildLayout`, `region` will not trigger attach on `grandchildLayout` unless `childLayout` is re-shown.

This would not be an issue if `attachedRegion` was guaranteed to be true, which is the case after attach the html to the dom.  Therefore, onAttach would not experience issues even when rendering sub views within onAttach.

**Comment by jmeas** [comment]
@ianmstew, I still don't follow. Have you looked through the unit tests to see if what you're thinking about is covered?

**Comment by ahumphreys87** [comment]
@ianmstew maybe a failing unit test would be helpful here, this would help explain and form the base for a fix

**Comment by ianmstew** [comment]
@jmeas, thanks for requesting more clarity, I see what you mean.  @ahumphreys87, that was I thinking--a failing test might be the best way.  If I arrive at one I will open a new ticket, since the topic is a bit tangential.

**Comment by jmeas** [comment]
Cool, gonna close this issue in the meantime, then.

**Comment by ianmstew** [comment]
:+1:
