### ISSUE TITLE
Start Marionette Guides

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2448]
There should be a guides section that walks through main concepts

**Comment by grimor** [comment]
+1

**Comment by timtan** [comment]
+1

**Comment by scott-w** [comment]
I just happened to start writing something about 20 minutes ago when I saw this. I'll push some of my initial thoughts as a readme in the repo and see what people think.

**Comment by jdaudier** [comment]
Need writers to plug the missing sections.  Feel free to add new subchapters or re-arrange them as you see fit. Ping me if you have any questions regarding the setup.

* Repo: https://github.com/marionettejs/guides
* Preview: http://marionette.gitbooks.io/marionette-guides/content/

cc/ @benmccormick @parris @moimikey @joshbedo @trezy @kkemple @techpeace @ianmstew @mmckelvy @MeoMix @scott-w

- [x] Introduction
- [x] Why Marionette?
- [ ] Getting Started
   - [ ] Installing Marionette
   - [ ] Installing Marionette Inspector (@ianmstew?)
- [ ] Creating an Application
- [ ] Implementing Routing
- [ ] Connecting Data to Your Views
- [ ] Handling Data Latency
- [ ] Dealing with Complex Persisted Data (@mmckelvy?)
- [ ] Nesting Your Views
- [ ] Passing Data with Events (@samccone? - this is your evented registry pattern)
- [ ] DRYing up Your Views with Behaviors (@jasonLaster?)
- [ ] FAQ
- [ ] Cookbook

![image](https://cloud.githubusercontent.com/assets/1666031/6989053/0ad689a0-da25-11e4-99c6-15f84af7151c.png)

**Comment by ianmstew** [comment]
Awesome stuff, @jdaudier @scott-w!  Complex persisted data is one of my favorite topics.  I'm talking about taking complex, nested data, modeling it with simple Backbone models, then passing into complex view trees.

**Comment by scott-w** [comment]
I've also put together something for tutorials. It's still WIP but have a read and see what you think at https://github.com/scott-w/backbone.marionette/tree/getting-started/docs/tutorial

The idea is to include this in the main documentation as one of the first sets of documents a new developer would access.

**Comment by parris** [comment]
I'd be up for taking a chapter. Maybe routing? Also, if we want a multi
page example + requirejs + grunt, I know a lot about that. Possibly part of
the cookbook?

**Comment by jdaudier** [comment]
@ianmstew Feel free to write a sub-chapter if you're free.  My friend Mark was gonna add some stuff to that along the lines of https://www.penflip.com/mmckelvy/marionette-blog-post

**Comment by jdaudier** [comment]
@parris @scott-w @ianmstew feel free to move the chapters around or add / change them as you see fit.     the outline for the patterns is inspired by Sulc's book and Sam's training deck.

**Comment by jdaudier** [comment]
@scott-w Could the tutorial and the guide become one?  Or is the tutorial different?

**Comment by scott-w** [comment]
My idea for the tutorial is just a link on the website that would take a user to a working Marionette app, and a few different ideas. I'm not going very in-depth on anything at all.

**Comment by jdaudier** [comment]
scott-w oh like a guick start guide... wonder if we should combine them and have a quick start at the top of the guides

**Comment by scott-w** [comment]
That's basically what it is, yeah. I can definitely do that if you'd like me to copy+paste the information over.

**Comment by benmccormick** [comment]
Related: https://github.com/marionettejs/marionettejs.com/issues/280  @samccone you may be interested in this discussion

**Comment by jdaudier** [comment]
@scott-w I'm kinda thinking of closing the guides repo 'cuz what you're writing is what I imagine guides to be. Maybe we can join forces?

**Comment by scott-w** [comment]
@jdaudier Absolutely, I just want to get something off the ground but I imagine there's better writers than me at this stuff :+1:

**Comment by jdaudier** [comment]
@scott-w cool! LMK if you have questions regarding how the guides repo is set up and how to add your sections.  Here's [Gitbook's documentation](http://help.gitbook.com/format/markdown.html) and their [source](https://github.com/GitbookIO/documentation) so you can see how they set up their site & book.

**Comment by scott-w** [comment]
@jdaudier Yeah no bother. I'll keep hammering away at the documentation here for now then maybe I can pick up with you on Gitter later tomorrow?

**Comment by jasonLaster** [comment]
:)

**Comment by SauloSilva** [comment]
+1

**Comment by toszter** [comment]
Hi all.  I was just over in the gitter Marionette thread mentioning that I'm in the middle of a port from 1.1.2 to 2.4.1 and I'm very willing to share some of the 'cookbook' patterns for modular view management, data management, routing and template integration... I'm actually porting to coffeescript from raw JS and using nunjucks for templating... Assuming this is of interest to many out there looking to get started with Marionette, I'd like to know what the path of least resistance is to writing and supporting Marionette long term? Thank you!

**Comment by stephanebachelier** [comment]
@jdaudier I'm can help in writing the section about the behaviors.

**Comment by jdaudier** [comment]
@stephanebachelier Thanks! That would be awesome.

**Comment by stephanebachelier** [comment]
@jdaudier let's go :)

**Comment by rafde** [comment]
Hmm... I am not sure when Marionette 3 will come it, but it seems like the guide having do to with Views will need some updating.

**Comment by jdaudier** [comment]
Yup

**Comment by jdaudier** [comment]
Thanks @scott-w! Closing.
