### ISSUE TITLE
sort() not taking effect after changing the viewComparator

### ISSUE THREAD

**Issue by mezod** [marionettejs/backbone.marionette#2449]
I have a compositeview that can be sorted in 3 different ways, date created (asc/desc), date completed (asc/desc) and custom sort. As you can see in the [implementation](https://github.com/mezod/multikanban/blob/master/app/scripts/apps/kanban/show/show_view.js#L314) I basically change the viewComparator and call .sort() again when any of the sort icons are clicked. The viewComparator appears to successfully get updated, but the sort() doesn't resort the collection.

Live version:

www.multikanban.com/login
user: wolol
pw: wolo
click on the "photography" link in the left menu to have a collection for testing.

Also, some sorts do work for some columns while not for others. All the columns are using the same implementation.

Any ideas of what could be wrong? Surprisingly this used to work smooth after this commit: https://github.com/mezod/multikanban/commit/8a1db2512c3987e1a517525ae3981fd9b71b2f1e
but now, coming back to that version doesn't work either... thanks for the help!

**Comment by jasonLaster** [comment]
@cmaher ?

**Comment by cmaher** [comment]
Are you passing in the `sort` option? https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L86

Note: should a `viewComparator` automatically trigger listening to sort events too?

**Comment by mezod** [comment]
could you provide an example of what you exactly mean?

**Comment by mezod** [comment]
I changed this.collection.sort() with this.resortView() and it apparently works now. I say apparently because this.collection.sort() worked perfectly the day 2.4.1 was released and now the docs have changed and this resortView has popped up... so basically I have:

       this.options.viewComparator = 'position';
       this.resortView();

**Comment by cmaher** [comment]
The `CollectionView` will only listen to sort events if `sort` is true (which is the default). Can you confirm that https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L176 is being hit, and if it is, what is the value of `orderChanged`?

**Comment by mezod** [comment]
going back to the version with this.collection.sort(), I confirm the line is hit:

- in the cases where the resort actually works orderChanged is an object: Object { cid="c29", attributes={...}, collection={...}, more...}
- in the cases where the resort doesn't work orderChanged is undefined. 

There is an order change in the case I am testing. I repeat, if I change this.collection.sort() by this.resortView() everything works as expected! Either there's something funny with that .find or ?

**Comment by cmaher** [comment]
Ok, I found the problem, going to open it in #2454 to reduce noise. Basically, reordering isn't properly updating the indices of views.  That said, sorting a collection when you have a custom view comparator seems like a waste, since the collection sort isn't actually doing anything to influence the view . So `resortView` might be the way to go.
