### ISSUE TITLE
Link to source tap

### ISSUE THREAD

**Issue by kvslee** [marionettejs/backbone.marionette#2456]
Hi, thanks for this awesome tool. When I click on method links in the Inspector, am I supposed to be led to Chrome Source tap automatically, right? Did I miss anything?

**Comment by samccone** [comment]
hey @kvslee can you open this on this repo please
https://github.com/marionettejs/marionette.inspector

**Comment by kvslee** [comment]
Sorry, my mistake. I post it on the repo. Thanks.
