### ISSUE TITLE
onBeforeShow and onShow on CollectionView child views are not called with view parameter

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2462]
There are 7 instances in total that lead to `onBeforeShow` and `onShow` of child views called without a view parameter.  Here are two examples:
* https://github.com/marionettejs/backbone.marionette/blob/08bfcbea6000901d8a268ad572883090c0c85868/src/collection-view.js#L317
* https://github.com/marionettejs/backbone.marionette/blob/08bfcbea6000901d8a268ad572883090c0c85868/src/collection-view.js#L75

This is out of line with the way `Region#show` calls `onBeforeShow` and `onShow`:
* https://github.com/marionettejs/backbone.marionette/blob/08bfcbea6000901d8a268ad572883090c0c85868/src/region.js#L99
* https://github.com/marionettejs/backbone.marionette/blob/08bfcbea6000901d8a268ad572883090c0c85868/src/region.js#L134

**Comment by ahumphreys87** [comment]
Fixed with #2463
