### ISSUE TITLE
View childViewEvents should support trigger

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2464]
`LayoutView` only supports `triggerMethod`. This inconsistency with `CollectionView` `childEvents`  has come up more than once now in gitter.

**Comment by jasonLaster** [comment]
Agreed

**Comment by jasonLaster** [comment]
I'm not sure if there's a ticket for this, but I wonder if the "fix" could be to make trigger triggerMethod in V3. In pseudo code, backbone.Events.trigger = triggerMethod. 

The advantage is that we'd be supercharging B.E not competing. If this is a distraction we'll just override trigger for M.AV to support bubbling. Thoughts?

**Comment by paulfalgout** [comment]
So perhaps this is bad pattern, but `triggerMethod` is not async safe, where-as `trigger` is.  Arguably you can use `triggerMethod` safely if you setup a different listener, or you can constantly be watching for situations not to trigger, but for instance:
This will trigger safely.  onSomeEvent will never be called.
```js
$.when(promise).done(_.bind(this.trigger, this, 'some:event'));
this.on('some:event', this.onSomeEvent);
this.destroy();
promise.resolve();
```
This will still call the method onSomeEvent:
```js
$.when(promise).done(_.bind(this.triggerMethod, this, 'some:event'));
this.destroy();
promise.resolve();
```

**Comment by jasonLaster** [comment]
@paulfalgout - this is a really interesting point, mind creating a separate issue for this discussion. I'd like to see why that is w/ the implementation

**Comment by ianmstew** [comment]
Hey guys, can we bump this to 2.5?  I am super anxious to have this is in, especially after making it clear in 2.4.3 docs that LayoutView does not support `childEvents` triggered with, er, `trigger`.

**Comment by paulfalgout** [comment]
FWIW if we fix this it will make bubbling work everywhere https://github.com/marionettejs/backbone.marionette/issues/2667

Previously I would have considered this a major issue.  With `childViewEventPrefix: false`  (hopefully the default for v4) I think this would actually be ok.  It would be easy enough to avoid bubbling or utilizing it when you needed to, and I think this is already the expected behavior.
