### ISSUE TITLE
Channels on the app not properly proxied

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2469]
The docs say that the application's Channel's methods are proxied on the app itself, but they are not.

For instance, [the example here](https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.application.md#request-response) says that these are equivalent:

```js
var groceryList = MyApp.reqres.request("todoList", "groceries");
var groceryList = MyApp.request("todoList", "groceries");
```

when, in fact, they are completely differently.

#### Wat?

[Look at this code.](https://github.com/marionettejs/backbone.marionette/blob/master/src/application.js#L145-L148) ...do you see it yet?

Okok I'll tell ya. The way these event buses *work* is by using an internal cache of events. For Radio, these are `_events`, `_requests`, and `_commands`. These internal caches are really what the Channel itself **is**. The methods themselves rely on these caches to know what events to use.

The problem is that we proxy the methods, but **not** the caches.

#### Wat to do?

Probably something like:

```js
this.channel._events = this.channel._events || {};
this.channel._requests = this.channel._requests || {};
this.channel._commands = this.channel._commands || {};

this._events = this.channel._events;
this._requests = this.channel._requests;
this._commands = this.channel._commands;
```

**Comment by jmeas** [comment]
Note that the app I'm currently working on *breaks* with that above hack, but they are overwriting Marionette classes directly. So it's a tough call on whether to release this as an actual bugfix, or to just update the docs.

**Comment by paulfalgout** [comment]
Sorry I don't quite follow.  What's the expected behavior that isn't happening?  I haven't looked into it too much but it seems to work as expected in a very simple case:
```js
var MyApp = new Marionette.Application();
MyApp.reqres.setHandler("todoList", function(list){ return "You requested " + list; });
MyApp.reqres.request("todoList", "groceries");  // =>  "You requested groceries"
MyApp.request("todoList", "chores"); // => "You requested chores"
```

**Comment by jmeas** [comment]
Ah interesting. With Wreqr it's not a bug 'cause of the `vent`, `reqres`, and `commands` objects. It's only a bug with the Radio shim in my Gist.

@paulfalgout you're right; the above example is wrong. But if you shim in Radio, then the following:

```js
var groceryList = MyApp.channel.request("todoList", "groceries");
var groceryList = MyApp.request("todoList", "groceries");
```

are not the same.
