### ISSUE TITLE
Redesign View architecture 

### ISSUE THREAD

**Issue by MasterLambaster** [marionettejs/backbone.marionette#2471]
***Background:***
I looking a way to create couple view extensions that'll allow some simpler subview rendering or even template rendering.
Here's code for some better understanding
```javascript
var View = Marionette.ItemView.extend({
  template: _.template(...),
  templates: [
    {
      template: _.template(...),
      selector: '#someOtherEl',
      strategy: 'prepend'
    }
  ]
})
```

After some back and forth I find out that you have to create separate extensions for ItemView/CompositeView, because the way how `render` method is implemented.
Also I've came across https://github.com/marionettejs/backbone.marionette/pull/2253 and https://github.com/marionettejs/backbone.marionette/issues/2268. Having `RegionManager` instance in every `ItemView` looks like an overhead for me, despite that fact that I do really like having regions for view where I need it.

***Suggestion:***
I was thinking how about moving regions, data serialization and rethinking the whole concept of specialized views into having generic views with more specific traits that'll support certain functionality:

```javascript
var View =  Marionette.View.extend({
  traits: [
    Marionette.ViewTrait.Serialize,
    Marionette.ViewTrati.Region
  ]
})
```
That would effectively allow compose views with only required functionality and build traits of your own without need to redefine every single type of view.

I guess having `super` and `mixin` from https://github.com/marionettejs/backbone.marionette/issues/2426 or any other proper `super` implementation may help it a lot.

**Comment by ahumphreys87** [comment]
i do like This idea @MasterLambaster.

I'm not convinced we would get community buy in for a change this big though. This is like a complete rewrite

**Comment by ahumphreys87** [comment]
This issue doesnt look like it has gained backing so closing for now
