### ISSUE TITLE
Official support for other templating engines

### ISSUE THREAD

**Issue by paulovieira** [marionettejs/backbone.marionette#2474]
One of the selling points for Backbone (and Marionette) is the independence relatively to the templating engine. Marionette comes with support for [underscore templates](http://underscorejs.org/#template) out of the box, but it's not difficult to use other engines. 

For instance, some time ago I switched to [Nunjucks](https://mozilla.github.io/nunjucks/) (for pythonians around here, it's a port of [Jinja2](http://jinja.pocoo.org/docs/dev/) for javascript). I've been using marionette with nunjucks without any problem. In fact, I cleaned up my Marionette code a lot because nunjucks can automatically handle the final visual details (like joining an array of strings).

All this to say: even though it's not difficult to adapt [`Marionette.Renderer`](http://marionettejs.com/docs/v2.4.1/marionette.renderer.html) to work with other engines, the users still needs to know some internals of both Mn and the engine to make it work. I think we would add great value if that was something readily available and officially supported. I'm not saying Mn should handle other engines out-of-the-box, but we should have official "adapters" (not sure if this is a good term) for other engines. Users should only have to include another module (besides the engine itself) to be able to use another engine immediately.

Here is an example of how I see it working from the perspective of the user:

A simple post model:

``` javascript
var postM = new Backbone.Model({
    title: "an awesome title!",
    body: "lorem ipsum",
    tags: ["politics", "health"]
});
```

The template (nunjucks syntax) could be something like:

``` html
<script type="text/template" id="blog-post">

    <h1>{{ title | upper }}</h1> 

    {{ body }}

    <span>tags: {{ tags | join(',')}}</span>

</script>
```

The view:

``` javascript
var PostIV = Mn.ItemView.extend({
    // here I am using the new long form for the template property
    template: {
        engine: "nunjucks"
        selector: "#blog-post"
    }
});

var postIV = new PostIV({
    model: postM
});

postIV.render();
var html = postIV.$el.html()
```

The `html` variable should be:

``` html
<h1>AN AWESOME TITLE</h1> 
lorem ipsum
<span>tags: politics, health</span>
```

Under the hood, `Marionette.Renderer` would use the nunjucks adapter instead of the (default) underscore adapter. If the user prefers to use underscore templates, as he/she have always been doing, the short form for the template property could be used instead:

``` javascript
var MyView = Mn.ItemView.extend({
    // the short form is the same as we currently use
    template: "#my-selector"
});
```

The template property in the above definition would be equivalent to this:

``` javascript
var MyView = Mn.ItemView.extend({
    template: {
        engine: "underscore"
        selector: "#my-selector"
    }
});
```

We would still have to take into account pre-compiled templates and template helpers. I'd like to have some feedback about this new feature before spending more time writing the issue.

I'm happy to work on a PR to bring this to v3.

**Comment by jasonLaster** [comment]
I like this idea a lot - maybe we could create a small repo w/ the custom renderer the package and a unit test...

**Comment by paulovieira** [comment]
Yeah, my idea was to have small repos under the marionettejs organization for each supported template engine. Users could pick and choose and be ready to code.

**Comment by jasonLaster** [comment]
In my experience it's better to build a shopping mall rather than a hundred boutiques. It's easier for users to come to the marionette-template-engines repo find the code that they need and copy and paste it. realistically, that's the last time they'd need the repo.

**Comment by ianmstew** [comment]
I love the idea of lowering the barrier for users to leverage other templating engines.  I agree with @jasonLaster that a single repo with multiple example renderers and a unit test would be great.  @paulovieira I know that's not exactly what you had in mind, but what do you think about creating a repository with 1-2 demo template engines featured?  Then we could gain consensus, transfer it to the marionettejs organization, and add add to the docs in time for `3.0`.

**Comment by StevenLangbroek** [comment]
Maybe we could expose a `setRenderer` method on `Mn`, and have the "engine" authors take care of pulling in dependencies etc. So i.e. implementing a `Handlebars` renderer would look like this:

```js
// main.js
import Mn from 'marionette';
import MnHandlebars from 'marionette-handlebars';

Mn.setRenderer(MnHandlebars);

// someView.js
import { ItemView } from 'marionette';
import template from './someTemplate.hbs';

export default ItemView.extend({
    template,
    tagName: 'li'
});
```

**Comment by jasonLaster** [comment]
that'd be nice @StevenLangbroek

**Comment by Tvrqvoise** [comment]
I've yet to find a templating language which doesn't already have an open source MN adaptor for it maintained by some random dude working for some random company.  And that's okay -- that dude probably knows more about that templating language than we would.  Maybe a ```renderers.md``` or a page on the docs site linking to the various repos, perhaps with some information about overriding the default Marionette renderer?
