### ISSUE TITLE
Merge layoutView docs into ItemView

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2477]
https://github.com/marionettejs/backbone.marionette/issues/2432#issuecomment-91217622

They were dropped in a merge.

**Comment by paulfalgout** [comment]
Also need to check `SpecRunner.html`

**Comment by paulfalgout** [comment]
Update: I suspect `SpecRunner.html` is updated in this missing PR https://github.com/marionettejs/backbone.marionette/commit/c63b5847e213b17be2cb7a5387b02c16ff6bd058

**Comment by paulfalgout** [comment]
closing in favor of #2920
