### ISSUE TITLE
Update copy to ensure people do not think that Regions are deprecated

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2490]
Something somewhere is giving people the idea that Regions as a class are deprecated for v3. This simply is not the case!

Only Regions _**on the application**_ are deprecated. Someone should dig through stuff to make sure that there's nothing potentially misleading out there.

It might even good to update the Application documentation to explicitly say that Regions are not deprecated, but App regions are.

**Comment by paulfalgout** [comment]
This looks to be moderately ok now.. and it will be very clear, very shortly.
