### ISSUE TITLE
Deprecate CollectionView Empty View

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2495]
I'd like to suggest that we deprecate the empty view functionality in collection and composite view.

---
The rationale is that the logic for when to show an "empty" view would better be handled by a containing view that either shows a list or an empty view. Further more, when, where and how to show empty views is up to interpretation.

Also, to be honest, as a maintainer, CollectionView is one of the most complicated classes in the library and I believe it would be significantly easier to maintain w/o supporting empty views

---

The road forward, I would like to land in a place that is better for everyone. We should create a small library or even a test case that demonstrates how we envision creating a layout view with a list and empty view region.

---

So, this sounds great, but isn't it really hard / risky to remove the empty view code... Good question, I would think so, but I just did it i think. 

https://gist.github.com/jasonLaster/52a36178a996ad03e6a5

---

Next steps, if we agree on this path forward somebody should grab the patch and make it happen

**Comment by jasonLaster** [comment]
We'd probaby want to create a small example repo or test for the shim

```js
View.extend({
  collectionEvents: { change: 'onChange'},
  onChange: function() {
    if(this.wasSome && this.collection.length == 0) {this.triggerMethod('empty')}
    if (this.wasEmpty && this.collection.length > 0) {this.triggerMethod('some')}
  },

  onEmpty: function() {
    this.showView('body', new EmptyBodyView());
  },

  onSome: function() {
    this.show('body', new ListView())
})
```

or add some hooks so it's easy to shim

```js
var MyCV = Marionette.CollectionView.extend({
  onEmpty: function () {
    this.show(new MyEmptyView());
    // or
    this.showEmptyView(new EmptyView());
  }
});
```

**Comment by ianmstew** [comment]
Thanks for starting this discussion, @jasonLaster!  I agree that it's actually not intuitive for a CollectionView to show an edge case alternative to a "child view".  For example, a pure array doesn't have an "empty value".

On a purely logical level, swapping out the entire CollectionView for an alternative view at the parent Region makes the most sense, at the cost of upgrade burden.  On the flip side, providing hooks within the CollectionView makes the most sense from an "ease of upgrading" perspective, at the cost of logical purity and some extra core code (although not nearly as much as supporting the EmptyView we have today).

If we choose to go with the first, I recommend including an "empty view" example in our first class CollectionView documentation, or at the least a link to an example.  I.e., give some serious hand holding to educate on "polymorphic" region usage.

**Comment by jasonLaster** [comment]
proposal: child view fires an empty and a some event, which the parent listens to and reacts

```js
View.extend({
  childEvents: {
    'empty': 'onCollectionEmpty',
    'some': 'onCollectionSome'
  },
  onCollectionEmpty: function() {
    this.showView('body', new EmptyBodyView());
  },

  onCollectionSome: function() {
    this.show('body', new ListView())
})
```

**Comment by JSteunou** [comment]
Could it be a behavior?

Marionette could start to pack in some behaviors and document and to use EmptyView behavior with collection / composite view.

**Comment by jasonLaster** [comment]
yea, id be down with that

**Comment by ianmstew** [comment]
@jasonLaster, I just thought of a potential complexity with the proposal that I want to iron out.

When it comes to the [CollectionView filter](https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.collectionview.md#collectionviews-filter), the CollectionView defines the filter and applies it after changes to the collection.  If we are replacing the CollectionView with an EmptyView using Region#show's default destroy behavior, then we lose the special filter listener when the CollectionView destructs.

For an EmptyView Behavior to work, it would have to cause the EmptyView swap out to be non-destructive to the CollectionView to keep collection listeners alive, and then swap back in the same CollectionView instance onCollectionSome.  The caveat here is that if the EmptyView is replaced _for any other reason_, then both EmptyView _and_ the CollectionView will then need to be destroyed together.

@cmaher, you're the filter guy, thoughts?

**Comment by ahumphreys87** [comment]
gonna close this and cover this as part of #2560
