### ISSUE TITLE
Cherry pick attachBuffer and _createBuffer onto 2.4.2

### ISSUE THREAD

**Issue by ahumphreys87** [marionettejs/backbone.marionette#2496]
#2494

**Comment by sentientnebula** [comment]
Please explain how getTemplate provides sufficient functionality to obviate any need to customize the buffer creation process in situations where there are more than just a few fixed options.

<a href="https://github.com/marionettejs/backbone.marionette/issues/2388">#2394</a>

**Comment by sentientnebula** [comment]
See <a href="https://github.com/marionettejs/backbone.marionette/issues/2388">#2394</a> for proposal to rename _createBuffer to createBuffer.  That thread is closed, but issue is not resolved, and nobody reads closed threads.

**Comment by ahumphreys87** [comment]
@sentientnebula I don't have an objection to this. Would you be interested in creating a PR for it? Its not something we will change in v2.x it will be a v3 change if the rest of the team approve (i cant see why not though).

Overriding a "private" method isn't ideal, I understand that - but it should be safe to assume this wont change in 2.x as once 2.4.2 is out we will be going to v3.0 so your app will be safe :smile:

**Comment by ahumphreys87** [comment]
Manually cherry-picked

**Comment by Ky6uk** [comment]
https://github.com/marionettejs/backbone.marionette/commit/eb51aeb01b3dc3121042e490d7fce1c43f78e47f
