### ISSUE TITLE
triggerMethod does not respect stopListening or destroy

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2501]
As discussed briefly in #2464 

There was mention of replacing `trigger` with `triggerMethod`, but `trigger` has additional utility that `triggerMethod` does not.

 `triggerMethod` is not async safe, where-as `trigger` is.  

This will trigger safely.  onSomeEvent will never be called.
```js
$.when(promise).done(_.bind(this.trigger, this, 'some:event'));
this.on('some:event', this.onSomeEvent);
this.destroy();  // or this.stopListening();
promise.resolve();
```
This will still call the method onSomeEvent:
```js
$.when(promise).done(_.bind(this.triggerMethod, this, 'some:event'));
this.destroy();  // or this.stopListening();
promise.resolve();
```

The issue is that `triggerMethod` has no concept similar to `stopListening`. When `triggerMethod` is called it simply looks for a function and calls it if it exists.

Perhaps it is possible that `triggerMethod` could respect `isDestroyed` and this flag could be added to `Object`?

**Comment by jridgewell** [comment]
> The issue is that triggerMethod has no concept similar to stopListening. When triggerMethod is called it simply looks for a function and calls it if it exists.

I think this is looking at it wrong. `#triggerMethod` works because you "listened" to an event by defining an appropriately named method. The equivalent to `#off` would be to delete the method.

```javascript
$.when(promise).done(_.bind(this.triggerMethod, this, 'some:event'));
this.on('destroy', function() { this.onSomeEvent = null; });
this.destroy();  // or this.stopListening();
promise.resolve();
```

My first thought would be to delete any on methods in `#destroy`

```javascript
class Class {
    constructor() {
        this.onMethods = _.filter(_.functions(this), (name) => /^on[A-Z]/.test(name));
        // ...
    }

    destroy() {
        _.each(this.onMethods, (name) => this[name] = null);
    }
}
```

But that seems as nasty as overriding `#triggerMethod`. A better option might be to check if this `#onMethod` is still "listening" in `#triggerMethod`.

```javascript
class Class {
    constructor() {
        this.onMethods = _.transform(_.functions(this), (memo, name) => {
                if (/^on[A-Z]/.test(name)) memo[name] = true;
        }, {});
        // ...
    }

    destroy() {
        this.onMethods = {};
    }

    triggerMethod(name) {
        // ...
        if (this.onMethod[name]) {
            // triggerMethod things...
        }
        Backbone.Events.trigger(name, ...);
    }

    offMethod(name) {
        this.onMethods[name] = false;
    }
}
```

But that'll bulk up the API quite a bit, not to mention still has to deal with enumerability of methods in ES6. :confused:

**Comment by paulfalgout** [comment]
I'm pretty sure I'm on the same page here.  

Unfortunately, I don't think there is a good clean way to solve this problem.  

But what I think that ends up meaning is that we should fully support `trigger` and `triggerMethod` as different event methods, and in places where we proxy events, we should support both.

**Comment by jasonLaster** [comment]
hmm, so it seems like `stopListening` and `off` should keep a record of the events that we've stopped listening for. Then `triggerMethod` could simply check to see if se should invoke the on method.

I also think that replacing `triggerMethod` with a no-op is a little extreme :)

I think this could relate to this ticket
https://github.com/marionettejs/backbone.marionette/issues/2508

**Comment by paulfalgout** [comment]
A totally other solution that might solve my use-case would be some method of preventing the method from being called.  Something like
this.triggerMethod({

**Comment by jasonLaster** [comment]
not sure if i follow?

**Comment by paulfalgout** [comment]
I think this can be solved with documentation of the "caveat"

**Comment by JSteunou** [comment]
Agreed, for my PoV it fits in the same case than unbinding or destroying some jquery plugin manually on view destroy. It's the user's responsibility to clean up its views outside the scope of what Mn does automatically.

**Comment by paulfalgout** [comment]
So I think my original assumptions were also somewhat incorrect.

```javascript
var Obj1 = Marionette.Object.extend({
  initialize: function(){
    this.on('some:event', this.onSomeEvent);
    this.destroy();  //destroy does not call `this.off`
    this.trigger('some:event');
  },
  onSomeEvent: function() {
    console.log('This will be called');
  }
});
```

I think the use-case of discussing `off` is fairly minimal
