### ISSUE TITLE
Marionette Controllers deprecated

### ISSUE THREAD

**Issue by PedroVinicius** [marionettejs/backbone.marionette#2507]
In the documentation:

"Warning: deprecated. The Controller object is deprecated. Instead of using the Controller
class with the AppRouter, you should specify your callbacks on a plain Javascript object."

I'm confused about this... Someone can show me a example of how use a javascript plain object instead the Marionette Controller with App Router?

**Comment by jasonLaster** [comment]
@PedroVinicius sorry for the confusion, hopefully we'll have an example of a Mn.Controller killer soon in the form of a better Router/Route. If not, Mn.Object is pretty close to what you have now

**Comment by PedroVinicius** [comment]
Okay! Thank you very much! :D

**Comment by paulfalgout** [comment]
```js
var someController = {
  someMethod: function(){ /*...*/ }
};

Marionette.AppRouter.extend({
  controller: someController
});
```

This is where the naming of `Marionette.Controller` didn't work out.  AppRouter never actually needed a `Marionette.Controller` to work.
