### ISSUE TITLE
We should extend Backbone.Events

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2508]
Marionette has added new application level functionality to Backbone.Events in the form of triggerMethod. We've made it possible to invoke on methods. We've enabled event bubbling up the view hierarchy for layouts and collections... These features have been added to triggerMethod and have lead to inconsistencies with trigger. This has created some considerable confusion. These features have also lead to regressions such as on methods been called post `stopListening` calls.

As we prepare for a major release in Marionette 3, it'd be great to use the opportunity to remove the distinction. What I'm proposing, might seem radical at first, but I'd like to extend Backbone.Events to add triggerMethod functionality to trigger and then remove triggerMethod.

How would this work? If we go ahead with Backbone.Metal, this would mean defining Backbone.Events as a Mixin and Marionette.Events as a subclass of Backbone.Events. Then mxing in Marionette.Events into Mn.Object, Backbone.View, Backbone.Model...

If we do not go aheas with Metal, we could do something like this, but it'd be a little uglier...

What do you guys think?

**Comment by paulfalgout** [comment]
I am :+1: for extending `Backbone.Events`  I'm not fully sure about how `triggerMethod` should "stop listening" yet, but without extending `Backbone.Events` it will be very complex to solve reasonably.

I also think this will be a useful extend for other things down the line

**Comment by paulfalgout** [comment]
Note: The proposed metal implementation is already introducing a `Marionette.Events`, but with no particular additional utility

**Comment by ianmstew** [comment]
:+1: The fact that we have to manage two separate implementations when we expect to have both function, for all intents and purposes, identically, is a huge argument for this.  For example #2464 and discussion on #2404 would both be simplified by consolidating our triggering impls.

**Comment by taburetkin** [comment]
please remove obsolete bind and unbind )
