### ISSUE TITLE
I have questions regarding bindEntityEvents, unbinding event listeners, and memory leaks!

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2512]
Hi!

So, I just bumped into a pretty weird memory leak in my program. I finally tracked it down, but I was a bit shocked to see why it happened.

A while ago, I used to write logic for initializing extra event handlers against a Backbone.Model in a view like this:

    var StreamusView = Marionette.ItemView.extend({
       initialize: function(options) {
           this.listenTo(options.fooModel, 'change:baz', this._onFooModelChangeBaz);
           this.listenTo(options.fooModel, 'change:bar', this._onFooModelChangeBar);
       },

       _onFooModelChangeBaz: _.noop,
       _onFooModelChangeBar: _.noop
    });

This worked well, but was a bit verbose! 

Along comes @jmeas who logged an issue against my code: https://github.com/MeoMix/StreamusChromeExtension/issues/303

His suggestion led to me using bindEntityEvents so that my stuff could look more sleek. Now, I rock code which looks like:

    var StreamusView = Marionette.ItemView.extend({
       fooEvents: {
           'change:baz': '_onFooModelChangeBaz',
           'change:bar': '_onFooModelChangeBar'
       },

        initialize: function(options) {
           this.bindEntityEvents(options.fooModel, this.fooEvents);
       },

       _onFooModelChangeBaz: _.noop,
       _onFooModelChangeBar: _.noop
    });

I honestly prefer this a lot more and was thankful for the suggestion.

Unfortunately... there's a deep, dark secret with this code! Normally, when destroying a view, a few things happen:

* stopListening gets called to clean up all this.listenTo calls
* undelegateEvents gets called. The Backbone implementation has been overridden in Marionette such that unbindEntityEvents gets called against the model, collection, and child behaviors.

But... there's a big difference between these two actions. stopListening is greedy and clears all event handlers, but unbindEntityEvents is not greedy and only targets very specific objects.

So, all of my calls to bindEntityEvents remain bound after the view has been destroyed unless I manually call unbindEntityEvents against everything.

I think that this is counter-intuitive because I do not need to do that with my listenTo calls. Shouldn't unbindEntityEvents be made greedy and fully unbind when the view is being destroyed?

Thanks!

**Comment by jmeas** [comment]
oh dang, I forgot about the caveat that you would need to manually unbind.

> Shouldn't unbindEntityEvents be made greedy and fully unbind when the view is being destroyed?

yes

:P

**Comment by MeoMix** [comment]
Heh, well, all I can say is I hit a really weird bug in my Chrome extension which was hinting at a memory leak and I was able to fix it by either switching to listenTo instead of bindEntityEvents, or by calling unbindEntityEvents manually after calling stopListening. :)

**Comment by paulfalgout** [comment]
```js
var StreamusView = Marionette.ItemView.extend({
   fooEvents: {
       'change:baz': '_onFooModelChangeBaz',
       'change:bar': '_onFooModelChangeBar'
   },

    initialize: function(options) {
       this.bindEntityEvents(options.fooModel, this.fooEvents);
   },

   _onFooModelChangeBaz: function(){ console.log('this will only log once'); },
   _onFooModelChangeBar: function(){}
});
var view = new StreamusView({ fooModel: new Backbone.Model() });
view.options.fooModel.set('baz', 1);
view.destroy();
view.options.fooModel.set('baz', 2);
```

@MeoMix Could use some additional info.. in the simple case, it does seem to get cleaned up correctly..  drop the above into console..

**Comment by ahumphreys87** [comment]
@MeoMix maybe a jsfiddle will help here, have you tried with 2.4.1 as well?

**Comment by MeoMix** [comment]
Upon further debugging I've learned that this issue is isolated to my use cases in Chrome extension land and isn't a Marionette bug. 

Although, still potentially worth discussing the discrepancies between listenTo and bindEntityEvents since jmeas does seem to agree that the code looks a bit weird.

Regardless, no bug here! Carry on :D

**Comment by paulfalgout** [comment]
ref 
https://github.com/marionettejs/backbone.marionette/issues/2292
