### ISSUE TITLE
Object should support a default radio channel

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2515]
Radio Events currently handle a hash containing `'channel eventName' : 'handler'`
```js
radioCommands: {
  'app doFoo': 'executeFoo',
},

radioRequests: {
  'resources bar': 'getBar',
},
```

As radio commands and requests can only be handled once per channel, I find most of my Objects are only utilizing a single channel for commands and requests... 

```js
radioRequests: {
  'resources foo': 'getFoo',
  'resources bar': 'getBar',
  'resources baz': 'getBaz',
  'other baz': 'getOtherBaz'
},
```

Therefore I think a `defaultRadioChannel` would be useful:

```js
defaultRadioChannel: 'resources',
radioRequests: {
  'foo': 'getFoo',
  'bar': 'getBar',
  'baz': 'getBaz',
  'other baz': 'getOtherBaz'
},
```

**Comment by jasonLaster** [comment]
Hmm, I could see going either way on this one. Ultimately, I feel like keeping the channel in the key is useful documentation and consistent. 

Two usecases:
1. new developer sees `radioRequests: { 'foo': 'getFoo'}` and is not sure what's happening.
2. seasoned Mn developer sees  `radioRequests: { 'foo': 'getFoo', 'pizza foo': 'getFoo'}` and thinks what's that key for obj channel... and has to look for it

One additional consideration:
For requests and commands, it makes sense that shop model handles requests/commands on that channel. For events, it's less clear that the shop model cares about events throughout the app...

**Comment by paulfalgout** [comment]
One particular use case where this feature would shine is when your channel name depends on the data.  for instance:
```js
defaultRadioChannel: function(){
  return 'user' + this.model.id;
},
radioCommands: {
  'doFoo': 'executeFoo'
},
executeFoo: function(){
  // do stuff you wouldn't do on the model directly
}
```

you can of course do this without but you'd have to:
```js
radioCommands: function(){
  var commands= {};
  commands[ 'user' + this.model.id + ' doFoo'] = 'executeFoo';
  return commands;
}
```

**Comment by ianmstew** [comment]
I rather think that the most common pattern if for a single object to listen on a single channel, and that an object listening on multiple channels is the exception.  In my own code, I prefer doing:

```js
channelName: // channel name
channel: // channel instance
```

This is how the Application object initializes the app channel in `2.4.x`, and would be cool if this method applied to all objects.  When I need to listen to multiple channels, I would rather register to additional channels manually.

**Comment by paulfalgout** [comment]
I actually much prefer what @ianmstew is suggesting.  Plus the implementation is drop-dead simple:
```js
var RadioAPI = Marionette.Object.extend({
  initialize: function(){
    var channelName = _.result(this, 'channelName');
    if(!channelName){
      return;
    }

    this.channel = Backbone.Radio.channel(channelName);

    var radioEvents = this.normalizeMethods(_.result(this, 'radioEvents'));
    this.listenTo(this.channel, radioEvents);

    var radioRequests = this.normalizeMethods(_.result(this, 'radioRequests'));
    this.channel.reply(radioRequests, this);
  },
  normalizeMethods: Marionette.normalizeMethods,
  onDestroy: function(){
    // this.stopListening() already in destroy
    this.channel.stopReplying(null, null, this);
  }
});
```

I think that might be it entirely.  Compare with the complexity of supporting channelNames in the hash:  https://github.com/marionettejs/backbone.marionette/blob/next/src/radio-helpers.js

This could possibly be improved with `replyFor` if/when Radio implements that.

**Comment by paulfalgout** [comment]
FWIW when Metal lands this could easily just be a Mixin and would not need to be baked into everything..  Particularly if https://github.com/marionettejs/backbone-metal/issues/20

**Comment by jasonLaster** [comment]
@paulfalgout that code *is* pretty nice. 

At Etsy, we often have props like `appRequests` or `listingRequests` where we do <channel><radioMessage>. and then bind them with a helper. I guess what I'm saying is that maybe we could have both. Out of the box you get `radioRequests`, but you could easily add `appRequests` and bind that with a method. We could magically do that, but lets not :)

Maybe, we can move some of this API discussion to documentation tickets and see if we can write some killer Mn Radio docs that highlight the use cases. That way, we'll have some examples to base this off of.

**Comment by jasonLaster** [comment]
Discussed offline. We'll add the simple one channel proxy method as a util. We'll then probably make it a default, but continue to support the multiChannel proxy method as well.

@paulfalgout mind not tackling this? I'd like to save it as a "beginners" ticket for the July 9th meetup

**Comment by paulfalgout** [comment]
:+1:  Oh yeah perfect

**Comment by jasonLaster** [comment]
This would be a fine API to me.
```js
channelName: 'resources',
radioRequests: {
  'foo': 'getFoo',
  'bar': 'getBar',
  'baz': 'getBaz',
},
```

To be clear, we'll switch support from two word keys (channel name and request) to just request

**Comment by ianmstew** [comment]
:+1: That's my ideal API.
