### ISSUE TITLE
Bug when `regions` is a function in `addRegions`.

### ISSUE THREAD

**Issue by codespawner** [marionettejs/backbone.marionette#2516]
Hey guys, got a small question on `addRegions` on `Marionette.View`. I believe it is intended to be able to give it a function which evals to an object literal containing the regions definitions. (The `RegionManager` indeed uses `Marionette._getValue`.) What bothers me is this piece of code:
```
 // Add multiple regions as a {name: definition, name2: def2} object literal
 addRegions: function(regions) {
    this.regions = _.extend({}, this.regions, regions);
    return this._buildRegions(regions);
  }
```
First problem is that if the given argument is function, it will just mix it in with the other region definitions. And the second one is that the comment isn't up to date. 

Am I missing something?

**Comment by ahumphreys87** [comment]
Fixed with #2513
