### ISSUE TITLE
Outdated test in `view.dynamic-regions.spec`

### ISSUE THREAD

**Issue by codespawner** [marionettejs/backbone.marionette#2519]
I don't understand the use of this test:

https://github.com/marionettejs/backbone.marionette/blob/caa776ef4d0f52e004473349d0b41bb639eab7e3/test/unit/view.dynamic-regions.spec.js#L153-L155

The `bar` region never existed and the test only succeeds only because both `this.layoutView.bar` and `this.barRegion` are `undefined`...

**Comment by jasonLaster** [comment]
kill the test

**Comment by codespawner** [comment]
Actually I think it should be moved of few lines below in "when adding a region to a layoutView that already has regions defined, and re-rendering the layoutView".

**Comment by ahumphreys87** [comment]
fixed with #2520
