### ISSUE TITLE
Users keep getting confused by the fact that 'childEvents' relies on 'triggers' and not 'events'

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2531]
All,

Simply reporting this because I have heard it come up twice in 24 hours in the Gitter channel.

When a user sets up a childEvents object like so:

    childEvents: {
        'item:clicked': _.noop
    }

they initially believe that the correct way to run this code from a child is by defining:

    events: {
       'click': 'item:clicked' 
    }

rather than: 

    triggers: {
        'click': 'item:clicked'
    }

I understand both arguments. Events are being triggered at the lower level and then the event is handled at an upper level... but, in my experience, most newcomers do not understand the point of 'triggers' after becoming familiar with 'events' and generally don't think to use them unless forced. So, when something says "childEvents" rather than "childTriggers", it leads them to believe they should go through 'events'.

I'm not sure if this warrants a change at all, but thought it was worth mentioning.

**Comment by newtonianb** [comment]
:+1: that's totally totally confusing, in some areas we clearly distinguish between an event and a trigger and then here we totally mix them up

**Comment by ianmstew** [comment]
@MeoMix, @newtonianb Thanks for having an ear to the ground!  It sounds like a documentation improvement is warranted here.  This would go nicely with #2464 and #2404 for 3.0.

**Comment by paulfalgout** [comment]
It seems like this could be solved by documenting an example of what you would need to do to accomplish the same functionality without using `childEvents` 

The naming is actually fairly consistent with backbone and follows the pattern of `modelEvents` and `collectionEvents`.  Backbone has an `events` hash on a view that are jquery dom related events with callbacks, where as backbone trigger triggers a backbone event.  Backbone events have nothing to do with the events hash on a backbone.view so the naming confusion is there in Backbone as well.  

Then of course Marionette's triggers is a combination of both such that `triggers` takes a hash of DOM events and triggers Backbone events.

**Comment by ianmstew** [comment]
@MeoMix, care to PR some docs into `patch` for the next release?

**Comment by samccone** [comment]
:+1: saw some people get confused by this as well

**Comment by MeoMix** [comment]
I am 100% swamped with work for the next couple of weeks. Moving houses + dealing with Google. More than happy to when I find a spare moment, but right now I'm drowning on my own!

**Comment by ianmstew** [comment]
Np!  Good luck!

**Comment by MeoMix** [comment]
I'm probably going to pull an all nighter this evening to get a lot of different tasks done. I'll try to pick this one up.

**Comment by paulfalgout** [comment]
@MeoMix can't assign it outside of the org unfortunately.  You still want to pick this up?

**Comment by jasonLaster** [comment]
haha @MeoMix would love to see you tackle this
