### ISSUE TITLE
Metal - Replace Object with Class

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2535]

**Comment by paulfalgout** [comment]
Any thoughts on just have 
``` Mn.Object = Mn.Class ``` 
for v3 and then removing this for v4?

We have quite a bit of things in flux for v3, and it might be easier for an upgrade path to hold on to the deprecations a bit longer.

**Comment by jasonLaster** [comment]
I'd be cool with that

**Comment by paulfalgout** [comment]
I'm iffy on this now.  If everything in `Marionette.Class` is added to everything else, we may still want a base object that has additional functionality that is not added to everything across the board.  Like the Radio proxy and additional `destroy` functionality.

**Comment by paulfalgout** [comment]
Closing.  Reopen when reinvestigating metal.
