### ISSUE TITLE
Allow behaviors to be added/removed after instantiation

### ISSUE THREAD

**Issue by adorsk** [marionettejs/backbone.marionette#2538]
It would be handy to add/remove behaviors dynamically to views, after instantiation.

For example, 

```
var view = new MyView({...});
view.addBehavior('fooBehavior', {fooBehaviorOpt1: 'blah'});
view.removeBehavior('fooBehavior');
```

However, implementing this would require some clarification and refactoring of the behaviors system.

The clarification would involve defining how behaviors should cascade. See this comment: https://github.com/marionettejs/backbone.marionette/issues/2386#issuecomment-97202548

Also, for deletion cascades, if a behavior is removed, should its nested behaviors also be removed?

**Comment by jasonLaster** [comment]
Interesting idea, I'm not opposed but fear it'd add some complexity. Let's see how many ppl want this.

**Comment by paulfalgout** [comment]
I'm not for or against this at the moment. but I'm having a hard time coming up with a scenario in which I could use this effectively.  Can you provide some practical example?

**Comment by adorsk** [comment]
Here are a few examples I had mind:

## Example 1: Dynamically making something draggable .

Say we are making a game with blocks that we can drag. Some of the blocks can be dragged right away, but others start out 'locked'. When we 'unlock' blocks, we want to add a 'draggable' behavior to them, but without blowing away the original view for the block.

Dynamic behaviors would allow us to do this. Perhaps something like this:
````
block.on('unlock', function() {
  block.addBehavior('draggable', {});
});
````

## Example 2: Dynamically creating components through a domain-specific language
Let's say we are creating components through a custom DSL. Our DSL has very low-level commands, like 'createWidget', 'addRegion', etc. 

We would like to have an 'addBehavior' command, so that we don't have to put behavior config in the 'createWidget' commands. This would make the DSL simpler to use.

For example, something like...
````
var commands = [
{cmd: 'createWidget', id: 'widget1', type: 'MyView', widgetOpts: {...}},
{cmd: 'addBehavior', target: 'widget1', behavior: 'draggable', behaviorOpts: {}}
]
````

Do these examples help?

**Comment by cmaher** [comment]
I really want this (at least dynamically adding behaviors).  It would also provide a way to create behaviors at initialize, as opposed to now where they get created before

**Comment by ianmstew** [comment]
Hey all, any further thoughts on this?

**Comment by paulfalgout** [comment]
See https://github.com/marionettejs/backbone.marionette/issues/2386#issuecomment-290418709
