### ISSUE TITLE
Use Marionette.Module shim for v3 remove for v4

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2542]
Currently though `Module` is deprecated there hasn't been a clear upgrade path for an object including the `start/stop` lifecycle functionality module currently provides.  
We should include the shim in v3 to make upgrading easier and provide a suitable replacement in v3.x and then remove the shim for v4.
Trying to replace the lifecycle functionality for v3 will certainly extend the release date and complicate the upgrade path for most people to `v3`.

**Comment by samccone** [comment]
https://github.com/marionettejs/marionette.module

**Comment by paulfalgout** [comment]
Reopen if necessary, but since `Application` is pretty easily reusable now, an extremely simple recipe can make a start/stop object.
