### ISSUE TITLE
region manager is calling onDestroy on every view

### ISSUE THREAD

**Issue by victorwpbastos** [marionettejs/backbone.marionette#2544]
When I call `regionManager.removeRegion(region)` the regionManager is calling onDestroy on every region. Why?

**Comment by cmaher** [comment]
Would you be able to provide some sample code (ideally using jsfiddle or comparable) that demonstrates the problem?  Without more information, all we have to work with is https://github.com/marionettejs/backbone.marionette/blob/master/src/region-manager.js#L67-L72, which looks like it makes sense to me.

**Comment by ahumphreys87** [comment]
Closing. @victorwpbastos if this is still an issue for you please feel free to reopen the issue and provide a small example illustrating this bug.
