### ISSUE TITLE
Regionify CollectionView

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2545]
Currently, the CollectionView behaves much like a region, but only after being "shown" by a Region.  This logical dependency between CollectionView and Region leads to difficult to maintain code.  The idea here is to make the behavior of CollectionView more consistent; specifically, make the CollectionView more like a first class "list region" in its own right.

**Comment by jasonLaster** [comment]
https://github.com/joefitter/backbone.enumerable/blob/master/src/backbone.enumerable.js

**Comment by ahumphreys87** [comment]
gonna close and cover as part of #2560
