### ISSUE TITLE
Be more consistent about the library's name

### ISSUE THREAD

**Issue by jamesplease** [marionettejs/backbone.marionette#2551]
Backbone.Marionette, Marionette.js, or Marionette? Which one? We should settle upon one of these variations and use it consistently. Throughout the README we use all of them!

I think we've been gravitating toward either `Marionette.js` or `Marionette`, so I would suggest going with one of those. `backbone.marionette` should be deprecated in favor of the simpler name. If I remember right, @samccone has access to the `marionette` npm module now?

I would recommend the following process to migrate the npm module:
1. publish the library to `marionette` immediately, and recommend people start using that in our copy (website, readme, etc.)
2. When 3.0 rolls around, deprecate the `backbone.marionette` module

**Comment by samccone** [comment]
Yep I have Marionette 

Publishing to multiple names is a bit of a hack currently... but I could write a script to back publish everything I think...

**Comment by jmeas** [comment]
Oh, you're right, that is a bit of a hack. Hm, it might be best to just wait for 3.0 and, in the meantime, publish a blog post now to prep people.

**Comment by jcrben** [comment]
Marionette.js is better than Marionette as there's too much stuff about Firefox's Selenium driver out there https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette

**Comment by paulfalgout** [comment]
@samccone can I get access to the `marionette` npm module.  This is something again under consideration as v4 approaches

**Comment by paulfalgout** [comment]
@marionettejs/marionette-core I originally added this to v4, but we can readdress later.  I even think there's a possible case for v5 to lose dependency on Backbone which would be an even better time to make the switch

**Comment by samccone** [comment]
you are all set!

**Comment by jmeas** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by JSteunou** [comment]
Cannot for v5 then :)

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/marionette
