### ISSUE TITLE
Marionette.Behaviors: _.tail(arr, n) should be _.drop(arr, n)

### ISSUE THREAD

**Issue by michaelaberman** [marionettejs/backbone.marionette#2557]
In underscore, these functions are identical, but in some alternative implementations (e.g. [lodash](https://lodash.com/docs)), `tail` specifically means n=1, while `drop` allows specifying the drop count.

This means that if I want to swap in a more efficient implementation where my dependencies require underscore, all of the `_.tail(arguments, 2)` calls in marionette.behaviors.js fail to drop both prefix arguments, resulting in bugs down the line.

Switching to `drop` would be a noop for underscore, but would improve the portability of the code.

**Comment by megawac** [comment]
Feel free to open pull requests to change it if you spot occurances of us using `tail(arr, n)` or `rest(arr, n)` but we've been actively fixing this for compatibility with lodash in the past couple months. Also lodash is tested by travis

See https://github.com/marionettejs/backbone.marionette/pull/2246 https://github.com/marionettejs/backbone.marionette/commit/8f8c59260e1c0dd12eb400f15296d1f7c31a90b4

**Comment by michaelaberman** [comment]
You're right. I saw this in an old codebase, and I thought I saw the same code in the HEAD, but now I can't find it, so I believe it's resolved. Thanks!
