### ISSUE TITLE
Introduce Marionette.assert

### ISSUE THREAD

**Issue by paulovieira** [marionettejs/backbone.marionette#2558]
Hello all! Here is a simple addition to Marionette which would make the code more clean, in my opinion.

Below is a typical snippet on how Mn is handling errors:

```javascript
      if (!template || template.length === 0) {
        throw new Marionette.Error({
          name: 'NoTemplateError',
          message: 'Could not find template: "' + templateId + '"'
        });
      }
```

This pattern is repeated all over the place. If we add a new `Marionette.assert` helper function those 6 lines would be reduced to

```javascript
      Marionette.assert(template && template.length > 0, 'NoTemplateError', 'Could not find template: "' + templateId + '"')
```

The implementation could be something as simple as this:

```javascript
Marionette.assert = function(condition, name, message, url){
    if (condition) {
        return;
    }

    throw new Marionette.Error({
      name: name || '',
      message: message || '',
      url: url || ''
    });
}
```

Pros:
 - this would reduce a substantial number of lines (I counted around 20 uses of `Marionette.Error`, so I would say between 60 to 100 loc)
 - it would make the code more readable because it's easier to read a condition that must hold for the code to proceed instead of the negation ("at this point, x && y must happen, otherwise an error will be thrown").

Cons
 - an extra function call 
 - an extra line would be present in the stack trace ("Marionette.assert  line xxx").
 - if the error name, message and url are too long, we have to break them in a new line

**Comment by jmeas** [comment]
Ember does this. :+1:

**Comment by paulfalgout** [comment]
Thanks! I like it. 

So in the near future we can most likely expect the `Marionette.Error` implementation will come from `backbone-metal`  https://github.com/marionettejs/backbone.marionette/issues/2548

Seems reasonable to consider adding this there.

https://github.com/marionettejs/backbone-metal

**Comment by ahumphreys87** [comment]
Yup I like this - also think it will be a good addition to metal

**Comment by ianmstew** [comment]
@paulovieira Closing this with the encouragement to open a similar ticket against Metal!  FYI, Metal is coming soon to Marionette, so any addition you make there will also present itself to Marionette.

**Comment by paulovieira** [comment]
Cool! I'll submite a pr to backbone metal shortly (I will have time on wednesday only)

**Comment by ianmstew** [comment]
:+1:

**Comment by instanceofpro** [comment]
:+1:
