### ISSUE TITLE
Region/CollectionView Plan

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2560]
CollectionView has already become Region-like in many circumstances, but the conditionals that enable Region-like behavior are fragile.  The aim of this plan is to essentially promote CollectionView to a "List Region", the direction it has been heading naturally.

**Refactor Events in Region#show()**
1. Move `before:show` to front of `show()`, the timeline other `before` events are triggered (#2552).
   - Tests to verify `Region#show()` event sequencing.
2. Move `onBeforeAttach`/`onAttach` triggering on children to view instead of calling all descendants at once.  This reduces logical overlap with CollectionView.
3. Solve quirks around nested rendering in `onBeforeAttach`/`onAttach` (#2546).
4. Simplify/improve/replace onDomRefresh (#2299).
5. Update official recommendations for showing child views (#2539).

**Region Maintenance**
1. Destroying a Region should empty it as well (#2379)

**Promote CollectionView to "List Region"** #2545
1. Kill `_isShown` checks in CollectionView: no more logical dependency on Region.
2. Match `Region#show()` events in CollectionView.
   - Tests to verify event sequencing identical to `Region#show()`.

**Discuss: Refactor EmptyView**
1. Remove EmptyView from CollectionView (#2495).
2. Add `empty`/`some` events to CollectionView to facilitate alternative "empty view" handling in parent.
3. Behavior or alternative to simplify EmptyView handling in parent.

**Discuss: View "List Region" API**
1. Add “list” API to View to automate a nested CollectionView.
   - **Where does “Replace Region el" ability fit in?
2. Ensure compatibility with EmptyView solution.

**Breaking Changes**
- `before:show` moved to _beginning_ of `Region#show()`
- EmptyView refactoring

**Comment by ahumphreys87** [comment]
@ianmstew Im interested in hearing your thoughts on whether you think we need all the events in `region.show` - it does an awful lot at the moment, any contenders for :skull:

**Comment by ianmstew** [comment]
@ahumphreys87 Good question.  I have to think more, but off the top of my head I'd like to make sure the `swap` events aren't duplicated by anything.  One thing is for sure, I would like to push "attach" events down the chain rather than calling them once for entire view tree in `show`.

**Comment by paulfalgout** [comment]
In relation to Region#show 4)  https://github.com/marionettejs/backbone.marionette/issues/2299

**Comment by paulfalgout** [comment]
Much of the `emptyView` removal was because it was non-trivial to maintain.  I think now it is fairly trivial in #3244   So I think this issue comes down to regionifying collectionView.  Honestly at this point I'm not super concerned with that as I can't find a use-case the new CollectionView doesn't cover without much trouble..  In any case, if we want a regionify issue, since that I believe is the only outstanding topic here, we should open a new issue.
