### ISSUE TITLE
addChild not added at the correct index

### ISSUE THREAD

**Issue by zheffie** [marionettejs/backbone.marionette#2562]
I'm trying to improve performance by only showing a certain number of rows in a collectionview (```this```).
There is whitespace padded before and after the rows to keep the proper total height and make sure that the scrollbar has the appropriate length.

The shown rows are depending on the current scrollbar position. When scrolling up or down, the app calculates which rows should be removed (```toremove```) or added (```toadd```). When scrolling up, rows need to be added before the other rows. When scrolling down, rows need to be added after the other rows. The ```filtered``` array contains all models.

Below, the two functions that take care of adding and removing rows
```
 for (var i = 0; i < toremove.length; i++) {
      var model=this.filtered[toremove[i]];
      ChildView = this.children.findByModel(model);
      this.removeChildView(ChildView);
}
```
```
for (var i = 0; i < toadd.length; i++) {
      var model=this.filtered[toadd[i]];
      ChildView = this.getChildView(model);
      this.addChild(model, ChildView, toadd[i]);
}
```

the function ```addChild``` takes an```index``` as the third argument, and for this, I'm using the index of the model in the ```filtered``` array (```toadd[i]```), hoping that this would control the position of where the row gets added. Yet this does not seem to have effect. Rows are always added after the other rows, which is undesirable.

Does anyone know how I have to prepend the necessary rows?

**Comment by zheffie** [comment]
forgot to say: Initially the collection is rendered using this overrided method:
```
showCollection: function () {
    var ChildView;
    this.filtered = this._filteredSortedModels();

    for (var i = this.first; i <= this.last; i++) {
      ChildView = this.getChildView(this.filtered[i]);
      this.addChild(this.filtered[i], ChildView, i);
    }
  }
```

**Comment by ahumphreys87** [comment]
@zheffie could you create a jsFiddle to demonstrate the issue your having? Looking to see how you calculate `toremove` and `toadd`.

**Comment by zheffie** [comment]
Here goes [http://jsfiddle.net/85vmrqm0/]

This is not my the full code but centers on the core problem. 
A portion of the complete collection is rendered with an index equal to the position in an array
3 more rows are added with a lower index
They appear at the bottom

Perhaps I'm just misunderstanding the use of the index, but I sure would love an alternative solution

**Comment by zheffie** [comment]
I'm playing around with the functions ```_updateIndices``` and ```_insertBefore```. And it is now clear to me that they are not designed for my use case. 

The code take all kinds of assumption on the indices, which are not true in my case.
