### ISSUE TITLE
untie ui & render

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#2563]
ui elements are bind from `render` method. If a view receive a `el` from outside and so have no template, `bindUIElements` is never called which is *not* convenient.

**Comment by JSteunou** [comment]
From developer point of view the solutions to bypass this are

* manually call `bindUIElements` at some point (show, attach, ...)
* manually call `render` from parent after view creation and set `template: false` in child view

**Comment by ianmstew** [comment]
@JSteunou interesting... are you suggesting to bind UI elements upon instantiation of a View if the `el` already exists in the DOM?  I see others have had this issue before (see comments here: http://stackoverflow.com/a/18379392/957813).  @paulfalgout what do you think?

**Comment by jridgewell** [comment]
I think a better place for this is attaching ui elements in `#setElement` and `#render`.

**Comment by ianmstew** [comment]
@jridgewell Awesome, `setElement` looks good.  (It's already in `render`.)

**Comment by paulfalgout** [comment]
I agree @jridgewell.  I think this is solved with this issue.  https://github.com/marionettejs/backbone.marionette/issues/1952

**Comment by ianmstew** [comment]
Oooh, nice reference.  Closing in favor of #1952.

**Comment by ianmstew** [comment]
Thanks, @JSteunou!
