### ISSUE TITLE
Remove minor and major branches and update contrib docs

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2564]
Our contrib docs don't match our current process.  Not super OS friendly.

using `next` and cherry picking to a patch / minor branch seems to be the way to go.

**Comment by paulfalgout** [comment]
We also need to document something about the `/api/` documentation

**Comment by jasonLaster** [comment]
just killed minor. major was already dead. the docs will be fixed soon

**Comment by ahumphreys87** [comment]
fixed with #2624
