### ISSUE TITLE
Calling destroy on CompositeView before it is rendered throws an error

### ISSUE THREAD

**Issue by trevorharwell** [marionettejs/backbone.marionette#2567]
```javascript
var a = new Marionette.CompositeView()
a.emptyView = Backbone.View
a.childViewContainer = '> tbody'
a.destroy()
```
Running this code throws an error.  I know it may seem silly to construct a view just to destroy it before it is rendered but it is also silly that destroying a CollectionView/Composite view makes them try and construct an empty table view.

**Comment by paulfalgout** [comment]
This is a duplicate fixed here https://github.com/marionettejs/backbone.marionette/pull/2384

Should go out with `2.4.2` but for some reason was being left out.  I'll make sure this is addressed.
