### ISSUE TITLE
How to show one view (with model is different) by one region.

### ISSUE THREAD

**Issue by Sophia-nguyen** [marionettejs/backbone.marionette#2575]
Hi all,

I have one region and one view.
I use:  region.show(view). 
And then I reset view with new model. 
And I want show view again by region.show(view).

Please help me!
Thanks.

**Comment by paulfalgout** [comment]
Almost always you should build a new view for your new model to show and not reuse the other one.

Please join us on gitter https://gitter.im/marionettejs/backbone.marionette  There's many people who can help with these kinds of questions there.

**Comment by Sophia-nguyen** [comment]
HI Paulfalgout,

About my issue, can i remove view in region before show view a gain?

**Comment by paulfalgout** [comment]
when you show a view in a region it will remove and destroy the previous view.
