### ISSUE TITLE
Marionette w/ browserify + babelify requires downgrading and inline shim

### ISSUE THREAD

**Issue by ashtonwar** [marionettejs/backbone.marionette#2576]
Whilst trying to include Marionette w/ browserify + babelify I encountered [this issue](https://github.com/jashkenas/backbone/issues/3291).

This es6 shim should have fixed the issue:

```
import Backbone from 'backbone';
import $ from 'jquery';
Backbone.$ = $;
import Marionette from 'backbone.marionette';
```

In the latest version (6.1.2) of babelify this transpiles to:

```
var _jquery = require('jquery');
var _jquery2 = _interopRequireDefault(_jquery);
var _backbone = require('backbone');
var _backbone2 = _interopRequireDefault(_backbone);
var _backboneMarionette = require('backbone.marionette');
var _backboneMarionette2 = _interopRequireDefault(_backboneMarionette);
_backbone2['default'].$ = _jquery2['default'];
```

jQuery obviously needs to be added before Marionette is required. Downgrading Babelify to 5.0.5 resolved this. I also downgraded Backbone to 1.1.2.

My files originally looked like this:

```
// main.js
import './plugins.js'

...
```

```
// plugins.js
import Backbone from 'backbone';
import $ from 'jquery';
Backbone.$ = $;
import Marionette from 'backbone.marionette';
```

But Backbone.$ was still undefined. Inlining plugins.js into main.js fixed this.

Relevant files:

```
// gulpfile.js

...

const bundler = _.memoize(function (watch) {
  var options = { debug: true };
  if (watch) { _.extend(options, watchify.args); }
  var b = browserify('./public.src/CORE/main.js', options);
  if (watch) { b = watchify(b); }
  return b;
});

function bundle(cb, watch) {
  return bundler(watch).bundle()
    .on('error', handleErrors)
    .pipe(source('script.js'))
    .pipe(buffer())
    .pipe(gulp.dest('./public.dist'))
    .on('end', cb)
    .pipe(reload({stream: true}));
}

gulp.task('scripts', function (cb) {
  process.env.BROWSERIFYSWAP_ENV = 'dist';
  bundle(cb, true);
});

...

```

```
// package.json

...

  "browserify-swap": {
    "@packages": [
      "underscore"
    ],
    "dist": {
      "underscore.js$": "lodash"
    }
  },
  "browserify": {
    "transform": [
      "babelify",
      [
        "hbsfy",
        {
          "extensions": [
            "hbs"
          ]
        }
      ],
      "browserify-swap"
    ]
  }

...

```

It'd be nice to at least see some documentation for this.

**Comment by kv-bpatram** [comment]
I don't think this will be an issue once marionette releases an update to use Backbone 1.2.0 since Backbone now requires jquery automatically.

**Comment by ahumphreys87** [comment]
@ashtonwar we are currently in the process of writing guides. Integrations with various build tools would be an obvious one, would you care to share your experiences?

**Comment by SpaceK33z** [comment]
Now that [v2.4.2](https://github.com/marionettejs/backbone.marionette/releases/tag/v2.4.2) is released, this is fixed, right?

**Comment by ahumphreys87** [comment]
That's correct providing you use backbone 1.2 as that now loads jquery for you

**Comment by ashtonwar** [comment]
I can confirm after upgrading to Marionette v2.4.2 the library loads perfectly without the shim. @ahumphreys87 I'm not sure how I can contribute to any integration guides past this report without writing them, do you have any specific questions?
