### ISSUE TITLE
problem with nested layout views

### ISSUE THREAD

**Issue by rvnath** [marionettejs/backbone.marionette#2577]
I am creating nested layout views in my application.  Essentially the outer layout view creates and adds the DOM elements and regions required for inner layout.  Inner layout then renders its own child views inside of its own sub regions.

I have posted this question with detailed problem description at stackoverfow here. http://stackoverflow.com/questions/30554514/marionette-nested-layouts-unable-to-show-view

Ideally, I would like to write my code look like below and work as expected.
outer_layout = Marionette.LayoutView.extend({
  render : function {
    ... do self rendering first.

   //call inner layout show here.
  var inner_layout = new InnerLayout();
  this.region.show(inner_layout);
  }
}); 

Since, the above is not working, I ended up writing like this...
outer_layout = Marionette.LayoutView.extend({
  render : function {
    ... do self rendering first.

   //call inner layout show here.
  var inner_layout = new InnerLayout();
  //this.region.show(inner_layout);
  inner_layout.render();
  }
}); 

The changed code is working, but looks like an incorrect hack fix.

My inner layout itself has 1 template plus 2 child views.  To draw them all, currently I am calling the render method to attach the template and then calling showChildView like below.

		render: function() { 
			this.$el.html(this.template());
			this.showDashboard();
			return this; 
		},

		showDashboard: function() {
			this.showChildView('menuRegion', this.getMenuView());
			 this.contentRegion.on("show", function(view, region, options) {
				 view.setText("Despicable me!");
			 });
			this.showChildView('contentRegion', this.getContentView());
			console.log("user_dashboard showDashboard returning...");
			return this;			
		}

I am not sure, if this is the best way to do, or should I be using onShow() or onBeforeShow() callbacks to avoid extra paint cycles.

Thanks for any help.

**Comment by paulfalgout** [comment]
Don't override `render`  use the `onRender` hook.  It looks like someone has already posted that to SO. Please join us on gitter with additional questions https://gitter.im/marionettejs/backbone.marionette
