### ISSUE TITLE
Get coverage up to 100% for next

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2581]
We lost coverage recently https://coveralls.io/builds/2719284

Some additional tests should be written to maintain 100%.

**Comment by ianmstew** [comment]
:cry:

**Comment by paulfalgout** [comment]
This is mostly down to filter related issues in collectionView, but I think we should also add something for `if(this.isDestroyed)` in `Object.destroy` and the RegionManager `_store` adding the same named region.

Really it'd be great to get branch coverage up to 100%.  Often the branches can indicate unused code.

Some of that is https://github.com/marionettejs/backbone.marionette/pull/2733 and https://github.com/marionettejs/backbone.marionette/pull/2732

**Comment by paulfalgout** [comment]
```md

**Comment by paulfalgout** [comment]
This is very close to coverage already.. actually the more worrying stat is some of the branches not covered.. anyhow.. the tests need love anyhow.. but this shouldn't hold up v3.

**Comment by rafde** [comment]
@paulfalgout this can be closed.

**Comment by paulfalgout** [comment]
Thanks
