### ISSUE TITLE
Why does CollectionView.reorder() resort to rendering the view if its children have been filtered?

### ISSUE THREAD

**Issue by Seebiscuit** [marionettejs/backbone.marionette#2584]
From the 2.4.1 source (abridged), `src/collection-view.js#L135`:
 ```
  reorder: function() {
    var children = this.children;
    var models = this._filteredSortedModels();
    var modelsChanged = _.find(models, function(model) {
      return !children.findByModel(model);
    });

    if (modelsChanged) {
      this.render();
    } else {
      var els = _.map(models, function(model) {
        return children.findByModel(model).el;
      });

     this._appendReorderedChildren(els);
    }
  },
```
So, after a short discussion with @ahumphreys87 we talked about how paging functionality may be unpredictable if the filter collection were resorted. But, I simply don't see it that way. For the following two reasons:

1. If the end-user filtered the list and wants to sort, the user doesn't suddenly want to sort the whole list. She may want to simply sort the filter. I'm not sure that when she wants to resort she *expects* to sort the original collection. Anyway, I think it's up to the Dev to ensure the user is aware of the set she's working with.

2. Why is Marionette making an assumption here? Is it Mn's responsibility to save the Dev from himself? I smell hankey :hankey: 

I propose to reduce the footprint of CollectionView.reorder, to naively do what is called upon to do, resort the children views without rerendering the parent view:

 ```
  reorder: function() {
    var children = this.children;
    var models = this._filteredSortedModels();

    var els = _.map(models, function(model) {
       return children.findByModel(model).el;
     });

     this._appendReorderedChildren(els);
    }
  },
```

We may also change the name to **`reorderChildren`**.

**Comment by cmaher** [comment]
If the children have changed, the CollectionView then has to remove old children, and render + insert new children. IIRC, `reorder` is intended as a more efficient `sort`, moving existing DOM elements rather than worrying about whether or not a view is rendering something depending on its sort order.  Since the filter can also depend on the order, we need to explicitly account for that case.

Handling the addition/removal of filtered children could probably be more efficient, however.

**Comment by ahumphreys87** [comment]
yeah so the way sorting works is it will sort based on the comparator in the collection, so we sort the based on the whole collection passed into the view.

However like @cmaher has said `reorder` is intended to be more efficient - however the `modelsChanged` check that you removed in your sample does more then check for filters. What if model is silently added the to the collection and then sort is called? We would need to render as we don't have that item in the DOM. I imagine quite a few of our tests would fail if we remove that check.

We should definitely look to the improve how filtering and sorting tie together though, i.e. some logic to check whether child is displayed before marking `modelsChanged`

**Comment by Seebiscuit** [comment]
@cmaher Let me see if I understand what you're saying (I read your statement only 44 times). Since the `filter` passed into the view is a function, and that function may use order as a parameter in the filter, it may come out that after a sort, the newly sorted and filtered set will be different than the first filter set. So views will be added/removed on render. Since all `_appendReorderedChildren()` does is, essentially, move around DOM elements, it can't remove views nor add new ones. This also answers @ahumphreys87 stament re silently adding a model, that should, on `'sort'`, be rendered.

I'll put some thought on this. Thanks for the explanation, gents.
