### ISSUE TITLE
undelegateEvents is not called in certain scenarios where it needs to be called. 

### ISSUE THREAD

**Issue by shakhar** [marionettejs/backbone.marionette#2586]
marionette destroy event triggers before the events are undelegated. This sometime cause undelegateEvents function to doen't call on view destroy.

**Comment by paulfalgout** [comment]
Can you create a code (jsbin/jsfiddle) example of this?

It does look like event unbinding was moved after the [destroy event](https://github.com/marionettejs/backbone.marionette/commit/ca7a423dee4fe3fd1b48f305ff5ffa50f11c4da5), and I'm not exactly certain why, but I don't know how that would prevent `undelegateEvents` from being called.

**Comment by ianmstew** [comment]
@shakhar Any further information on this?
