### ISSUE TITLE
Add Marionette to Babel's "Who's Using"

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2597]
//cc @thejameskyle 

We're using the boilerplate for Radio.

**Comment by thejameskyle** [comment]
https://github.com/babel/babel.github.io/issues/new?title=New+User%3A+Marionette&body=Please+fill+the+following+out%3A%0A%0A-+Name%3A+%28correctly+formatted%29%0A-+Homepage+url%3A+%28homepage%2Fprimary+entry+point+for+users%29%0A-+Brand+Guidelines%2FLicensing%3A+%28or+anything+we+need+to+know+before+using+your+logo%29%0A-+Logo%3A+%28svg+if+possible%2C+pngs+over+500x200px+with+transparent+backgrounds+are+also+acceptable%29%0A%0A%3E+Example%3A%0A%3E%0A%3E+Name%3A+CloudFlare%0A%3E+Homepage+url%3A+https%3A%2F%2Fcloudflare.com%0A%3E+Brand+Guidelines%2FLicensing%3A+https%3A%2F%2Fwww.cloudflare.com%2Flogo%0A%3E+Logo%3A+https%3A%2F%2Fwww.cloudflare.com%2Fmedia%2Fdownloads%2Fcloudflare-logo-kit.zip%0A

**Comment by thejameskyle** [comment]
[Metal](https://github.com/marionettejs/backbone-metal) uses it [too](https://github.com/marionettejs/backbone-metal/commit/1462fb907b6afa45e867bdf6ee582edb02562cd4) btw.

**Comment by paulfalgout** [comment]
https://github.com/babel/babel.github.io/issues/343
