### ISSUE TITLE
How to check before or after render childView in compositeView

### ISSUE THREAD

**Issue by Sophia-nguyen** [marionettejs/backbone.marionette#2598]
Hi all, 

I have the problem.
I use compositeView to render childView, and I call one collection to fetch data.
Anywhen the collection have data the childView will be render, I wants check when collection have data (not check in collection, i need check it in compositeView) to check data and call function to renderChild view or not.
But, if can not check data, maybe check before or after childView render, I can check data and remove childView.

Any solution for this?
Thanks

**Comment by Haraldson** [comment]
Marionette takes care of all this for you. An empty collection by default won’t render any children, naturally.

In addition, you can use [isEmpty](http://marionettejs.com/docs/v2.4.1/marionette.collectionview.html#collectionviews-isempty) and [emptyView](http://marionettejs.com/docs/v2.4.1/marionette.collectionview.html#collectionviews-emptyview)/[getEmptyView](http://marionettejs.com/docs/v2.4.1/marionette.collectionview.html#collectionviews-getemptyview) if you need more control.

**Comment by paulfalgout** [comment]
If you're still having issues.  A jsfiddle or some code showing the problem will help.  However please join us on https://gitter.im/marionettejs/backbone.marionette where the growing community can help.
