### ISSUE TITLE
How to add LoadingView in CollecitionView ?

### ISSUE THREAD

**Issue by KeyHui** [marionettejs/backbone.marionette#2600]
Hi All,
How to add LoadingView in CollecitionView ?

**Comment by cytomich** [comment]
I'm not sure, but may be this helps
https://github.com/gogiel/marionette.loading#setting-loading-view

**Comment by KeyHui** [comment]
@cytomich  thank you

**Comment by paulfalgout** [comment]
Personally I keep them separate.
```js
region.show(loadingView);
var somePromise = myChannel.request('some:collection');
somePromise.then(showCollection);
```

Please come join us on https://gitter.im/marionettejs/backbone.marionette for more in depth answers from our growing community.
