### ISSUE TITLE
Remove component.json support?

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2601]
Does anyone use this?  Babysitter's had been a version outdated for a while and no one complained.

If it is in use, is it important that the dependency's component.json files are maintained / available

For instance:

https://github.com/marionettejs/backbone-metal/pull/23

Is it necessary?

**Comment by thejameskyle** [comment]
Component seems pretty dead to me: http://npm-stat.com/charts.html?package=component

**Comment by ianmstew** [comment]
I would :+1: its removal in `next`.  Since Metal is behind a feature flag in `2.5` I think it's acceptable to keep Marionette supporting it while Metal does not until the breaking release when Metal is fully integrated by default.
