### ISSUE TITLE
Nested View Structures - Clarification

### ISSUE THREAD

**Issue by bazineta** [marionettejs/backbone.marionette#2604]
In the documentation section that describes how to efficiently render nested view structures:

http://marionettejs.com/docs/v2.4.2/marionette.layoutview.html#efficient-nested-view-structures

It describes LayoutView showing children in onBeforeShow().  When attempting this with a CollectionView with LayoutView children, the documented technique does seem to work properly when the view is first rendered.  However, thereafter, any fetch() on the collection that results in add operations results in exceptions in the LayoutView's onBeforeShow(), when the LayoutView attempts to render children into regions denoted by DOM elements that don't exist yet.

I'm curious if the technique described in the documentation is specific only to use of LayoutViews all the way down, and thus having a CollectionView in play is an unsupported case, or if this is actually intended to work.  While it seems that onShow() is always safe, at this point I can't see how using onBeforeShow(), as documented, could possibly be a proper course of action in this case.

**Comment by bazineta** [comment]
Possibly related, #2539, #2546, #2560.  Given discussion in #2539, I'm starting to wonder if the attach events are the right way to go here, but then there's this:

http://marionettejs.com/docs/v2.4.2/marionette.layoutview.html#use-of-the-attach-event

Which leaves me thinking that I should just move to a commune in Vermont, and consider no technology more complex than a shovel going forward.

Seriously though, is there a 'correct' answer here with respect to nested render efficiency, or should I just punt to onShow() for everything until 3.0?

**Comment by jbarreiros** [comment]
This is a point of confusion for me too. Dug into the code, and found the following...

```
_addChildView: function(view, index) {
      ...

      // trigger the 'before:show' event on `view` if the collection view
      // has already been shown
      if (this._isShown && !this.isBuffering) {
        Marionette.triggerMethodOn(view, 'before:show');
      }
  
      // Store the child view itself so we can properly
      // remove and/or destroy it later
      this.children.add(view);
      this.renderChildView(view, index);
  
      if (this._isShown && !this.isBuffering) {
        Marionette.triggerMethodOn(view, 'show');
      }

      ...
}
```

It seems that "before:show" is based on the CollectionView and not the child view? I expected the flow to look more like: 
```
_addChildView: function(view, index) {
      ...
      // Store the child view itself so we can properly
      // remove and/or destroy it later
      this.children.add(view);
      this.renderChildView(view, index);
      ...
}

renderChildView: function(view, index) {
      view.render();
      Marionette.triggerMethodOn(view, 'before:show');
      this.attachHtml(this, view, index);
      Marionette.triggerMethodOn(view, 'show');
      return view;
}
```

**Comment by ianmstew** [comment]
Great catch.  It appears that `CollectionView#_addChildView` is firing `before:show` too early.  For `_addChildView` to accurately model `Region#show`, which is its goal, it must call `before:show` _after_ rendering the child view.  This issue existed [pre-2.4.2](https://github.com/marionettejs/backbone.marionette/blob/f16a3ca11b9b573cdaf553d3dd65281dc535c5c8/src/collection-view.js#L316-L327) but [this fix](https://github.com/marionettejs/backbone.marionette/pull/2506) surfaced it.  I already have a test case and a fix in mind, and will move on this asap.

**Comment by ianmstew** [comment]
@bazineta before you pick up and move to Vermont, I think you'd appreciate that the "best way to render child views" is going to be very clear in `3.0`--one of our focuses is cleaning up the `show` lifecycle.  :stuck_out_tongue_winking_eye:

**Comment by bazineta** [comment]
Ian, it is really quite a lovely place, but I shall desist for the moment.  Thanks for the update; looking forward to 3.0.

**Comment by ianmstew** [comment]
Glad you'll be around for a bit longer!  :)

**Comment by ianmstew** [comment]
Moving discussion/PR to #2633
