### ISSUE TITLE
2.4.2 Regression?

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#2605]
I have some views without a model during the creation, and a state model is set during the initialize like this

```js
        initialize: function() {
            this.model = new ViewStateModel();
        }
```

and using `modelEvents` to update the view.

Unfortunately, this does not work anymore since 2.4.2. Worked very fine with 2.4.1.

I tried to debug the thing, and `delegateEvents` is called before the `initialize` and never called again after.

(will be out until next week, I'll cannot respond until then)

**Comment by jridgewell** [comment]
This is a change in Backbone v1.2. We now call `#delegateEvents` before calling `#initialize`. As a workaround, you can set the model in the View's constructor instead.

The next major includes #2241, which handles this. I think it could be backported easily if both `#delegateEntityEvents` and `#undelegateEntityEvents` were still called in `#delegateEvents` and `#undelegateEvents`.

**Comment by Ky6uk** [comment]
Another problem with using `ui` attribute inside `initialize` (e.g.: extending `ui` from prototype).

**Comment by paulfalgout** [comment]
@marionettejs/marionette-core so what's the solution here?  Document the breaking change when using backbone >1.2.1 ?

**Comment by samccone** [comment]
This is a backbone change, and another example of our upstream dependency not following semver and causing problems for users. 

Since Marionette (core) works with 1.2.1 and does not break we **do** support 1.2.1, but as a developer using both you should totally not blindly update to the latest backbone just because marionette (core) works with the latest backbone. 

your code !== Marionette core, and because of that, it is possible for your code to not "support" or "work with" the latest backbone. 

We can assure you @JSteunou that your Mn code will not break between minor and patch bumps, however since Marionette is an extension lib that sits on top of Backbone, it is easy for BB to break your code while not breaking Marionette core.

Going to close, but we can continue the discussion.

**Comment by JSteunou** [comment]
thanks for the explanation @samccone I totally follow you on this

**Comment by jridgewell** [comment]
Re: https://github.com/jashkenas/backbone/pull/3060

**Comment by JSteunou** [comment]
The thing is `initialize` exists so we dont have to override the constructor and call super. This same existence can be reconsidered as soon as we have to move things into constructor again, just to *make things work*.

I'm very fan of using a model as state storage for some big views, so I'll always have some model created in this `initialize` method. And for collection views, I'm using visual loader / spinner a lot (empty view) and I just create the collection and call fetch inside the view `initialize`.

For now I'm just stuck on BB 1.1.x because of this.

**Comment by akre54** [comment]
Just call `delegate` or turn your events hash into a method. Not sure why you'd want to edit your `events` in initialize.

**Comment by JSteunou** [comment]
I think you misread. I'm not editing my `events` in `initialize`. I'm creating a model / collection in `initialize`. Doing this & having a `modelEvents` or `collectionEvents` worked with BB 1.1.x, do not work with BB 1.2.x.

My issue is simple as that.

And no I wont search & replace or re-write hundreds of views just to go with a new way of doing this or that.

**Comment by akre54** [comment]
`delegateEvents` deals with DOM events only, it doesn't touch model or collection events. Those should work exactly as before. If they don't, mind creating a small reproducible JSFiddle (that used to work on 1.1.x and stopped working in 1.2.0) and open an issue on Backbone so we can take a look? Thanks.

**Comment by JSteunou** [comment]
The issue is not more on BB or Mn. `delegateEvents` still work as before and as it should in a BB context. That's why this issue is on Mn and not on BB github repo.

The issue come when using BB 1.2.x with Mn **and** model / collection events **and** model / collection attached in `initialize`. @samccone as a point when he said above that Mn did not break is code in 2.4.x and you have a point saying `delegateEvents` deals with DOM events only.

None the less, the use case & the bug coming along with exists when mixing Mn + BB 1.2.x

**Comment by Ky6uk** [comment]
@akre54 `Mn` bind `model` and `collection` events together with DOM events by replacement of `delegateEvents`. https://github.com/marionettejs/backbone.marionette/blob/b0711585b022cfeb4822129a4cde5591f21f06bc/src/view.js#L86

**Comment by akre54** [comment]
Urg. So much for "not breaking code" ;)

If you override a method to do something it's not supposed to do things are going to break. Model and collection events are very different from DOM events, and they shouldn't be mixed this way.

**Comment by jmeas** [comment]
> If you override a method to do something it's not supposed to do things are going to break. Model and collection events are very different from DOM events, and they shouldn't be mixed this way.

For sure. We identified this as a problem quite some time ago, actually. It's one of those features from a time before the current team of maintainers, and it's scheduled to be fixed in the next major release (@jridgewell referenced the PR that fixes it [above](https://github.com/marionettejs/backbone.marionette/issues/2605#issuecomment-113177356)).

**Comment by paulfalgout** [comment]
This issue was introduced in Mn `1.0.0` :-)

**Comment by ianmstew** [comment]
Excellent point on the override dealing with unrelated events.  All the more why I'm excited for the next major: https://github.com/marionettejs/backbone.marionette/pull/2241/commits.

**Comment by jmeas** [comment]
> This issue was introduced in Mn 1.0.0 :-)

Ah, I stand corrected, then!

**Comment by paulfalgout** [comment]
WAT?  Who else was around then?  https://github.com/marionettejs/backbone.marionette/commit/16daa2ee6c78cd915c50df8b6e3ec5caaf9876b3

**Comment by JSteunou** [comment]
So is #2241 will be backported into 2.4.3? Pretty pleeeaaassee :sweat_smile:

**Comment by samccone** [comment]
I summon @derickbailey

**Comment by JSteunou** [comment]
Such power :sparkles:

**Comment by jmeas** [comment]
> WAT? Who else was around then? 16daa2

Oh, oops. I originally read that as v2. I'm drugged up on pain meds right now...you'll have to forgive me :stuck_out_tongue: 

> So is #2241 will be backported into 2.4.3? Pretty pleeeaaassee

I think it would go against semver to change the behavior of this public method. I know it's a pain, but it'll have to wait until v3.

Feel free to patch your base View class directly, though. I do it all the time to change APIs before they get released officially! It does require a bit more maintenance, so it's not for everyone, but it's worked well for me.

**Comment by jridgewell** [comment]
> I think it could be backported easily if both #delegateEntityEvents and #undelegateEntityEvents were still called in #delegateEvents and #undelegateEvents. — https://github.com/marionettejs/backbone.marionette/issues/2605#issuecomment-113177356

Adding `#delegateEntityEvents` to the end of `#delegateEvents`, then calling `#delegateEvents` in the constructor after the super call is all that's needed. You'll actually be preserving backwards compatibility.

**Comment by JSteunou** [comment]
Though the same.

**Comment by theodorDiaconu** [comment]
I had a similar problem to the CompositeView, events were attached prior to construction. Solution was, after I instantiated the collection, I manually called the managing of events.

```js
        this.collection = this.model.get('childrenCol');
        this._initialEvents();
```

**Comment by JSteunou** [comment]
If there is no backport of a fix, can we at least document this so people using the last BB dont get annoyed?

An official simple way to get around or a monkey patch or both.

**Comment by paulfalgout** [comment]
@theodorDiaconu I don't think this is the same thing..  InitialEvents is not called until the first render

**Comment by JSteunou** [comment]
His issue was "add" event were not detected anymore if I recall from gitter discussion. And collectionEvents do not work anymore when setting `this.collection` in initialize with BB 1.2.x. It's definitely related.

**Comment by sirianni** [comment]
+1 for backporting this.  We just updated to the latest Marionette and Backbone and were hit by this issue.

**Comment by pwnall** [comment]
+1 for backporting this. Fixing this up in a large codebase is no fun.
