### ISSUE TITLE
CollectionView does not respect false as a return value from isEmpty()

### ISSUE THREAD

**Issue by sdnetwork** [marionettejs/backbone.marionette#2606]
I think there is a little problem with the use of this function : 

in the doc the isempty is describe by  : 

    If you want to control when the empty view is rendered, you can override isEmpty

in my case i don't want display the empty view if my collection model query is empty.

so i override the isEmpty like that : 

    isEmpty: function() {
    		if (this.collection.length == 0) {
    			if (this.ui.query.val() == "") {
    				return false;
    			}
    			return true;
    		}
    		return false;
    	}

but the problem is in the _renderchildren

     // If we have shown children and none have passed the filter, show the empty view
      if (this.children.isEmpty()) {
        this.showEmptyView();
      }

to correct the problem i have done that but ...

    // If we have shown children and none have passed the filter, show the empty view
        if (this.children.isEmpty() && this.getOption('filter') && this.getOption('filter') != '') {
          this.showEmptyView();
        }

do you think that is a good workaround ?

**Comment by vanessanutrio** [comment]
I am in the process of upgrading to 2.4 and noticed this issue as well. I am using  isEmpty as specified in the documentation to not show the empty view but now it is not working. To me, the workaround proposed makes sense based on the comment and the commit description when this was added.

https://github.com/marionettejs/backbone.marionette/commit/4c5ef018d813116e66fce421a874c44fdda13a1a

**Comment by jasonLaster** [comment]
seems reasonable. @cmaher @ahumphreys87 ?

**Comment by ahumphreys87** [comment]
Is the workaround proposed to make isEmpty look at children and the filtered set? Then change the check in _renderChildren to look at isEmpty?

I'd be happy to accept a PR for that change, I don't think changing isEmpty would cause issues elsewhere so let's do it.

@sdnetwork would you be interested in submitting a PR?

**Comment by ianmstew** [comment]
@sdnetwork Any word on a PR?  Otherwise we can take a stab at it.

**Comment by sdnetwork** [comment]
@ianmstew i have just done https://github.com/marionettejs/backbone.marionette/pull/2641

**Comment by ianmstew** [comment]
Fixed by https://github.com/marionettejs/backbone.marionette/commit/a8771a4f5cd94d847d4e94db88dca26ea51a1acf.
