### ISSUE TITLE
Simplify travis-ci testing matrix

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2609]
We should remove node 0.11.
Testing should likely be done mostly on 0.12 with a few on 0.10 and on io.js

Example:
https://github.com/marionettejs/backbone-metal/blob/master/.travis.yml#L7

**Comment by megawac** [comment]
I mean, it doesn't really matter what we test on as we're not trying to test node. So yeah, 100% agree I'll do a quick refactor of the `.travis.yml`
