### ISSUE TITLE
Figure out a jsdom alternative

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2610]
jsdom is keeping our windows users from actively contributing.

Let's try cheerio or something else?

**Comment by Seebiscuit** [comment]
I tried setting up the dev environment and error'd out when compiling contextify (jsdom dep). I'm using a Windows machine, running Win 7, and using Visual Studio 2012. Our version of jsdom uses an old version of contextify  that tries to link with Visual Studio 2010 build tools. And while I have build tools all the way back to VS 2005 I can't overcome the compile time error. 

(Btw, it is possible to properly build this version of contextify as a stand alone with this command: `npm install contextify -msvs_version=2012`, but the jsdom install does not issue the `-msvs_version=2012` flag.)

Clearly, I'm strongly in support of upgrading jsdom or moving to other phantom DOMs.

**Comment by samccone** [comment]
can someone link up some jsdom issues here for some context?

**Comment by paulfalgout** [comment]
jsdom depends on contextify.  The work arounds for contextify to work on Windows seem excessive.  https://github.com/brianmcd/contextify/wiki/Windows-Installation-Guide  and/or don't seem to work?

Not to mention we're locked in with lower versions unless we want to drop node support and go all-in io.js
 > Note that as of our 4.0.0 release, jsdom no longer works with Node.js™, and instead requires io.js.

**Comment by Seebiscuit** [comment]
See for example: tmpvar/jsdom#378

**Comment by samccone** [comment]
ok when I get back to work next week, I will try this on windows, but based on what I have read it seems like jsdom should work on windows

cc @domenic

**Comment by domenic** [comment]
Yeah, contextify is not even needed anymore with recent jsdom.

**Comment by Seebiscuit** [comment]
That's the rub @samccone, you can't generalize the Windows experience, because contextify depends on the particular dev environment of the user. I can't compile contextify without sacrificing my dev environment, which I can't do.

**Comment by ianmstew** [comment]
:+1: to sorting out a Windows compatible solution.  Unfortunately, there is no version of jsdom that supports Node.js yet does not require contextify.

**Comment by Seebiscuit** [comment]
So...I'm installing VirtualBox. I'll be deving in Ubuntu. Unless anyone's found a lightweight *nix OS they love

**Comment by paulfalgout** [comment]
I think this issue is probably dead until node.js === io.js.  Chances are that'll happen prior to any sort of significant overhaul, and I am not aware of reasonable solution.  Closing for now.

**Comment by Seebiscuit** [comment]
Looks like it's happening faster than you think, @paulfalgout:
[io.js decides to join the Node Foundation](https://medium.com/node-js-javascript/io-js-week-of-may-15th-9ada45bd8a28)

**Comment by paulfalgout** [comment]
Oh yeah there's a convergence repo already that is essentially mostly io.js named node.js under a node foundation.  But I dunno when it'll be ready.
