### ISSUE TITLE
Region.empty fails to destroy view when called with any options

### ISSUE THREAD

**Issue by bradlord** [marionettejs/backbone.marionette#2611]
In Marionette 2.4.2, calling `region.empty` with any options prevents the contained view from being destroyed. Here is an example:

```
var region = new Marionette.Region({el: $('<div>')});
var view = new Marionette.ItemView({template: false});
region.show(view);
region.empty({});
console.log(view.isDestroyed); // Logs false
```

Calling `region.empty()` without any arguments results in the view being destroyed as expected. The bug seems to be due to the fact that the `empty` function uses `Marionette._getValue` incorrectly to find the value of preventDestroy that is passed into the function:

```
var preventDestroy = Marionette._getValue(options, 'preventDestroy', this);
```

When the line above runs, `preventDestroy` gets set to the value of `options` (`{}` in my example) instead of the value of `options.preventDestroy`.

**Comment by ahumphreys87** [comment]
fixed with #2636
