### ISSUE TITLE
Marionette.Application does not pass all arguments to .initialize()

### ISSUE THREAD

**Issue by kgoggin** [marionettejs/backbone.marionette#2615]
I'm working on upgrading from 2.2 to 2.4, and ran into an issue based on the new inheritance structure released in 2.3. I've got a place where I'm instantiating a Marionette.Application, and am passing in two arguments which are referenced inside the Application's `initialize()`. This worked fine in 2.2, but broke in 2.3 - only the first argument gets passed through.

I've tracked the issue to this line inside Marionette.Application's `constructor()`:
```
Marionette.Object.call(this, options);
```
I think if this were changed to `Marionette.Object.apply(this, arguments);` it'd remain backwards-compatible with the earlier release, without hurting anything. I'll go ahead and get PR together with the change, but did want to make sure the change wasn't intentional for some reason.

**Comment by ahumphreys87** [comment]
fixed with #2616
