### ISSUE TITLE
Add isDestroyed flag to Mn.Object/Mn.Class

### ISSUE THREAD

**Issue by pascalpp** [marionettejs/backbone.marionette#2620]
When an object is destroyed, it should be marked with `isDestroyed = true` in the same way that views are.

Use case: I have an object which calls one of its methods on a 5-second `_.delay` after being instantiated. If the object is destroyed in the mean time, that delayed method needs a way to detect that the object has been destroyed and return early.

Workaround: I've added an `onDestroy` method to my controller and applied the `isDestroyed` flag myself.

(I understand that Marionette.Object is getting replaced by Marionette.Class in a future version; the same issue applies.)

**Comment by pascalpp** [comment]
Wondering what to make of the above suggestion in light of https://github.com/marionettejs/backbone.marionette/issues/2170

**Comment by samccone** [comment]
I think adding a isDestroyed prop to Marionette.Object is a good idea, it would allow us to lift it from Mn.View

**Comment by paulfalgout** [comment]
This is actually kind of a dupe of https://github.com/marionettejs/backbone.marionette/pull/2352 
Though I think I'm in favor of `isDestroyed` working the same everywhere

**Comment by ahumphreys87** [comment]
@pascalpp would you be interested in submitting a PR for this work?

**Comment by pascalpp** [comment]
Sure. I think? It's only a one-line change. Stay tuned.

**Comment by pascalpp** [comment]
Ok it was more like three lines and a couple tests.

**Comment by ahumphreys87** [comment]
fixed with #2626
