### ISSUE TITLE
Docs rewrite/cleanup proposal

### ISSUE THREAD

**Issue by billyjanitsch** [marionettejs/backbone.marionette#2629]
The Marionette docs have gotten better in the past year, but I think there's still a lot of improvement that could be made. I've compared the [Marionette docs](http://marionettejs.com/docs/current/) to [those of Backbone](http://backbonejs.org/) (which are some of the best I've encountered). In short, Mn doesn't have a clear read path for first-time users, forces users to guess and click around much more than they should need to, and makes it easy to miss features. More specifically:

- **Overview**
The [first paragraph](http://backbonejs.org/#) of BB succinctly introduces its main classes and their use cases. Mn has [no general technical overview](http://marionettejs.com/docs/current/).

- **Class subheadings**
Each BB subheading corresponds to one method (e.g. [`Model.get`](http://backbonejs.org/#Model-get)). The Mn subheadings are inconsistent, both [be](http://marionettejs.com/docs/v2.4.2/marionette.collectionview.html)tw[een](http://marionettejs.com/docs/v2.4.2/marionette.itemview.html) and [within](http://marionettejs.com/docs/v2.4.2/marionette.compositeview.html#organizing-ui-elements) classes, and often don't obviously follow from the class's overview.

- **Class descriptions**
Each BB class (e.g. [`Events`](http://backbonejs.org/#Events)) begins with a more detailed description of its general purpose and main features. Mn classes explain their purpose but usually [not their features](http://marionettejs.com/docs/v2.4.2/marionette.collectionview.html) (or they link to an [external, out-of-date blog post](http://marionettejs.com/docs/v2.4.2/marionette.layoutview.html)). In combination with the above, there isn't a good way to broadly figure out what a class can do without reading its entire doc page.

- **Readability/organization**
BB docs read well top-down. Neither BB classes nor methods are sorted by name, but instead grouped by functionality. Mn classes are sorted by name, and classes/methods are [riddled with references](http://marionettejs.com/docs/v2.4.2/marionette.layoutview.html) to other classes/methods, making the docs a confusing web of dependencies. I'm not even sure there exists an ordering of the classes that one could read through without encountering a reference to something that hasn't been explained yet. Read paths (e.g. `View` > `ItemView`) should be more clear.

- **Redundancy/consistency**
Largely because of the above, BB rarely needs to repeat itself. Mn contains lots of redundancy and inconsistency (e.g. [`View`](http://marionettejs.com/docs/v2.4.2/marionette.view.html#viewbinduielements), [`ItemView`](http://marionettejs.com/docs/v2.4.2/marionette.itemview.html#organizing-ui-elements), and [`CompositeView`](http://marionettejs.com/docs/v2.4.2/marionette.compositeview.html#organizing-ui-elements) all document the UI hash -- but LayoutView doesn't), which is a pain to parse through. Mn methods are grouped by functionality but inconsistently so between classes.

These problems are particularly apparent in the gitter channel, where users will regularly ask if there's any way to do X, and yes, it turns out that X is one of Marionette's (often main) features, but the user missed it in the docs. I imagine many more users haven't even bothered to ask on gitter.

I'd love to take a stab at reorganizing/rewriting the docs while I have a few weeks of spare time. Would the core team be interested in this? If so:

1. Any disagreements with, or additions to, my suggestions for improvement?
2. Which version should I target? I know there are some API changes coming up for v2.5 and v3.
3. How should I go about doing this? Fork `next` and eventually submit a large PR?

**Comment by paulfalgout** [comment]
I actually really like this proposal.  Sorry for the delay.  I think this will be great as part of a `v3.0.0` release which'll be the next focus.  Hopefully some of the documentation will be cleaned up during that time, so this may prove to be good timing.

**Comment by ianmstew** [comment]
@bi

**Comment by ianmstew** [comment]
@billyjanitsch We may have missed your few weeks of spare time, but if you're still interested, exactly what you suggested would be outstanding.

Forking, branching from `next`, and submitting a large PR will be fine.  The only thing you'll want to do is squash down to a single commit and then rebase before PRing and integrate any doc updates that may arise during your development.

**Comment by ahumphreys87** [comment]
Really like this proposal! @billyjanitsch do you have time to work on this?

@marionettejs/marionette-core I propose we remove the 3.0.0 milestone from this and add it as soon as it lands, I don't think one of us can feasibly pick this up for 3.0.0, 3.x might be more realistic?

**Comment by paulfalgout** [comment]
I would like to release a  release candidate for 3 and start on this during that time with hope to finish it when it goes gold.

**Comment by paulfalgout** [comment]
Oh this is the consolidation ticket..  Yeah I suspect this is multiple tickets of work too

**Comment by JSteunou** [comment]
Could we also list all recurrent question we get on gitter and show way(s) to solve it 
I always see a lot of 

* Do I have to use Controller, how, where?
* How can I have a collection & a collection view but different child views
* Where do I start? How to use `Application`, `Application#onStart`
* How can I do data binding
* Should I use onRender / onShow / onAttach / onDOMRefresh for *<insert action>*
* ...

**Comment by paulfalgout** [comment]
@scott-w this is an older issue.. worth scanning.  we might be able to close this out for the other docs tickets.. but might be worth a read

**Comment by scott-w** [comment]
I'll self-assign this so I can find it quicker when I have a chance.

**Comment by scott-w** [comment]
I've just read through this and #3066 - and its dependent issues - cover all the issues here. I'll close this now.
