### ISSUE TITLE
CollectionView children fire before:show too early

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2633]
@bazineta opened a discussion in #2604 that led to a this finding.

It appears that `CollectionView#_addChildView` is firing `before:show` too early.  For `_addChildView` to accurately model `Region#show`, which is its goal, it must call `before:show` _after_ rendering the child view.  This issue existed [pre-2.4.2](https://github.com/marionettejs/backbone.marionette/blob/f16a3ca11b9b573cdaf553d3dd65281dc535c5c8/src/collection-view.js#L316-L327) but [this fix](https://github.com/marionettejs/backbone.marionette/pull/2506) surfaced it.

**Comment by MeoMix** [comment]
Is this really able to be fixed in a non-major release? Feels like someone could've built a dependency on the order of events firing.

**Comment by ianmstew** [comment]
@MeoMix That's a good point, although the only docs on `before:show` are contained within [Region docs](https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.region.md#events-raised-during-show), indicating it comes after `render`.  I think the risk of someone following the Region docs for region-like CollectionView events and hitting unexpected behavior is much greater (#2604).
