### ISSUE TITLE
Consider only classifying Marionette extends with Metal

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2637]
In a recent discussion there were some concerns about modifying backbone, and altering its behavior from its documentation.  Certainly very reasonable concerns to consider.

Historically it has been mentioned that this classifying is required:  
> it is required to maintain the correct prototype chain when we extend from Backbone. 
https://github.com/marionettejs/backbone.marionette/pull/2271#discussion_r24703299
I am not sure I fully understand the prototype issue here.  If we classify `Marionette.AbstractView` this isn't enough?

I do think this would complicate things like modifying `trigger` on `Backbone.Events`.  Sure we can make a `Marionette.Events` but it won't be mixed into things like Radio.  (not that radio benefits or would really be affected by `triggerMethod` type functionality)

It would prevent https://github.com/marionettejs/backbone.marionette/issues/2278

**Comment by ianmstew** [comment]
Shimming Backbone classes is uncomfortable for me.  I am not aware of any other case of shimming a core dependency for our purposes.  Adding undocumented features to anything `Backbone.*` is not expected and could possible interact with Backbone plugins in unexpected ways.  Backbone plugin authors are certainly under no contract to avoid conflicts with Metal.  I would prefer to only classify `Marionette.*`, including `Marionette.Model`, `Marionette.Collection`, etc, even if this means some compromises will make made (such as no `triggerMethod` for `Radio`).

I am also open to education on this if anyone believes my concerns to be short-sighted.

**Comment by paulfalgout** [comment]
So we should just make classify public so you could classify something if you need it.

```js
var MyBbView = Backbone.View.extend({ ... });
Marionette.classify(MyBbView);
var myBbView = new MyBbView();
Marionette.Class.isClass(myBbView); // => true
```

**Comment by samccone** [comment]
xpost

So I am -1 to modifying the bb prototype, the reason being that it simply does not scale.

Marionette works off of the idea that if you provide a view that adheres to the interface API that what we expect (see a backbone view or Mn View) you can just use it inside of Marionette and things "work". 
Thus making things interop with BB without any prototype shenanigans means things like ampersand's view and other view layers can be dropped into Mn and things just work. Without having to classify or metalify or whatever we want to call it.
