### ISSUE TITLE
Controllers usage message 

### ISSUE THREAD

**Issue by claughlin-r7** [marionettejs/backbone.marionette#2638]
In the docs the following is stated
>Warning: deprecated. The Controller object is deprecated. Instead of using the Controller
> class with the AppRouter, you should specify your callbacks on a plain Javascript object.

Should it be suggested to use a marionette object instead of/as well as a JavaScript object?

**Comment by samccone** [comment]
totally, @claughlin-r7 would you like to make a PR?
