### ISSUE TITLE
Remove `preventDestroy` option from region `show` and `empty`

### ISSUE THREAD

**Issue by ahumphreys87** [marionettejs/backbone.marionette#2640]
`preventDestroy` is a bad idea. It will create memory leaks everywhere!

Lets remove the option in 3.0 and encourage people to create and dispose of views correctly

**Comment by trezy** [comment]
:+1:

**Comment by samccone** [comment]
there are still many usecases for this feature, keep in mind people can have expensive views that take time to rerender. The initial goal for the flag was to let users know they were opting into a dangerous thing. Since we prevent this behavior by default, and plenty of  (power) users use the flag I am totally fine keeping this.

**Comment by bgaillard** [comment]
Hi, we use the `preventDestroy` option is several Cordova / Marionette applications. This is very useful when we need to agressively cache views on client side.

**Comment by trezy** [comment]
@samccone That's a good point. There are valid reasons for using `preventDestroy` but our implementation is super risky. We could at least do a few things to make it less dangerous such as maintaining a list of views to be GC'd and providing mechanisms for a lower level automatic GC plus or easier resurrection. If this doesn't make sense I can elaborate on it.

The point is that while preventDestroy may have valid use cases, I believe we could offer a less risky alternative that still meets those needs.

**Comment by paulfalgout** [comment]
I'd certainly like to explore alternatives.  Anecdotally it seems `preventDestroy` is very often used for poor or misguided reasons and it seems to complicate a lot of Mn development.

**Comment by ahumphreys87** [comment]
In my haste to remove, im now happy we havent - had a case where this was needed recently for modals.

I'm gonna vote we keep as an option with it defaulting to off

**Comment by paulfalgout** [comment]
Can you describe the use-case more?  I still think there's a potential to solve this a better way
