### ISSUE TITLE
Is there any merit to allowing users to set flag indicating tagName/className for view is inside template?

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2649]
I've see this question come up more than a few times. I have mixed feelings on it.

Users want to do something like:

    var MyView = Marionette.ItemView.extend({
        templateOnly: true,
        template: _.template('<span class="myView"></span>')
    });

which would be equiv. to:

    var MyView = Marionette.ItemView.extend({
        tagName: 'span',
        className: 'myView'
    });

I can't imagine this would be exceedingly difficult to do, but might be a slight perf. hit for the extra check when rendering, but it would allow all HTML to stay inside the template.

Thoughts?

**Comment by jridgewell** [comment]
We're having this conversation over in #2357.

**Comment by MeoMix** [comment]
Gotcha, ty.
