### ISSUE TITLE
buildChildView() is called for the empty view, prefer buildEmptyView() ? 

### ISSUE THREAD

**Issue by bgaillard** [marionettejs/backbone.marionette#2652]
Hi, we have collection views with both the `emptyView` option and the `buildChildView(child, ChildViewClass, childViewOptions)` method defined. 

With this it seems the `buildChildView()` method is called when an empty collection is passed to the collection view (i.e when the empty view has to be instantiated). 

Here is a code sample to illustrate that.
```javascript
var MyCollectionView = Marionette.CollectionView.extend(
    {
        childView : MyChildViewClass,
        emptyView : MyEmptyViewClass,
        buildChildView: function(child, ChildViewClass, childViewOptions) {

            var view = null;

            if(this.collection.isEmpty()) {

                // If we are here then it means the buildChildView() method is called for an Empty View
                view = ... ;

            } else {
               
                // If we are here then it means the buildChildView() method is called for a Child View
                view = ... ;

            }

            return view;

        }
    }
);
```

It seems the call to build the empty view is done here : https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L342.

I think this is very confusing, also when the method `buildChildView()` is called for an empty view its called with a "raw" Backbone.Model (https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L298) which is strange. 

For Marionette 3.X perhaps we should have 2 separate methods to clarify this ?
```javascript
buildChildView : function(child, ChildViewClass, childViewOptions) {
},
buildEmptyView : function(EmptyViewClass, emptyViewOptions) {
} 
```

What's your opinion about that ?

**Comment by samccone** [comment]
I think this makes sense, we could introduce this in 2.x @bgaillard interested in opening a PR?

**Comment by bgaillard** [comment]
Hi, I would be happy to do it but i'm curently in holidays for 2 weeks and i'll have a lot of work to do when i'll come back. So i will be able to work on this not before 3 or 4 weeks, don't know if it feets the 2.5 scheduled release date ? Thanks

**Comment by ahumphreys87** [comment]
I think this ties in with the deprecation of EmptyView, we are covering this over in #2560
