### ISSUE TITLE
Backbone.Wreqr reference with browserify

### ISSUE THREAD

**Issue by newtonianb** [marionettejs/backbone.marionette#2655]
It seems this problem has been mentioned twice before but I wanted to make sure I understood correctly.

I keep getting this error

    Uncaught TypeError: Cannot read property 'Commands' of undefined

With this code

    Backbone = require('../shims/backbone');
    
    module.exports = new Backbone.Wreqr.Commands;

This is my setup

**main.coffee** (browserify entry point)

    app = require('./app')
    Backbone = require('./shims/backbone')
    commands = require('./config/commands')

**shims/backbone**

    module.exports = Backbone

**shims/marionette**

    module.exports = Backbone.Marionette

**config/commands**

    Backbone = require('../shims/backbone')
    module.exports = new (Backbone.Wreqr.Commands)

As you can see from above I decided to not use browserify for the main dependencies so essentially I'm including them in the page globally but then using these custom shims above to include them in my app.

The problem I'm having is it seems Wreqr does not exist on the Backbone object. I guess that sort of makes sense as I saw in the source this is added with the Marionette library. 

https://github.com/marionettejs/backbone.marionette/issues/1297
https://github.com/marionettejs/backbone.marionette/pull/2075
https://github.com/marionettejs/backbone.marionette/issues/2074
http://stackoverflow.com/questions/31199485/backbone-object-does-not-have-wreqr-property

So is this the current method to use with require('backbone.wreqr'); ? Or should I somehow try to extract it from the Marionette.Backbone object?

**Comment by ahumphreys87** [comment]
@newtonianb this can sometimes happen if your app's BB dependency does not satisfy Marionettes BB dependendcy (or Wreqr) - what happens is Marionette will pull in its own BB dep and attach itself to that. Could you check your `node_modules/backbone.marionette/node_modules` directory and look to see if it has pulled down `backbone` - if it has this is most likely your problem

**Comment by newtonianb** [comment]
@ahumphreys87 thank you for your feedback. I don't have a node_modules folder under node_modules/backbone.marionette should i?

**Comment by paulfalgout** [comment]
This may also have been related to https://github.com/marionettejs/backbone.wreqr/issues/74

You would have a nested node_modules folder in npm2 but not npm3.  If you are using npm3 it may not be as forgiving.. I'm not certain.  Is this still an issue?   Regardless you should use `Backbone.Radio` and not Wreqr

**Comment by paulfalgout** [comment]
If there's still something here, let us know.
