### ISSUE TITLE
getChildViewContainer is not consistent

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#2656]
This method seems to be here to help us returning a different container depending on the model / child being processed, but it gets called 3 times with different arguments, making it impossible to use in certain condition

```javascript
    // You might need to override this if you've overridden attachHtml
    attachBuffer: function(compositeView, buffer) {
      var $container = this.getChildViewContainer(compositeView);
      $container.append(buffer);
    },
  
    // Internal method. Append a view to the end of the $el.
    // Overidden from CollectionView to ensure view is appended to
    // childViewContainer
    _insertAfter: function(childView) {
      var $container = this.getChildViewContainer(this, childView);
      $container.append(childView.el);
    },
  
    // Internal method. Append reordered childView'.
    // Overidden from CollectionView to ensure reordered views
    // are appended to childViewContainer
    _appendReorderedChildren: function(children) {
      var $container = this.getChildViewContainer(this);
      $container.append(children);
    },
  
```

**Comment by ianmstew** [comment]
Interesting.  It doesn't appear the second argument is even used, so the _insertAfter case could be trimmed by one argument.

https://github.com/marionettejs/backbone.marionette/blob/23658edab4f4eafb1f9871e5d392b1775f68b9e2/src/composite-view.js#L147-L177

**Comment by JSteunou** [comment]
It is very used ! Not by Marionette, but by user who can override `getChildViewContainer` and return different container depending on the childView.

It was added for this purpose the first time.

**Comment by ianmstew** [comment]
I totally missed that--it looks like that second argument would have to support a list of childViews rather than a single childView to catch all cases.

**Comment by JSteunou** [comment]
This is `CompositeView` stuff related. I understand the focus is on v3 right now so if this not gonna be an issue in v3 this can be closed.
