### ISSUE TITLE
Bulk/batch updating of views when models are added/removed from collection view in bulk

### ISSUE THREAD

**Issue by RealAdamSinger** [marionettejs/backbone.marionette#2660]
Currently adding x models to a collection view causes x browser repaints even if the models are added all at once, this causes many unnecessary repaints.
I may be generalizing but this means if you add 1000 models to an existing collection view, the dom gets repainted 1000 times even though all the information was provided to have done in 1 (like how reset works)

This causes performance issues especially noticeable in long lists or during animations.

This could be fixed by batch loading the HTML into some type of string, array or detached DOM nodes and then inserting the views into the page all at once.

With backbone's addition of the "update" event, I believe solving this problem is not too difficult but I am unsure of how to make it backwards compatible with older versions.

Thoughts?

**Comment by ahumphreys87** [comment]
@RealAdamSinger we use a `DocumentFragment` for this very reason on initial render. @jmeas didn't you do some investigation on this not long ago?

Use of the `update` event may come in for v3 - we are talking about bumping the BB dependency.

**Comment by ianmstew** [comment]
I think this would be great to roll into #2723.

**Comment by ahumphreys87** [comment]
@RealAdamSinger we are investigating this over in #2979 and have an open PR #3113. This will likely make it into v3.1
