### ISSUE TITLE
isEmpty in collectionView is no longer useful as public method since 2.4.0...

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#2661]
... because of a call on `children.isEmpty`

We could override `isEmpty` because it's public, and provide another logic then the simple `this.collection && this.collection.length` but this logic of ours get squashed by a new incomer from 2.4.0

https://github.com/marionettejs/backbone.marionette/blob/v2.4.0/src/collection-view.js#L209

The use case is: overriding `isEmpty` to return false in some cases we dont want the empty view even if the view is empty for real. With the new LoC `isEmpty` is called a second time, but on `children` this time, which is not overridden, and BOUM, the empty view is shown whereas it should not.

**Comment by jridgewell** [comment]
https://github.com/marionettejs/backbone.marionette/pull/2641

**Comment by JSteunou** [comment]
Nice catch, could fix this. But I'm still wondering the real utility of this line, and if there was not a better way to achieve what it does.

**Comment by jridgewell** [comment]
> But I'm still wondering the real utility of this line, and if there was not a better way to achieve what it does.

[I agree](https://github.com/marionettejs/backbone.marionette/pull/2641#issuecomment-119308566).

**Comment by JSteunou** [comment]
Should the `isEmpty` check on `children` is a filter is set, and if not, fall-back on `collection && collection.length`

**Comment by ianmstew** [comment]
Fixed by manual merge, see https://github.com/marionettejs/backbone.marionette/pull/2641#issuecomment-130507335.

For future reference, the current solution is a nonbreaking stopgap.  The more comprehensive solution is already in next for 3.0: https://github.com/marionettejs/backbone.marionette/blob/2af55e5020da9d74c043bd5c121e1f95c45457d9/src/collection-view.js#L277-L285
