### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2663]
we should improve this doc:
[contributing.md](https://github.com/marionettejs/backbone.marionette/blob/master/CONTRIBUTING.md)

#### should have a table of contents
we've got lots of material but it's hard to follow. it'd be better if there were a TOC on the top so that we could see all the material.

#### should have the steps for getting started:

```
1. go to the project
2. git clone the repo
3. install libraries
4. run tests
5. create a branch
6. make a change
7. run tests
8. create a commit
9. fork marionette
10. push branch to remote
11. make a pull request on project
```

the eslint people have some good content too:
http://eslint.org/docs/developer-guide/contributing.html#pull-requests

**Comment by jasonLaster** [comment]
We should add this dude to the contributing docs.


```
<img style="position:center" src="https://www.dropbox.com/s/wj68so87r1aofdh/marionette%20construction%20worker.jpg?dl=0" width="128" height="128"></img>
```

the html is helpful in markdown docs for centering images :)

![](https://www.dropbox.com/s/wj68so87r1aofdh/marionette%20construction%20worker.jpg?dl=1)

**Comment by megawac** [comment]
It better be a gif

**Comment by jasonLaster** [comment]
lol - the dude or the cat?

**Comment by paulfalgout** [comment]
@jasonLaster is this closed, or is it open for the image?

**Comment by paulfalgout** [comment]
Cleaning out old issues.  We can reopen if need be.
