### ISSUE TITLE
triggerMethod bubble fail?

### ISSUE THREAD

**Issue by lococo--0** [marionettejs/backbone.marionette#2667]
the are two cases: 

1) layoutView -> region -> collectionView -> layoutView -> itemView
2) layoutView -> region -> collectionView -> itemView

in the first case, i triggerMethod in the itemView, i can't catch the event in the first layoutView.
in the second case, i do the same thing, the layoutView catch the event

it seemed that layoutView can not bubble the event to the parent view.
is that right?

i also want to know is there a method to stop the event bubble? something like:

``` javascript
tirggerMethod('event', {bubbleOne: true})
```

sometime i just want the parent view catch the event, other than the parent parent view can also catch the event.

**Comment by ahumphreys87** [comment]
@ianmstew is this related to your `childEvent` PR's on `CollectionView`?

@lococo--0 for a bit of background there is some work ongoing to clean up the API and differences between childView in `CollectionView` and a `childView` in a region/`LayoutView`. The PR to fix this may have already landed in the `next` branch actually

**Comment by ianmstew** [comment]
@lococo--0 Marionette doesn't bubble view events--you have to do that yourself.  In Marionette today (until #2404) you have to perform bubbling like so:

**Grandparent View**
```js
childEvents: {
  'show:modal': function () { console.log('Show the modal!'); }
}
```

**Parent View**
```js
childEvents: {
  'show:modal': function () { this.triggerMethod('show:modal'); }
}
```

**Child View**
```js
this.triggerMethod('show:modal');
```

Take care to use only `triggerMethod`, as support for `childEvents` and `trigger` is pending (#2464).  Like @ahumphreys87 said, the work coming down the pipe will make bubbling events yourself a little smoother.

**Comment by lococo--0** [comment]
@ianmstew 
but in my second case, the parent view is a collection view, I have a listener in the grandparent view like:

``` javascript
childEvents: {
  'do:stuff': 'doStuff'
}
``` 

in my child view, I trigger the `do:stuff`
``` javascript
this.triggerMethod('do:stuff');
```

I do nothing in the parent collection view, it means i do nothing to bubble the `do:stuff` event, but in my grandparent view the `doStuff` function has been invoked.

**Comment by ianmstew** [comment]
Huh!  I was able to reproduce myself: https://jsbin.com/dizebolala/1/edit?html,js,console,output.

It appears that when a child view of a CollectionView triggers an event, it is catchable by _both_ the CollectionView and first ancestor LayoutView's `childEvents` hash.  After some investigating, I found that when a child view of a CollectionView fires an event it takes two paths--[one path](https://github.com/marionettejs/backbone.marionette/blob/23658edab4f4eafb1f9871e5d392b1775f68b9e2/src/collection-view.js#L658-L660) to the CollectionView parent as you would expect, and [another path](https://github.com/marionettejs/backbone.marionette/blob/23658edab4f4eafb1f9871e5d392b1775f68b9e2/src/view.js#L307-L309) to the [first ancestor that is a LayoutView](https://github.com/marionettejs/backbone.marionette/blob/23658edab4f4eafb1f9871e5d392b1775f68b9e2/src/view.js#L345-L350).

I doubt this is expected; i.e., this event bubbling you found isn't a feature, it's probably a bug.    :open_mouth:  The parent bubbling is supposed to stop at the first parent.  @paulfalgout @jasonLaster

**Comment by passa763** [comment]
+1 this would be a great feature.

**Comment by paulfalgout** [comment]
@ianmstew this is fixed for `v3` right?

**Comment by paulfalgout** [comment]
not fixed:  https://jsbin.com/xareforulo/edit?html,js,console,output
