### ISSUE TITLE
Use of deprecated $.selector does not work with Zepto

### ISSUE THREAD

**Issue by PhilippMi** [marionettejs/backbone.marionette#2668]
[Region.reset()](https://github.com/marionettejs/backbone.marionette/blob/master/src/region.js#L272) uses [$.selector](https://api.jquery.com/selector/) which was deprecated in jQuery 1.7. 

Furthermore, Zepto returns an Array instead of a String when this.$el.selector is invoked. Hence, Region.reset() does not work with Zepto.

I made a little fiddle illustrating the issue:
Zepto-Version: http://jsfiddle.net/PhilippMi/vzoo95so/
jQuery-Version: http://jsfiddle.net/PhilippMi/vzoo95so/5/

IMHO this issue is closely related to #1379, though it provides a different view on the problem.

**Comment by paulfalgout** [comment]
Also see https://github.com/marionettejs/backbone.marionette/issues/1852

**Comment by JSteunou** [comment]
One left https://github.com/marionettejs/backbone.marionette/blob/next/src/region.js#L197

**Comment by JSteunou** [comment]
Or maybe another, I cannot see what's `definition` https://github.com/marionettejs/backbone.marionette/blob/next/src/mixins/regions.js#L92

**Comment by paulfalgout** [comment]
Yeah.. hmm the one in the error.. I suppose the error could also attempt to display the initEl if it's a string.. 
The second one is ok.  it is just bad naming and not related to $.selector.  I believe the use of selector here will be deprecated for removal in v4 as you should simply use "el"  For most people just using a region on a view without customization, they won't see this anyways.

**Comment by JSteunou** [comment]
Should be ok now, #2906 was the only one I found
