### ISSUE TITLE
Should the events hash be responding to jQuery's triggerHandler method?

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2669]
Hey,

I'm working with some legacy code at the office and this plugin we use seems to use `triggerHandler` rather than `trigger` for firing events. I don't have a ton of XP with `triggerHandler`, so maybe this functionality makes sense, but I was really confused with unexpected results from the following:

	var TestView = Marionette.ItemView.extend({
	  template: _.template('<div class="foo"></div>'),
	  ui: {
		foo: '.foo'
	  },
	  events: {
		'custom.event @ui.foo': function(){
		  console.log('custom.event ran');
		}
	  },
	  onRender:function(){
		this.ui.foo.on('custom.event', function(){
		  console.log('custom.event is in here');
		})
	  }
	})

	var testView = new TestView();
	testView.render();
	jQuery.event.trigger('custom.event', null, testView.ui.foo[0], true);

In this example only the the event handler bound in onRender fires, but I thought "on" and "events" were bound identically.

Is this expected behavior? If so, could someone explain why it is expected behavior?

**Comment by paulfalgout** [comment]
I expect the issue here is that DOM events are all attached to the `el`.  And `triggerHandler` very specifically only triggers on the exact elements with no propagation.  That's a bit of an guess though.  However this might be a good issue to open on backbone.  If there is a fix it'll most likely need to occur there.

**Comment by ianmstew** [comment]
Closing for now, please continue the convo if there are more developments.

**Comment by MeoMix** [comment]
Sure. I asked it on BB: https://github.com/jashkenas/backbone/issues/3761 thanks for the reminder.
