### ISSUE TITLE
Why region invoke view's render method every time it shows it？

### ISSUE THREAD

**Issue by anianj** [marionettejs/backbone.marionette#2673]
It seems that the region should only invoke view's render only when the view has not been rendered.
How do you say?

**Comment by lococo--0** [comment]
the region's show will destroy the view that has already been showed in the region. and render the new one. it should invoke the render every time.

**Comment by ahumphreys87** [comment]
yeah this is desired behavior. Views are intended to be destroyed and recreated rather than reused. We made a decision to encourage this in v2 by renaming `view.close` to `view.destroy`.
