### ISSUE TITLE
Wouldn't it be wonderful if triggers would also pass original event down?

### ISSUE THREAD

**Issue by nezaidu** [marionettejs/backbone.marionette#2677]
Now you're passing only this:
```javascript
        var args = {
          view: this,
          model: this.model,
          collection: this.collection
        };
```
Example: i have collection view that listens to its children to open modal window to play video, but since i can't have access to original event, i can't get video id to find it in model to get link to it.

**Comment by cvisco** [comment]
Agreed. I was just about to file this same issue. Looking at the `View#_buildViewTrigger` source, it seems like it would be trivial to do this.

**Comment by ahumphreys87** [comment]
I think this would be nice, I have come across this myself. @nezaidu @cvisco would either of you be interested in submitting a PR for this?

**Comment by cvisco** [comment]
@ahumphreys87: sure I can take a look at this.

**Comment by cvisco** [comment]
I went with "originalEvent" as the argument property in the PR. "event" seemed like it might be confusing. "domEvent" was another option. If anyone has strong opinions i'm happy to change it.

**Comment by paulfalgout** [comment]
XRef: https://github.com/marionettejs/backbone.marionette/pull/2690#issuecomment-136871570
