### ISSUE TITLE
Deprecate region.reset and remove in v3

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2680]
Because https://github.com/marionettejs/backbone.marionette/issues/2668 and https://github.com/marionettejs/backbone.marionette/issues/1852

**Comment by paulfalgout** [comment]
https://github.com/jquery/jquery/commit/0ea8c32863af31fb5cfc184e8d513bbae35583e8

@marionettejs/marionette-core I hate adding one more thing, but if we want to support jQuery v3 in a month we need to remove or rebuild reset

**Comment by paulfalgout** [comment]
Is fixing reset as easy as just caching the el from the constructor on `._el` and then running getEl again on it?

**Comment by ahumphreys87** [comment]
fixed with #2869
