### ISSUE TITLE
Adding multiple models re-renders CollectionView

### ISSUE THREAD

**Issue by RickHolmes** [marionettejs/backbone.marionette#2681]
This might be deliberate, but if you add more than one model at a time to a CollectionView's collection, the entire CollectionView will re-render. This will happen if you add a model or let Backbone create one by adding json. Adding a single model works as expected.

This affected me when lazy loading items four at a time on scroll. While it does make any new images all load at the same time, it's not really too efficient, especially when there may over 30 ItemViews, each with multiple DOM elements and an image.

If this is deliberate, perhaps it should be documented.

**Comment by ahumphreys87** [comment]
@RickHolmes could you provide a simple fiddle showing your problem? Were you sorting the collection?

I don't think this functionality is deliberate but I don't think I have seen this behavior before so a fiddle would be a great help for us to try and debug

**Comment by JSteunou** [comment]
Mn should listen to "update" event, but this event is BB >= 1.2

**Comment by RickHolmes** [comment]
Yes, it turns out that the collection was being sorted, even though the comparator is an auto incremented "index" which doesn't fire a sort event in a simpler example. I added a "silent-update": true option, but that didn't seem to do the trick in this case.

So, please close and ignore this issue. My fault, not Marionette's.
