### ISSUE TITLE
childEvent no use in Behavior

### ISSUE THREAD

**Issue by lococo--0** [marionettejs/backbone.marionette#2683]
there are events, modelEvents, collectionEvents in Behavior, but childEvent no use ! no use ! no use !

**Comment by ambischof** [comment]
See this issue https://github.com/marionettejs/backbone.marionette/issues/2235

**Comment by paulfalgout** [comment]
@ambischof good xref.  Thanks!

**Comment by lococo--0** [comment]
Does it means `onChildviewDoStuff` is useful in all behavior? 

But it seems that `onChildviewDoStuff` in my LayoutView can be invoked, no work in the behavior of the LayoutView.

**Comment by ambischof** [comment]
I found that too, so in my behavior instead of `this.triggerMethod('foo')`, I did `this.view.triggerMethod('foo')` and it worked. 

If anyone can explain this to me, it'd be great, since it wasn't immediately obvious from reading the source code.

**Comment by lococo--0** [comment]
@ambischof the behavior not a view, you can just `triggerMethod` in the view not in the behavior.
