### ISSUE TITLE
CollectionView length collection has not correct

### ISSUE THREAD

**Issue by z0091** [marionettejs/backbone.marionette#2684]
HI!!

After filling out the data collection, the length of the template (<% = length%>) is not the correct value.
But if I replace the function serializeData, everything works.

```javascript
serializeData: function() { 
     return this.collection; 
}
```
Thanks!

**Comment by ahumphreys87** [comment]
hi @z0091 could you provide a simple jsfiddle that illustrates your problem?

**Comment by ianmstew** [comment]
Hey @z0091, if you're trying to render a collection in a simple ItemView, check out a lesser-known feature of ItemViews: http://marionettejs.com/docs/marionette.itemview.html#rendering-a-collection-in-an-itemview.  Here's an example: https://jsbin.com/barovevene/edit?html,js,console,output.

If you're trying to add collection length to the template of a CompositeView, then you would want to do
```js
serializeData: function() {
  var data = Marionette.CompositeView.prototype.serializeData.apply(this, arguments);
  data.collectionLength = this.collection.size();
  return data;
}
```

**Comment by paulfalgout** [comment]
Closing for now.  If this is still an issue, please provide a fiddle or some additional example code of the problem.
