### ISSUE TITLE
Controller and Object are pretty similar

### ISSUE THREAD

**Issue by mindrones** [marionettejs/backbone.marionette#2685]
Hi,

while reading the source code I've noticed that `Controller` and `Object` are pretty similar

![backbone_marionette_object_controller_similar_code](https://cloud.githubusercontent.com/assets/1309648/8983129/e036027a-36c7-11e5-8eb4-899f812ba67d.png)

Is there any specific reason for that?

Why not merge the `Controller` in the `Object`?

By looking at this portion of a *preliminary* / *draft* / *incomplete* Marionette's "class" diagram, the only class depending on the `Controller` would be the `RegionManager` and both `Controller` and `Object` extend from `Backbone.Events`:

![backbone_marionette_object_controller_similar_uml](https://cloud.githubusercontent.com/assets/1309648/8983130/e036c868-36c7-11e5-8979-41a7b074bce5.png)

**Comment by paulfalgout** [comment]
Controller wasn't a great name, but is deprecated and scheduled for removal in v3.

**Comment by mindrones** [comment]
Thanks @paulfalgout.
BTW when is v3 scheduled? I keep reading about deprecation but I can't find a roadmap :/

Also, reading a lot of deprecation warnings in docs sends a message of uncertainty and makes you feel like the lib is not well maintained or designed. Is there any sort of design document around? Maybe I help with docs?

**Comment by ahumphreys87** [comment]
@mindrones there will be quite a bit of deprecation in v3 but we are looking at some nice new features as well. We will of course be doing our best to ensure the upgrade process is as smooth as it was for v1 => v2.

We introduced `Object` in v2 to replace `Controller`, however did not want to completely remove it until the next major release as it obviously a change that could break some applications.

We are always looking for contributors willing to help out and docs/guides are a great way to get involved. @jdaudier is looking at getting some useful guides together.

**Comment by mindrones** [comment]
@ahumphreys87 it would be nice to have things documented using jsdoc, even right now as it helps documenting deprecated stuff, etc. I know that [annotated source](http://marionettejs.com/annotated-src/backbone.marionette.html) is built upon current comments but I think we might get to the same result using jsdoc as well.

**Comment by ahumphreys87** [comment]
@mindrones this is something we have actually started to implement: https://github.com/marionettejs/backbone.marionette/tree/master/api

If you are offering assistance in this area that would be awesome, more than awesome in fact :)

**Comment by mindrones** [comment]
@ahumphreys87 nice! I'll have a look at that. Meanwhile do you have any link to a roadmap or proposals to follow a bit the transition? Thanks!

**Comment by mindrones** [comment]
The only downside of separating jsdoc from the code is that editors won't be able to benefit from it.

![marionette_jsdoc_annotations](https://cloud.githubusercontent.com/assets/1309648/9085544/10f67e52-3b7e-11e5-8f98-895af3359702.png)
