### ISSUE TITLE
Support template-less CompositeView

### ISSUE THREAD

**Issue by blikblum** [marionettejs/backbone.marionette#2688]
Just as ItemView that you can set `template:false`: http://marionettejs.com/docs/v2.4.2/marionette.itemview.html#template-less-itemview

Trying to use `template:false` with CompositeView i get message TemplateNotFoundError: Cannot render the template since its false, null or undefined.

Using version 2.4.2

**Comment by frankcortes** [comment]
As far as I know, you can create a CompositeView without template, but this view [cannot be rendered.](http://marionettejs.com/annotated-src/backbone.marionette.html#section-211)

**Comment by frankcortes** [comment]
I cannot think a real case where you could need a compositeView without template! Could you add an example, @blikblum ?

**Comment by blikblum** [comment]
I hit this issue doing http://codepen.io/blikblum/pen/XbydRE . I added meancalc-tpl just because CompositeView can not be template less. I'm starting with marionette, so no examples from bigger apps.

Should be considered also for consistency. I see CompositeView as a sort of specialized LayoutView, and the later allows to be template less. In fact, i took as granted that would work when i tried to use this feature.

**Comment by ahumphreys87** [comment]
@blikblum I think #2565 would solve this issue. Also note that as of v2.5/v3 you will be able to create CompositeView functionality with a LayoutView - CompositeView is a candidate for removal in v3 as it's usefulness will disappear once #2625 lands
