### ISSUE TITLE
underdash/Lodash v4 support

### ISSUE THREAD

**Issue by megawac** [marionettejs/backbone.marionette#2689]
There are some major changes taking place in lodash v4/underdash.

First of I'd like to suggest that v3 update its backbone and underscore dependencies to something like `>= 1.1.2` and either `>= 1.6` or `>= 1.8`, respectively (which would have other advantages besides making it less of a pain to support cross version compatibility). Next, we if we want to be future compatible with lodash v4 (should be coming soon) and underdash there are some refactoring to be done. Below is a non exhaustive list of changes (feel free to edit this issue directly):

- [ ] Remove any uses of alias methods
- [ ] drop all uses of context binding (`_.each(items, function, context)` be replaced with `_.each(items, _.bind(function, context))` For this one in particular, I think using babel for arrow functions would be a great win
- [ ] Try to use only core functions (see underdash)

I haven't gone over the codebase for specifics, this list is only from memory. For specific changes see https://github.com/lodash/lodash/wiki/Roadmap

**Comment by megawac** [comment]
This may be a good reason to reopen/fork https://github.com/marionettejs/backbone.marionette/pull/2440

**Comment by paulfalgout** [comment]
I'd be :+1: for updating the Bb and _ dependencies.  I'm not sure if there's any strong feelings against that for v3?  `1.1.2` and `1.6.0` are pretty old now, but I'm sure widely used..  I'd doubt that anyone pre-that would be upgrading to Mn v3.  But we should do it particularly if that opens the path easier for future proofing and less maintenance headaches.

Everything else though seems doable and non-breaking outside of a major release?  I'm just nervous about anything else holding up v3.

**Comment by jasonLaster** [comment]
Thanks @megawac. I think we should feel safe upgrading in a major release. I agree with Paul with respect to starting another Major project right now. If a PR was opened that did the upgrade and the tests passed I'd merge, or if there was a way to do a small breaking PR and then do incremental non-breaking improvements that would be fine.

This might be one of the rare cases where an AST search could help: http://www.graspjs.com/ identify how much work there is

**Comment by ahumphreys87** [comment]
yup im pro for doing this as well

**Comment by anthony-redFox** [comment]
Hello, I try create report using underscore/lodash in MarionetteJs (only folder src).
https://docs.google.com/spreadsheets/d/1auq_MbgMFqbhx7u__ky4XhnU_j_Z16LEdQCzVThQAp0/edit?usp=sharing

In core Underdash
_.invert
_.keys
_.each
_.extend
_.invoke
_.bind
_.find
_.rest
_.reduce
_.defaults
_.values
_.partial
_.chain
_.filter
_.flatten
_.map
_.pick

Not in core Underdash
_.isFunction
_.result
_.bindAll
_.isObject
_.isString
_.indexOf
_.isUndefined
_.union
_.toArray
_.clone
_.drop
_.omit
_.template
_.identity
_.isArray

**Comment by megawac** [comment]
Fantastic stuff, thanks @anthony-redFox. Though some of the ones you mentioned are in core underdash (see https://github.com/underdash/underdash/issues/4#issuecomment-123401192)

So from the list you provided:
```diff
+ _.isFunction
+ _.result
+ _.isObject
+ _.isString
+ _.indexOf
+ _.toArray
+ _.clone
+ _.identity
+ _.isArray
```

Leaving

```_.isUndefined
_.bindAll
_.union
_.drop
_.omit
_.template
```

**Comment by jasonLaster** [comment]
just geeked out on this https://docs.google.com/spreadsheets/d/1ZCUAczEE-FuLf41ColFAk6pvBhsD1ZjdwU8_qvblgqA/edit#gid=0

@anthony-redFox - feel free to make yours the official
I added custom formats, sorted by files with the most _ usage, and made it editable

**Comment by jasonLaster** [comment]
@megawac - mind commenting in the spreadsheet, what we need to do for each function?

**Comment by megawac** [comment]
So the ones that will be most annoying to work around for `core` support are `template` and `union`.

@jdalton why are `omit` and `drop` not included as they are simple derivatives of other functions included?

**Comment by jdalton** [comment]
I wouldn't worry about `core` support. It's intended for devs who make snap judgements about a lib based solely on file size without the technical chops to crasp modules or build systems. These folks are probably the copy/paste style devs who like to make a bunch of noise on social media but have little impact elsewhere.

**Comment by jdalton** [comment]
#realtalk

**Comment by jdalton** [comment]
For the `core` build the choice of why one method over another literally comes down to what has the least deps and can fit into a 4kb build. Methods like `omit` have deps which inflate the build size so it comes down to having `omit` or having 3 other smaller methods.

**Comment by jdalton** [comment]
That said, I've been able to squeeze in a few more methods (up to 62 now). So if there's one you'd dig let me know and I'll shift some stuff around.

I've added `_.slice` which is a dep of `_.drop` so I could see fitting that in.
The `_.union` method would require `_.uniq` so that's a bit trickier and `_.template` is rather large.
I could see `_.template` being a popular request so I could see dropping some methods to fit it in.

**Comment by megawac** [comment]
Nah, I wouldn't worry about template in core. I mentioned omit and drop as all their deps were already included in core

**Comment by jdalton** [comment]
The main knock against `_.omit` is it would require a reduced `difference` method which then leaks in to the other related methods.

**Comment by paulfalgout** [comment]
While it is understandable: `_.omit(_, 'omit') === 'sadness'`
