### ISSUE TITLE
rendering only childviews within a composite view

### ISSUE THREAD

**Issue by kp25** [marionettejs/backbone.marionette#2695]
I'm using composite view to render a table, with some filter like options on top of the table. I'm wrapping the table rows (collection) with table header and filter options. On applying the filter option i don't want the entire table to be re-rendered, i just want the collection, childviews to be re-rendered, so that template wrapping the collection could be rendered only once at the begining. 
Is there any way to do that like rendering only childviews within a composite view.? I'm looking for something like 
```javascript
//childView: xyz
childView.render(); // renders the childView 
```

**Comment by jmeas** [comment]
:+1:

There should be a public method, say, `renderChildren()`, that does just this.

**Comment by ianmstew** [comment]
Without a CompositeView at all in 3.0 (#2268), I don't see a need to separate `render()` and `renderChildren()` or maintain separate events (#1309).
