### ISSUE TITLE
Why dont we use "marionette" in the AMD definition?

### ISSUE THREAD

**Issue by coulix** [marionettejs/backbone.marionette#2701]
define(['backbone', 'underscore', 'backbone.wreqr', 'backbone.babysitter'], function(Backbone, _) {

should be

    define('marionette', ['backbone', 'underscore', 'backbone.wreqr', 'backbone.babysitter'], function(Backbone, _) {

https://github.com/marionettejs/backbone.marionette/blob/d182dc3f09b13a2603c142029d45994e1455105c/src/build/core.js#L4

This behavior breaks the use of almond.js (require.js for optimized build).

**Comment by coulix** [comment]
Ok Backbone does, the same. If I want to use almond with Marionette I guess I will need to fork both.

https://github.com/jashkenas/backbone/issues/3151

**Comment by ianmstew** [comment]
@coulix You don't need to fork the repos, just provide an alias to `marionette` within your require config.  Here's my app's abbreviated config:

```js
require.config({

  catchError: {
    define: true
  },

  // mustache template extension (compiled by requirejs-hogan)
  hgn: {
    templateExtension: '.html'
  },

  paths: {
    'jquery':                  '../assets/vendor/jquery/jquery',
    'underscore':              '../assets/vendor/underscore/underscore',
    'backbone':                '../assets/vendor/backbone/backbone',
    'marionette':              '../assets/vendor/backbone.marionette/backbone.marionette',
  }
});
```
