### ISSUE TITLE
Consider merging CV#setFilter algo into #reorder

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2703]
_Exploratory_

If there's another way to set a filter (https://github.com/marionettejs/backbone.marionette/pull/2592#issuecomment-130510012), then perhaps we could have setFilter function without the API footprint by merging the diff algorithm into `reorder()` (#2596) and doing something like:
```js
view.filter = filterMethod;
view.reorder();
```
The merge may not be trivial, but it could be worth taking a look.  Thanks @jmeas.

**Comment by ianmstew** [comment]
@Seebiscuit, interested?  The idea is hopefully to make `reorder()` a smart `render()` method that accounts for both sorting and filtering.

**Comment by Seebiscuit** [comment]
Sorry, haven't check my notifications in a few days. Let me get my head back into this, hopefully tonight and give a decent response.

**Comment by ahumphreys87** [comment]
closing in favour of #2723
