### ISSUE TITLE
Router navigate not working on webpack dev server.

### ISSUE THREAD

**Issue by subpublic** [marionettejs/backbone.marionette#2713]
Hello!

I'm running a backbone/marionette app on a webpack dev server (https://github.com/webpack/webpack-dev-server). My problem is that
```javascript
router.navigate('/hello', {trigger: true});
```
doesn't change the url. Nothing happens. No error either.

When running the same code on a gulp express connect server, it works fine. Both on localhost:8080.
A friend of mine had the same problem. Really strange.

My settings are
```javascript
devServer: {
      contentBase: ".",
      historyApiFallback: true,
      inline: true,
      watch: true,
      hot: true
    }
```
Anybody else with the same problem?

**Comment by subpublic** [comment]
Rolling back backbone 1.2.2 to 1.2.1 solved the problem, so it must have sneaked in after that!

**Comment by paulfalgout** [comment]
@jridgewell ?  Possible Backbone regression?

**Comment by jridgewell** [comment]
RE: https://github.com/jashkenas/backbone/issues/3773

**Comment by paulfalgout** [comment]
Thanks.  @subpublic is your `router` instance a `Marionette.AppRouter`?

**Comment by subpublic** [comment]
Yep! It's an Marionette.AppRouter.
I see now that my Marionette version (2.4.2) is depending on backbone 1.2.1, so maybe that's the reason?

**Comment by jasonLaster** [comment]
I believe so. Closing, but re-open if that doesn't fix it
