### ISSUE TITLE
Loss of code coverage for 2.4.3

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2714]
https://github.com/marionettejs/backbone.marionette/commit/9070bad2940564e7a975e4b0310d25768d986fea

and

https://github.com/marionettejs/backbone.marionette/commit/454d2cbdd37e4c3f27abd3f655b9cbf84f04ea27

have taken code coverage below 100%

**Comment by jasonLaster** [comment]
oy. I wonder how we lost code coverage?

**Comment by paulfalgout** [comment]
this line isn't tested:
https://github.com/marionettejs/backbone.marionette/commit/454d2cbdd37e4c3f27abd3f655b9cbf84f04ea27#diff-b8da5292cb07ec757ac64e78ff5af5c1R255

I looked through old PR merges on coveralls to determine which merges caused issues,
But looking at the coverage report of what is currently on patch, it looks like this line is the only non-tested line.

**Comment by jasonLaster** [comment]
not so bad

**Comment by ianmstew** [comment]
Sorry for the multiple commits--first commit had an unnecessary whitespace change and lint errors.  I'll just run a PR next time, since it's the appropriate sandbox for anything code (non-docs).

**Comment by ianmstew** [comment]
Okay, this needs a real PR.

**Comment by paulfalgout** [comment]
A note:  I had to blow away my node modules dir to get https://github.com/marionettejs/backbone.marionette/commit/9070bad2940564e7a975e4b0310d25768d986fea to fail on coverage.  But apparently `index` is never falsey on line 105

**Comment by ianmstew** [comment]
Fixed by #2724
