### ISSUE TITLE
Marionette.Object.cid ?

### ISSUE THREAD

**Issue by pascalpp** [marionettejs/backbone.marionette#2717]
I would like to add a .cid to the Marionette.Object constructor, for parity with other BB-derived objects. 

For instance, we use the cid as a .scope for jquery event listeners so we can remove them onDestroy.

Should I submit a PR for this change?

**Comment by pascalpp** [comment]
This change would basically just be:

```
  // A Base Class that other Classes should descend from.
  // Object borrows many conventions and utilities from Backbone.
  Marionette.Object = function(options) {
    this.options = _.extend({}, _.result(this, 'options'), options);

+   this.cid = _.uniqueId('object');

    this.initialize.apply(this, arguments);
  };
```

Other objects which extend from Marionette.Object which would be affected by this change:

- Marionette.Region
- Marionette.Behavior
- Marionette.Application

Should those all use their own cid prefix, or would it be acceptable for them to all use 'object' as their cid prefix?

**Comment by paulfalgout** [comment]
This change is coming in the next version which is priority after the next patch release which could be any day now.

https://github.com/marionettejs/backbone.marionette/pull/2524

**Comment by pascalpp** [comment]
:+1:

**Comment by paulfalgout** [comment]
:-) This is a good issue.  Going to help with making the inspector more useful.
