### ISSUE TITLE
Marionette.View#ui does not work with hyphenated names

### ISSUE THREAD

**Issue by jaapz** [marionettejs/backbone.marionette#2718]
The following ui hash will not work:

```javascript
ui: {
    'some-name': '.some-class'
}
```

The hyphen makes it break, silently.

If this is intended behaviour, please put a note in the documentation that hyphenated strings do not work in the UI hash, or have the view constructor throw an Error when this happens, so it does at least not fail silently.

**Comment by jeffijoe** [comment]
It works if you access it through `this.ui['some-name']` - that's a JavaScript thing, not just Marionette-specific..

**Comment by jasonLaster** [comment]
yea, @jeffijoe maybe update the docs?

**Comment by jeffijoe** [comment]
@jasonLaster not sure exactly why, as this is a JavaScript thing?

**Comment by stackptr** [comment]
It's a JavaScript thing because the `-` character will trip up the interpreter reading the code, mistaking it as an operator instead of part of the property name. Hence the different syntax to access the UI element: `this.ui['element-with-hyphen']` versus `this.ui.elementWithoutHyphen`

**Comment by jeffijoe** [comment]
@stackptr Right, which is why I don't think this info belongs in Marionette docs.

**Comment by stackptr** [comment]
oh my bad I thought the question was "why is it a JavaScript thing"!

Agreed it's not necessarily Marionette related but it might be easy to fall into this trap and a friendly reminder wouldn't be hard to give

**Comment by paulfalgout** [comment]
I'm going to agree that this does not need to be documented.  It would need to be nearly everywhere.
This true for anything attached to an object.
```js
var MyView = Marionette.ItemView.extend({
  'some-function': function(){ 
    console.log('hello'); 
  }
});

var myView = new MyView();

myView['some-function'](); // logs "hello"

myView.some-function() // throws "Uncaught SyntaxError: Unexpected token }"
```

**Comment by scottbedard** [comment]
@jeffijoe @paulfalgout I agree that the Marionette docs shouldn't double as basic Javascript docs. But I disagree that this situation shouldn't be mentioned. With the square bracket syntax you're able to access the ui elements from your view, but binding events is where I found some unexpected behavior. For example, the following won't hit `doStuff` when `.some-thing` is clicked. I believe this is caused by the way Marionette [normalizes ui strings](https://github.com/marionettejs/backbone.marionette/blob/master/src/helpers.js#L76). A mention in the docs about this gotcha would have been helpful.

```js
var MyView = Marionette.ItemView.extend({
    ui: {
        'some-thing': '.some-thing',
    },
    events: {
        'click @ui.some-thing': 'doStuff',
    },
});

**Comment by paulfalgout** [comment]
perhaps that regex just needs to account for dashes 
```diff
-   return uiString.replace(/@ui\.[a-zA-Z_$0-9]*/g, function(r) {
+   return uiString.replace(/@ui\.[a-zA-Z-_$0-9]*/g, function(r) {
```
- https://regex101.com/r/cF7aK2/1 regex without the dash
+ https://regex101.com/r/pA4qB0/1 regex with the dash

**Comment by jaapz** [comment]
I didn't follow up on this, and I didn't really fully describe what actually broke for me. But what @scottbedard mentions is exactly the bug that I was encountering. Thanks for explaining it a lot better than I did :)
