### ISSUE TITLE
Rerendering collectionviews on `reset` events throw.

### ISSUE THREAD

**Issue by jeffijoe** [marionettejs/backbone.marionette#2719]
I've managed to reproduce this in a Fiddle:

http://jsfiddle.net/jeffijoe/wzxxpp06/2/

The issue arises when a LayoutView is hosting a collectionview, and the layoutview also
rerenders when the collection is reset.

This does not apply to removing all models from the collection, it's just resetting.

Code from Fiddle:

``` javascript
console.clear();
let Mn = Marionette, Bb = Backbone;

let Col = Bb.Collection.extend();

let data = new Col([{cat: 'Bob'}, {cat: 'Mittenz'}]);

let ListView = Mn.CollectionView.extend({
    childView: Mn.ItemView.extend({template: '#item'})
});

let MainView = Mn.LayoutView.extend({
    el: '#app',
    template: '#main',
    initialize() {
        this.listenTo(data, 'add reset remove', this.render);
    },
    templateHelpers() {
        return {
            hasAnyCats: data.length > 0
        };
    },
    regions: {
        list: '.list'
    },
    onRender() {
        if (data.length > 0) {
            this.showChildView('list', new ListView({collection: data}));
        }
    }
});

new MainView().render();

setTimeout(() => data.add({cat: 'Dog'}), 1000);
setTimeout(() => data.reset(), 2000);
```

**Comment by jasonLaster** [comment]
@ianmstew any ideas?

@jeffijoe what marionette version?

**Comment by jeffijoe** [comment]
@jasonLaster The latest on npm.

**Comment by paulfalgout** [comment]
This is a dupe https://github.com/marionettejs/backbone.marionette/issues/1736

If a parent view and a child view is queued to listen to the same event, the parent view cannot do anything that will destroy the child, as the child view event will still be queued to run.

**Comment by paulfalgout** [comment]
Actually this is a less of a dupe, and more of a very related issue.

The problem here is that there isn't a way to work around the "error" that marionette throws when you try and render a destroyed view.

https://github.com/marionettejs/backbone.marionette/blob/v2.4.2/src/collection-view.js#L92

```
this.listenTo(this.collection, 'reset', this.render);
```
should probably change to something like:
```
this.listenTo(this.collection, 'reset', function(){
  if(this.isDestroyed) return;
  this.render();
});
```

**Comment by jeffijoe** [comment]
@paulfalgout that's the only way? Would not throwing internally "fix" it?

**Comment by jeffijoe** [comment]
@paulfalgout I can verify that your suggestion works.

Check the updated fiddle, where I patch the _initalEvents of CollectionView: http://jsfiddle.net/jeffijoe/wzxxpp06/3/

**Comment by paulfalgout** [comment]
FWIW you can also "fix" this by `_.defer`'ing your layout's listener.  this way the `collectionview` would handle the `reset` first..  or.. perhaps better in this case you don't want your collectionview to listen to the reset.  So you could:
```js
onRender() {
    if (data.length > 0) {
        var myCv = new ListView({collection: data});
        this.showChildView('list', myCv);

        // after the show which triggers the listener
        myCv.stopListening('reset');
    }
}
```

**Comment by jeffijoe** [comment]
Wouldn't it be better to *not* have to think about it?
