### ISSUE TITLE
Create a smarter `render` method for `CollectionView`

### ISSUE THREAD

**Issue by ahumphreys87** [marionettejs/backbone.marionette#2723]
Currently CollectionView contains various features that require DOM manipulation (sorting, filtering). We have a performant "render" for sorting by enabling `reorderOnSort` but for `filter` the default is to re-render.

For 3.0.0 we should change the default behaviour of `render` to perform a smart render for filter and sorting.

https://github.com/marionettejs/backbone.marionette/issues/2703
https://github.com/marionettejs/backbone.marionette/issues/2596

**Comment by thousand** [comment]
As an add-on to this, I would suggest that filtered views be "hidden" instead of removed from the list of children. This they do not have to be spun up and again on subsequent shows, allowing both better performance and ability to maintain state.
