### ISSUE TITLE
Calling `CollectionView.destroyChildren` does not trigger `destroy:collection`

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2731]
https://github.com/marionettejs/backbone.marionette/blob/v2.4.2/src/collection-view.js#L606

These are triggered only in `destroy` but this public function should likely trigger them itself.

**Comment by ianmstew** [comment]
I think I would rather make `_destroyChildren()` private, remove the `children` events, and encourage developers to rely on top level `render` and `destroy` events as implying these.
