### ISSUE TITLE
Reconsider the addition of region management code to Marionette.View

### ISSUE THREAD

**Issue by blikblum** [marionettejs/backbone.marionette#2743]
In next  branch (future 3.0), LayoutView was removed and the region management code was added to Marionette.View. 
I understand the reasoning behind this move (simplify the API) but there's a potential performance hit considering that majority of Marionette.View (formerly ItemView) instances in one typical app will not use the region code (think of list items, table rows). These are views that generally are the most rendered and rerendered. 

I think of two options:
- keep LayoutView and View classes as is in current version
- add first class mixin (functional mixin plus advice?) support that would allow to declare something like:
```
var MyViewWithRegions = Mn.View.extend({
   mixins: [Mn.RegionsMixin]
});
```
The later would open other possibilities to be used in other features

**Comment by paulfalgout** [comment]
Well I think in v3 the simplification will go further than just making everything a layout.  Essentially I do not think there will be any perf decrease than if you were to add `_.isEmpty({})` to your `ItemView`'s initialize.  And region management will only occur when needed.

**Comment by ianmstew** [comment]
What about lazily instantiating the RegionManager?

**Comment by blikblum** [comment]
> there will be any perf decrease than if you were to add _.isEmpty({}) to your ItemView's initialize

This is the region management code called when a View is instantiate:
````
_initializeRegions
  _initRegionManager
    getRegionManager
      new Marionette.RegionManager
    4x listenTo(this.regionManager)
  _addRegions
    Marionette._getValue
    normalizeUIValues
    _buildRegions
      regionManager.addRegions
  _addRegions
    Marionette._getValue
    normalizeUIValues
    _buildRegions
      regionManager.addRegions
```

When re-rendered:

    _reInitializeRegions

AFAICS is more expensive then _.isEmpty({}) and also increase memory usage (a RegionManager instance thus the events addition)

**Comment by ianmstew** [comment]
@blikblum Great point, and I think we are actually all in agreement.  @paulfalgout is working on a simplification to Marionette.View that will allow it to support regions _without_ the burden of RegionManager.  An early proposal is here: https://github.com/paulfalgout/backbone.marionette/pull/3/files#diff-54628cdbb43b8b10d359b3bfa2a80387R6.

**Comment by blikblum** [comment]
Fine. I'll keep looking.

**Comment by paulfalgout** [comment]
@blikblum the latest merge should help alleviate this issue

**Comment by blikblum** [comment]
Thanks. Nice work
