### ISSUE TITLE
Maximum call stack size exceeded caused by ui trigger events

### ISSUE THREAD

**Issue by xueyuchen** [marionettejs/backbone.marionette#2745]
```javascript
ui: {
    addAlbumBtn: '#bind-addAlbum'
    },
```
```javascript
events: { 
    'click #add-album': 'addAlbum'
    },
```
```javascript
addAlbum: function() {
    this.ui.addAlbumBtn.click();
    },
```
when addAlbum been triggered, the error "Uncaught RangeError: Maximum call stack size exceeded" should be happen?
this is an issue?

**Comment by paulfalgout** [comment]
more example code or a jsfiddle would help a lot here, but..  if clicking on the #add-album button then triggers a click event on the addAlbumBtn which then propogates back to the #add-album button then you're going to have an event loop which will cause a call stack.  I don't think this is a Mn issue, but please if there's more details, we'll be willing to look into it further.  Additionally please join us in the gitter room https://gitter.im/marionettejs/backbone.marionette
