### ISSUE TITLE
Make CollectionView `destroyChildren()` private

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2755]
I think I would rather make _destroyChildren() private, remove the children events, and encourage developers to rely on top level destroy events as implying these.  The only value it brings is for CompositeView.  This could be pushed down to CompositeView or else wait until we remove CompositeView completely.

**Comment by paulfalgout** [comment]
I agree.  And what's particularly interesting is that this function is documented on the [`CollectionView`](https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.collectionview.md#collectionviews-destroychildren)  But I think I'd rather privatize this when `CompositeView` is removed.
Or we could privatize it for `CollectionView` and expose it for `CompositeView`?

**Comment by ianmstew** [comment]
Cool, yeah maybe it doesn't make sense to diverge the two APIs.  I just realized we'll need a major version bump to remove CompositeView anyway, so I don't think it will be a particular shock to privatize then.  We _could_ add a deprecate notice to `destroyChildren` on CollectionView (`! instanceof CompositeView`).

**Comment by rafde** [comment]
resolved https://github.com/marionettejs/backbone.marionette/blob/e740f066bcea5ca40b1a28d222da13d414d905c9/src/collection-view.js#L647

**Comment by paulfalgout** [comment]
Ah interesting.. oops.  well I suppose for v3 anyone needing to destroyChildren in the CompositeView can just call `_destroyChildren`?  Or should we expose it?  Seems like a waste of time to maintain CompositeView

**Comment by rafde** [comment]
Unless someone ask for it, I say close this ticket. If people want it, then they can PR making it public again.
