### ISSUE TITLE
Change marionette.module shim function to setup

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2761]
We will use the `marionette.module` project in 3.0 and when there is an alternative we wll deprecate them.

We need two changes:
1. update the project readme to be more like babysitter
2. change `shim` function to `setup`

**Comment by rafde** [comment]
@jasonLaster , wouldn't the alternative be something like `RequireJS`?

**Comment by JSteunou** [comment]
@rafde yes, for those using Module as a namespace system, but not for those using Module as a subapp system and already having requirejs / browserify / webpack / <add your loader>

**Comment by ahumphreys87** [comment]
@jasonLaster I wonder if this lib from @thejameskyle could be useful to replace Module all together: https://github.com/thejameskyle/backbone.service

Just gonna leave this here for 4.0

**Comment by JSteunou** [comment]
I might be missing something but I dont see how to use backbone.service as module / submodule (app / subapp) system.

**Comment by ahumphreys87** [comment]
I guess it depends on what you use them for. I'm discounting using for
namespacing as I don't feel that should be marionettes responsibility in
this day and age.

With services you can start them and assign radio requests to them to
perform certain actions - what do you feel is missing to give you what you
need?

**Comment by JSteunou** [comment]
I very like the hash to configure radio requests / events, that's a feature I'll be happy to see in a Controller or App (Module / SubApp / ...)

The things that I'll miss the more is the ability to declare a Service as a child to another so when one is started the children are started with it.

For the moment the better replacement I see for module & app as app / subapp logic is https://github.com/RoundingWellOS/marionette.toolkit (kudos @paulfalgout)

**Comment by paulfalgout** [comment]
Similar to https://github.com/marionettejs/backbone.marionette/issues/2542 maybe we don't worry about this as far as integration.
