### ISSUE TITLE
Request: bindUIElementsSubset

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2762]
Hey,

I'm not keen on using bindUIElements frequently. I think it's usually a code smell or, at the very least, a necessary evil when integrating with third-party libraries.

That said, I do use it sometimes... but I've **never** wanted to re-bind the entire UI hash. I just want to update a known subset of elements which were dynamically inserted. Marionette doesn't have any support for that out of the box and it'd be awesome if it did.

So, for instance, I'd like to do something like:

```
this.bindUIElementsSubset({  foo: '.foo' });
```

would refresh the "foo" element inside of UI without re-querying for all the other elements in the UI cache.

Thoughts?

**Comment by paulfalgout** [comment]
I wonder if this could be accomplished via just passing a hash to `bindUIElements`  This is also interesting as I assume you'd be able to dynamically add to the ui hash.

**Comment by jasonLaster** [comment]
yea, worth checking out. @MeoMix It's time we see you're name in the commit log :)

**Comment by MeoMix** [comment]
Yeah yeah :p I'll take a look. I'm up in SF travelling for the next 4 days or so, but I'll take a peek.

**Comment by paulfalgout** [comment]
So I now think the best way to add UI elements on the fly would be via `getUI` as I think we should allow for `getRegion('.selector')` as well which would also pair with `showChildView('.selector', myView)`

**Comment by paulfalgout** [comment]
related https://github.com/marionettejs/backbone.marionette/issues/2831

**Comment by paulfalgout** [comment]
I think we should look into mirroring regions here

| Region | UI |
| ------------ | --- |
| getRegion | getUI |
| addRegions | addUI? |
| addRegion | addUI? |
| removeRegion | removeUI? |
| removeRegions | unbindUIElements |
| hasRegion | hasUI? |
