### ISSUE TITLE
Handlebars custom helpers not working inside iterators

### ISSUE THREAD

**Issue by mark-lester** [marionettejs/backbone.marionette#2764]
I believe my helper doesn’t work inside an iterator if I apply within the view declaration,i.e. with
templateHelpers:.., but does if I apply it directly before the view declaration is made using Handlebars.registerHelper. Which looks like an asynchronous issue, the body of the iterator appears to have already made it's mind up about what helpers its getting before my custom ones have been applied.

**Comment by paulfalgout** [comment]
I'm not sure that I follow.  Can you post a jsfiddle or some example code?  Also, if you haven't try asking the community [here](https://gitter.im/marionettejs/backbone.marionette).  There may very well be someone who has dealt with this there who could answer quickly.

**Comment by mark-lester** [comment]
Yes I'll try and get a simple fiddle working. I've been on the chat thread and they've been very helpful indeed. For some reason my helper wasnt available inside an {{#each items}} block, but was outside it.
When I register the helper prior to making my ViewItem then it works. But I dont really believe my asynchronous argument.

**Comment by rafde** [comment]
@mark-lester This doesn't sound like a marionette issue, this sounds more like an issue in which you order you handlebars and marionette. I use both all the time at work and haven't run into that issue. Using Marionette 2.4.1 and Handlebars 3.0.3

**Comment by mark-lester** [comment]
I accept that my claims are highly dubious. I'm not going to get back to the templating end for another week or so. I've closed it for now and if I end up in the same place again I will demo in jsfiddle before reopening.
