### ISSUE TITLE
Improve gulp runner

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2767]
Here's a checklist of things to look into for the new gulp runner

- [ ] jscs is not being run
- [ ] takes longer than grunt to run.
- [ ] locally the output is a mess.. 
- [ ] I think it’s linting the instrumented files or something.

**Comment by paulfalgout** [comment]
I actually think eslint should be able to replace jscs.  It might take a little bit of tweaking to get it to line up.

**Comment by jasonLaster** [comment]
@paulfalgout perhaps - JSCS was running last night when I was working on the ES6 modules ticket.

**Comment by paulfalgout** [comment]
I was seeing linting in the output oh those crazy files.  I do wonder if most of the issues with the gulp stuff have to do with preexisting temp stuff left over by grunt.  I haven't tried from a clean dir.
Like locally try
```
grunt coverage
gulp
```

**Comment by jasonLaster** [comment]
yea, that's interesting.
