### ISSUE TITLE
Cannot add behavior to a view using ES6 new specification

### ISSUE THREAD

**Issue by gorkalaucirica** [marionettejs/backbone.marionette#2768]
We are using ES6 and Marionette in a project and until now we were doing to the following to reuse a behavior:

```js
constructor(options) {
    this.behaviors = {
      navigableCollection: {
        behaviorClass: NavigableCollectionBehavior,
      }
    };

    super(options);
  }
```

With the new specification is not allowed to use `this` before calling `super()`. `super()` launches the view constructor where behaviors are added with the following lines in `Marionette.Behaviors` class:

```js
if (!_.isObject(view.behaviors)) {
  return {};
}

// Behaviors defined on a view can be a flat object literal
// or it can be a function that returns an object.
behaviors = Behaviors.parseBehaviors(view, behaviors || _.result(view, 'behaviors'));
```

There is no possibility (as far as I know) to pass the behaviors object before the lines above are executed.

**Comment by paulfalgout** [comment]
This might help with this issue: https://github.com/marionettejs/backbone.marionette/issues/2605

Also @benmccormick has done some excellent research in this area. http://benmccormick.org/2015/07/06/backbone-and-es6-classes-revisited/  I do think this problem starts at backbone to some extent, but if we can figure out solutions to fix some Marionette specific scenarios, it would likely be worth checking out.

**Comment by benmccormick** [comment]
@gorkalaucirica you can define the behaviors has as a method for now and manage it that way.

**Comment by josielrocha** [comment]
What about use ES6 getter?
```javascript
get behaviors() {
    return {
        navigableCollection: {
            behaviorClass: NavigableCollectionBehavior,
        }
    };
}
```

Defining behaviors at constructor you will set it to view directly while using ES6 getter it will be set to Marione.View's prototype.

**Comment by paulfalgout** [comment]
I'm going to close this as it is mostly a discussion on how ES6 works.  If there's anything to be done, I suspect it will bubble up from backbone as well.  But please let us know if this needs more investigation.
