### ISSUE TITLE
Rename 'rootEl' param on application to 'region'

### ISSUE THREAD

**Issue by RobertCZ** [marionettejs/backbone.marionette#2770]
RootEl indicates, well, element. Why not call it just 'region'? Name 'rootEl' doesnt work very well when you want to pass previously created region. With 'region' name, it can still be initialized as el, selector or region, but will give us a much nicer pattern for child apps - basically every app could have a region to use passed from outside (eg parent app or main):

    // main with default region
    let rootApp = new RootApp()
    // equivalent to 
    let rootApp = new RootApp({region: document.body})

    // RootApp#ctor
    this.view = new View()
    this.region.show(this.view)

    // RootApp#startChildApp
    let region = this.view.getRegion('child')
    let childApp = new ChildApp({region})
    childApp.start()

Also, regions' show (and maybe also getRegion) can be aliased directly on app (from this.region and this.region.currentView resp.)

    this.show(new View())
    let region = this.getRegion('child')
    (new ChildApp({region})).start()

**Comment by blikblum** [comment]
Why not rootRegion?

**Comment by RobertCZ** [comment]
Backbone view receives model, option is called model and is available in view as this.model. Marionette region has option el with the same conventions. This application.region looks quite similar.

**Comment by jasonLaster** [comment]
Thanks @RobertCZ - feel free to comment directly on the PR #2763

**Comment by RobertCZ** [comment]
I did but I wasn't sure it was the right place. Shall I close this one and we continue in PR?

**Comment by paulfalgout** [comment]
Closing for continuation on PR
