### ISSUE TITLE
IE8 Error: Unexpected call to method or property

### ISSUE THREAD

**Issue by Tranfu** [marionettejs/backbone.marionette#2773]
Marionette v2.4.3 line 1260
...
```js
  // Override this method to change how the new view is
  // appended to the `$el` that the region is managing
  attachHtml: function(view) {
    if (view.template !== false) {
      this.$el.contents().detach();
      this.el.appendChild(view.el);
    }
  },
```
  ...
IE8 Error: Unexpected call to method or property

**Comment by paulfalgout** [comment]
This line in general does not cause issues in IE8 unless under edge case circumstances.  Do you know what you're attempting to append to when it fails?

For instance IE8 cannot append to a `<style>` tag.

**Comment by samccone** [comment]
@Tranfu what is your el in this case?

--

Going to say this is not a Marionette issue rather an ie8 debug request. I am going to close this issue for now but we can help you resolve this :smile:

**Comment by Tranfu** [comment]
@samccone Set the Browser mode to IE8 and the Document Mode to IE8 to get IE9 to pretend to be IE8. Hello Marionette Example http://jsfiddle.net/samccone/F59qp/

**Comment by Tranfu** [comment]
@samccone copy the code from Hello Marionette Example http://jsfiddle.net/samccone/F59qp/ into a html file and open it in IE. You will get this IE Error.

**Comment by paulfalgout** [comment]
This fiddle uses jquery 2.x which is incompatible with ie8. Perhaps this is your issue?  I run a very complex app in ie8 with no issue

**Comment by Tranfu** [comment]
@paulfalgout just checked my jquery is v1.11.3 underscore 1.8.3 backbone 1.2.3 marionette 2.4.3.
no error occurs if I comment line 18 //App.appRegion.show(view); in Hello Marionette Example http://jsfiddle.net/samccone/F59qp/

**Comment by Tranfu** [comment]
IE Tester ->  IE8 has the same error.

**Comment by samccone** [comment]
going to defer this to @paulfalgout I do not have a windows box to test on atm

**Comment by paulfalgout** [comment]
I've assigned it to myself.  My laptop was stolen while on vacation so it'll be a bit before I can look into it specifically.  I do want to track it down.  However as previously mentioned, I run a non-trivial app that surely is doing exactly what this fiddle is doing without issue..  not sure what the difference might be here.

**Comment by jridgewell** [comment]
Like @paulfalgout [said](https://github.com/marionettejs/backbone.marionette/issues/2773#issuecomment-146393304), the fiddle is running jQuery 2 which won't work with old IE. Here's the fiddle [updated](http://jsfiddle.net/F59qp/41/) to run with jQuery 1.11, [working perfectly](https://dl.dropboxusercontent.com/spa/keyy7k9vgnogrqa/3m_8ikh3.png).

**Comment by samccone** [comment]
will wait @Tranfu 's response before we close again :) thanks a ton @jridgewell

**Comment by paulfalgout** [comment]
@jridgewell big thanks!
That was my expectation.

@Tranfu are you using a package manager?  perhaps you're getting a 2.x version of jQuery somewhere you weren't expecting.  Again though there are some edge cases in which IE8 cannot append to a tag.. so this might be specific to your use-case as well.

**Comment by Tranfu** [comment]
I found the difference. <div id="app"></div> the fiddle is doing without issue. If try this <section id="app"></section>, IE error Unexpected call to method or property. Just div and section, why?! why?!

**Comment by paulfalgout** [comment]
Section is html5. If you aren't using the html5shim this is the result.  I think this is solved.

**Comment by Tranfu** [comment]
Solved. Thanks!
