### ISSUE TITLE
LayoutView behavior can't pick up child events in any way?

### ISSUE THREAD

**Issue by fraserharris** [marionettejs/backbone.marionette#2776]
I'm trying out behaviors for the first time to encapsulate some child view event tracking code. This never fires:
```
var LayoutViewBehavior = Marionette.Behavior.extend({
  onChildviewBuyClick: function(childView){ ... }
}
```
I threw together a demo of what does & does not fire:
http://codepen.io/anon/pen/epgjRx?editors=001

Is there a work around? 

(Note: similar to this issue, but for LayoutView vs CompositeView: https://github.com/marionettejs/backbone.marionette/issues/2235)

**Comment by fraserharris** [comment]
Doesn't appear i'm alone, @lococo--0 reported this too: https://github.com/marionettejs/backbone.marionette/issues/2683#issuecomment-128610406

**Comment by lococo--0** [comment]
It seems that the behavior designed for ItemView, not for the LayoutView.

I finally write a BasicLayoutView to resolve this problem.

But I really think the behavior should support more feature like 'onChildviewDoStuff' or 'regions'. It's very useful. @ahumphreys87

**Comment by fraserharris** [comment]
@lococo--0 can you share your implementation?

**Comment by jasonLaster** [comment]
Thanks for the demo. Will investigate. 

Also, if you can it'd be nice to add a unit test for this.

**Comment by paulfalgout** [comment]
I'd vote for behaviors supporting `childEvents` in the same way it supports `modelEvents` and `collectionEvents`

I would be opposed to further auto-proxying triggered event methods.

**Comment by ur5us** [comment]
@paulfalgout That would be really really useful! Being new to MarionetteJS I was surprised to learn that `childEvents` on `Behavior` is not implemented yet after reading about those 2 things to begin with.

**Comment by bsherrill480** [comment]
I ran into the same problem as @fraserharris. While I don't like my solution, I thought I would share it in case someone can improve on it, or it could help someone else.

I added this to the behavior:
```
onRender: function() {
    this.view.onChildviewDoSomething = function() {
         //stuff
     };
}
```

and the precondition for behavior that the view will not use the function onChildviewDoSomething.

**Comment by paulfalgout** [comment]
I think in `v3` the best way to handle this is to use the parent (layout) view's `childViewTriggers`  This will proxy the event onto the Layout and allow for the parent behavior to handle the event
