### ISSUE TITLE
Jasmine and jsdom error: An "el" X must exist in DOM

### ISSUE THREAD

**Issue by jedrichards** [marionettejs/backbone.marionette#2779]
I'm trying to write some Marionette view unit tests using Jasmine and jsdom. I'm running into an error whereby LayoutViews don't seem to be able to find their regions. Here's my jsdom setup code

```js
const html = `
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
  </head>
  <body>
    <div id='#test-harness'></div>
  </body>
</html>
`

jsdom.env({
  html,
  done: (err, window) => {
    if (err) throw new Error('Failed to init jsdom', err)
    global.window = window
    global.window.console = global.console
    global.document = window.document
    global.window.$ = require('jquery')
    const {LayoutView} = require('backbone.marionette')
    const TestHarness = LayoutView.extend({
      el: '#test-harness',
      template: `<div class='TestHarness-inner'></div>`,
      regions: {
        inner: '.TestHarness-inner'
      }
    })
    global.window.testHarness = new TestHarness()
  }
})
```

Which throws,

```
Error: An "el" .TestHarness-inner must exist in DOM
```

This confuses me because surely `.TestHarness-inner` must exist in the DOM since I've attached the LayoutView to #test-harness?

Any help appreciated!

**Comment by MeoMix** [comment]
I don't see where you render this view at all...? When would that template be placed into jsdom?

**Comment by jedrichards** [comment]
Since I'm setting `el` to `'#test-harness' shouldn't auto attach to that element when I create the instance with `new TestHarness()`? In any case, the error I'm getting above is happening without calling `render()` ...

**Comment by MeoMix** [comment]
Instantiating a view != rendering a view. Template is only injected when rendered regardless of whether it's given a target element.

Anyway, I put your code into a codepen (which I'd suggest doing first!) and it became pretty apparent. You put a '#' marker in your HTML template id which doesn't make any sense.

It works fine when you remove that: http://codepen.io/anon/pen/yYbeBQ

**Comment by jedrichards** [comment]
Hey, thanks for the input. Good catch on the errant `#` in the HTML. Also you're right about "instantiating a view != rendering a view". That wasn't the issue though ... your Codepen helped me solve it. Something to do with the template I think. It didn't like the plain string I was using, your `_.template()` helped me find it. Sorry, my Backbone is pretty rusty ... was convinced this was some sort of weird jsdom issue. Cheers!
