### ISSUE TITLE
Concurrent render?

### ISSUE THREAD

**Issue by alekop** [marionettejs/backbone.marionette#2781]
I would like to render a view with an initial template, and then re-render it (with a different template) after its data is fetched.

```javascript
Marionette.ItemView.extend({
    template: ...,

    initialize: function(config) {
        Marionette.ItemView.prototype.initialize.call(this, config);

        this.model.on('sync', this.updateUI, this);
        this.model.fetch();
    },

    updateUI: function() {
        this.template = ...;
        this.render(); // What if there is a render in progress?
    }
});
```

Looks simple enough, but if the `sync` event fired during the initial render phase, it would trigger a second render while the first one is still in progress. Looking at the Marionette source, I don't see any code to handle and reject a render request when there is one already in progress.

I haven't actually encountered any problems with this code yet, but something tells me there is a possibility for weird issues, like the view getting attached twice, or multiple event handlers being attached, or child views getting rendered twice. 

Am I being paranoid? Or maybe there is a more reliable pattern for what I'm trying to do?

**Comment by paulfalgout** [comment]
you can use `getTemplate` to determine which template to load..  set a flag if need be in your updateUI and call `render`   You also don't need to call `initialize` on the prototype it's a noop.  And you could use `modelEvents: { sync: 'updateUI' }`
