### ISSUE TITLE
Trigger handler arguments

### ISSUE THREAD

**Issue by jbarreiros** [marionettejs/backbone.marionette#2785]
Not sure if this is simply a documentation issue or a bug.

The docs at http://marionettejs.com/docs/marionette.view.html#trigger-handler-arguments show
```
view.on("some:event", function(args){
  args.view; // => the view instance that triggered the event
  args.model; // => the view.model, if one was set on the view
  args.collection; // => the view.collection, if one was set on the view
});
```

Messing around with childview:* events (from a CompositeView) and the arguments actually look like `[ItemView object], {collection: *, model: *, view: *}`.

I'm guessing the docs are incorrect since most events pass the object that triggered it as its first argument. So, the behaviour seems correct. Is that the case?

**Comment by blikblum** [comment]
When using childview events there's an extra argument (the child view instance) compared when childview is not used.

As an example see http://codepen.io/blikblum/pen/QjMmWw 
Open the console and see output for onSaveModel and onChildviewSaveModel

Anyway is an inconsistency

**Comment by paulfalgout** [comment]
As @blikblum mentioned proxied child events have their arguments prefixed by the event originator.
