### ISSUE TITLE
Feature Request: Behavior options should be set with Marionette._getValue

### ISSUE THREAD

**Issue by jasonmng** [marionettejs/backbone.marionette#2787]
Since _.extend() doesn't do a deep clone, I ran into reference issues

**Comment by JSteunou** [comment]
Maybe you should define your behaviors as a function returning an object / hash.

**Comment by jasonmng** [comment]
I don't think I understand, are you saying I should do something like this?

```
var MyView = Marionette.ItemView.extend({
   behaviors: {
      behaviorOne: function(){
         return {
            optionOne: true
            optionTwo: true
         }
      }
   }
});
```

Because if you are, that is what I'm asking to be able to do.

**Comment by JSteunou** [comment]
nope:

```
var MyView = Marionette.ItemView.extend({
   behaviors: function() {
     return {
      behaviorOne: {
            optionOne: true
            optionTwo: true
         }
      };
   }
});
```

most hash attributes can defined as function returning a hash.

**Comment by jasonmng** [comment]
Thanks! I did not know you could do this.  I still feel, however, that this would be a good addition: 
```
this.options  = _.extend({}, this.defaults, Marionette._getValue(options, view));
```

**Comment by paulfalgout** [comment]
So in `v3` you can pass either a definition hash with `behaviorClass` on it or you can simply pass the class in..  We could still _possibly_ check to see if it is an instance of Behavior, but it's not longer trivial to just execute any attached function..  I'm going to close this for now, referring to https://github.com/marionettejs/backbone.marionette/issues/2787#issuecomment-150610998 for the best option currently.
