### ISSUE TITLE
CollectionView can Add new child views for models which are no longer in the collection

### ISSUE THREAD

**Issue by cusial** [marionettejs/backbone.marionette#2788]
it is possible to have a process which removes models from a collection if they fail certain criteria, and have the collection view which is listening to that collection carry on and add a view for that model, even it was removed.

Currently the CollectionView tests for the model's index within the collection, but if it finds no index it still adds a new childView. I think it should not do that. the collection view should only add a new child view if that model can be found in the collection.

**Comment by paulfalgout** [comment]
A fiddle or some example code would be really useful.

**Comment by paulfalgout** [comment]
We can reopen this if there are any further details to investigate
