### ISSUE TITLE
CompositeView with no childView renders itself as child view

### ISSUE THREAD

**Issue by alekop** [marionettejs/backbone.marionette#2800]
I just spent almost an hour debugging a weird issue, where a composite view's onBeforeRender was being called once for each model in the collection. (Actually, a unit test caught it!)

The cause was that I had forgotten to specify the `childView` option. In this case `getChildView()` will return `this.constructor`. I understand that this is to allow recursive tree structures, but it seems wrong to quietly default to self. Since a child view is always used it's not really optional, so I think we should require it to be set explicitly, and not rely on the "hidden knowledge" that it will default to the parent.

What do you think?

**Comment by paulfalgout** [comment]
This is the default and it is documented: http://marionettejs.com/docs/v2.4.3/marionette.compositeview.html#recursive-by-default

However I agree with you, but this will eventually be removed when CompositeView is replaced by a simpler set of views and for those needing composite or trees there will be simple examples as to how to reproduce them

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/pull/2759
