### ISSUE TITLE
Create `backbone-emulate-collection`

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2808]
We killing the `actAsCollection` method here https://github.com/marionettejs/backbone.marionette/pull/2806/files and should replace it with a small backbone library.

**Comment by paulfalgout** [comment]
better name too :-)

**Comment by paulfalgout** [comment]
This library would ideally use https://github.com/babel/generator-babel-boilerplate/tree/master/app/templates and be written in ES6 with full coverage.

**Comment by paulfalgout** [comment]
Done https://github.com/marionettejs/backbone-emulate-collection
