### ISSUE TITLE
Region selectors may not be sudo classes

### ISSUE THREAD

**Issue by miphe** [marionettejs/backbone.marionette#2810]
In the following case, we create two regions for a LayoutView.

```javascript
var layoutView = Mn.LayoutView.extend({
  // code ....
  regions: {
    'section-1': 'section:first',
    'section-2': 'section:nth-child(2)'
  }
})
```

If we later show ItemViews in these regions, they don't act as expected.

```javascript
layoutView.getRegion('section-1').show(someItemViewInstance)
layoutView.getRegion('section-2').show(someOtherViewInstance)
```
It seems that `someOtherViewInstance` will override whatever view was rendered in the previous region, as if Marionette believes they are both to be rendered in the same region, or that there are two regions which are referring to the same place in the DOM.

Does this work as intended? I haven't seen any note about it anywhere.

**Comment by paulfalgout** [comment]
does `$('section:nth-child(2)') return what you expect if you log it inside `initialize`?

**Comment by miphe** [comment]
In the `initialize` fn of the layout view with the regions, `$('section:nth-child(2)')` doesn't find any elements. Though if I check after a timeout, the element is there.

**Comment by paulfalgout** [comment]
ah I'm sorry, I should have said `onRender` not `initialize`  does it show the correct selector there?  And maybe a jsfiddle would help as well.

**Comment by JSteunou** [comment]
Add an `id` or `data` attribute for test purpose and try again. There are high chances your selectors does not hit the element you think about.

**Comment by miphe** [comment]
@JSteunou Yes. With any non sudo-class selector it works well.

I'm trying to get a Fiddle working, but so far I can't reproduce this. I'll be back with more info.

**Comment by paulfalgout** [comment]
@miphe any luck isolating the problem on a fiddle?

**Comment by paulfalgout** [comment]
Definitely let us know if you're able to track this down any further
