### ISSUE TITLE
Update Docs w/ CompositeView usecases

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2811]
Now that composite view is gonzo, we should update the docs to go through the primary use cases.

e.g.
+ table
+ tree
+ list

**Comment by JSteunou** [comment]
Using Mn 3.0 new views & region?

**Comment by paulfalgout** [comment]
Yep.  We need to make recipes to show easy ways to reproduce all of the use cases for compositeview in v3.  Although I don't think it's "gonzo" until v4.

**Comment by scott-w** [comment]
I've thrown together a quick example of a CollectionView replacement for CompositeView. I'm happy to provide complete table and list examples.

By "tree" do you mean something like:

```
Item
|--- Nested
|--- Nested
        |--- Double-nested
|--- Nested
Item
|--- Nested
```

**Comment by paulfalgout** [comment]
xref: https://lostechies.com/derickbailey/2012/04/05/composite-views-tree-structures-tables-and-more/

**Comment by scott-w** [comment]
Awesome, cheers.

**Comment by scott-w** [comment]
I'm marking this as done. If I've missed anything feel free to reopen this issue and I'll get it sorted.
