### ISSUE TITLE
Make _getValue public.

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2814]
On #2793  @msiconolfi asked why `_getValue` was private.  I don't really have an answer for that.
It was requested here: https://github.com/marionettejs/backbone.marionette/pull/2136#issuecomment-67424178

@samccone @marionettejs/marionette-core what was the reason this was privatized?  Seems to me like it could be useful publicly.

**Comment by msiconolfi** [comment]
Also, I noticed the [comment](https://github.com/marionettejs/backbone.marionette/blob/master/src/helpers.js#L47-L48) before the `Marionette._getValue` definition should probably remove the line `if the value is undefined return a default value`.

Based on the conversation in  [#2136](https://github.com/marionettejs/backbone.marionette/pull/2136#issuecomment-67424178) made by @megawac *"I couldn't decide whether there should be a defaultVal or an args param, I went with the args param as it seemed more useful internally."* 

It looks like this [comment](https://github.com/marionettejs/backbone.marionette/blob/master/src/helpers.js#L47-L48) never got updated after the decision was made to have an args param.

**Comment by jasonLaster** [comment]
nice. lets do this

**Comment by samccone** [comment]
I think the initial reason why we did this was because we were not 100% sure of the API and keeping this private let us iterate on the API... it also kept the overall api namespace down, but if this is something that we want to expose to others then :+1: :ship:

**Comment by msiconolfi** [comment]
I can take this on. Are we simply just removing the underscore and calling it `getValue` and replacing all invocations with the new name?

**Comment by samccone** [comment]
yep @msiconolfi :) you will also want to document the method

**Comment by jasonLaster** [comment]
Yep. 

The other part too make it public would be to add it to the Marionette namespace in backbone.marioette.js and of course the docs.

**Comment by paulfalgout** [comment]
Also look at doing this off of the `next` branch
