### ISSUE TITLE
Using Generic Views with Models

### ISSUE THREAD

**Issue by trevorharwell** [marionettejs/backbone.marionette#2821]
I wanted to open up a discussion with the Marionette team about a pain point that my team has with Marionette as it currently exists (we use v2.4.1).  We have been developing a single page application with considerable complexity for some time now (2+ years) and a quick `wc -l` on the entire project adds up to ~80,000 lines of javascript.  We heavily depend on Marionette for our views and semantic ui for our styling.

##### The Problem
One of our main pain points with Marionette is not being able define generic views and then use them in conjunction with random models.  A simple example of this would be an input view.  We have a generic input view that we want to use throughout the application but the model that drives this input view will be different depending on where we use it. I do not know of or see any tools in Marionette that allow you to solve this problem easily.  The definition of a view seems tightly coupled to the data that it is intended to display.

##### Our Solution
The team that I am apart of has started to solve this problem by making views that are driven by their options.  We reasoned that the external interface to a view instance should be like a DOM element. 
```javascript
// dom setting
input.value = "new value";
// view option
view.set("value", "new value");
```
By doing this we made views have inherent options that made them easy to re-use.  Once this was in place, we solved the original problem by allowing view instances to be configured to have their inherent options be driven by models.
```javascript
var model = new Backbone.Model({ firstName: "James" });
var view = new InputView({ model: model });
view.bindings.value = "firstName";
```
In this example we could configure this view's value property to be driven by the model's firstName property and thus generic views could be used for any data.

##### My Question
I don't expect the Marionette team to adopt this but I wanted to start a discussion with you guys about how we could solve this problem the "Marionette" way or perhaps introduce a new mechanism.

Thoughts?

**Comment by paulfalgout** [comment]
I don't entirely follow.  if it's not too much a trouble a more involved fiddle/codepen/etc of the scenario you are describing would probably help

**Comment by jasonLaster** [comment]
Hi @trevordixon! I'm not exactly sure I follow either. Would Marionette Behaviors help?

**Comment by JSteunou** [comment]
I think I understand, but that kind of afraid me. Do you want View without Model? Just being tight to a generic `object` because some of your views are so tiny they handle just one *value* and having a all model for one *value* seems too much for you?

My 2 cents: even for only one *value* I'm using a BB Model, and it's very fine like that. I sometimes event have 2 models, one for state, one for data.

**Comment by trevorharwell** [comment]
First off I wanted to relay how much I appreciate you guys taking the time to look into this.

@paulfalgout @jasonLaster Here is a js fiddle that shows the problem I am trying to solve.
http://jsfiddle.net/dob3qkxb/1/

If you guys are familiar with an Ember Component then that is almost exactly the solution I am looking for.  It is a completely re-usable component where you tell the component which properties from a model you are interested in using:  http://guides.emberjs.com/v2.1.0/components/passing-properties-to-a-component/

Please let me know if you need further explanations/examples.  I could also get on gitter if that would make things easier.

@JSteunou We do use models for everything and I have no problem using a model for one value.
We have spent a lot of time creating very versatile view definitions that pack in a ton of re-usable functionality. Doing this has been invaluable to our development velocity. Unfortunately when you start to focus on making highly configurable views the lines between options and data start to blur.  For example our input view has 14 different configuration options:

* visible (boolean)
* inputAutocomplete (boolean)
* value (string)
* placeholder (string)
* icon (string)
* error (boolean)
* loading (boolean)
* label (boolean)
* transparent (boolean)
* size (string)
* focusable (boolean)
* readonly (boolean)
* fluid (boolean)
* disabled (boolean)

Any one of these configuration values could come from a model.  Which ones should be put in the model and which ones should be put in the options? This is a question that we kept running into so we decided that views should have all their configurations inside of their options and then those options could be bound to an attribute of a model.  

The conversation here has split a little and I just wanted to re-iterate that my main focus is trying to solve the problem in the js fiddle above the "Marionette" way.

**Comment by trevorharwell** [comment]
Here is very simplistic solution that could be a Marionette View mixin:

```javascript
export default {

  _initComponent: function(options) {
    this.bindings = _.extend({}, this.bindings, options.bindings);
  },

  serializeData: function() {
    var data = {};
    // copy all bindings from the model to the
    // template data
    _.each(this.getBindingKeys(), function(dest) {
      var src = this.bindings[dest];
      data[dest] = this.getBindingValue(src);
    }, this);

    return data;
  },

  getBindingKeys: function() {
    if (!this._bindingsKeys) {
      this._bindingsKeys = _.keys(this.bindings);
    }
    return this._bindingsKeys;
  },

  getBindingValue: function(src) {
    if (!this.model) { return; }
    return this.model.get(src);
  }

}```

And this is how you would use it:
```javascript
var ComponentView = Mn.View.extend(ComponentMixin).extend({
  constructor: function(options) {
    options = options || {};

    this._initComponent(options);
    
    Mn.View.prototype.constructor.apply(this, arguments);
  }
});
var InputComponent = ComponentView.extend({
  template: _.template('<input value="<%= value %>" />')
});
var model = new Backbone.Model({ name: "James Smith" });
var view = new ComponentView({ model: model });
view.bindings.value = 'name';
```

Now you could use this input view with any data throughout your app.

**Comment by samccone** [comment]
@trevorharwell I kinda feel like behaviors are the exact solution you are looking for.... have you experimented with them at all?

**Comment by trevorharwell** [comment]
I am familiar with the idea behind them but to be honest I do not use them and I am not entirely well versed in their design patterns.  I was looking into them last night and I don't see what you mean.  Could you detail a very basic/stubbed prototype of what you are thinking?

**Comment by ahumphreys87** [comment]
@trevorharwell sorry this thread went stale. @samccone is right, behaviors would work for you in this case. A good example can be found here: https://github.com/thejameskyle/marionette-wires/blob/master/src/forms/behavior.js

It is used here: https://github.com/thejameskyle/marionette-wires/blob/master/src/colors/edit/view.js#L12-L14

Notice in the `handleSubmit` function on the view its using the `form` property that the behavior sets, I think you could follow similar principles to achieve what you desire.

Gonna close the issue but feel free to reopen or ping me on our gitter.im channel if you have anymore questions!
