### ISSUE TITLE
UI interpolation eagerly evaluated and cached

### ISSUE THREAD

**Issue by jiaweihli** [marionettejs/backbone.marionette#2831]
I've written a wrapper around a UI element that only injects an element into the DOM when it's clicked.
The selector to the injected element is getting evaluated / overwritten to empty array before I ever access it.

**Comment by paulfalgout** [comment]
I think I follow, but some pseudo code could help

**Comment by jasonLaster** [comment]
If you want you can recall bindUiElements

**Comment by jiaweihli** [comment]
```typescript
class SidebarDropdownView<T> extends DropdownView<T> {
  ...

  onRender(): void {
    super.onRender();

    this.ui.select2Input
      .on('select2-open', () => {
        // :UPGRADE: (marionette) Selectors are auto eagerly-cached, so we can't use the UI hash.
        // :LINK: https://github.com/marionettejs/backbone.marionette/issues/2831
        // :KLUDGE: Add select2 dropdown styling specific for this view.
        $('#select2-drop').addClass('for-sidebar-dropdown');
      });
  }
}
```

When the dropdown (powered by select2) is opened, a new div `#select2-drop` is appended to `body` and a [`select2-open` event is fired](https://select2.github.io/select2/).

It feels inconsistent to sometimes call `bindUIElements` and sometimes not.

Maybe add an option to completely disable UI interpolation caching in a view?  I recognize per-selector disabling takes a little bit more thought and design :smile:

**Comment by paulfalgout** [comment]
I'm not sure what the solution is here..   `bindUIElements` is called currently when `View#render` is called.  If DOM is added after the view is rendered it is unaware and can't bind the UI.

But the bigger problem here I think is that view ui is scoped within the view.  so if `#select2-drop` is appended to the `body` the `SidebarDropdownView` is never going to be able to append it to the `ui` hash.  You can only bind things that you can access via `this.$()`  So if you can replace `$('#select2-drop')` with `this.$('#select2-drop')` in your code and have it work.. then some sort of smarter binding _might_ be possible..  but in this case, I do not think that it is.

**Comment by jiaweihli** [comment]
Making UI interpolation work for global elements is a separate concern - a possible solution would be to treat selectors beginning with `:root` as a global selector during interpolation.  (e.g. `:root #select2-drop`)

I don't use UI interpolation anywhere right now because I don't want to think about whether it applies to a dynamic element or not - a solution that works 90% of the time but subtly doesn't work the other 10% of the time isn't that useful.

A possible solution that both preserves cache-by-default and handles dynamic elements is to wait until first access before caching.

**Comment by paulfalgout** [comment]
I don't quite understand.  `this.ui` is just a POJO, so it doesn't understand when you try to access it.  

There is a `getUI` in v3, but since we're not removing `this.ui` I don't see how we could cache it any time after the render.  However it is intriguing that we could switch to caching a UI element only on first access if we only used `getUI`... for like a v4.

I'd also argue that except for the edgiest of cases nothing should be dynamic about a view after a render that the view should be concerned with.

And I think almost always, if not always, a view reaching to understand something outside of its own DOM is an anti-pattern.

**Comment by jiaweihli** [comment]
> I don't quite understand. `this.ui` is just a POJO, so it doesn't understand when you try to access it. 

Ah...right.  I'm been living in ES5 so long I neglected to remember Marionette supports older browsers.

> There is a `getUI` in v3, but since we're not removing `this.ui` I don't see how we could cache it any time after the render. However it is intriguing that we could switch to caching a UI element only on first access if we only used `getUI`... for like a v4.

This could be added as a feature in v3 through an additional option e.g. 
`getUI('name', { requery: true })` (naming could be better)

> I'd also argue that except for the edgiest of cases nothing should be dynamic about a view after a render that the view should be concerned with.

> And I think almost always, if not always, a view reaching to understand something outside of its own DOM is an anti-pattern.

I agree in principle, but sometimes you really have no choice.  A lot of popular UI libraries inject elements into the DOM, either inside the element or at `body` - dropdowns, datepickers, etc.

There are other legitimate use cases for 'dynamic' views.  Sometimes you need to actually remove an element from the DOM instead of just hiding it - maybe some styling uses `:first-child`.  Even `CollectionViews` are dynamic!

**Comment by jiaweihli** [comment]
Bump - any thoughts?

**Comment by paulfalgout** [comment]
I'm interested in what this looks like.  Potentially both ui and regions could be queried upon first use through the getUI / getRegion API.  This is something that could be added via a feature flag.  And then as you mention, some flag to force the querying of one element might be useful.. though if that is the case inside the view `this.$('.my-selector')` might be the better solution.  If you have something that has to be dynamically queried `view.$` is always there.

**Comment by jiaweihli** [comment]
Yes, `this.$('.my-selector')` is what I'm doing right now as a workaround.
But I'd much rather use `ui` to dry up element references as well as usages in `events` - I have some very long selectors :stuck_out_tongue: .

If this all sounds good, I'll open a PR based on your suggestions above?

**Comment by scott-w** [comment]
Just an idea, maybe extend the `getUI()` API with an option like `requery`? e.g.

```javascript
this.getUI('myUI', {requery: true});
```

**Comment by paulfalgout** [comment]
alternatively an expensive lookup for these edge-cases is `this.$(this.ui.mySelector)`
