### ISSUE TITLE
Create a v3 release candidate

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2836]
@marionettejs/marionette-core 

I'm feeling somewhat confident that we could soon tie a bow on the progress that is v3 and get a release candidate put together.

This will mean that we'll continue to have some known issues around view life-cycles, particularly as it pertains to `onAttach` and `CollectionViews`.  But I think any issue on the [v3.0.0](https://github.com/marionettejs/backbone.marionette/milestones/v3.0.0) milestone that doesn't have a PR and that isn't docs/tests related could be moved to `v4`.

In order to get the RC ready I believe we should look into the following PRs:
~~[#2834 - Gulp build es6 libs](https://github.com/marionettejs/backbone.marionette/pull/2834)~~
~~[#2736 - View mixin proposal](https://github.com/marionettejs/backbone.marionette/pull/2736)~~
[#2758 - Add radio mixin](https://github.com/marionettejs/backbone.marionette/pull/2758)
~~[#2832 - childEvents -> childViewEvents](https://github.com/marionettejs/backbone.marionette/pull/2832)~~

And some nice to haves would be:
~~[#2835 - Simplify bindEntityEvents](https://github.com/marionettejs/backbone.marionette/pull/2835)~~
~~[#2825 - Add Rest & Spread ES6 syntax](https://github.com/marionettejs/backbone.marionette/pull/2825)~~
~~[#2818 - Implement childTriggers](https://github.com/marionettejs/backbone.marionette/pull/2818)~~

[#2850 - View events refactor / Region and CollectionView cleanup](https://github.com/marionettejs/backbone.marionette/pull/2850)

Additionally there is a ton of work to be done around documentation, though I don't think that should slow a RC release.  Our documentation is far worse off than our open issues https://github.com/marionettejs/backbone.marionette/issues/2647 and https://github.com/marionettejs/backbone.marionette/issues/2477
And similarly our test coverage has dropped. https://github.com/marionettejs/backbone.marionette/issues/2581
But once the documentation has been polished a bit, even perhaps after 3.0 is gold, the tests need some love and can hopefully align better with our documentation.
And of course we'll need to update the changelog and the upgrade guide

In addition to all of this we need a very clear upgrade path, potentially with a nice tool like we had for v2, and we need to make sure the shims are up to snuff.
https://github.com/marionettejs/marionette.module
https://github.com/marionettejs/backbone-emulate-collection
https://github.com/marionettejs/marionette.app-channel

And we should take a glance at babysitter.. It is still a dependency and we're making a breaking change, so we can possibly get some cheap quick wins by giving it a once over.

On top of that, we'll need to look at a blog post / website stuff related to this release.

Home stretch now.

**Comment by paulfalgout** [comment]
I'll add https://github.com/marionettejs/backbone.marionette/issues/2814 Make _getValue public to the nice to haves list.

**Comment by jasonLaster** [comment]
Thanks for the write up. I agree the emphasis should be on 3.0 RC. 

Once we have an RC we can figure out e soft stuff, documentation, upgrade, website. Would be great to market the new great Mn.

**Comment by paulfalgout** [comment]
We'll need this https://github.com/marionettejs/backbone.marionette/pull/2839  It includes some bugfixes

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/pull/2840 too

**Comment by paulfalgout** [comment]
We should investigate https://github.com/marionettejs/backbone.marionette/issues/1579 and https://github.com/marionettejs/backbone.marionette/pull/2847#issuecomment-162008534
