### ISSUE TITLE
Region creation too slow due to jQuery

### ISSUE THREAD

**Issue by jiaweihli** [marionettejs/backbone.marionette#2846]
We're using Marionette for a medium-size codebase (~100 views) with heavy nesting of `LayoutViews`.  One perf issue we noticed was how expensive region creation was - nearly 5ms went to element lookup.  When a single action can create 10 regions, this already costs 50ms.  We're trying to keep app latency per action below 100ms to avoid a poor user experience, and this was killing our budget.

We reduced element lookup time to 1ms by using [qwery](https://github.com/ded/qwery) v3.4.2:

``` typescript
class QweryLookupRegion extends Marionette.Region {
  getEl(el: string): JQuery {
    // :UPDATE: (marionette) We patched the implementation to use `qwery` instead of `$.find`.
    // This reduces lookup time from ~5ms to 1ms.
    const jquery: JQuery =  Backbone.$(qwery(el, Marionette['_getValue'](this['options'].parentEl, this)));
    // :KLUDGE: Since we're using a `Node` and not a string in constructing the JQuery object, patch
    // the object to make it seem like we used a string.  (Marionette expects this.)
    jquery.selector = el;

    return jquery;
  }
}

class QweryLayoutView<T extends Backbone.Model> extends Marionette.LayoutView<T> {
  get regionClass(): { new(...args: Array<any>): Marionette.Region } { return QweryLookupRegion; }
}

export default QweryLayoutView;
```

qwery v4 removed the documentation describing which selectors it doesn't support.  Might be worthwhile to ask @ded if it's fully compatible / if perf is similar to v3.  

Food for thought, in case anyone else runs into the same issue.

**Comment by paulfalgout** [comment]
oh super interesting  cc: @ianmstew 

There's has been some discussion of what it would look like to reduce/remove dependency on jQuery, but it won't make v3.

That said, have you seen Backbone.NativeView?  Particularly: https://github.com/akre54/Backbone.NativeView/blob/master/backbone.nativeview.js#L76 

that's a fairly similar functionality with no external dependencies.. not sure speed-wise how that might compare with qwery.

**Comment by jiaweihli** [comment]
I hadn't heard of this until now.  It should give perf similar to qwery v4, which is also built on top of `querySelectorAll`.

**Comment by paulfalgout** [comment]
I think this can be considered closed since the DOM mixin will allow you to swap it out
