### ISSUE TITLE
Remove spread calls in next

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2849]
https://github.com/marionettejs/backbone.marionette/pull/2847#issuecomment-162008534

**Comment by jasonLaster** [comment]
all spreads, or just the one's w/ apply?

**Comment by paulfalgout** [comment]
just the one's w/ `call`

**Comment by jasonLaster** [comment]
yup. cool

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/blob/next/src/utils/getValue.js#L9

**Comment by ahumphreys87** [comment]
fixed via #2864
