### ISSUE TITLE
how to mixin

### ISSUE THREAD

**Issue by cnfi** [marionettejs/backbone.marionette#2854]
like this: https://github.com/kjbekkelund/writings/blob/master/published/backbone-mixins.md

**Comment by rafde** [comment]
Or use Marionette.Behavior

**Comment by paulfalgout** [comment]
You could do this, or as @rafde behaviors is likely better for Marionette.  There's also https://github.com/marionettejs/backbone-metal

In general my personal preference is to avoid deep inheritance.  So while I may utilize some form of mixing-in / behavior, I don't like to enforce much calling of the parent prototype within an overridden function

Join us on [gitter](gitter.im/marionettejs/backbone.marionette) to continue the discussion!
