### ISSUE TITLE
When a view is attached to an existing element, `isRendered()` should reflect `true`

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2859]
The argument here is that `isRendered()` intuitively means a view does not need to be rendered, which is the case when it is attached to an existing element.  Currently, `isRendered()` is only set during a normal `render()`.  It would be helpful if, as a view is bound to an existing element, `_isRendered` were also set to `true`.

https://github.com/marionettejs/backbone.marionette/pull/2850#discussion_r47439238

/cc @paulfalgout

**Comment by paulfalgout** [comment]
we need to pay attention to how this relates to  `setElement`

**Comment by paulfalgout** [comment]
@ianmstew is this entirely handled now in https://github.com/marionettejs/backbone.marionette/pull/2850 ?

**Comment by ianmstew** [comment]
No, I wasn't considering this one during #2850.  I was, however, considering whether a view bound to an existing element should set `_isAttached`.  I got as far as overriding `setElement()` to add logic that would include an `isNodeAttached()` check, but thought this could get out of hand performance-wise, especially since that check would be entirely redundant in an app build the prescribed way--starting with an application region.

Instead of Marionette core providing first-class support for binding to existing elements, I would rather keep core to "standard use" as a single-page app where a view tree starts with an app region and is built from there.  It might make sense to either provide officially or encourage from the community an "isomorphic" module that, when included, would support attachment to existing elements--but only for those who need it.

@ahumphreys87 has talked about isomorphic Mn before, and there are one or two other issues concerning that... What do you think about separating these concerns from core?

**Comment by ianmstew** [comment]
Then again, we could remove the `isNodeAttached` check from region entirely and have views always perform that check themselves.  That would eliminate redundancy by pushing all checks to the views.  While working on #2850 I was trying to optimize calls to isNodeAttached by what we know about the view tree, but there is certainly a compromise evident when it comes to self-attaching views.

**Comment by paulfalgout** [comment]
Yeah.  Though I don't know that this is a isomorphic aka universal issue necessarily.  [`setElement`](http://backbonejs.org/#View-setElement) is on Backbone.View so not doing this is only kind of partially supporting `Backbone.View`'s API.  Although I'm not 100% sure when you would need to do this where it wouldn't be a better idea to use a region.

**Comment by ianmstew** [comment]
Right, I'm just not sure about supporting an off-path use case if there could be a performance penalty.  I would be more comfortable with it if knew the consequences of overriding `setElement` with our own logic, especially for `_isAttached`...  I think a benchmark is in order.  :)

**Comment by ahumphreys87** [comment]
fixed via #3031
