### ISSUE TITLE
A lot of attributes are not accessible from Behavior declaration

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#2861]
When adding Behaviors in a View and needed to give in some options, view attributes are not set yet, like `cid`

```
    behaviors: function() {
        return {
            foo: {
                behaviorClass: FooBehavior,
                ref: this.cid // undefined
            }
        };
    },
```

I suspect behaviors are resolved way to early.

Another inconvenience, but not a bug, we have to use `this.options.model` to pass in the view model instead of `this.model`

**Comment by paulfalgout** [comment]
When extending Bb.Views you have the choice of running things before `initialize` and not having any of the Bb.View things such as cid, or you have to wait until after the `initialize` in which case nothing that happened during the initialize would be known.  The case with behaviors and regions is that we're calling them before the `initialize` for that reason.  However behaviors also have full access to their view, so passing in most things from the view is not necessary as, with the exception of the behavior's own `initialize` you can reach those things via `this.view.cid`

Certainly interested to hear any alternate solutions, but I think this is a known situation that is the better of two evils.

**Comment by JSteunou** [comment]
I'm confuse right now, I though `initialize` was empty by default and called at the end of the constructor?

**Comment by paulfalgout** [comment]
Correct it is called at the end of the `Backbone.View` constructor
https://github.com/marionettejs/backbone.marionette/blob/master/src/view.js#L24

So if in any view you do something like:
```
var MyView = Marionette.ItemView.extend({
  initialize: function(){
    //currently heard by behaviors because they're init'd before Bb.View's constructor.
    this.render();
    // also heard
    this.triggerMethod('some:foo');
  }
});
```

**Comment by JSteunou** [comment]
Then why `this.cid` would undefined from `behaviors` in Mn.View?

Is this the correct flow?

BB.View#constructor  <--- cid is set
Mn.View#constructor
behaviors lookup  <--- cid should be accessible
initialize

**Comment by paulfalgout** [comment]
This is the flow:
Mn.View#constructor
behaviors lookup
BB.View#constructor <-- cid is set, initialize is called

**Comment by JSteunou** [comment]
Of course! `initialize` is called by BB constructor. And I said it just before =_= I don't know why I pictured it like this... 

I understand the struggling and the choice. Closing this.

**Comment by jasonLaster** [comment]
sorry @JSteunou. it's a tough one :)
