### ISSUE TITLE
Children’s in the CompositeView and CollectionView are not always indexed according to the position that it holds in the model Collection.

### ISSUE THREAD

**Issue by Nageshgowthamjv** [marionettejs/backbone.marionette#2863]
Collection container is an array of models. View Collection(ie children in Marionette) container is an Object. When a new model is inserted at some index with ({at:index}) in collection, view is always inserted at last.
Because,  In an object, last added property always stays last, and converting properties to array of keys will not result is correct index.

``` javascript
              // Find by index. This is not guaranteed to be a
                // stable index.
                findByIndex: function(index) {
                    return _.values(this._views)[index];
                },
```

I also understand from the comment that findByIndex is not stable and developers know about the issue. But it will be great to see that this is fixed.
###### When it affects?
1. If Composite or Collection view is used in any component, with insert at option({at:index}), and looping through each on children will give incorrect result.
2. If Composite or Collection view is used in any component, with insert at option({at:index}), and findByIndex will give incorrect result.
###### My use case

I have a tree structure that is built on Composite view which can grow n-levels. Here node can be moved from any level to any other level which means any composite view to any other. I am using JQuery Sortable to show UI interactions.

I tried detaching the item view itself from Composite view children and adding it to another. But getChildView() provides the reference and adding it to another with add(view, customIndex) didn't help because getChildView and add will not remove old reference and add will result in custom indexing only for item views which are inserted later through add manually.

I also tried using removeChildView() to remove the child view. but it destroys the removed child view and makes it not reusable.

I wanted move only views instead of models because my tree can contain more than 30000 nodes and each node can contain large meta data. It will be very difficult to copy meta data to new node if i don't move view itself.

Finally i have done it trough copying model and adding it to composite view model collection with add(model,{at:index}). but it will be good to move view itself.

**Comment by paulfalgout** [comment]
It looks like when `findByIndex` was added initially to babysitter it was considered unstable.  I'm not sure the caveats here, or really even where the issue shows up exactly.  I'm pretty sure I follow you, but a jsfiddle or something would be very useful.

**Comment by Nageshgowthamjv** [comment]
Here is the link to jsfiddle : http://jsfiddle.net/nagesh/csp1age5/

Move the node from one position to other by dragging and dropping.
what we see in the DOM will be correct but the view position will not be correct ( dropped node view will be always at the bottom).

Also  this will give incorrect view after multiple moves as last added view is at bottom
    var node = that.children.findByIndex(sortHelper.from);

Let me know if any thing required.

**Comment by ahumphreys87** [comment]
@Nageshgowthamjv sorry for the stale thread. Have you considered maintaining the order in the `Collection` rather than the `View`?

**Comment by Nageshgowthamjv** [comment]
@ahumphreys87 , 

Here is the code that is moving the node from one position to another position. Since node is removed and again added at new position with `{ at : toIndex }` in collection, order in collection is correct. jsfiddle : http://jsfiddle.net/nagesh/csp1age5/ shows the same in red color.

```
    that.collection.remove(node.model);

    that.collection.add(user, {
      at: sortHelper.to
    });
```

**Comment by ahumphreys87** [comment]
Yeah so the problem is that babysitters indexes do not get updated along with the CollectionView DOM.

I would discourage using this method. How attaching a data attribute to the node you move and use that to retrieve the model? Maybe the `cid`?
