### ISSUE TITLE
CollectionView#showCollection rendering performance issue

### ISSUE THREAD

**Issue by rafde** [marionettejs/backbone.marionette#2873]
Marionette 2.4.4
BackboneJS 1.2.3 
underscore 1.8.3
jQuery 2.1.3

http://codepen.io/rafde/pen/GorLyg?editors=101

![perf issue](https://cloud.githubusercontent.com/assets/833429/12102474/c9f1f646-b2ef-11e5-9556-4651b061f33a.gif)

When Marionette renders a collection view of 3000 models, the view takes (on my computer) between 2.5 and 3 seconds to render the entire collection.

Using Chrome Dev tools, I saw these lines affect rendering performance.

https://github.com/marionettejs/backbone.marionette/blob/v2.4.4/lib/backbone.marionette.js#L84
https://github.com/marionettejs/backbone.marionette/blob/v2.4.4/lib/backbone.marionette.js#L2634
https://github.com/marionettejs/backbone.marionette/blob/v2.4.4/lib/backbone.marionette.js#L2577

To go around this, I ended up extending the collection view and overwriting the Marionette implementation
https://github.com/marionettejs/backbone.marionette/blob/v2.4.4/lib/backbone.marionette.js#L2414
```js
showCollection: function() {
      var ChildView;
      var models = this._filteredSortedModels();
      var childViewOptions = this.getOption('childViewOptions');
      var firstView;
      var firstIndex;

      if (models.length) {
        ChildView = this.getChildView(models[0]);

        _.each(models, function(child, index) {
          var computedChildViewOptions = Marionette._getValue(childViewOptions, this, [child, index]);
          var view = this.buildChildView(child, ChildView, computedChildViewOptions);

          if (_.isUndefined(firstView)) {
            firstView = view;
            firstIndex = index;
          }

          this.triggerMethod('before:add:child', view);
          this._addChildView(view, index);
          this.triggerMethod('add:child', view);

          view._parent = this;
        }, this);
        //UPDATE index after everything is done adding.
        this._updateIndices(firstView, true, firstIndex);
        this.children._updateLength();
      }

      return this;
},
// Internal Method. Add the view to children and render it at
// the given index.
_addChildView: function(view, index) {
      // Only trigger attach if already shown, attached, and not buffering, otherwise endBuffer() or
      // Region#show() handles this.
      var canTriggerAttach = this._isShown && !this.isBuffering && Marionette.isNodeAttached(this.el);
      var nestedViews;

      // set up the child view event forwarding
      this.proxyChildEvents(view);

      view.once('render', function() {
        // trigger the 'before:show' event on `view` if the collection view has already been shown
        if (this._isShown && !this.isBuffering) {
          Marionette.triggerMethodOn(view, 'before:show', view);
        }

        // Trigger `before:attach` following `render` to avoid adding logic and event triggers
        // to public method `renderChildView()`.
        if (canTriggerAttach && this._triggerBeforeAttach) {
          nestedViews = this._getViewAndNested(view);
          this._triggerMethodMany(nestedViews, this, 'before:attach');
        }
      }, this);

      // OVERWRITE what Marionette is doing to prevent calling
      // Backbone.ChildViewContainer#_updateLength
      this.children.addBulk(view);

      this.renderChildView(view, index);

      // Trigger `attach`
      if (canTriggerAttach && this._triggerAttach) {
        nestedViews = this._getViewAndNested(view);
        this._triggerMethodMany(nestedViews, this, 'attach');
      }
      // Trigger `show`
      if (this._isShown && !this.isBuffering) {
        Marionette.triggerMethodOn(view, 'show', view);
      }
},
```js
and had to create a new function like 
https://github.com/marionettejs/backbone.marionette/blob/v2.4.4/lib/backbone.marionette.js#L72
but one that doesn't do `_updateLength`
```js
addBulk: function(view, customIndex) {
  var viewCid = view.cid;
  // store the view
  this._views[viewCid] = view;
  // index it by model
  if (view.model) {
    this._indexByModel[view.model.cid] = viewCid;
  }
  // index by custom
  if (customIndex) {
    this._indexByCustom[customIndex] = viewCid;
  }
  //REMOVED index updater
  return this;
},
```
This fixed the major bottlenecks but there are other parts that weren't addressed such as simple `ItemView` event delegation also slows down rendering when a `CollectionView` renders it. This fix is also a hack for the case that I need it to render.

I am looking for some input on a potential improved approach to dealing with major collectionView rendering.

**Comment by paulfalgout** [comment]
While I'm sure there's work to be done around perf in larger collections, much of what you're looking at would be much faster if you set `sort: false` on your `CollectionView`  Maintaining the sort of very large collections might not be reasonable.  That'll probably halve the time.  The other findings seem to relate to backbone.babysitter which certainly needs some looking into.

Thanks a bunch for the research!

**Comment by rafde** [comment]
Thanks for `sort: false`, @paulfalgout .
Something else I notice was how `ItemView.triggerMethod` in CollectionViews can also be expensive.
Same thing for Backbone.View.delegateEvents and undelegateEvents. The expense is small in comparison to what I mentioned earlier. Not sure what can be done though since the delegate stuff is all Backbone. I ended up `_.noop` ing those functions and doing something like
```
var itemViewSymbol = Symbol('itemview');
...
// MyItemView
// It's a very stripped view.
...
className: 'js-item-view',
initialize: function (){
  this.el[itemViewSymbol] = this;
},
triggerMethod: _.noop,
delegateEvents: _.noop,
undelegateEvents: _.noop
...

// MyCollectionView
...
ui:{
  itemView: '.js-item-view'
},
events:{
  'click @ui.itemView: 'onItemViewClick'
},
onItemViewClick: function (event){
  var itemView = event.currentTarget[itemViewSymbol];
  if(itemView instanceof Marionette.ItemView){
  // do something.
  }
},
...
```
which allows me to do DOM event view delegation from the CollectionView.
Looking to squeeze as much performance as possible.

**Comment by paulfalgout** [comment]
Yeah Mn v3 will cut down on some of the event noise for child views..  I am hoping that we can stop auto-proxying events in the following version such that most events are opt-in for situations such as these.

However at this point, if you aren't using the child views for any particular delegation you might as well just use an itemView and render the collection.  http://marionettejs.com/docs/v2.4.4/marionette.itemview.html#rendering-a-collection-in-an-itemview

Well except I suppose you are trying to tell the children apart from each other for your click event?

You could also try making a leaner Backbone.View to use as a child for this instance.  You may still need to noop the event delegation stuff, and you'll have to write your own `render` but it'd be bare minimum.

**Comment by rafde** [comment]
I am unsure of how to deal with this issue other than by addressing it by PR, but finding time the time to address this issue can be tough. The way I dealt with the issue I already posted in my previous comments, but I don't like the way I did some of it.
I also found some issues with `CollectionView#destroyChildren` taking a long time to run also.

I guess a plan of action would be ideal to create in order to start thinking of some possible solutions.
So I think a good start would be:

* Come one with a way for `CollectionView` to handle adding multiple `ChildViews` that will be sorted.

Which can be done by doing `CollectionView#_updateIndices(firstView, true, firstIndex);` after all the children have been added and knowing where to start updating the indices.

* `Backbone.ChildViewContainer#add` conditionally use `Backbone.ChildViewContainer#._updateLength`

Or create a `@private` function that is used by the`@public` `Backbone.ChildViewContainer#add` which will do the `updateLength` where the private function will not. The private function will fall into use by the function that adds multiple views.

Unless there has been some thought and execution done already from a contribute that has been committed, I'll try submitting a PR at some point when I have the time.

**Comment by samccone** [comment]
@rafde mind opening up a PR so this is easier to talk about?

**Comment by rafde** [comment]
Will try some time tonight. Just posting to assure I am not copping out.

**Comment by rafde** [comment]
So one of the first problems I want to address has to do with creating a function that moves https://github.com/marionettejs/backbone.babysitter/blob/master/src/childviewcontainer.js#L31-L44 into another function that gets called by https://github.com/marionettejs/backbone.babysitter/blob/master/src/childviewcontainer.js#L30
but I am having trouble running the test suite for the babysitter code.
Trying to run the test on a vagrant box, but it's not giving me a good time. Will try to resolve tomorrow.

**Comment by samccone** [comment]
@rafde mind posting the error you are hitting when trying to run the tests?

**Comment by rafde** [comment]
I was trying to do everything via a vagrant box on a Windows host machine. Switched to a *nix based OS and `npm install` worked fine now.

I made a PR for Babysitter childviewcontainer to address my first need before I start creating a PR to address the performance issue.
