### ISSUE TITLE
If a composite view is used for building tree view, upon re-rendering nodes, nodes from 3rd level gets destroyed. 

### ISSUE THREAD

**Issue by Nageshgowthamjv** [marionettejs/backbone.marionette#2874]
If a composite view is used for building tree view, upon re-rendering tree,nodes from 3rd level gets destroyed. 

When i went trough code, i see that only one level is rendered. collection which was available in the childView is destroyed and hence next level is also destroyed.

```javascript
// Renders the model and the collection.
        render: function() {
            this._ensureViewIsIntact();
            this._isRendering = true;
            this.resetChildViewContainer();

            this.triggerMethod('before:render', this);

            this._renderTemplate();
            this._renderChildren();

            this._isRendering = false;
            this.isRendered = true;
            this.triggerMethod('render', this);
            return this;
        },
```

```javascript
        // Internal method. Separated so that CompositeView can have
        // more control over events being triggered, around the rendering
        // process
        _renderChildren: function() {
            this.destroyEmptyView();
            this.destroyChildren();

            if (this.isEmpty(this.collection)) {
                this.showEmptyView();
            } else {
                this.triggerMethod('before:render:collection', this);
                this.startBuffering();
                this.showCollection();
                this.endBuffering();
                this.triggerMethod('render:collection', this);

                // If we have shown children and none have passed the filter, show the empty view
                if (this.children.isEmpty()) {
                    this.showEmptyView();
                }
            }
        },
```

Since compositeView is the only view Which can be used to represent the hierarchical data, all the nested collections also should be remembered and re-rendering. There should not be any data loss.

**Comment by paulfalgout** [comment]
Hmm I'm not sure how re-rendering would be acting different than the initial render?  essentially `renderChildren` calls `showCollection` which will build the children, and in the case of a tree hierarchy, the children should be itself to rebuild the tree.

I'm not sure where it could be broken.  Can you setup a relevant jsfiddle?

**Comment by Nageshgowthamjv** [comment]
First Time when tree is created, all the hierarchical data is sent as an input to composite view.
once the node is created, **children** attribute is deleted and new collection is created and fed as an input to child view.  

When all the nodes are rendered, data in the model may change on certain action. To show the model changes i have to re-render the tree or re-render the branch from where change has occurred.

Since changes are not available in the main JSON that i have sent as input, i feel re-render should consider the collection that has been already created for re-rendering the tree.

Here is the link to jsfiddle
http://jsfiddle.net/nagesh/wgmt0jd3/2/

Let me know if anything is required ...

**Comment by paulfalgout** [comment]
I would recommend not mutating the original data.  Don't deleting the attribute.

you can `omit` the `children` in `serializeData`

http://jsfiddle.net/nagesh/wgmt0jd3/2/

**Comment by Nageshgowthamjv** [comment]
@paulfalgout , 
I have updated jsfiddle with ```updateModelData``` method. It appends the ```node``` in model with ```0``` every time "Update and Re-Rerender" is clicked.

So here every time button is clicked, only model holds the newly modified data and children holds the old data. Deleting children should not affect the re-rendering correct? 

updated jsfiddle:
http://jsfiddle.net/nagesh/wgmt0jd3/4/

**Comment by paulfalgout** [comment]
a re-render is the same as the initial render.  So if you can initially render the tree without ever having the children data, then you can re-render the tree without it. 

I think you are wanting to render the model and the childViewContainer, without re-rendering the children, but that is not something that CompositeView does.

In a far future version of Mn we will hopefully be able to re-render a layout without destroying the children and perhaps this could work.

But currently if you re-render a view that has children, all of its children are destroyed and rebuilt.  So you will need the data to rebuild the children or it will not work as expected.

**Comment by Nageshgowthamjv** [comment]
Thanks for your time @paulfalgout 

I am not sure how to render a tree with out children, but i will write a method to refresh the DOM instead of re-rendering view when model changes.
