### ISSUE TITLE
[idea] CollectionView rerender only one child

### ISSUE THREAD

**Issue by stepan-perlov** [marionettejs/backbone.marionette#2877]
Hi.

This is my dirty implementation.
If you agree with this idea I can try to add it to marionette.

```javascript
var originConstructor = Mn.CollectionView.prototype.constructor;
Mn.CollectionView.prototype.constructor = function(options) {
    var self = this;
    this.childEvents = this.childEvents || {};
    this.childEvents["child:changed"] = function(view, callback) {
        self.onChildChanged(view, callback);
    })
    originConstructor.apply(this, arguments);
}

Mn.CollectionView.prototype.onChildChanged = function(view, callback) {
    var NewViewClass = this.childView || this.getChildView(view.model);
    var newView = new NewViewClass(model: view.model);

    newView.triggerMethod("before:render");
    newView.render();
    newView.triggerMethod("render");

    var $nextEl = view.$el.next();
    var $parent = view.$el.parent();

    newView.triggerMethod("before:attach");
    if ($nextEl && $nextEl.length) {
        $nextEl.before(newView.el);
    } else {
        $parent.append(newView.el);
    }
    newView.triggerMethod("attach");

    view.remove();
    this.children.remove(view);

    this.proxyChildEvents(newView);
    this.children.add(newView);
    (callback || _.noop)(newView);
}
```

**Comment by JSteunou** [comment]
Thank you for the idea but I dont get it. Why not just call `render` from inside the childView?

Usually people do listen to `change` event inside childView and call render in it, or do partial update manually or with data binding like with backbone.stickit

**Comment by stepan-perlov** [comment]
I need change childview. getChildView function will return another view class

Example

I have list of news and click edit on one of this.

**Comment by JSteunou** [comment]
The other way would be each childView be a LayoutView with a region with the *real* childView in it. On change event the LayoutView would update the *real* childView inside the region.

This would add 2 more nodes but I find it more easy to read, especially if you're working in a team. This pattern will be easier with v3 as any view could have children.

**Comment by stepan-perlov** [comment]
ok. thanks for information.
