### ISSUE TITLE
One hook for view dom upgrading when region.show(view) and view.render

### ISSUE THREAD

**Issue by stepan-perlov** [marionettejs/backbone.marionette#2878]
When route change I call region.show(view).
This action call render, then show -> hooks: onRender, onShow.
When called onRender view.el didn't attached to html.

When I did interaction on this route, for example add another element, I call view.render.
This action call render -> hook: onRender.
When called onRender view.el attached to html.

**Comment by paulfalgout** [comment]
I think you might be looking for `onDomRefresh` which is the result of the first `show` and every following `render`
The behavior of this is improved for `v3`, but for the common case this event should work fine.

**Comment by stepan-perlov** [comment]
thank you
