### ISSUE TITLE
A concept which could offer template designers more control.

### ISSUE THREAD

**Issue by howardroark** [marionettejs/backbone.marionette#2879]
Hey!

I have been playing with a concept that I think could be a useful part of this library.  The example is pretty self explanatory. The approach could easily be a conditional part of ItemView.  The idea is to help template designers make html changes without needing to change the core application code.

https://gist.github.com/howardroark/dd818d44ecaffbccc40a

Just wondering if anyone else thought this concept had merit :P

**Comment by howardroark** [comment]
I figured it would be best as a plugin, so I made one :P 

https://github.com/everysquare/marionette.templateview

I'll close this up for now.

**Comment by JSteunou** [comment]
Well, it's nice force those using inline templates. But a lot of us use template engine like Handlebars so our template designers just write HTML. Used with package builder like webpack and ES6 or CJS syntax it make it cleaner.

```
var FooView = Marionette.ItemView.extends({
  template: require('./foo.hbs'),
  // ...
});
```

**Comment by howardroark** [comment]
Good point!  I updated it have inline as an option and be more about general efficiencies when working with templates :)

https://github.com/everysquare/marionette.templateview
