### ISSUE TITLE
Reserved region names?

### ISSUE THREAD

**Issue by stackptr** [marionettejs/backbone.marionette#2882]
Just ran into this tonight, seems like a LayoutView with a `regions` hash specifying an `events` key will end up with the actual `events` never bound to the DOM.

Makes sense, since `this.regionName` would collide with `this.events` in this case. However, no errors emitted and it took a while to figure out what was going wrong. In hindsight this sort of thing seems obvious to avoid, but perhaps it would be good to include in documentation or provide a built-in error?

**Comment by paulfalgout** [comment]
This is documented here: http://marionettejs.com/docs/v2.4.4/marionette.layoutview.html#region-naming
Although it isn't super defined.. the abbreviated list of names has some glaring omissions.  However this issue has been addressed in `v3` and it is recommended that regions only be used via `getRegion` as they will no longer be attached directly to the view.
v3 should have a release candidate very shortly.
