### ISSUE TITLE
render a collection

### ISSUE THREAD

**Issue by tomaspl** [marionettejs/backbone.marionette#2883]
Do you know how can I render a collection? Because the list comes from a java service and it returns me a json. There, i need to enter to an specify list and there i have the items of the collection i need

      EventManager.Evento =Backbone.Model.extend({
            urlRoot:"BusquedaLaboralActionGetBusquedasLaborales"
        });
        EventManager.EventosCollection =Backbone.Collection.extend({
            //i need to enter to listaBusquedasLaborales bacause mi JSON returns something like this:
            // [
            //     {
            //     listaBusquedasLaborales:[
            //         {
            //             id:1,
            //             date:"2015-06-23T12:00:00Z"
            //             name:"Curso de Marionette",
            //             categoria:"Marketing",
            //             lugar:"Lima, Perú"
            //         },
            //         {
            //             id:2,
            //             date:"2015-06-23T12:00:00Z"
            //             name:"Curso de LoQueSea",
            //             categoria:"Diversión",
            //             lugar:"Montevideo, Uruguay"
            //         }
            //     ]}
            // ]
            url:"BusquedaLaboralActionGetBusquedasLaborales",
            model:EventManager.Evento
        });

**Comment by paulfalgout** [comment]
Not 100% sure of your needs here, but if this is all of the info you want off this endpoint, it seems like you want:
```
EventManager.EventosCollection = Backbone.Collection.extend({
  parse: function(data){
    return data[0].listaBusquedasLaborales;
  }
  url:"BusquedaLaboralActionGetBusquedasLaborales",
  model:EventManager.Evento
});
```

**Comment by tomaspl** [comment]
hello, i was testing your solution but return an error:
data[0] is undefined.

I dont have problem if the json is

**Comment by tomaspl** [comment]
Hello I was testing your answer but it returns me an error:
data[0] is undefined.

If my json were like this I would not have problem:

        // [
        //        {
        //             id:1,
        //             date:"2015-06-23T12:00:00Z"
        //             name:"Curso de Marionette",
        //             categoria:"Marketing",
        //             lugar:"Lima, Perú"
        //         },
        //         {
        //             id:2,
        //             date:"2015-06-23T12:00:00Z"
        //             name:"Curso de LoQueSea",
        //             categoria:"Diversión",
        //             lugar:"Montevideo, Uruguay"
        //         }
        // ]

I need to enter to listaBusquedasLaborales to access to the list and there becomes the problem to render it

**Comment by paulfalgout** [comment]
your original example was and array with on object in it.  You can simply `console.log(data)` to see what you need to return from the endpoint in the parse.  perhaps it only needs to be:
```
  parse: function(data){
    console.log(data);  //return the data you want for your collection from data.
    return data.listaBusquedasLaborales;
  }
```

**Comment by tomaspl** [comment]
Yes, It works! It was "return data.listaBusquedasLaborales".
Thanks a lot!
