### ISSUE TITLE
Central Marionette.Application events fire twice if event name has space

### ISSUE THREAD

**Issue by singhvijayy** [marionettejs/backbone.marionette#2885]
Lets say I have

    var Usertracker= new Marionette.Application();
    Usertracker.vent= _.extend({}, Backbone.Events);

    var Router= Backbone.Router.extend({
    		    routes:{
		   	    "first": "route1"
		    },
		
		    route1: function(){
			    var str= "tree";
			    Usertracker.vent.trigger("current: first", str);
		    }
    });

    Usertracker.vent.on("current: first", function(str){
                    console.log("1st "+str);
    });

when we go to localhost8080#first and press Enter, 1st tree is logged twice!

However, if we change the vent.trigger("current: first", str); to vent.trigger("current:first", str); 
we get 1st tree logged once (as it should be).

Spacing creates a problem in events bound to central Marionette Application Object.

**Comment by JSteunou** [comment]
This is due to Backbone.Events. Backbone split event name by spaces, so your example triggers `current:` & `first` and your listener is listening to `current:` & `first`. Nothing wrong, but understand you might be surprised.

**Comment by paulfalgout** [comment]
Yep, as @JSteunou mentioned, this is a feature of `Backbone.Events` which Application uses spaces indicate multiple events to trigger or listenTo
