### ISSUE TITLE
Jquery as a devDependency ?

### ISSUE THREAD

**Issue by ThomasCrvsr** [marionettejs/backbone.marionette#2886]
In the `package.json` I was looking for jquery in the dependencies but I surprisingly found it in the devDependencies. It may be a silly question but is it deliberate ?

**Comment by paulfalgout** [comment]
jQuery is used in the test runner, but it's more of a dependency of backbone, not Marionette.  Marionette strictly uses `Backbone.$`

**Comment by JSteunou** [comment]
Using Backbone you can replace jQuery by Zepto and as @paulfalgout said Marionette use what Backbone exposes, not requiring jQuery explicitly.

**Comment by ThomasCrvsr** [comment]
Yep, I get it ^^ So to be more consistent, jquery should be removed from the bower.json deps, shouldn't it ?

**Comment by JSteunou** [comment]
Or maybe remove bower.json, who's still using it? :p Just kidding, but yeah you might got a point here.

**Comment by paulfalgout** [comment]
Yep I think removing it from bower is reasonable.  @ThomasCrvsr want to make a PR?
Looks like this conversation has happened before, it just hasn't changed https://github.com/marionettejs/backbone.marionette/commit/4c2cc6307a636e9a44ddb8b5385241d8c5429ea1#commitcomment-5873557

If you are up for it, and don't mind making it off the `next` branch that'd be great

**Comment by ThomasCrvsr** [comment]
@paulfalgout Yep ! I'll try to do it today and if not tomorrow morning ^^
