### ISSUE TITLE
Behavior event bind error when no handler is specified

### ISSUE THREAD

**Issue by happylinks** [marionettejs/backbone.marionette#2888]
Hi,

I spend some time debugging a bug I made when I removed a behavior method but left the event that referenced that handler.

The error is because here:
https://github.com/marionettejs/backbone.marionette/blob/master/src/behaviors.js#L61
```
var handler   = _.isFunction(behaviour) ? behaviour : b[behaviour];
_events[eventKey] = _.bind(handler, b);
```
it isn't checked if the handler is a function with _.isFunction.
If it is not we could return a error message so it's easier to debug.

Shall I make a pullrequest for this? I'm not sure if logging these kind of errors is encouraged.

**Comment by JSteunou** [comment]
Backbone dont with `events` and marionette does not with `modelEvents` and `collectionEvents` but indeed could be a cool thing for debugging. Does [marionette.inspector](https://chrome.google.com/webstore/detail/marionette-inspector/fbgfjlockdhidoaempmjcddibjklhpka) help on this @paulfalgout?

**Comment by paulfalgout** [comment]
So backbone bails with behaviors it looks like https://github.com/jashkenas/backbone/blob/1.2.3/backbone.js#L1278

We should really probably be doing whatever backbone is doing.  I'm not sure if inspector would help with this specifically, but it is an interesting idea.

**Comment by paulfalgout** [comment]
Ah FWIW `v3` aligns with the Bb behavior https://github.com/marionettejs/backbone.marionette/blob/next/src/behavior.js#L102

I do think there might be a `2.4.5`.  @happylinks if you wanted to add the bail ala backbone for the non-existing event I would :+1:

**Comment by happylinks** [comment]
Ok, thanks for checking it. I'll make a pullrequest for it!

**Comment by paulovieira** [comment]
Uhmm, this was actually a nice feature of marionette, i'm sad to see it go. You could save some precious debugging time if marionette tells you right away that the method is missing (a common mistake when the name of method is long).

I don't see much sense in imitating backbone just for the sake of it, especially the questionable parts.

What about add a "DEBUG" flag to the `Marionette` object and warn the user about this kind of problems when it is true? This would align with Radio:

https://github.com/marionettejs/backbone.radio/blob/master/src/backbone.radio.js#l21
