### ISSUE TITLE
CompositeView filter function hides all child views in Safari

### ISSUE THREAD

**Issue by GaryRogers** [marionettejs/backbone.marionette#2893]
With the following code filtering child view working in Chrome, Firefox, IE, but hides all children in Safari (Both MacOS X and iOS). I have simplified to the filter to return just true/false and still have the same problem. The Safari JS Console doesn't throw any errors. 

```
my.View.List  = Marionette.CompositeView.extend({
        el: "#list",
        template: "#tmpl_database_list",
        childView: my.View.Item,
        childViewContainer: 'ul',
        filterValue: "",
        filter: function (child, index, collection) {
            if (this.filterValue != "") {
                if (typeof child.get('SLUG') == "string" && child.get('SLUG').toLowerCase().match(this.filterValue.toLowerCase())) {
                    return child;
                }
            } else {
                return collection;
            }
        },
        ui: {
            "add": "#form_CREATE",
            "filter": "#form_filter",
            "filter_clear": "#filter_clear"
        },
        events: {
            "change @ui.filter": function () {
                var self = this;
                var filter = $('#form_filter');
                self.filterValue = filter.val();
                self.render();
                self.$el.find('#form_SEARCH').html('<i class="fa fa-search"></i> Filter: ' + self.filterValue).removeClass('btn-default').addClass('btn-info');
            },
            "click @ui.filter_clear": function () {
                var self = this;
                self.filterValue = "";
                self.render();
            },
            "click @ui.add": function() {
                var self = this;
                var new_model = self.collection.add(new my.Model.Database());

                var createView = new my.View.Edit({model: new_model});

                $('#modal').html(createView.render().el).find('.modal').modal('show');
            }
        },
        onRender: function () {
            var self = this;

            $('#form_filter').val(this.filterValue);
        }
    });
```

**Comment by JSteunou** [comment]
Never seen that kind of issues while I'm using this feature at some places, and using all browsers.

You're using a lot html id `#`, do you have any double by any chance? Did you try without CSS? You are also using a lot of manual `render`, Marionette is more about `regions` to put views in, and `ui` to avoid dynamic jquery find.

**Comment by GaryRogers** [comment]
I'm wondering if maybe Safari handles the match differently. I'll poke at that today.

The jQuery find stuff is just to update a button on the form to display the filter text.

**Comment by GaryRogers** [comment]
Even changing the filter down to be a simple `return true` causes the views to disappear.

**Comment by JSteunou** [comment]
Could you write a fiddle reproducing the issue?

**Comment by GaryRogers** [comment]
Can't reproduce in fiddle. Must be interaction with bootstrap or some other component. Thanks for pointing me in a different direction.

**Comment by JSteunou** [comment]
No problem

**Comment by GaryRogers** [comment]
Turns out it was related to how Safari handles the enter keypress. I trapped that and made `event.keyCode == 13` fire a `blur` event and things worked just fine.
