### ISSUE TITLE
CompositeView.emptyView not shown when filtered collection is empty

### ISSUE THREAD

**Issue by akupiec** [marionettejs/backbone.marionette#2896]
In case when CompositeView is set up with:
non empty collection
implemented CompositeView.filter method 
reorderOnSort property set to true

After calling collection.sort() filter method is being called, but if all models are filtered out then emptyView should render.

And because there is no access to filtered models by collection.sort() to workaround it I have to filter again collection manually and render it if its empty.

**Comment by paulfalgout** [comment]
A jsfiddle or a breaking test would be super helpful if you can

**Comment by paulfalgout** [comment]
Any additional info so this can be investigated would be useful!  Thanks.

**Comment by akupiec** [comment]
I'm sorry for delay. I will do my best to add reproduction sample today.

**Comment by jamesisaac** [comment]
Believe this is due to the first issue I describe in #2948

**Comment by paulfalgout** [comment]
I _think_ this bug was introduced in `2.4.4` and I'm not sure setting the filter is necessary to recreate.  I can't quite nail it down exactly, but I've seen this issue on a `CollectionView`utilizing `reorderOnSort` that had an empty collection that was then `collection.sort()`ed that did not use the `filter`

**Comment by scott-w** [comment]
Shall we close this as not relevant to v3?

**Comment by paulfalgout** [comment]
I think this issue is also true for `CollectionView`.. but this might be fixed in `v3.1`, but I believe it still exists in `3.0`
