### ISSUE TITLE
Add PR and issue templates

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/backbone.marionette#2897]
Might be a good idea to add these to the repo:

**Pull request template**
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Issue template**
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by paulfalgout** [comment]
Agreed :+1:

**Comment by denar90** [comment]
fixed by #3011
