### ISSUE TITLE
Get selector of region

### ISSUE THREAD

**Issue by Jameskmonger** [marionettejs/backbone.marionette#2902]
I've created a region `_testRegion` for selector `.test-region-container` in my class `Foo` with the following method:

    this.addRegion('_testRegion', '.test-region-container');

Now, for testing purposes, I'd like to be able to check that the region `_testRegion` was created for the correct selector.

I imagine I would do something like the following:

    fooInstance.getRegion('_testRegion').getSelector();

But I can't see any mention of functionality like that in the [LayoutView documentation](https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.layoutview.md)

**Comment by scott-w** [comment]
Is the functionality in the Regions documentation: https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.region.md

**Comment by Jameskmonger** [comment]
No @scott-w it doesn't appear in that documentation either.

**Comment by scott-w** [comment]
I don't this is the "right" way to do it but you may be able to do `fooInstance.getRegion('_testRegion').$el.selector` to check.

Whether it's worth adding a specific method to handle this case, I'm not entirely sure. Is this something that people will want to do regularly?

**Comment by Jameskmonger** [comment]
I think it is something that could be quite valuable for people who want to TDD projects without using an external dependency such as JQuery. Would you be willing to accept a PR for the change?

**Comment by paulfalgout** [comment]
So regions don't _have_ to be built from a selector, you can pass in a DOM element.. so in `2.x` it does use the `$.selector` to determine what selector was previously used.. However that is deprecated and scheduled for removal in jQuery v3, and it was never a very reliable attribute to begin with. In Marionette `v3` the `selector` or the `el` that the view gets instantiated with will be stored on `_initEl` which shouldn't be used for production, but might be reasonable for a test:
https://github.com/marionettejs/backbone.marionette/blob/next/src/region.js#L20

**Comment by Jameskmonger** [comment]
Thanks @paulfalgout. This isn't for production use, only for test purposes, so that will be fine.

I'll close this issue now - thanks @scott-w and @paulfalgout
