### ISSUE TITLE
collectionview defer > 1 childviews

### ISSUE THREAD

**Issue by elgubenis** [marionettejs/backbone.marionette#2903]
hey, not an issue though but i wanted to know if anybody had the luck to implement some sort of behavior e.g. for deferring n + childviews, not sure if that explains it, what I mean with that is that the 1st child of a collectionview gets rendered directly (using for example show on some region) but that the other childviews are getting rendered n time unit after the first child was rendered, or is that maybe default behavior? (just without a variable unit)

**Comment by JSteunou** [comment]
better to ask on SO or gitter https://gitter.im/marionettejs/backbone.marionette

**Comment by paulfalgout** [comment]
This is not how I'd put together the code, but a simple model of how it could work...
```js
function showCollectionView(myCollection) {

  var viewCollection = new Backbone.Collection([myCollection.at(0)]);
  var index = 1;
  var myCollectionView = new Marionette.CollectionView.extend({
    collection: viewCollection
  });

  region.show(myCollectionView);

  var interval = setInterval(function() {
    if(index === myCollection.length) {
      clearInterval(interval);
      return;
    }
    viewCollection.add(myCollection.at(index));
    index++;
  }, 1000);
}
```
