### ISSUE TITLE
bug use with requirejs

### ISSUE THREAD

**Issue by tastafur** [marionettejs/backbone.marionette#2907]
Hi,

My mainjs fails why it's trying to instantiate backbone.babysitter and backbone.radio at the same time.

how could i manage this bug?

thanks in advance

Ruben

**Comment by scott-w** [comment]
Hi @tastafur 

Do you have an example of the code that's failing as well as the error message you're seeing?

Regards,
Scott

**Comment by tastafur** [comment]
hi @scott-w 

i thought backbone.radio and babysitter code was included into the marionnete code, but i realize that requirejs calls both, backbone.radio and babysitter code.

anyway, thanks for your response
Ruben

**Comment by paulfalgout** [comment]
It is included in one build if downloaded off the website, but for other builds or npm/bower it'll only be the core.
