### ISSUE TITLE
Should Bb and _ be peer dependencies?

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2909]
This seems like it would help fix the pains everyone has when Bb updates before Mn can, but it will throw a warning if there is an issue.  It looks like it was started at one point, but wasn't merged https://github.com/marionettejs/backbone.marionette/pull/1296

We could also do it for all of the various dependencies.. Radio.. babysitter etc. which would prevent having to upgrade all of the libraries at once.

Plus it would help with reoccurring issues: https://github.com/marionettejs/backbone.marionette/pull/1296  https://github.com/marionettejs/backbone.marionette/issues/2907 https://github.com/marionettejs/backbone.marionette/issues/2559

Is there any reason not to do this?
It might open us up for having to troubleshoot breaking changes for Bb versions directly after a release. However I think those will be less harmful than the issues we deal with now when a version is released.

@marionettejs/marionette-core please weigh in.

**Comment by MeoMix** [comment]
I don't see why it would invite having to troubleshoot breaking changes for BB versions directly after a release. Just describe the peerDependency locked to a certain version or lower.

Seems like a pretty simple win? The only question is how to handle the fact BB doesn't do semver. It'd be nice to just say "Mn works with only the current major version of BB and all minor/patch", but, as we see, BB has breaking issues in minor revs. So, maybe it'd be better to just lock it at whatever the current BB version is and, at our leisure, bump it once we have confidence in a BB version?

Note that all of this is written with a pretty minor understanding of npm's dependency management. I just skimmed: https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by paulfalgout** [comment]
Additionally once everything is run off of peer dependencies, we should be able to run tests off of the backbone master branch to get ahead of the issues we're seeing with the `1.3.1` release

**Comment by samccone** [comment]
I know peer deps come with a ton of issue / complexities -- I think it is worth some serious investigation around this before deciding one way or the other.

**Comment by paulfalgout** [comment]
https://github.com/npm/npm/issues/6565#issuecomment-76488227
I think changing to `peerDependency` will make some things harder for people using npm < 3 if they don’t specify what version of backbone/underscore to use.. however I suspect the common use-case is that people are already installing backbone and underscore.. which is often why when Bb or _ updates we get a ton of issues.
I think this'd be more of a headache if marionette was a frequent dependency of some other library, and people who consumed that other library didn't install or really know what marionette was.. but in this case because Mn is essentially at the top of the chain, it should be very reasonable to say:
```
npm i underscore
npm i backbone
npm i backbone.marionette
```
and you're good to go.

**Comment by ahumphreys87** [comment]
Im :+1: for this, if we're gonna do it - we should do it for the next 3.0.0 rc.

It opens the door for us to provide hooks to make jquery optional in 4.0.0

**Comment by paulfalgout** [comment]
Yep this stuff is getting out of hand: https://github.com/marionettejs/backbone.marionette/issues/2559
And people are just shimming around the dependency issue.  They are using peer dependency even if we aren't, and we should support a feature rather than passively supporting a hack.

Worst case if this is a disaster it will most likely be a non-breaking change to eventually switch back to hard setting the backbone dependency.

**Comment by ahumphreys87** [comment]
I agree, let's get this into the next rc

**Comment by paulfalgout** [comment]
What does this mean for bower?

**Comment by paulfalgout** [comment]
I think I still like peer dependencies, but we could also consider just bundling everything.. https://medium.com/@Rich_Harris/how-to-not-break-the-internet-with-this-one-weird-trick-e3e2d57fee28#.oj9lejd0l

Seems dirty though.

**Comment by JSteunou** [comment]
Does this issue should be closed with last RC including both deps as peer?
