### ISSUE TITLE
Use gitter as a discussion board

### ISSUE THREAD

**Issue by paulovieira** [marionettejs/backbone.marionette#2910]
Discourse is now offering free hosting for successful open-source projects like marionette. More details here:

http://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/

There's been some discussion about this move before (see #2483  ). I think this would be a great opportunity.

**Comment by paulfalgout** [comment]
@samccone @jdaudier this.
Can we get this setup for the domain?

**Comment by jdaudier** [comment]
@paulfalgout I submitted the request form for it.  It just mean we have to be active in answering questions that are posted there.

**Comment by rafde** [comment]
As in the active community answering? Or any random framework user like myself suggesting an answer?

**Comment by paulfalgout** [comment]
It would certainly be open to anyone. Hopefully there the longer form discussions can occur.. That way issues really become things that can be triaged and handled faster.
https://github.com/marionettejs/backbone.marionette/issues?q=is%3Aissue+is%3Aopen+label%3Adiscussion
There may be more, but all of these I would think would move.

**Comment by jdaudier** [comment]
If you're ready to set up your Discourse forum then simply:

1. Visit our [Buy](https://payments.discourse.org/buy/) page and sign up for the Standard discourse plan *
2. Go through the setup process. Remember to follow the _discourse.example.com_ sub-domain convention. Let me know if you'd like to start off with a temporary domain name instead.
3. Let me know when you're ready to launch your community =)

\* Since we haven't set up a custom onboarding process for open source projects yet you'll have to sign up with a credit card just like ordinary customers. However we never automatically start paid subscriptions, so there's nothing to worry about here. I'll promptly mark your account as "free" when I see it's set up.

If you have some questions for us before setting up the forum, ask away. Usually doesn't hurt to start trialing the forum whilst talking through the specifics though.


Erlend (erlend@discourse.org)

**Comment by paulfalgout** [comment]
@samccone @jasonLaster who has registrar access that could set this up?

**Comment by paulfalgout** [comment]
This never seemed to get forward momentum, but now that gitter provides topic boards..  even if discourse is a better platform it probably makes sense to keep our discussions / support in one place?

Thoughts on moving `discussion` tags to gitter? @marionettejs/marionette-core

**Comment by rafde** [comment]
👍 for the move

**Comment by scott-w** [comment]
Totally agree with just using Gitter - we're all active on it anyway and it's the place we send everyone for support so we may as well stick with what we know :+1:

**Comment by paulovieira** [comment]
I agree. I like discourse a lot, but it makes more sense to have the community united in one place.

**Comment by denar90** [comment]
I'm 👍 for gitter.

**Comment by paulfalgout** [comment]
Note that gitter topics has an issue with linking to a github issue.. kind of _ironically_  I'm waiting until that is resolved so we can make topics that link to the closed discussion topics on github for history.

**Comment by paulfalgout** [comment]
I'm just going to hijack this topic :-P  Forgive me @paulovieira  :-)

**Comment by rafde** [comment]
https://gitter.im/marionettejs/topics/categories/general

**Comment by paulfalgout** [comment]
The gitter discussions haven't been super useful unfortunately.. though I'm starting to wonder if just keeping them tagged in issues is ok

**Comment by rafde** [comment]
issues as discussion are confusing to me. They tend to linger and look as if no progress has been made and mostly opinion. 
An SEO friendly discussion board would be better, while issues should be used to address closable issues with the library.

**Comment by paulfalgout** [comment]
I mostly agree. I am just concerned that another service will just make them less visible and ignored

**Comment by scott-w** [comment]
I have to admit I've not even looked at the Gitter discussion board, which is mostly a reflection of the discoverability of it through Gitter.

Do we have links to it from the README and the Marionette website?

**Comment by paulfalgout** [comment]
We never really moved anything to the gitter discussion board because you could effectively link back to github and the they're practically hidden from users.  I do not think we should consider gitter discussion boards further.

**Comment by paulfalgout** [comment]
Thoughts on making a `marionette-discussion` repo or something and moving long-running discussion issues there?  It's not a new service.. super easy to get going...

**Comment by blikblum** [comment]
IMO a separate repo would only increase the friction to discuss. It should stay as is (use GH issues) or use a specialized board like discourse or other

**Comment by paulfalgout** [comment]
gitter is killing this feature plus we don't have a ton of new discussions so I'm closing this for now.
