### ISSUE TITLE
Issue after upgrade Backbone 1.3.1

### ISSUE THREAD

**Issue by latik** [marionettejs/backbone.marionette#2913]
marionette v2.4.4
backbone 1.3.1 
After upgrading BB to 1.3.1  my app stopped working.
examining this issue has found that the problem arose after commit changes 
https://github.com/jashkenas/backbone/commit/c3806077047220609b7ef79a7863a4c6cb8b5523

My solution has:
```
--- A / lib / core / backbone.marionette.js
+++ B / lib / core / backbone.marionette.js
@@ @@ -1710.7 1710.7
      // Option to pass `{comparator: compFunction ()}` to allow the `CollectionView`
      // To use a custom sort order for the collection.
      constructor: function (options) {
- This.once ( 'render', this._initialEvents);
+ This.once ( 'render', this._initialEvents, this); 
```

**Comment by paulfalgout** [comment]
I do not think Marionette will support Backbone `1.3.1` until the bug you are referring to is fixed in `1.3.2`

**Comment by alexbuijs** [comment]
Is this a bug in backbone or in marionette? See: https://github.com/jashkenas/backbone/issues/3979

**Comment by paulfalgout** [comment]
Backbone fixed here: https://github.com/jashkenas/backbone/pull/3980
Just waiting on the `1.3.2` release.  After that point, Marionette will _still_ need to increase the dependency before anyone can really use `1.3.2` with Mn.

**Comment by jdalton** [comment]
1.3.2 has been released.

**Comment by paulfalgout** [comment]
Yep.  We've got a PR in the works for updating to `1.3.2` too.

**Comment by jdalton** [comment]
Related to #2929.

**Comment by paulfalgout** [comment]
The fix for this is in `patch` just a few more things before a `2.4.5` release
