### ISSUE TITLE
Multiple instances of the behavior are sharing context?

### ISSUE THREAD

**Issue by ishaikovsky** [marionettejs/backbone.marionette#2914]
Hi,

Have a strange behavior in the application we are developing. 

I have a behavior that facilitates validation in the views. 

And in one case I have two ItemViews in the LayoutView with this same behavior applied to each of them.

At one point I decided that I need a bit of state saved at the behavior level. So I added an array in one of the methods called by triggerMethod. But then I discovered that second instance of behavior is modifying the data that was actually added by the first. 

So I had 
```
  onValidationShowMessages: function(errorMap) {
    this._clearTooltips();
........
        console.log("creating tooltip: ", $element);
        console.log("adding tooltip: ", _this.view.cid);
        _this.tooltips.push($element);
.....
```
and
```
  _clearTooltips: function() {
    console.log("clearing all tooltips: ", this.view.cid, this.tooltips);
    if (this.tooltips && this.tooltips.length) {
....
      this.tooltips = [];
```

So the call from the first view will come find an array empty and add two tooltips. But the call from the second view will come and find two elements (added for the first view) - remove them and add its own ones.

The issue disappeared after I moved initialization of the array to the
```
  initialize: function() {
    this.tooltips = [];

```
from the _clearTooltips. 

I would be glad at least to learn the reason for such context sharing. However the fact that simple move of the the initialization code for the array to the initialize method changes that - makes me think of this as a bug.

**Comment by ishaikovsky** [comment]
It seems I found the solution right after posted the question - sorry :)

What I had actually was 

`
  ui: {
    editInputs: 'input.form-control, textarea.form-control',
    submitBtn: ':submit'
  },

  events: {
    'blur @ui.editInputs': 'handleBlur',
    'submit form': 'handleSubmit'
  },

  tooltips:[],
`
tooltips is defined together with events and ui hashes,

and so this code from _clear.. :
`this.tooltips = [];
`
was unreachable because of that. So the array was actually the same for all of them. 

Not sure that I'm 100% clear on the roots of this context issue - but I'm sure I could find some answer by reading more about behaviors initialization and contexts.

**Comment by paulfalgout** [comment]
I'm not 100% following this, but is it resolved?  This'd also be a great question for https://gitter.im/marionettejs/backbone.marionette
