### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#2916]
We would have a forum it will be more a discussion than a real issue, but I would like to put some light on https://github.com/xlfishbone/marionette.morphdom project.

Besides the use of https://github.com/patrick-steele-idem/morphdom  @xlfishbone go on several DOM involved function to rewrite them. Maybe without going morphdom or vdom or idom, Marionette can get a boost on performance by going more native or working on detached elements.

**Comment by jeffijoe** [comment]
So we already have a `Renderer` that we can patch to our hearts content, and I am using that extensively to provide global helpers for Jade.

If we abstracted everything that manages the DOM into a pluggable interface, providing VDOM/ IDOM/whateverDOM implementations should be more or less straightforward?

**Comment by JSteunou** [comment]
Looking at marionette.morphdom, a lot of method are already exposed as public method; all `attach` things. There are mostly 4/5 private methods left.

**Comment by paulfalgout** [comment]
I'm going to close this in favor of #3145 and it's related PR.
