### ISSUE TITLE
Bump and build 2.4.5

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2930]
Needs review and merging:
- [x] https://github.com/marionettejs/backbone.marionette/pull/2928 - Nonexistent event handlers now fail silently
- [x] https://github.com/marionettejs/backbone.marionette/pull/2929 - Update 2.x for Bb 1.3.2

---
- [x] Update babysitter dependency
- [x] Update Wreqr dependency
- [ ] Update Radio dependency

---
- [ ] Update changelog for https://github.com/marionettejs/backbone.marionette/milestones/v2.4.5 and https://github.com/marionettejs/backbone.marionette/pull/2459
- [ ] Update package.json / bower / component
- [ ] Build files

**Comment by paulfalgout** [comment]
This one'd be good too: https://github.com/marionettejs/backbone.marionette/issues/2718

**Comment by megawac** [comment]
Also cherry-pick f6886c46aa19ede7f50a17dbfae2c6dafbd26706 to patch

**Comment by paulfalgout** [comment]
@megawac yep should already be done
