### ISSUE TITLE
Warning about sourcemap

### ISSUE THREAD

**Issue by sofuxro** [marionettejs/backbone.marionette#2935]
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead

**Comment by jmeas** [comment]
I suspect that this is an upstream issue with probably Uglify

**Comment by paulfalgout** [comment]
This is fixed for `v3` https://github.com/marionettejs/backbone.marionette/blob/next/gulp/build.js#L84

**Comment by samccone** [comment]
should be able to fix this with the 2.4.5 release :)
