### ISSUE TITLE
Add lodash v4 test to matrix

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2940]
We'll also have to:
- [x] Update dependencies to be lodash 4 compat (babysitter, radio)
- [x] Update our tests to be lodash 4 compat (as the tests use the same underscore that gets lodashed in travis via the matrix)

**Comment by rafde** [comment]
So address
https://github.com/marionettejs/backbone.radio/issues/244

https://github.com/marionettejs/backbone.babysitter/issues/66 which https://github.com/marionettejs/backbone.babysitter/pull/67 is addressing

and replace https://github.com/marionettejs/backbone.marionette/blob/master/package.json#L44 with radio?

**Comment by paulfalgout** [comment]
Ah! so this'd be off the `next` branch, so Radio should already be a dependency there for the package.json

**Comment by rafde** [comment]
I think the first check is complete.
Unfortunately, I have no idea how to resolve the 2nd check.
