### ISSUE TITLE
Throwing more info on using destroyed views

### ISSUE THREAD

**Issue by rogovdm** [marionettejs/backbone.marionette#2944]
Current error look like this:

> View (cid: "view126") has already been destroyed and cannot be used.

My proposal is to add some more information to this error. I know that it happened to view with id view123. Why not provide some more context?

For example:
- Cannot show view in a destroyed region
- Cannot show destroyed view in a region
- Cannot show destroyed view in a destroyed region :smile: 
- etc

What do you think?

**Comment by paulfalgout** [comment]
Related: https://github.com/marionettejs/backbone.marionette/issues/2795

I'm more comfortable making our current errors more useful than adding any.

**Comment by paulfalgout** [comment]
Going to close this as part of #2795
