### ISSUE TITLE
Yellow text on white background is very difficult to read (http://marionettejs.com/updates/)

### ISSUE THREAD

**Issue by tjoneseng** [marionettejs/backbone.marionette#2945]
The changelog styling uses yellow on white for some links.  Those are basically impossible to read.

![image](https://cloud.githubusercontent.com/assets/13930/13861206/4401f1ce-ec49-11e5-85ed-6cd962a0a8c6.png)

**Comment by paulfalgout** [comment]
Thanks!  Moving this issue to the website repo here: https://github.com/marionettejs/marionettejs.com/issues/441

**Comment by peterblazejewicz** [comment]
fixed via: https://github.com/marionettejs/marionettejs.com/commit/30aac164dd6f2fe3d5938717007499f4da67c939
