### ISSUE TITLE
Logic issues in CollectionView rendering with filter and renderOnSort

### ISSUE THREAD

**Issue by jamesisaac** [marionettejs/backbone.marionette#2948]
- Marionette v2.4.5 (latest)
- Backbone v1.3.2 (latest)

I've been trying to integrate the new Marionette view classes into my project (upgrading from pre 2.4), but have come across a few issues.  After digging through the code, I think I've spotted a couple of places where the logic doesn't play correctly with the new `filter` and `reorderOnSort` options.

These are all related to when models are added or removed from a view due to the filter.  For example, if I'm filtering visibility based on a single property of the model, and I change that property, then call `collection.sort()`, as far as I understand the desired behaviour is for the `CollectionView` to update.  But I'm experiencing inconsistent behaviour where things work if the model is entering view but not exiting, or vice versa.

It looks like all these bugs are present on the v3 branch too.
### 1. `_sortViews` doesn't account for items removed due to filtering

[**CollectionView#_sortViews**](https://github.com/marionettejs/backbone.marionette/blob/47fea121f81670a22608defb86d162faa2e7a2d8/src/collection-view.js#L216) (which is triggered by the collection being sorted) fetches a fresh result for `_filteredSortedModels()`, then compares it against the current `CollectionView#children`.  However, the `_.find` method used to determine `orderChanged` will only match the predicate if a model has been added relative to the views, not if one has been removed.

This problem only comes to light if all indexes of the remaining models remain the same (i.e. the last view was removed, with the highest index), as any change in index is also picked up by `orderChanged`.

One way to correct this is to simply compare the counts between the two collections after the first check, e.g. by adding this after line 225:

``` js
orderChanged = orderChanged || models.length !== this.children.length;
```
### 2. `reorder` can produce invalid indices

[**CollectionView#reorder**](https://github.com/marionettejs/backbone.marionette/blob/47fea121f81670a22608defb86d162faa2e7a2d8/src/collection-view.js#L161) on line 179 updates the `_index` attribute for all child views based on the `_filteredSortedModels()` result, which is correct.

But then, if any views have been filtered out (calculated on line 186), `removeChildView` is called on them.  `removeChildView`, on line 556, [decrements the `_index` of later views](https://github.com/marionettejs/backbone.marionette/blob/47fea121f81670a22608defb86d162faa2e7a2d8/src/collection-view.js#L555), invalidating the correct `_index` values set on line 179.

For example, if you filter out the current first item in the view, then pluck out the child view indices left behind, you'll see everything is 1 lower than it should be, the first view being on -1 instead of 0.

One way to fix this would be to have a `noIndexUpdates` flag passed to `removeChildView` when it's called from `reorder`, as it already manages the indices itself, whereas the other parts of code that call the method do not.
### 3. `reorder` falling back to `render()` if `anyModelsAdded` is a big waste of performance

This one isn't really a bug, just a potential performance boost.  If the collection contains 100 items, and a single new item is added via the filters, [**CollectionView#reorder**](https://github.com/marionettejs/backbone.marionette/blob/47fea121f81670a22608defb86d162faa2e7a2d8/src/collection-view.js#L161) falls back to `this.render()` on line 176, destroying and recreating all child views.

While it doesn't quite make semantic sense, changing the logic here to a call to `CollectionView#_onCollectionAdd` seems to work perfectly, and performs much better.  So this method could be rewritten as something along the lines of:

``` js
reorder: function() {
  var children = this.children;
  var models = this._filteredSortedModels();
  var modelsAdded = _.filter(models, function(model) {
    return !children.findByModel(model);
  });

  // If there are any new models added due to filtering
  // We need to add child views
  _.each(modelsAdded, $.proxy(function(model) {
    this._onCollectionAdd(model, this.collection, {});
  }, this));

  // get the DOM nodes in the same order as the models
  var elsToReorder = _.map(models, function(model, index) {
  ...
```

Creating and inserting 1 chlid view, instead of destroying 100 then creating 101.

**Comment by paulfalgout** [comment]
So these are great finds.  

I'm not 100% sure the best plan of attack here.  Since these features were introduced we seem to just be moving the pain around.  For one `CollectionView` filtering was added simultaneously to reordering by different contributors and so how they would interact together was unfortunately overlooked a bit. Personally I'm not sure that filtering is even a good idea on the `CollectionView`, but I also think the implementation of both features is a bit squirrelly.  

Babysitter is the collection of views/models, and that has indexing and collection like functions on it.. then marionette on top of babysitter is doing additional collection like work with indexing and filtering, and that seems pretty incorrect.  

It might be best to patch these two features a bit, but I think possibly for v4, babysitter, reorder, and filter need to be rearchitected considering each other.

**Comment by JSteunou** [comment]
my 2 cents: filtering and sorting should not be in CollectionView. Those should be done on the collection or a mirror collection, and the view should just reflect the collection. The only part involved in the view should be present to increase perf, adding some smart things to avoid re-rendering the all thing and minimize DOM update.

**Comment by paulfalgout** [comment]
I don't entirely disagree with removing `CollectionView` filter stuff. It'd be great I think to provide hooks or a recipe where you could add it if you want, but it creates so many edge cases. 
sorting though is the behavior of how the `CollectionView` reacts to a Bb Collection sorts.. so I don't think that should be removed.
However babysitter is doing the job of keeping the views in sync with the collection.  Doing that yet again, creating new indexes, or even in the case of filtering.. _if_ we were going to keep it, it seems like something that babysitter should be doing.
Although I'd like to drop babysitter altogether and just get this into the collectionview.

**Comment by JSteunou** [comment]
I forgot the all index thing when sorting. Just read again the `reorderOnSort` doc. Things sure would be simpler without filter. So I agree, order option is a keeper to choose between re-render or DOM sort, and totally agree with you on babysitter. Now that v3 is modular, a babysitter-like module inside the project should be better.

**Comment by scott-w** [comment]
I'd also agree with chopping out things like filter from the `CollectionView`. It's not something that sits naturally for me - I'd much rather handle that stuff with `Backbone.Collection` or a clearly-defined intermediary that handles the interaction between collections and views. 

That interface/magic/thing could be a nice place to handle things like filter, page, sort, perhaps? I appreciate it's much easier to hypothesise about it than build it ;-)
