### ISSUE TITLE
parent layout will not catch events from child view, using `.trigger` method

### ISSUE THREAD

**Issue by derickbailey** [marionettejs/backbone.marionette#2950]
Using Marionette v2.4.5

I have a parent layout attempting to listen to child view events. When I have a child view hosted in the layout, and I use the `triggers: { ... }` configuration, the parent layout will receive the event as expected.

However, when I use the `view.trigger("some:event")` method on the child view, the event is not bubbled up through to the parent layout.

Here is my code, to reproduce the problem

```js
// Layout
// ---------

var DialogLayout = Marionette.LayoutView.extend({
  template: "#modal-dialog-layout-template",
  className: "modal-content",
  regions: {
    bodyRegion: ".modal-content-region"
  },

  childEvents: {
    close: "closeClicked",
  },

  closeClicked: function(){
    console.log("CLOSE WAS TRIGGERED");
    this.trigger("close");
  }
});

export default DialogLayout;
```

```
// View
// ------

var EffectiveDates = Marionette.ItemView.extend({ 
  template: "#entries-edit-effective-dates-template",

  // triggers: {
  //   "click .cancel-dates": "close"
  // }

  events: {
    "click .cancel-dates": "cancelClicked",
  },

  cancelClicked: function(e){
    e.preventDefault();
    this.trigger("close");
  }
});

// exports
// -------

export default EffectiveDates;
```

if you uncomment the "triggers" section of the child view, the event will be correctly caught by the parent layout. however, if you use `this.trigger("close")` from the `cancelClicked` method, the event will not be bubbled up to the parent layout.

The event should bubble up, no matter where or how the event is triggered on the child view.

Am I doing something wrong, or is this behavior not working correctly in marionette v2.4.x? (I've tried several released of v2.4.x)

**Comment by JSteunou** [comment]
look at it, only `triggerMethod` have `_triggerEventOnParentLayout`

**Comment by derickbailey** [comment]
@JSteunou that's a good workaround, for now. I've changed my code to use `triggerMethod` until this can be fixed. 

in the past, i thought any trigger would cause the child event to be caught. i would expect all child view events to be caught, no matter how they are triggered, even if that's not how it has worked in the past.

**Comment by paulfalgout** [comment]
This was unfortunately never implemented: https://github.com/marionettejs/backbone.marionette/issues/2464

**Comment by derickbailey** [comment]
thanks, @paulfalgout - closing this as duplicate of #2464
