### ISSUE TITLE
Destroy should go with isDestroyed

### ISSUE THREAD

**Issue by rogovdm** [marionettejs/backbone.marionette#2954]
At least in 2.4.*:
- Controller has a `destroy()` method
- Controller instance does not have `isDestroyed` property
- View has a `destroy` method
- View instance has `isDestroyed` property

I consider this as an inconsistency.

If method has `destroy` method it's okay to expect that it will have `isDestroyed` property/method.

**Comment by paulfalgout** [comment]
I'm pretty sure this is already resolved in v3, though worth checking that it is consistent.
