### ISSUE TITLE
Application Region should accept objects

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#2955]
The Application `region` attribute should work the same way as `regions` on a view. For example:

```javascript
var MyApplication = Mn.Application.extend({
  region: {
    selector: '#selector',
    replaceElement: true
  }
});
```

Currently, it only seems to work by setting a selector:

```javascript
var MyApplication = Mn.Application.extend({
  region: '#selector'
});
```

**Comment by JSteunou** [comment]
Did not we talked about removing region from app?

**Comment by paulfalgout** [comment]
the regions hash was removed from application.  it was a halfway broken layout with problematic edge cases.  Now it's a single point to attach your rootLayout to.

**Comment by paulfalgout** [comment]
FWIW I think `selector` needs to be deprecated for all regions.  It's practically just an awkward alias for `el`, but I can see why the rest of the possible options might be useful.

**Comment by scott-w** [comment]
As an aside, I assume that means I should replace all instances of `selector` with `el` in the docs?

**Comment by paulfalgout** [comment]
@scott-w wouldn't hurt.  FWIW it is an old issue: https://github.com/marionettejs/backbone.marionette/issues/2289

**Comment by scott-w** [comment]
Is there any difference in practice or do they do exactly the same thing?

**Comment by paulfalgout** [comment]
none really when a view builds a region it takes the `selector`and makes it a default for the `el` like:

**Comment by paulfalgout** [comment]
In order to do this nicely the region builder methods should really be pulled from the mixin:
https://github.com/marionettejs/backbone.marionette/blob/next/src/mixins/regions.js#L68

However.. inside those functions is the `parentEl` stuff specifically for scoping to the views.  And that'd need to only exist for the mixin.
