### ISSUE TITLE
Mn 3.0: replaceElement option isn't respected in most scenarios.

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2957]
Hey,

I'm doing:

```
import { Region } from 'marionette';
import HeaderView from './headerView.js';

export default Region.extend({
  initialize() {
    this.listenTo(App.channels.body, 'rendered', this._onBodyRendered);
  },

  _onBodyRendered() {
    this.show(new HeaderView(), {
      replaceElement: true
    });
  }
});
```

and it doesn't replace the element.

This is because `this.getOption('replaceElement')` always returns false. Options passed to `show` aren't extended onto the object (doubtful that they should be?). The passed in options are just discarded.

**Comment by MeoMix** [comment]
Oh, if I pass in `replaceElement` like this it works:

```
  regions: {
    header: {
      selector: 'header',
      regionClass: HeaderRegion,
      replaceElement: true
    },
  }
```

**Comment by MeoMix** [comment]
Nah, I think this is an issue. If you pass `replaceElement` into `showChildView` it fails, too. That's not correct.

**Comment by paulfalgout** [comment]
Yep,
https://github.com/marionettejs/backbone.marionette/blob/next/src/region.js#L89

Looks like though `_attachView` is passed options it isn't using them..  should be considered for `replaceElement` and `allowMissingEl` too I guess.  This would also fix `showChildView`.

**Comment by MeoMix** [comment]
Yeah. I noted that they weren't using them but I wasn't sure if it was a bug since when I looked in other places options was being discarded as well.

**Comment by paulfalgout** [comment]
It looks like the initial implementation of the feature did include it in `show` and it seems like you'd want it there too..  but region show had a huge overhaul since then.  So clearly we were missing an important test :-)

**Comment by MeoMix** [comment]
I'll grab it in the morning :)

**Comment by JSteunou** [comment]
Soooo, is @MeoMix PR fixed this issue?
