### ISSUE TITLE
Code Choice Question: attachElContent

### ISSUE THREAD

**Issue by HauptmannEck** [marionettejs/backbone.marionette#2960]
In this function I am curious why the current code is used:
`this.$el.html(html);`

instead of:
`this.$el.empty().html(html);`

Im my project I had different behavior for Chrome and IE during rendering due that code difference. I ended up just overriding it in my ItemViews.

Just wondering if there is a reason I have not thought of.

**Comment by Xuefeng-Zhu** [comment]
According to jquery document, 
```
The .html() method is not available in XML documents.

When .html() is used to set an element's content, any content that was in that element is completely replaced by the new content. Additionally, jQuery removes other constructs such as data and event handlers from child elements before replacing those elements with the new content.
```
I think it is not necessary to use empty here

**Comment by JSteunou** [comment]
@HauptmannEck which IE version? If you're using old IE check you're using the correct jquery version.

**Comment by HauptmannEck** [comment]
I was using IE11. I noticed, and this may have be on purpose, that if you attached an view's jquery object like:
 `this.$(<some part>).html(this.childView.$el)`
The next time you render it resets:
`this.$el`
which in in chome you can just reconnect the `childView.$el` and keep going but in IE, the childView looses all the HTML in the $el, and it must be re-rendered.

**Comment by JSteunou** [comment]
Ok so it's really a Marionette issue, maybe you should use a region to correctly attach your view.

**Comment by paulfalgout** [comment]
Super old but related to `empty` https://github.com/marionettejs/backbone.marionette/pull/2030#discussion_r19430192

Is there a jsfiddle that can reproduce this issue for IE11?  I haven't seen this behavior in IE11, so I'm wondering the use-case or at least how I'm avoiding it.

**Comment by paulfalgout** [comment]
Closing because it's stale
