### ISSUE TITLE
onShow not always called when a view has been displayed

### ISSUE THREAD

**Issue by dougalg** [marionettejs/backbone.marionette#2962]
With Marionette (v2.4.5 and below) the documentation explains that `onShow` will trigger when a view is rendered **and displayed**.

My issue is that with nested views and regions, the `onShow` method might be called before the view is in fact displayed.

In the example here: https://jsfiddle.net/599dtsb7/2/ the inner view's onShow is called (a) before it's parent's onShow, which seems strange to me, and (b) it isn't actually displayed in the DOM yet when onShow is called so the attempt to select its element fails.

Obviously, calls to eg `this.$el` would work, but this is just an example, and causes problems with other libraries, like D3.

I'm interested in working on a solution for this if there is interest for this in the community. But maybe you've already thought about this problem and have reasons for the current behaviour?

**Comment by paulfalgout** [comment]
I believe this is improved for `v3` https://github.com/marionettejs/backbone.marionette/pull/2850  That was a very large refactor, but I believe it resolves this issue

**Comment by dougalg** [comment]
Thanks a lot for that, @paulfalgout . Quick question, I tried running my above snippet against Marionette 3, but there is no LayoutView. Is that deprecated? I'm just curious because it's showing up in the docs.

**Comment by paulfalgout** [comment]
Yeah the docs are all WIP.  Itemview and layoutview are now just view.  Also show is no longer triggered on the view..  You'll want either onAttach or onDomRefresh

**Comment by dougalg** [comment]
Thanks for the update! When I test with those methods against the latest v3 build (3.0.0-pre2) I still get some weird behaviour, most notably that `onAttach` and `onDomRefresh` of the sub-child view are being called twice, which seems a bit strange to me: https://jsfiddle.net/599dtsb7/6/

I will look into this some more and see if I can submit a failing spec at least. To me, this behaviour seems strange, but maybe a known issue, or expected bahaviour?

**Comment by dougalg** [comment]
Also, is there a v3 version of the `next` and `patch` branches?

**Comment by scott-w** [comment]
Hi @dougalg, the `next` branch is v3. We're in the process of updating the documentation for it.

**Comment by paulfalgout** [comment]
@dougalg I think in `v3` only `onRender` should be used for making childViews. `onAttach` / `onDomRefresh` are if you need something non-Marionette.. like a jquery plugin that needs to know when the view is in the DOM.

**Comment by paulfalgout** [comment]
@ianmstew can you check this out?

**Comment by paulfalgout** [comment]
I'm pretty confident that `onAttach` on `onDomRefresh` will work for this use case in `v3` for any Marionette or non-Marionette purpose.
