### ISSUE TITLE
Add installing guide to a doc

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#2963]
We've been discussing with @paulfalgout and @scott-w that it would be great to have installing guide in documentation. This page has to be based on this [file](https://github.com/marionettejs/guides/blob/master/en/getting_started/installing_marionette.md).
Also it will be cool if this page be a first one in list of doc pages. We have to find fancy solution how to do this and replace navigation bar
```
<nav>
          <% files.forEach(function(file) { %>
            <a href="/docs/<%- tag + '/' + file.basename %>.html"><%- file.title %></a>
          <% }); %>
</nav>
```
on something else. To have possibility to add files order.

**Comment by paulfalgout** [comment]
I think some sort of installation / getting-started is important for the Mn Docs.  I don't know if it should be here and the guides or if there's a simplified version and then a link to the guides or some other option..

As for the file order.. That's handled by the website tooling.  I would think there is already a way to set the order, but if not, we can look at that on the `www` repo

**Comment by scott-w** [comment]
I agree. Should we document a simple "recommended" method and link to the Guide for different methods?

**Comment by denar90** [comment]
Can we build something like [Mn with Brunch](https://github.com/denar90/brunch-with-marionettejs) for `webpack` and `browserify` (several commands and project will be deployed)?
In installation / getting-started doc we will provide people with info for e.g.
```
Quick start with webapck
some short info

Quick start with brunch 
some short info

Quick start with browserify 
some short info

link for more info
```

**Comment by scott-w** [comment]
I've merged the changes in and I'm happy to close this in favour of opening specific tickets for improvements.
