### ISSUE TITLE
Consistency of filtering 

### ISSUE THREAD

**Issue by rogovdm** [marionettejs/backbone.marionette#2966]
Use case:
- partial rendering of a collection via `filter` option
- then adding some children via `addChild` method

As far as I can see we don't filter those children which are rendering with a direct addChild method. So filter method does not call `filter` all the time. Is that okay? Just opening discussion.

I thought to propose to name filter => initialFilter, but it's not that good too.

**Comment by paulfalgout** [comment]
Yeah, trying to maintain two totally different collections is difficult.  Most of the `filter` functionality did not take into account the rest of the `CollectionView` API.  My personal opinion is that it should be removed from Mn.  `addChild` is privatized in `v3`.  The best way to update a `CollectionView` in my opinion is to maintain the `collection` passed to it.  If it needs to be different that the source collection, just clone it before handing it to the `CollectionView`

**Comment by rogovdm** [comment]
@paulfalgout  yeah, that seems to be the most valid approach.

I've spent two days experimenting with an idea of a partial rendering — when I have to a quite big collection but want to insert only a visible through UI part into DOM.

Most of my experiments was in changing how child views has been attaching. The result is a blast, but my neighbour is asking what's thats smelling :)

> addChild is privatized in v3.

Ooops :) So It means there will be no documented way to insert a specific child view into specific place manually?
