### ISSUE TITLE
Upgrade guide from v2 to v3

### ISSUE THREAD

**Issue by jjanssen** [marionettejs/backbone.marionette#2971]
Forgive if this was already asked. I could not find anything relevant in the search.
As the final release of version 3 is getting closer. Will there also be an upgrade guide and/or tool available on its release?

**Comment by scott-w** [comment]
Hi @jjanssen 
At the minute, we're putting the upgrade instructions throughout the documentation.

We'll also be doing some form of Release Notes with the top-level changes for 2-3 with instructions for how to do it.

**Comment by gavrashenko** [comment]
Any new about instructions ?

**Comment by jjanssen** [comment]
Thanks for the update @scott-w

**Comment by scott-w** [comment]
We've merged an upgrade guide in from #3003 
@jjanssen it would be great to get some feedback on it at https://github.com/marionettejs/backbone.marionette/blob/next/docs/upgrade.md

If anyone has any other notes that I may have missed, ping them here and I'll get them added.

**Comment by jjanssen** [comment]
Awesome! Thanks for the update. I'm going to take a look at it. Probably can give you an update earlier next week.

**Comment by scott-w** [comment]
That's great @jjanssen, thanks for your help 👍

**Comment by paulfalgout** [comment]
This should be moved to or at least linked from this file https://github.com/marionettejs/backbone.marionette/blob/next/upgradeGuide.md

**Comment by scott-w** [comment]
Good shout 👍

**Comment by scott-w** [comment]
Additional TODO: `childViewEvents` are only built and cached once - in v2 they were built on every event.

This means we can't create `childViewEvents` after the view has been created.

**Comment by jjanssen** [comment]
I promised to get back with some feedback. But unfortunately I'm a little caught up with other stuff at work. I started replacing `addInitializer` and module loading, but I haven't made any progress regarding the details. Hope to get back to you as soon as possible.

**Comment by scott-w** [comment]
No bother @jjanssen, thanks for letting me know :)

**Comment by paulfalgout** [comment]
Noticed a breaking change I'm not sure is documented somewhere..

In v2 the View triggers hash will pass an object to the handler where the object is
{
  view: view,
  model :model,
  collection: collection
}

**Comment by paulfalgout** [comment]
I think this covered in the upgrade guide.. between that.. the compat tool and the compat tool docs..  maybe there's room for improvement.. but I think this is done enough for release.. reopen if anyone disagrees.
