### ISSUE TITLE
[v3.0.0-pre.3] `global` variable not defined in browser.

### ISSUE THREAD

**Issue by devel-pa** [marionettejs/backbone.marionette#2972]
Hi,
Loaded in browser you'll receive: Uncaught ReferenceError: global is not defined

https://github.com/marionettejs/backbone.marionette/blob/next/lib/backbone.marionette.js#L444

**Comment by paulfalgout** [comment]
I've got this one.  This is the `Mn` alias that works with the UMD wrap, but the bundled fix for `pre.3` switched to IIFE so that it doesn't break the local dependency vars.

**Comment by paulfalgout** [comment]
FWIW the quickfix if you're downloading the bundled version is to replace `global['Mn']` with simply `Mn`

**Comment by devel-pa** [comment]
NPM installed, just before the scripts loading `global = window` and works.
