### ISSUE TITLE
Marionette 3.0 release date

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [marionettejs/backbone.marionette#2973]
When will Marionette 3.0 be formally released? Is v3.0.0-pre.2 ready for production usage? Thank you.

**Comment by paulfalgout** [comment]
Mn will be released after a release candidate is deemed stable and documentation is ready.  anything with a `-pre` should not be used in production.  Certainly trying `v3` on a production app might help find any issues in the current candidate, and could help speed along a final release.
