### ISSUE TITLE
issue while installing with npm: cannot read property 'AppRouter' of undefined

### ISSUE THREAD

**Issue by baptistebriel** [marionettejs/backbone.marionette#2974]
Hello,

I'm having a really weird issue with `npm` and `marionettejs` modules. Especially `backbone.marionette` and `backbone.wreqr`. I'm using these versions of node and npm: `node v5.0.0`, `npm v.3.3.6`.

The actual error on the console is the following:

![screen shot 2016-04-06 at 15 11 51](https://cloud.githubusercontent.com/assets/2464663/14317932/dea6fbd6-fc0a-11e5-96e7-5df181f06670.png)

![screen shot 2016-04-06 at 15 12 01](https://cloud.githubusercontent.com/assets/2464663/14318085/90906b3e-fc0b-11e5-8bee-0d804fa97573.png)

If I copy the `backbone.marionette` folder from a previous project's `node_modules` and replace it, I don't have the error anymore. But then comes another one from `backbone.wreqr`;

![screen shot 2016-04-06 at 15 12 43](https://cloud.githubusercontent.com/assets/2464663/14317991/2134555c-fc0b-11e5-9342-403f75dbee9b.png)

The actual problem is that both `backbone.marionette` and `backbone.wreqr` installs `backbone` in its own `node_modules` folder;

![screen shot 2016-04-06 at 15 12 19](https://cloud.githubusercontent.com/assets/2464663/14318101/9c107fbc-fc0b-11e5-8222-2c95b19e2821.png)

![screen shot 2016-04-06 at 15 13 04](https://cloud.githubusercontent.com/assets/2464663/14318105/a26cc712-fc0b-11e5-849a-de5dcb2ed81b.png)

If I remove those two folders, I don't have the previous errors. That's (I think) because `backbone.marionette` and `backbone.wreqr` will import `backbone` from the root folder instead of having deep-dependencies.

Not sure why this issue comes into place; I don't understand why these two modules have they own `node_modules` folder since an update on npm all packages should be installed in the root directory.

Any further installs will be broken, if not removing these two folders by hand.
If anyone has an idea why those modules have their own `node_modules` folder... I'd gladly take it.
Thanks!

**Comment by scott-w** [comment]
How are you installing Marionette?

**Comment by baptistebriel** [comment]
with npm, such as `npm install backbone.marionette --save`

**Comment by scott-w** [comment]
Ahh I think I see it. How are you importing Marionette?

I believe newer versions just need you to:

```js
var Marionette = require('backbone.marionette');

var Router = Marionette.AppRouter.extend({
});
```

And not try to access the member on `Backbone` as it may not exist.

**Comment by paulfalgout** [comment]
This typically happens because dependencies are loaded out of order.
Like you need to ensure that your version of backbone (one that is compatible with Marionette) is loaded prior to wreqr and marionette.  Once your backbone is resolved to node's require it will continue to use that one.  Otherwise if your project's backbone isn't loaded first it will load wreqr it's own.. then marionette will load it's own.. then your project will.
And like I mentioned the other caveat is versioning.  If you're loading backbone `1.3.3` then you'll load that version into your project.. the wreqr will load `1.3.2` and so will marionette.

**Comment by baptistebriel** [comment]
Thank you for such a fast answer! I'm using ES6 with babel so I'm doing `import` instead of `require`. not sure if it can be related or not.

I tried using `Marionette` instead of `Backbone.Marionette` but I still have the second error;

![screen shot 2016-04-06 at 18 33 21](https://cloud.githubusercontent.com/assets/2464663/14324704/3499691e-fc26-11e5-967f-b7c08f1982a6.png)

@paulfalgout I do load Backbone before everything else, see screenshot.

![screen shot 2016-04-06 at 18 35 33](https://cloud.githubusercontent.com/assets/2464663/14324822/c0a08186-fc26-11e5-96ff-7736cc0873a9.png)

I do not understand tho why wreqr and marionette would load Backbone `1.3.2` if I'm using `1.3.3`?
Thank you very much for your time and help, really appreciate it.

**Comment by paulfalgout** [comment]
Backbone does not follow semver, so currently marionette must update its dependencies when backbone does. This means that currently marionette will not work with backbone 1.3.3.  Now Backbone 1.3.3 adds 0 behavior to backbone 1.3.2, so for now all you'll need to do is use backbone 1.3.2.

**Comment by baptistebriel** [comment]
Still have the same error from `backbone.marionette` with backbone `1.3.2`. Any ideas would be much appreciated! Thanks.

**Comment by paulfalgout** [comment]
Can you post your package.json?

**Comment by baptistebriel** [comment]
```json
{
  "name": "starter",
  "version": "1.0.0",
  "description": "",
  "main": "gulpfile.js",
  "browser": {
    "config": "./assets/js/config.js",
    "utils": "./assets/js/utils.js",
    "vent": "./assets/js/vent.js",
    "default": "./assets/js/views/default.js",
    "components-factory": "./assets/js/components/factory.js",
    "gsap-draggable": "./assets/js/lib/gsap/src/uncompressed/utils/Draggable.js",
    "gsap-throwprops": "./assets/js/lib/gsap/src/uncompressed/plugins/ThrowPropsPlugin.js",
    "gsap-scrollto": "./assets/js/lib/gsap/src/uncompressed/plugins/ScrollToPlugin.js"
  },
  "dependencies": {
    "babel-preset-es2015": "^6.6.0",
    "backbone": "^1.3.2",
    "backbone.babysitter": "0.1.0",
    "backbone.marionette": "^2.4.5",
    "backbone.wreqr": "1.3.5",
    "dom-classes": "npm-dom/dom-classes",
    "dom-create-element": "^1.0.2",
    "dom-event": "npm-dom/dom-event",
    "dom-select": "npm-dom/dom-select",
    "gsap": "^1.18.0",
    "jquery": "^2.1.4",
    "masonry-layout": "^4.0.0",
    "picturefill": "^3.0.1",
    "prefix": "^0.2.4",
    "query-dom-components": "baptistebriel/query-dom-components",
    "smooth-scrolling": "^2.1.5",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.6.0",
    "babelify": "^7.2.0",
    "browserify": "^11.1.0",
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^0.0.10",
    "gulp-changed": "^1.3.0",
    "gulp-concat": "^2.3.5",
    "gulp-minify-css": "^0.3.13",
    "gulp-notify": "^2.0.1",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "~2.1.0",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-uglify": "^1.4.1",
    "gulp-util": "^3.0.4",
    "lodash.assign": "^3.2.0",
    "mjml": "^1.2.1",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "vinyl-transform": "^1.0.0",
    "watchify": "^3.4.0"
  },
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "only": "assets/js/",
          "presets": [
            "es2015"
          ]
        }
      ]
    ]
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by paulfalgout** [comment]
Yeah you'll need to take the `^` off of Backbone or it will load `1.3.3`  You also probably do not need to load babysitter or wreqr in package.json.  But that isn't hurting anything.

**Comment by baptistebriel** [comment]
Thank you! It worked.
