### ISSUE TITLE
Listen to Collection#event:update instead of Collection#event:add/remove in CollectionView

### ISSUE THREAD

**Issue by rafde** [marionettejs/backbone.marionette#2979]
https://github.com/marionettejs/backbone.marionette/blob/0d913a524a71a9b4427256b0ba1b3236abeee9d6/src/collection-view.js#L90-L91

Collection#event:add and Collection#event:remove works on adding Views one at a time when they should be added using something like https://github.com/marionettejs/backbone.marionette/blob/0d913a524a71a9b4427256b0ba1b3236abeee9d6/src/collection-view.js#L252-L254 for bulk adding [options.added](https://github.com/jashkenas/backbone/blob/master/backbone.js#L930) and probably a bulk remove using [options.removed](https://github.com/jashkenas/backbone/blob/master/backbone.js#L931)

Listening to [Collection#event:update](https://github.com/jashkenas/backbone/blob/master/backbone.js#L934) will allow you to start doing bulk add/remove views instead of doing it 1 +/- at a time.

**Comment by JSteunou** [comment]
update event is Backbone >= 1.2

**Comment by paulfalgout** [comment]
This is something that can be looked at for `v3`, but not `v2.x`

**Comment by rafde** [comment]
To address being able to do add/remove large numbers of views, I suggest creating
```
/**
 * @param {Backbone.Model[]} addedModels array of Backbone.Models
 * @returns {Marionette.CollectionView}
 */
Marionette.CollectionView#addChildrenViews
```
```
/**
 * @param {Backbone.Model[]} removeModels array of Backbone.Models
 * @returns {Marionette.CollectionView}
 */
Marionette.CollectionView#removeChildrenViews
```

Could replace `Marionette.CollectionView#_showCollection` with `Marionette.CollectionView#addChildrenViews`

https://github.com/marionettejs/backbone.marionette/blob/0d913a524a71a9b4427256b0ba1b3236abeee9d6/src/collection-view.js#L90-L91

Would get replaced with CollectionView will listen to Collection#event:update
and go to an internal function Marionette.CollectionView#_onCollectionUpdate
```
_onCollectionUpdate: function (collection, options){
  this.addChildrenViews(options.added, options);
  this.removeChildrenViews(options.removed, options);
  return this;
}
```

And start fixing performance issues 

#2873 
#2660 
#2723
#2156

**Comment by rafde** [comment]
### Update: Working on removing `CollectionView` child views
![collectionview remove perf](https://cloud.githubusercontent.com/assets/833429/16716502/0890f328-46b3-11e6-8be9-6694eeab5888.gif)
The above displays removing `CollectionView` child views with `sort` enabled.
Clearing the `CollectionView` is done by resetting the region that host the `CollectionView` (`layout.getRegion('list').reset()`)
The current childViewRemove takes 2876.6 ms
The new way takes 388.4 ms
The new way uses the updates done to Backbone.Babysitter from this PR https://github.com/marionettejs/backbone.babysitter/pull/73

Here's my current branch work https://github.com/marionettejs/backbone.marionette/compare/next...rafde:collectionview-update-remove

this is the page I used to do the test https://github.com/rafde/backbone.marionette/blob/CV-Perf-Test-Page/perf/collectionview-add-remove.html

**Comment by paulfalgout** [comment]
this is great.  need some time to sit with it.. it is on my todo list.. soon as v3 is all the way out.

**Comment by rafde** [comment]
I'll keep plugging away at it. I can't submit a PR for it until babysitter and radio allow for <=1.3.3 support. The way I have it now seems to be in an ideal state for making a PR. I'll tackle adding views next.

**Comment by rafde** [comment]
![collectionview-optimized](https://cloud.githubusercontent.com/assets/833429/17460539/230693c0-5c20-11e6-9c7c-4a807ebc70b4.gif)

On render perf update
from ~4000ms to ~1000ms for 3000 models.

Test are still the same, but lost code coverage on a new change I made when `_bufferedChildren` are not used from `attachHTML`. I am not using `_bufferedChildren` on render anymore though since I am adding to a different buffer.

Trying to pin point where else perf can be improved. `mergeOptions` could be done better but it takes off 50ms or so.

Here is the initial branch work
https://github.com/marionettejs/backbone.marionette/compare/next...rafde:collectionview-render-perf?expand=1

@paulfalgout you might want to take a look there also

Gonna need some proper help when I start doing `update` added models

**Comment by ahumphreys87** [comment]
#3113
