### ISSUE TITLE
is there a way to trigger something when all the views is ready?

### ISSUE THREAD

**Issue by dayukiller** [marionettejs/backbone.marionette#2982]
hi I'm using marionette recently,and i want a way to trigger something when all the views are ready,including all the subviews.And as you know, window.onload is triggered earlier than the onrender event.
So is there a way to trigger something when all the views is ready?

**Comment by JSteunou** [comment]
Depends on what do you mean by *ready*. `onAttach` is the cool kid because it means your view is rendered, shown in a region and attached to the DOM. So maybe you could listen for that event on your deepest view.

**Comment by dayukiller** [comment]
Maybe onAttach is not what i want.For i have many views as regions in one page;and i want to trigger something when all the views in one page is loaded(including images and so on);

**Comment by JSteunou** [comment]
Will be hard to do. You will have to emit some event or resolve some Promise from each view, either on `onAttach` or image.onload and listen for all events or Promise.all but that apply that you know by advance how many events or Promise you're waiting for.

**Comment by JSteunou** [comment]
Or maybe each view could emit an event on creation, so you do not have to know the exact count by advance, and for each view related to a creation event received, wait for a *done* event. But I'm afraid that could have some impact on performance.

**Comment by dayukiller** [comment]
3Q~ maybe i can find some way else to avoid using this

**Comment by paulfalgout** [comment]
I think this is a great question for https://gitter.im/marionettejs/backbone.marionette or http://stackoverflow.com/questions/tagged/marionette

Although I don't know that you want anything aware of every view's render..  there could be so many various async renders or animations or interactions that cause renders, that view rendering as a whole may never be "done"
