### ISSUE TITLE
rendering submodels in a CollectionView

### ISSUE THREAD

**Issue by tjaartvdwalt** [marionettejs/backbone.marionette#2984]
I am trying out `marionette v3.0.0-pre-3`.

The context:
- I am using `backbone-relational` to get nested models.
- I use `handlebars` templates

l render a `CollectionView` and I have have a collection of model `foo`, each containing a submodel `bar`. 

In `marionette v2.x.x` my handlebars template would look like this:
```handlebars
{{foo.bar}}
```
In `marionette v3.0.0-pre-3` this does not work. To get the same result I have to do:
```handlebars
{{foo.attributes.bar}}
```
which does not feel very backbony... Is this a regression issue?

**Comment by paulfalgout** [comment]
hmm I'm really unsure how `v3` would make a difference here.  Are you using any `templateHelpers`? that's renamed to `templateContext`

A jsfiddle or something would be useful here.

**Comment by belackriv** [comment]
Backbone relational overides the toJSON of models, v2 used this as the default serializeData
```
serializeModel: function(model) {
      return model.toJSON.apply(model, _.rest(arguments));
    },
```
where as v3 uses:
```
serializeModel: function serializeModel() {
	    if (!this.model) {
	      return {};
	    }
	    return _.clone(this.model.attributes);
	  },
```
(I  use a shim in my current v2 app, and I have to use the `{{foo.attributes.bar}}`` method to get nested attributes

**Comment by tjaartvdwalt** [comment]
@belackriv Thanks very much for the clarification.

I am not sure what this means for this issue... I do not know enough to know if it is solvable by either `marionette` or `backbone-relational`. Should I just learn to live with it?

**Comment by paulfalgout** [comment]
Ah I see.  
Well toJSON is not supposed to be for view rendering. 
But you could override your serialize functions to use it for your usecase.

**Comment by tjaartvdwalt** [comment]
Ok thank you. I will close this issue.

**Comment by rogovdm** [comment]
> Well toJSON is not supposed to be for view rendering. 

What you you recommend instead?

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/issues/1476 xref
