### ISSUE TITLE
undefined is not an object (evaluating 'this.options.parentEl')

### ISSUE THREAD

**Issue by dottodot** [marionettejs/backbone.marionette#2988]
I've just started using https://rollbar.com to log errors in my app and I seeing this error a lot 

```
undefined is not an object (evaluating 'this.options.parentEl')
```
which relates to 

```
  getEl: function(el) {
      return Backbone.$(el, Marionette._getValue(this.options.parentEl, this));
    },
```

Just trying to understand why this is happening as a little lost on what the cause could be.

**Comment by JSteunou** [comment]
with which Marionette version? Can you provide a fiddle with this error?

**Comment by dottodot** [comment]
I'm using 2.4.4. Problem is there is so much code going on that I don't think posting it is going to help. Was hoping to narrow down where the problem is first. Also I'm unable to replicate the error myself, the only time I see it is in Rollbar.

**Comment by dottodot** [comment]
Actually if i log `getEl` like

```
    getEl: function(el) {
      console.log(this.options);
      console.log(Marionette._getValue(this.options.parentEl, this));
      return Backbone.$(el, Marionette._getValue(this.options.parentEl, this));
    },
```
parentEl is undefined on quite a lot of occasions for example all regions defined in my Application return an undefined parentEl

```
var app = new Mn.Application({
    regions: {
        headerRegion: "#header",
        mainRegion: "#main",
        footerRegion: "#footer"
    }
});
```

So is it an issue with my app or is Rollbar being over sensitive with it's error logging?

**Comment by paulfalgout** [comment]
`parentEl` not being defined is fine.  `this.options` not being defined would be a problem.

If `parentEl` is not defined `$` will use the document.  Maybe rollbar shows this as an error for some reason?

**Comment by paulfalgout** [comment]
Will reopen if additional info is added
