### ISSUE TITLE
Feature request — bindEntityReplies

### ISSUE THREAD

**Issue by rogovdm** [marionettejs/backbone.marionette#2989]
`bindEntityReplies` is an analogue to `bindEntityEvents`, but will bind / unbind within a channel using `.reply` and `.stopReplying` functions accordingly.

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/blob/next/src/bind-radio-requests.js#L34

**Comment by rogovdm** [comment]
@paulfalgout oh, cool.

Are we sure that it's exactly bind-radio-*requests*? What we are binding in that code are replies, not requests

**Comment by rogovdm** [comment]
Also, why to "limit" it's usage to only radio objects by naming it like that? It will work with any object, that has reply method with specific signature.

So my proposal to name this util functions like this: 
- bindEntityReplies
- unbindEntityReplies

**Comment by paulfalgout** [comment]
I _think_ the naming comes from the key and not the value such that `{ "request:name": "replyHandler" }` we're binding the "request:name" to the reply handler.  The same could be said about "events" where the event is the key of the hash and the value is the handler.

It is true it'll work with any object with the reply API. I don't disagree with your suggestion either. However I think the naming is related to promoting Radio.  I'd have to dig back through the issue related to radio a bit, but for instance `bindEntityEvents` will be aliased as `bindRadioEvents` as well.  https://github.com/marionettejs/backbone.marionette/blob/next/src/backbone.marionette.js#L63

@marionettejs/marionette-core I'd actually support dropping the radio specific naming of the new API in favor of just using `bindEntityRequest` and not introducing an alias.  Thoughts?
