### ISSUE TITLE
Feature request — bindEntityEventsToLifeCycle 

### ISSUE THREAD

**Issue by rogovdm** [marionettejs/backbone.marionette#2990]
```
bindEntityEventsToLifeCycle (context, entity, hash, eventName) {
  // acts like bindEntityEvents
  // ...
  context.listenTo(context, eventname, M.unbindEntityEvents ... )
}

```
What do you think? Must be pretty handful.

**Comment by paulfalgout** [comment]
I don't quite follow.  What's the goal?

**Comment by rogovdm** [comment]
I think bindEntityEvents almost always coded with unbindEntityEvents. The most common pattern (for me) is to call unbindEntityEvents in ````onDestroy```` method. And I have to remember this.

Why not to set up unbinding circumstances during binding for that case? So it will be possible to do something like this:
````
bindEntityEventsToLifeCycle(view, channel, channelEvents, "destroy");
````

**Comment by paulfalgout** [comment]
I need a bit more info I think..

If you have a view like:
```js
var View = Marionette.View.extend({
  initialize: function(options) {
    this.bindEntityEvents(options.fooModel, this.barEvents);
  },
  barEvents: {
    'change': 'onModelChange'
  },
  onDestroy: function() {
    // no need to unbind, events will already be cleaned up by the view's destroy
  }
});
```
Is there a different use-case?

**Comment by paulfalgout** [comment]
Let's reopen if additional info arises
