### ISSUE TITLE
Migrations — consider using jscodeshift

### ISSUE THREAD

**Issue by rogovdm** [marionettejs/backbone.marionette#2991]
https://github.com/facebook/jscodeshift

It's investigation this tool and and it indeed seem very good for massive code updates. Maybe we can use one to make our migrations?

**Comment by rafde** [comment]
I am trying to understand what the added benefit of using this is.

**Comment by JSteunou** [comment]
@rafde think of it like a better find & replace to handle code migration through AST.

**Comment by ahumphreys87** [comment]
Yup I like this idea - @rogovdm would you consider contributing to https://github.com/marionettejs/Marionette.Upgrade? Would be a great help for users migrating to v3.0

**Comment by scott-w** [comment]
Shall we close this now?

**Comment by paulfalgout** [comment]
I wonder if we should move the posts marked `discussion` to the gitter topics?  This might be a viable tool for the future.  would have been difficult for v3 because we had some awkward breaking changes.

**Comment by rafde** [comment]
After checking it out, I think it's worth looking into relative to a migration tool. Would it be best as a separate repo or part of this project's repo under a _codemod_ folder?
