### ISSUE TITLE
onRoute parameter incorrect if multiple routes use same action

### ISSUE THREAD

**Issue by berniezhao** [marionettejs/backbone.marionette#2992]
Let's say we have multiple routes pointing to the same controller action

```
...
 appRoutes: {
        'home': 'displayHome',
        'home/:menu/:id': 'displaySecondLevel',
        'home/aboutus/contactus/email': 'displaySecondLevel'
    },

onRoute: function(name, path, params) {
    console.log.apply(console, arguments);
}
```

If I visit http://yourdomain.com/#home/product/features, the correct route was picked and `onRoute` function will be triggered.  However the `path` is actually wrong.  It will be `home/aboutus/contactus/email` instead of `home/:menu/:id`.

I think Marionette uses the below undercore function to find the path 
`var routePath = _.invert(this.getOption('appRoutes'))[routeName];`
This could cause problem if multiple routes points to the same method.

Any thought is appreicated.

**Comment by rise2semi** [comment]
```_.invert(this.getOption('appRoutes'))``` creates an object with the inverted keys and values. If routes object contains duplicate values, subsequent values overwrite property assignments of previous values.
In your case the result will be:
```
{
    'displayHome': 'home',
    'displaySecondLevel': 'home/aboutus/contactus/email',
}
```
As you can see we lost one route. This issue can be solved, but the main problem in other place.

Backbone returns to Marionette just ```routeName``` without any relation to a route path. In your case ```routeName``` is ```displaySecondLevel```.

Even if we have all routes and their paths:
```
{
    'displayHome': 'home',
    'displaySecondLevel': 'home/:menu/:id',
    'displaySecondLevel': 'home/aboutus/contactus/email',
}
```
there is no way how to get the related route. I think the best solution for this is a route path will be returned by Backbone.
