### ISSUE TITLE
Add route generator to Router?

### ISSUE THREAD

**Issue by gonzalovilaseca** [marionettejs/backbone.marionette#2993]
I'm quite new to BB and Marionette, so hopefully what I say makes sense...

I've found that routes have to be composed manually. If at some point you want to change a specific url it can get quite cumbersome as you need to search through all your base code. 
Also having to manually compose routes everywhere seems like something that should be performed by the router.
The idea would be to add a name to each route (syntax is just to show the idea):
```
...
routes: {
        'item_new': { 'item/new': 'newItem' },
        'item_show' : { 'item/:id': "showItem"}
    },
...
```
then in code:
```
Router.generate('item_new');
Router.generate('item_show', {'id' : 23 });
```
This should also be used in templates to generate urls.
So if at some point we want to change ``'item/new'`` for ``'item/add'``, it just needs to be done in one place.

Also it would facilitate url generation when there are multiple parameters in a path:
``item/:name/:id/show``
``'item/' + model.get('name') + '/' + anotherModel.get('id') + '/show'`` could be replaced by ``Router.generate('my_route', {'name': model.get('name'), 'id': anotherModel.get('id')})``

**Comment by JSteunou** [comment]
Brainstorm around the Router is generally in the Backbone project. There were a few like this one https://github.com/jashkenas/backbone/issues/3653 but still on progress.

**Comment by gonzalovilaseca** [comment]
Cool thanks.

**Comment by voblivion** [comment]
A bit late but I wrote a very simple route reverser for backbone/marionette. It's named route-reverser on npm. Hope it helps. [(https://www.npmjs.com/package/route-reverser)]
