### ISSUE TITLE
[2.4.x] Possible regression on Mn.Regions

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#2998]
I am not using that much customized `Regions` but for once I needed it, I found it very difficult to give it an `el` from a `LayoutView`. From my memories, it seems way easier before.

in my `LayoutView`, this...

```js
    regions: function() {
        return {
            fooRegion: {
                regionClass: SwipeRegion,
                el: this.ui.fooRegion
            }
        };
    },
```

is not working, because during `regions` definition `el` is a `String` selector instead of jQuery el, then during  `onShow` it cannot find `el` even if the selector is valid. I also tried

```js
    regions: function() {
        return {
            fooRegion: SwipeRegion.extend({el: this.ui.fooRegion})
        };
    },
```

but it's just the same.

I solve it by passing by an option `parentView: this` and overriding `getEl` in the region

```js
    getEl: function(el) {
        return this.options.parentView.$el && this.options.parentView.$el.find && this.options.parentView.$el.find(el);
    },
```

but man, that's ugly!

**Comment by paulfalgout** [comment]
> during onShow it cannot find el even if the selector is valid. I also tried

Can you make a fiddle of this not working? I don't know how regions work at all if it can't take a string selector.

**Comment by JSteunou** [comment]
Documentation says it should work. I'll make a fiddle tomorrow.

**Comment by paulfalgout** [comment]
I wonder if this is fixed in v3..  regions in v2.x are weird because the initialize oddly.. so some things aren't available when they should be.  I _think_ v3 is at least better.

**Comment by JSteunou** [comment]
Oops I forgot this one. Will test with v3... one day :'(

**Comment by paulfalgout** [comment]
@JSteunou do you want to keep this open?

**Comment by JSteunou** [comment]
Yes, I'm back next week, will test this against v3 to be sure.

**Comment by JSteunou** [comment]
Simple working example https://jsfiddle.net/xr7jj8of/1/

Demonstrate `regionClass` & `'@ui'` use https://jsfiddle.net/xr7jj8of/3/ 
`regionClass` & `this.ui` use https://jsfiddle.net/xr7jj8of/4/

All working well with v3 :)
