### ISSUE TITLE
no destroy or before:destroy event on region in a view

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#2999]
When using Region class it's hard to unbind or clean up things because there is no event to tell so from Region. Listening to parent view event do not work either because `stopListening` on region is called very soon. Add to override a bunch of method and listen to region manager to get it work.

**Comment by rafde** [comment]
Are you asking in favor of triggering `before:destroy` on regions?
https://github.com/marionettejs/backbone.marionette/blob/master/src/region.js#L255

**Comment by JSteunou** [comment]
Yep, on regions. The loc you're linking is on view.

**Comment by paulfalgout** [comment]
```js

**Comment by JSteunou** [comment]
I cannot get it worked in a layoutView :( 
I saw some loc removing regions listeners, maybe it's too soon.

**Comment by paulfalgout** [comment]
Ah yes, so what you're saying it that regions are not destroyed with the `LayoutView#destroy`

I think you can use `before:remove:region` on the layout to do what you're looking for.  Clearly not ideal.

I actually think in `v4` or possibly even `3.x` regions should be created on their first `getRegion` and should be recreated and destroyed with a lifecycle more like views instead of `Region#reset`  In this case there'd be much more use for `destroy`  Region never originally even had a destroy it was added incidentally when most things were made to extend `Object`

**Comment by JSteunou** [comment]
Here is a better description of my pain & sadness around this missing feature ;)

https://jsfiddle.net/jhr7qqre/1/ 

none of the region `console.log` are called :(

**Comment by paulfalgout** [comment]
I still think the `remove:region` events would cover this use-case.  I think in the future Regions should be created and destroyed instead of reset, but in the meantime, Regions aren't really meant to be destroyed.. they're "reset"

https://jsfiddle.net/jhr7qqre/2/

**Comment by JSteunou** [comment]
I understand, but I was looking for an easier API, from dev PoV. When creating regions to add some animation behaviors, it should be usable as it is, like a plugin. Instead I have to hack it or add some code in each views using this region. Not the simplest for custom regions user.

**Comment by paulfalgout** [comment]
I think perhaps this should be renamed.  The issue isn't the events it is that regions never get destroyed.  However I would suggest that we cannot do this right now.  When a region destroys, it empties itself, but that's probably not a performant action right now to tack on to view destruction.

**Comment by JSteunou** [comment]
I do not agree. The issue _is_ the missing events. Destroying the region is one technical way to solve this. But maybe it is simpler to just forward events or moving the stopListening from the parent.

**Comment by paulfalgout** [comment]
I don't think we should throw an event for something that did not occur.

As far as moving `stopListening`.. what's wrong with `this.listenTo(options.parent, 'before:destroy', this.onParentDestroy);`?

**Comment by paulfalgout** [comment]
actually.. the stopListening that's messing things up is the region remove.. not the views.. we might actually be able to fix this non-breaking..
