### ISSUE TITLE
v3 build file should be using this not global

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3013]
Currently it is building `global['Mn']` as an alias which works in node, but it should be `this['Mn']`

**Comment by denar90** [comment]
Will [this](https://github.com/rollup/rollup/issues/553#issuecomment-202166713) comment fix issue?

**Comment by paulfalgout** [comment]
this was actually wrong,  global is passed in via the UMD

I'm not sure exactly what issue I was seeing previously, but there isn't one, and I can't reproduce a problem
