### ISSUE TITLE
Try jQuery v3 rc with Marionette v3

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3018]
Just _in case_ it requires a breaking change.. might be worth doing today?

**Comment by JSteunou** [comment]
I think the only breaking change to be careful about is the removal of `.selector`

**Comment by JSteunou** [comment]
Just in case, I tested jquery v3 with Marionette v2 and Marionette.Modules are very impacted. With jquery v2 module launches its children, wait for it in sync mode then fire its own start event. With jquery v3, $.Deferred is now truly async and it as a huge impact on Marionette.Callback, which is used inside Module initializer. As an effect module are started from parent to children like always but parent start event is fired before children are started => async mode yay.

**Comment by paulfalgout** [comment]
I can confirm that there are 6 tests that fail with jQuery3, but they are only failing due to the tests themselves using the removed $.selector property.  I think this is 👍
