### ISSUE TITLE
Incorrect tag version

### ISSUE THREAD

**Issue by maratfakhreev** [marionettejs/backbone.marionette#3019]
[Last commit](https://github.com/marionettejs/backbone.marionette/commit/35e0f5ab9657be5fdd57d114c70ce7c3455eb66a) changes Marionette version to 2.4.6 but name of commit and tag version are wrong (2.5.6). I think it should be fixed b/c it confuses when you visit http://marionettejs.com

**Comment by JSteunou** [comment]
huu nice catch, everyone missed it. ping @ahumphreys87 ;)

**Comment by rafde** [comment]
A little late, isn't it?

**Comment by paulfalgout** [comment]
@rafde the version on npm and the data are inconsistent.  We might not be able to walk back a number somewhere but things need to be made consistent.  Even if this means we need to roll out `2.5.7`

**Comment by rafde** [comment]
Yeah, i figure it's confusing now.
So all the changes in https://github.com/marionettejs/backbone.marionette/commit/35e0f5ab9657be5fdd57d114c70ce7c3455eb66a now have to be updated to 2.5.7

**Comment by maratfakhreev** [comment]
Why? In npm it has 2.4.6. The problem just in github version tag and commit name. I think better solution just recreate tag without release. In the worst case change version to 2.4.7.

**Comment by ahumphreys87** [comment]
We can just delete the tag and retag the version.

Npm doesn't use git tags so it's fine but we should update for bower.

The only thing missing from the current tagged version is the bower and
component version bump

**Comment by paulfalgout** [comment]
I _think_ this is resolved.  Website needs to be redeployed, but otherwise this is ok now. If not, lemme know.
