### ISSUE TITLE
Marionette v3 should use any patch version as the peer dependency

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3037]
The peerDependencies for `Bb` and `_` should be `1.3.x` and `1.8.x`

**Comment by JSteunou** [comment]
peerDependencies or direct dependencies?

That aside I agree, bb and _ team seems to be more careful about semver than 2 years ago :)

**Comment by paulfalgout** [comment]
`v3` is peerDependencies.  Bb and _ still isn't following semver, but if there's breaking changes they're saying it won't be on the "patch" number.

**Comment by JSteunou** [comment]
With some `import from`, do bb and _ should be direct dependencies?

**Comment by paulfalgout** [comment]
because Bb and _ do not follow semver, in order to follow semver with Mn, direct dependencies make it a nightmare anytime either Bb or _ update.  People will install newer versions of Bb or _ regardless of what versions Mn defines as a direct dependency, and then not understand why their app breaks.  With peerDependencies, people will set Bb and _ as dependencies in their own projects, which for the most part people are doing already anyways, and if they attempt to use a version outside of the officially supported versions, it will let them and it might work just fine.. but it will warn them.

**Comment by JSteunou** [comment]
Right! It seems we already discussed about that because it rings a bell :D

**Comment by ahumphreys87** [comment]
I think they are following semver a bit better these days cant we go for `^1.3.0` etc?

**Comment by JSteunou** [comment]
Might be to lose. Wont go this far.

**Comment by denar90** [comment]
@ahumphreys87 wouldn't `^1.3.0` cost us problems if in future Bb will release v2 with breaking changes?

**Comment by paulfalgout** [comment]
for Bb v2 we'd probably want to do a major bump anyhow.. but `^1.3.0` === `1.x.x` and is set to v1.  But I don't think Bb is really following semver so much.. they're attempting to not introduce breaking changes.. particularly into the patch version, but there's absolutely no saying that at the last moment of building a `v2` that ashkenas wouldn't make the call that it wasn't worth a major version and would call it `1.5` and break everyones apps.

However.. with peerDependencies people can run _any_ version they want.. It'll just warn them if they're outside the "supported" versions.  I like this personally as things will probably work, but if there are breaking changes in Bb we don't have to officially support the change right away.
