### ISSUE TITLE
v3 childViewEvents destroy events can't trigger destroy

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3045]
This API worked in v2 but not in v3-pre.4

https://jsfiddle.net/599dtsb7/9/

**Comment by denar90** [comment]
Found the problem. So when [destroy](https://github.com/marionettejs/backbone.marionette/blob/next/src/mixins/view.js#L172) is calling it's calling region `empty` method which is deleting [view._parent](https://github.com/marionettejs/backbone.marionette/blob/next/src/region.js#L223).
So when `_triggerEventOnParentLayout` was called childView doesn't have parent so all [this](_triggerEventOnParentLayout) logic which is responsible for `childViewEvents` wasn't run.

**Comment by paulfalgout** [comment]
Yep you are correct.  A possible solution is to move the view._parent deletion until after the empty event is triggered, but I haven't tried that yet

**Comment by denar90** [comment]
What do you think about [this](https://github.com/denar90/backbone.marionette/blob/ffa8dbe2e38f775f951fe1e8f3b88959cd723199/src/region.js#L286-L288) solution?

**Comment by denar90** [comment]
.. should be `delete this.currentView._parent`

**Comment by paulfalgout** [comment]
Oh I don't think the regions destroy is part of this.  In fact a region currently is almost never destroyed.  Something that I think should change in the future.

**Comment by denar90** [comment]
fixed by #3049
