### ISSUE TITLE
Remove apply:filter event from v3 CollectionView#setFilter

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3047]
### Description

This event only occurs when using `setFilter` and the filter is attempted.  The new filter may not actually change the collection. And if you prevent the render or the view has never been rendered, this event won't fire.  I think the use-case for this event is nearly non-existent and it has edge cases that are odd to explain.  This event is new to v3 and I think we should remove it now.  We can always add it later if there is need, but I do not think we should add to the API / documentation if we don't have to.

@marionettejs/marionette-core thoughts?

### Environment

1. Marionette version: v3

**Comment by JSteunou** [comment]
Gotcha, :+1: to remove it, better now than having a cross to bear for all v3

**Comment by scott-w** [comment]
Happy with that, I can make a note on the `CollectionView` ticket that I'll (eventually) raise to not document that event.

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/issues/3051 @scott-w 😀

**Comment by scott-w** [comment]
:D
