### ISSUE TITLE
Update Documentation for Functions

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#3055]
We should look through removed methods and docs for new one.

Were removed:
 - `proxyGetOption` 
 - `proxyBindEntityEvents`
 - `proxyUnbindEntityEvents`
 - `normalizeUIKeys`
 - `normalizeUIValues`
 - `actAsCollection`

Were added:
 - `bindRequests`
 -  `unbindRequests`
 - `deprecate`
 - `isEnabled`
 - `setEnabled`
 - `monitorViewEvents`

**Comment by scott-w** [comment]
Are these related to any topic in particular? It'll be good to have a think about how this fits into #3066. It should be fine to put this into the `marionette.functions.md` file for now, however.

**Comment by denar90** [comment]
I think we should leave this file as it is between `Templates and Rendering` and `Errors` topics. What do you think about name `API` instead of `Functions`?

**Comment by scott-w** [comment]
API could work, or as part of "Advanced Topics"?

**Comment by paulfalgout** [comment]
soo..
I don't think we necessarily need to document `deprecate`

`monitorViewEvents` can be / will be documented as part of the View lifecycle
`isEnabled` / `setEnabled` should go along with installation / configuration I would think.. this is for feature flags...  _although_ we might want feature flags to have its own section now, as depending on how often they get used, that could be a significant bit of documentation.
bind/unbind seems perhaps like advanced topics.  I'm indifferent to where they go, but they're definitely for someone who is digging deeper..  Though a lot of it will be anything but "advanced" as far as difficulty or complexity..  for instance `isNodeAttached` is a very simple utility.  but as far as "advanced" means anything beyond the basics of what you need to know to get started.. 👍

**Comment by denar90** [comment]
resolver by #3068
