### ISSUE TITLE
Backbone + Marionette Basics

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3063]
I'm finding that a lot of documentation is repeating the same basic concepts e.g. attributes can take values or functions returning values, references can be methods on the view or function definitions.

I think it would be helpful to put together a "Backbone and Marionette Basics" doc that covers these cases that can be referenced everywhere. This gives two major benefits:

1. Readers can understand that some things are universal in the Marionette framework
2. We can assume base levels of knowledge when writing docs and shorten them a little

We can use this to introduce a basic Application/View so users can see the ideal case.

### Required Documentation

* [x] Setting functions for attributes
* [x] Setting options when creating a instance

Related to: #3066

**Comment by paulfalgout** [comment]
👍

**Comment by paulfalgout** [comment]
I think previously lack of consistency has kept this from being possible. :-)

**Comment by scott-w** [comment]
I'm pretty happy this is in place and we can slowly move the rest of the documentation over to referring to this in time.
