### ISSUE TITLE
Restructure Documentation

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3066]
Now that we have a good chunk of documentation in place, it's becoming clearer that we need to break up the documentation into different topics that can be more easily referenced from each other. The idea is to make the individual documentation pages shorter (Both `View` and `CollectionView` are over 1000 lines) and minimise duplication within the documentation.

### Topics

1. Install/Getting Started
2. Basic and Common concepts
3. Views
4. Collection Views
5. Events
6. Regions
7. Application
8. Behaviors
9. Radio
10. View Lifecycle
11. Routing
12. Object
13. Templates and Rendering
14. Errors
15. Upgrade from 2 to 3

### Discoverability

I think it's going to be really important to ensure that readers can find the documentation they need. This is going to involve some duplication - both the `View` and `CollectionView` docs will contain simple examples from the Events, Regions, Behaviors, and Radio documentation. We'll need to be conscious of this when we're updating features and documentation for those features.

### Discussion Points

I'd appreciate feedback on the topics - is there anything missing or unnecessary here? Does the order look alright?

**Comment by paulfalgout** [comment]
Might be worth putting application, object, and radio together..  The rest of the docs are view related.   We also need a doc for routing.  Possibly suggesting options, but AppRouter is still in v3.

**Comment by scott-w** [comment]
That's a good point that I've missed the `AppRouter`. We could roll `Object` into an Advanced topics for now with #3055. We can roll `Radio` into both `Application` and `Object` with a link to the official `Radio` documentation.

Another option could be to get a brief description of `Application` into the Getting Started overview with all the extra detail going into the Application/Object/Radio documentation merged as you suggest.

**Comment by rafde** [comment]
Mission Accomplished, @scott-w ?

**Comment by scott-w** [comment]
Yeah, I think it's safe to close this and we can open specific tickets for the extra bits needed.
