### ISSUE TITLE
TypeError: ChildViewContainer is not a constructor

### ISSUE THREAD

**Issue by Regnoy** [marionettejs/backbone.marionette#3070]
Simple example from documentation Marionette 3.0.0 - pre.4 + Require.js

 var MyChildView = Marionette.View.extend({});

 var Col =  Marionette.CollectionView.extend({
    childView: MyChildView
  });
  new Col();

I have console error.
> TypeError: ChildViewContainer is not a constructor	
> this.children = new ChildViewContainer();

**Comment by denar90** [comment]
Looks fine https://jsfiddle.net/599dtsb7/13/

**Comment by Regnoy** [comment]
jsfiddle use AMD?

**Comment by Regnoy** [comment]
My solution temporary is:

`ChildViewContainer =  factory(Backbone, _);
				/*define(['backbone', 'underscore'], function(Backbone$$, _$$) {
					return factory(Backbone$$, _$$);
				});*/`
and comment this line
//var ChildViewContainer = (backbone_babysitter && typeof backbone_bab .....

After that all work fine.

**Comment by JSteunou** [comment]
I dont understand fully your issue. Is there a problem using Marionette with requirejs?

Can you make fiddle demonstrating the issue?

**Comment by paulfalgout** [comment]
It sounds like perhaps you want to be using the bundled version 
https://github.com/marionettejs/backbone.marionette/blob/next/lib/backbone.marionette.js

Instead of the core version:
https://github.com/marionettejs/backbone.marionette/blob/next/lib/core/backbone.marionette.js

The bundled version includes babysitter.  If you're using the core then you need to include babysitter separately.

**Comment by paulfalgout** [comment]
Ahhhh. never mind.. after reviewing your last comment it looks like you are using the bundled version.  I don't see any particular reason the `define` wouldn't work.  The bundler is modifying the variable names so that it is clear that the included library is not reaching outside of its closure to get Backbone and _... I am not certain why there would be any issue.. a fiddle of this loading with require might be necessary to debug any issue

**Comment by Regnoy** [comment]
Thanks for response, and sorry for bad english :)

I use Marionette 3.0.0 - pre.4 (Bundled Version)
with 
/*!
* Includes BabySitter
* https://github.com/marionettejs/backbone.babysitter/
*
* Includes Radio
* https://github.com/marionettejs/backbone.radio/
*/
+ Require.js

I attach zip file.
[git.zip](https://github.com/marionettejs/backbone.marionette/files/317822/git.zip)

I hope help you. Wait for response.

**Comment by JSteunou** [comment]
Ok now I see it. @paulfalgout there is indeed an issue with the baby sitter build. In AMD it's just a void object, so `ChildViewContainer` is not null or undefined, but certainly not the baby sitter constructor.

**Comment by JSteunou** [comment]
Got it I think. The UMD header in each dependency (like radio, baby sitter) is legit and debugging step by step in it shows the issue. `define` is async in AMD and unfortunately we are getting out of `var backbone_babysitter = __commonjs` before it's loaded, so `ChildViewContainer` is not correct after that.

I dont know about the build process, but our dependencies should be marked as not only CJS so the wrapping loader inside Marionette above the UMD loader of each lib handles async.

This issue shows not on a CJS or compiled AMD project.

**Comment by Regnoy** [comment]
My solution is simple, manual change code in Mn 3.0 (Bundle Version)
Line 2226
`var ChildViewContainer = null;`
Line 2239 add this
`if (typeof define === 'function' && define.amd) {
		ChildViewContainer = factory(Backbone, _);
	    /*define(['backbone', 'underscore'], function(Backbone$$, _$$) {
	      return factory(Backbone$$, _$$);
	    });*/
	  } else if (typeof exports !== 'undefined') {`

Line 2421 add bloc code
`var ChildViewContainer = (backbone_babysitter && typeof backbone_babysitter === 'object' && 'default' in backbone_babysitter ? backbone_babysitter['default'] : backbone_babysitter);`

This code worked only who use require JS via MN 3.0 Bundle Version

**Comment by paulfalgout** [comment]
This is most likely an issue with on of the rollup plugins :-/  Not sure of the best plan to fix that..  This needs to be fixed at the tool level as all of that is generated code... so we can't simply add the suggestion as mentioned.
