### ISSUE TITLE
Remove References to AbstractView

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3073]
### Description

 1. The `AbstractView` was removed from Mn 3 but references are still in the documentation. It also forces people to look at the documentation there, away from the actual API they're using.
 2. We need to remove all references to `AbstractView` and move the detail into the respective documentation.
 3. This will update the documentation in line with the codebase and help readers find the information they need.
 4. This is related to #3066.

### Environment

1. Marionette version: 3.0.0-pre4
2. Backbone version: All
3. Additional build tools, etc: N/A

**Comment by denar90** [comment]
@scott-w should this issue wait until `View Lifecycle`, `View`, `Events` etc docs is done, to add right references?

**Comment by scott-w** [comment]
If there's anything to be pulled into other docs, we could start by getting that all put into roughly the right places then just ditch this file.

After that, we can start figuring out how to cleanly split up the docs to make them easier to navigate. I don't see #3066 blocking Mn 3 as long as the content is there.

**Comment by denar90** [comment]
merged #3074
