### ISSUE TITLE
Error with Marionette 2 and Jquery 3

### ISSUE THREAD

**Issue by mchu42** [marionettejs/backbone.marionette#3077]
I'm facing with problem when update jquery to version 3.

Here is examples:
It's working with jquery2.2.4 and marionette2.4.7: https://jsfiddle.net/hL9fbc0m/
And throw error with jquery3 when i try to return first layout view to the region: https://jsfiddle.net/7L2mLLt1/2/

In the console, you can see the cause of the error.

**Comment by paulfalgout** [comment]
jquery 3.0 is not going to work with marionette 2.x.  However Mn v3 will.

**Comment by wbercx** [comment]
It does seem to lead to some interesting issues. It seems you cannot re-render any views in regions because the `el` will be `undefined`. 

Will hold off until Mn v3 is stable.  Thanks for the heads up @paulfalgout

**Comment by devel-pa** [comment]
Fixable by overriding:

'''
Marionette.Region.prototype.reset = function() {
  this.empty();

    this.el = this.options.el;

  delete this.$el;
  return this;
};
'''

**Comment by rvnath** [comment]
Does marionette now suppoort JQuery 3.x version?  We have the same challenge.  After the initialize method call in a ItemView component, the screen goes totally blank and there are no errors or warning in web console.

**Comment by paulfalgout** [comment]
It does

**Comment by johnpmitsch** [comment]
> It does

@paulfalgout Does this mean the just later (v3 and v4) versions of Marionette work with jQuery 3.x or Marionette v2 now supports jQuery 3.x?

**Comment by paulfalgout** [comment]
Marionette v3+ supports jQuery v3.x and v2 would have to be patched as mentioned here https://github.com/marionettejs/backbone.marionette/issues/3077#issuecomment-238217100 (at least) to work.
