### ISSUE TITLE
region#showChildView does not check if the region exists

### ISSUE THREAD

**Issue by jonas-db** [marionettejs/backbone.marionette#3078]
region#showChildView throws an error (Uncaught TypeError: Cannot read property 'show' of undefined) when a given region name does not corresponds to an existing region object. 
Shouldn't this be checked somehow?

I'm using the latest version of marionette v3.0.0-pre.4

Location in the code:
https://github.com/marionettejs/backbone.marionette/blob/v3.0.0-pre.4/src/mixins/regions.js#L178

**Comment by scott-w** [comment]
Hi @jonas-db, thanks for posting this.

See #2795 for more discussion on this issue.

**Comment by paulfalgout** [comment]
I'm going to close this since it is linked now on the discussion
