### ISSUE TITLE
Change Documentation to Say jQuery 3.0 is Unsupported

### ISSUE THREAD

**Issue by nfcopier** [marionettejs/backbone.marionette#3080]
Currently (v.2.4.7), jQuery 3.0 breaks a lot of functionality. See #3018.
The docs at Marionettejs.com do not mention its dependencies at all and the readme on GitHub does not make it clear that it breaks with versions of jQuery above 2.X.X.
I discovered this issue after spending most of a day tracking down breaking change that occurred in region resetting.
I suggest updated the readme.md to reflect this incompatibility. I'll submit a pull request for this.

**Comment by denar90** [comment]
@nfcopier what do you think about throwing error using `MarionetteError` if jQuery version 3+?
```
throw new MarionetteError({
        name: 'Invalid jQuery version',
        message: 'jQuery 3+ version is not supported'
      });
```

**Comment by paulfalgout** [comment]
@denar90 I hesitate to introduce changes to 2.x.  A docs change is super easy.  But unless there's a bug, releases are time consuming.

**Comment by paulfalgout** [comment]
We can open a new issue if need be, but I merged the doc change

**Comment by devel-pa** [comment]
Please, do not block Marionette to use jQuery 3.0. Thank you

**Comment by scott-w** [comment]
This issue was that, while jQuery 3 worked, it caused our tests to fail. We've since amended our tests for it to pass so, in Marionette 3, jQuery 3 should be supported.

**Comment by paulfalgout** [comment]
jquery 3 works in Mn v3, but not in Mn v2

**Comment by devel-pa** [comment]
In my project Mn v2 works with jQ v3 and jQ migrate v3. Until now I found only one issue with `.selector` in regions, easy fixable.
