### ISSUE TITLE
how can i get the demo of backbone.marionette

### ISSUE THREAD

**Issue by dericgit** [marionettejs/backbone.marionette#3084]
### Description

 1. The problem you are facing (in as much detail as is necessary to describe the problem to someone who doesn't know anything about the system you're building)
 2. A summary of the proposed solution
 3. A description of how this solution solves the problem, in more detail than item #2
 4. Any additional discussion on possible problems this might introduce, questions that you have related to the changes, etc.

### Expected behavior

Tell us what you think should happend.

### Actual behavior

If it is possible, please create a small demo that demonstrates the issue.
Please refrain from giving code examples in altJS languages like CoffeeScript, etc. Marionette is written in plain-old JavaScript and is generally easier for all members in the community to read.

### Environment

1. Marionette version:
2. Backbone version:
3. Additional build tools, etc:

**Comment by paulfalgout** [comment]
This is an excellent question to ask here: https://gitter.im/marionettejs/backbone.marionette

Also look here: http://marionettejs.com/additional-resources/  There are plenty of tutorials and example apps.
