### ISSUE TITLE
Bulk removal of childViews for Collection Views

### ISSUE THREAD

**Issue by KamalAman** [marionettejs/backbone.marionette#3086]
### Description

 I'm work with a Collection View who's entire collection can change, the Collection has roughly 100 models at any time. When the Collection changes it causes a render on the Collection View. When Collection Views render it calls destroyChildren and removeChildView for each child. The performance issue come in removeChildView in the following  lines where each child is removed one at a time and this.children.remove and _updateIndices are called. 

```
this.children.remove(view);
this.triggerMethod('remove:child', this, view);

// decrement the index of views after this one
this._updateIndices(view, false);
```

`this.children.remove` calls _updateLength which then calls  _.size(this._views);
`this._updateIndices` calls _.values(this._views)

Both of these _. operations are expensive to do.

 1. Don't call this._updateIndices and this.children.this._updateLength 'n' times, only call them once from destroyChildren
 2. Pass in an options to reviewChildView to bypass this._updateIndicies and this.children.remove's _updateLength. After destroyChildren calls removeChildView for each child, it can then call this._updateIndicies and this.children._updateLength
 

### Expected behavior

Removing childViews should be a quick processes. On my computer with a collection of about 100 models it takes about 0.4ms to destroy a child view, so the removal of a child view should be roughly 0.4ms.

### Actual behavior

A collection view of 100 models it takes about 2ms to remove a child view. On average 0.4ms is spent destroying the view, 0.6 ms in _updateLength, and 1ms in _updateIndices 

![screen shot 2016-07-28 at 1 02 06 pm](https://cloud.githubusercontent.com/assets/2692357/17221847/8eb9ac74-54c3-11e6-873c-00aa9ca9e057.png)

### Environment

1. Marionette version: ^2.4.5
2. Backbone version: 1.3.2

**Comment by megawac** [comment]
I'm all for this (though rather than an option I'd prefer a new "internal" method. Any interest working on this patch @KamalAman?
