### ISSUE TITLE
Event Doc Improvements

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3092]
Some feedback on the events documentation:

1. The opening is a little confusing
2. Try opening with `listenTo` and `trigger` from Backbone
3. Introduce an example of event binding from inside the view
4. Introduce an example of event binding from another source onto the view
5. Explain that the event listeners must be unbound manually when created on external context
6. Move onto `triggerMethod`

@JSteunou Can you check that I've got the gist of what you're trying to say here?

**Comment by JSteunou** [comment]
on the 5th I would add: *Explain that the event listeners from inside the view  with `on` and `listenTo` are automatically unbind on view destroy but...* and continue with the explanation and the why when what on the manual necessary unbind. Maybe with a continuation and a little sensitivity / warning on external plugins (like jQuery's ones) used inside a view that often needs to be unbind **and** destroyed on view destroy.

**Comment by scott-w** [comment]
I'm closing this as it was related to the v3 release.
