### ISSUE TITLE
babysitter PR not in pre5

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3099]
A commit to the major branch of babysitter was overlooked moving it to Mn.

https://github.com/marionettejs/backbone.babysitter/pull/73/files

@rafde interested in adding this to `next`?

**Comment by rafde** [comment]
@ahumphreys87 beat me to it. But I did present the question of why babysitter test are included in marionette. Code coverage for babysitter should be dealt with in babysitter.

**Comment by paulfalgout** [comment]
babysitter is no longer a dependent of Mn3.

**Comment by ahumphreys87** [comment]
Fixed via #3105
