### ISSUE TITLE
Separate Templates from View

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3103]
The template rendering logic is mixed in with the View documentation. We should separate this into its own file so it's easier for the reader to find the specific information they need. It'll also give us a clear place to put all the extra little bits from `marionette.templatecache.md` and `marionette.renderer.md` into.

All three of these sections should link heavily to the initial template document so we can direct the user to find it more easily.

**Comment by denar90** [comment]
resolved #3108
