### ISSUE TITLE
show/onShow event not raised on a view when it's shown in a region

### ISSUE THREAD

**Issue by dmcknight26** [marionettejs/backbone.marionette#3104]
### Description

Region docs for v3 state that **"show / onShow - Called on the view instance when the view has been rendered and displayed. This event can be used to react to when a view has been shown via a region."** though that event is not being raised.

Previous versions of marionette (2.4.x) included this snippet inside the region 'show' method, which seems to have been removed.  Can it please be restored?

`Marionette.triggerMethodOn(view, 'show', view, this, options);`

### Environment

Marionette version: v3.0.0-pre.4
Backbone version: 1.3.3

**Comment by rafde** [comment]
https://github.com/marionettejs/backbone.marionette/blob/v3.0.0-pre.5/docs/upgrade.md#show-and-beforeshow

show has been removed.
you can use anything from

https://github.com/marionettejs/backbone.marionette/blob/v3.0.0-pre.5/docs/marionette.view.md#lifecycle-events
or
https://github.com/marionettejs/backbone.marionette/blob/v3.0.0-pre.5/docs/marionette.collectionview.md#collectionview-events-and-callbacks
or 
https://github.com/marionettejs/backbone.marionette/blob/v3.0.0-pre.5/docs/marionette.region.md#region-events-and-callbacks

just not `show` or `before:show`

**Comment by scott-w** [comment]
Thanks @rafde for helping to answer this.

@dmcknight26 Also see http://marionettejs.com/docs/v3.0.0-pre.4/upgrade.html
