### ISSUE TITLE
Remove link to Backbone.BabySitter in CollectionView doc

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#3110]
Since we don't have dependancy from `Backbone.BabySitter` I propose remove link on it form our doc
https://github.com/marionettejs/backbone.marionette/blob/next/docs/marionette.collectionview.md#collectionviews-children
and inject doc of it into Mn doc. It can be separate file or just extending our CollectionViewDoc file.

@scott-w @paulfalgout what do you think?

**Comment by scott-w** [comment]
Sounds like a plan. We can just do a copy and paste job initially and work it around later.

**Comment by ahumphreys87** [comment]
fixed via #3111
