### ISSUE TITLE
Update TodoMVC example

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#3122]
After v3 release it will be great to update [TodoMVC example](https://github.com/tastejs/todomvc/tree/master/examples/backbone_marionette)
P.S. There also some outdated references in readme.

**Comment by kostyay** [comment]
Please update it with ES6 as well

**Comment by scott-w** [comment]
Hi @kostyay, we're still discussing whether this is best for readers. Whilst Marionette itself is written in ES6, it still introduces a build step between writing your code and seeing your code run. It also requires extra configuration in webpack, browserify, grunt, etc. that we'd have to clearly document and link to everywhere.

It would be great if you could help us by outlining what you see as the important benefits of documenting Marionette in ES6 against remaining in ES5.

**Comment by vernondegoede** [comment]
I could pick this one up this week! Could you assign it to me? @scott-w

**Comment by scott-w** [comment]
@vernondegoede Unfortunately, Github only lets me assign it to Marionette.js members.

I'll add a couple of tags that should help identify it for you.

**Comment by denar90** [comment]
@scott-w I think we just expanded this issue more then I proposed to do... I was talking about updating TodoMVC example. I already created PR for this https://github.com/tastejs/todomvc/pull/1676

If we wanna update doc using es6/7 then we should better create some kind of topic for this. What do you think?

**Comment by paulfalgout** [comment]
@denar90 is this done now?

**Comment by denar90** [comment]
Yes, this one can be closed since PR was merged.
