### ISSUE TITLE
Feature: Persistent regions that survive a containing view's re-render

### ISSUE THREAD

**Issue by rbu** [marionettejs/backbone.marionette#3124]
### Description

When re-rendering a view, its child views get re-rendered as well even when that might not be necessary.
If regions/child views could be marked as persistent, Marionette would simply detach a child view and reattach it after the region is re-rendered.

This would probably require a way to explicitly provide a generator function so Marionette could generate a view itself.

### Expected behavior

What I am trying to achieve is this:

```js
SomeView = Mn.View.extend({

	modelEvents: function() {
		return {
			'change': 'render'
		};
	},
	
	regions: {
		editor: '.editor-region'
	},
	
	childRenderers: {
                editor: function() { return new EditorView(); }
	},
```

Now, when the model changes, causing a re-render of SomeView, it's editor (which may contain edited state) is not destroyed and simply re-attached (same View instance/cid, same region $el).

### Actual behavior

Currently, this is rather hard to achieve:
```js
	regions: {
		editor: '.editor-region'
	},
	
	onRender: function() {
		if ( ! this.cachedEditor) {
			this.cachedEditor = new EditorView();
		}
		this.showChildView('editor', this.cachedEditor);
	},
```

This will raise a ```ViewDestroyedError``` for the EditorView. Now, I could hook into the unload hooks and detach the Editor before SomeView is re-rendered and remove it in a non-destructive way, but it seems this is functionality best suited for Marionette proper.

### Environment

1. Marionette version: 3.0.0.0 pre 5
2. Backbone version: 1.3.3

**Comment by paulfalgout** [comment]
I think this is: https://github.com/marionettejs/backbone.marionette/issues/1263

Regions are moving in the direction where this seems like it would be pretty possible.

**Comment by rbu** [comment]
@paulfalgout, sorry for reporting a duplicate and thank you for finding the original. That issue is pretty much what I meant to report. Hoping for this to land with the region changes you mentioned.

**Comment by paulfalgout** [comment]
no need to be sorry.  Issues with Mn are deep.  This is definitely a good one to remember!
