### ISSUE TITLE
Channel name for Mn.Object is required 

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#3131]
### Description

`Mn.Object` supposed to manage events/requests from several channels like
```
radioEvents: {
  'app start': 'onAppStart',
  'books finish': 'onBooksFinish',
}
```
where `app`, `books` are channel names.
But to make it works it's needed to add channel name, no matter which one, like
```
channelName: 'app',
radioEvents: {
  'app start': 'onAppStart',
  'books finish': 'onBooksFinish',
}
```
Here an example - https://jsfiddle.net/denar90/gegbhfyu/1/
Example which doesn't work - https://jsfiddle.net/denar90/gegbhfyu/2/

### Expected behavior

It has work without passing `channelName`.

### Actual behavior

It's needed to pass `channelName` to handle channel events/requests

### Environment

1. Marionette version: v3.0.0-pre.5
2. Backbone version: 1.3.3
3. Additional build tools, etc:

**Comment by paulfalgout** [comment]
I think at one point Mn was going to do this: 
> supposed to manage events/requests from several channels like

But it doesn't now.. it's currently 1 channel per object.

The implementation was much simpler and for requests having multiple channels is potentially problematic.  You can only have _one_ replier to any channel in an app.  I believe this helps to enforce SRP for any particular object and for other one-off listeners of channel events, you just spawn a channel then and there.

So with the current implementation they keys do not support other channel names.

Ref: https://github.com/marionettejs/backbone.marionette/issues/2515#issuecomment-116831583

**Comment by denar90** [comment]
Oh agree, but here appears another problem or no... If channel name was specified, either `onAppStart` or `onBooksFinish` will be called if either `app.trigger('start')` or `books.trigger('finish')` is executed.  (take a look at first fiddle)  But `onBooksFinish` has to be ignored to prevent errors in future.
So somehow we have to track if second channel is present in Object and throw error or something...

**Comment by denar90** [comment]
I'm closing this due to stupid using same hash of event `some:event`.
