### ISSUE TITLE
Add forkable fiddle in contribution template

### ISSUE THREAD

**Issue by rafde** [marionettejs/backbone.marionette#3141]
### Description

 1. Guidelines suggest including demos for issues.

### Expected behavior

Provide a forkable fiddle link in the guidelines template with the bare minimum deps for using Mn. This will allow for quicker demo setup up.

### Environment

demo fiddle.

**Comment by rafde** [comment]
https://jsfiddle.net/rafde/o800t9kn/
Base fiddle with
jquery 3.1.0
underscore 1.8.3
Backbone 1.3.3
Backbone.Radio 2
Marionette 3

**Comment by denar90** [comment]
Here fiddle under Mn account if someone needs it 
https://jsfiddle.net/marionettejs/adhv48ky/

**Comment by rafde** [comment]
Thanks, I'll PR some time later.
