### ISSUE TITLE
Fix Bower dependencies

### ISSUE THREAD

**Issue by hashchange** [marionettejs/backbone.marionette#3148]
Marionette 3.0.0:

- The Bower dependency for Backbone.Radio is still stuck at 2.0.0-pre.1. 
- Backbone and Underscore are missing. Bower doesn't have peerDependencies (it [wouldn't make sense](https://github.com/bower/bower/issues/292), dependencies are not nested anyway). So it appears that Backbone and Underscore should be listed as ordinary dependencies, which is nearly the same as npm peerDependencies.

  (I'd recommend a range of acceptable releases, not a "newest or higher" `~1.3.3`.)

Marionette 2.4.7:

- Installs Backbone 1.2.3, rather than 1.3.3. The version range in bower.json is ok, though. The problem seems to originate in Backbone.Babysitter as well as Backbone.Wreqr, which both use an invalid range format (`"backbone": ">=0.9.9 <=1.3.x"`). I've opened [issues](https://github.com/marionettejs/backbone.babysitter/issues/79) [there](https://github.com/marionettejs/backbone.wreqr/issues/83).

**Comment by paulfalgout** [comment]
I'm not a bower user but am I correct in thinking all we need to do is get these changes into master?  no new release needed?

**Comment by paulfalgout** [comment]
well with the exception of maybe `2.4.7` hmmm

**Comment by hashchange** [comment]
No, it actually needs a new release I'm afraid. Just like npm, Bower checks out the Marionette version you specify, and with tag 3.0.0., you get bower.json in the state it had at the time.

**Comment by ahumphreys87** [comment]
ok it just needs a patch release. @hashchange would you be interested in opening a PR for this?

**Comment by hashchange** [comment]
I would be interested ;)
