### ISSUE TITLE
Duplicates in View doc

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#3151]
We have pretty same blocks in View doc
https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.view.md#defining-listeners-1
https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.view.md#defining-listeners
I think we should remove one of them.

**Comment by scott-w** [comment]
I agree, it's a bit too copy and paste. I'll have a re-jig of the docs to make it look a bit more like:

1. Binding to User Input
2. The mechanisms (how `events`/`triggers` object itself works)
3. The `events` object
4. The `triggers` object
