### ISSUE TITLE
Missing some regions old documentation

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#3152]
Some advanced features are not documented (yet ;)) in the `regions` section. This was part of the old doc.
- using `regionClass` option to provide a custom region class / object
- using `@ui` as selector
- using `el` option when providing an extending region definition with `this.ui.foo` or `'@ui.foo'` or `'#foo'`

see #2998 last comment for some fiddle

**Comment by JSteunou** [comment]
@scott-w do you wanna take this one?

**Comment by rafde** [comment]
related to https://github.com/marionettejs/backbone.marionette/issues/3154

**Comment by scott-w** [comment]
Yeah, so as part of my work on the regions docs, I wasn't sure what we were keeping and removing from the public API so i erred on the side of caution.

My thinking was that we can just restore docs to the API easier than removing functionality we decided wasn't right later.

In terms of the selector features, I'll have a look at getting those documented.

What is the current general consensus on the `Region` class? How do people see it being used outside of the Marionette code?

**Comment by paulfalgout** [comment]
I think for the common case we want to remove needing to worry about what the Region is doing.. but I think there are plenty of cases for using regions directly.  

I personally use plenty of custom regions.  They act as containers where no matter what view I show in them, they add the same behavior to the view being shown.
