### ISSUE TITLE
Are Region-specific events still part of the API?

### ISSUE THREAD

**Issue by marfire** [marionettejs/backbone.marionette#3154]
Huge changes were made to the documentation of `Region` between v3.0.0-pre.5 and v.3.0.0. One of those changes was the removal of any documentation of `Region` events (e.g. `show`). 

#2959 implies that this is to "clean out unsupported features". I hope that's not the case here, because this is a useful feature that as far as I know is not available elsewhere in the framework. Given a region object, how can I be notified when something is shown within it?

Just to be clear, this event is still fired and everything works as before, I'm just addressing the fact that it's been removed from the documented API.

(By the way, the removal of this documentation also left a [broken link](https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.region.md#showing-a-view) for "events fired during show".)

**Comment by rafde** [comment]
@marfire thanks for 
> (By the way, the removal of this documentation also left a broken link for "events fired during show".)

would you be willing to remove that broken line by PR?

add/remove region events are around. But swapIn/swapOut are not. Was there some other region specific event you were wondering about?

**Comment by paulfalgout** [comment]
It does look like `### Events Raised on the Region During `show()`` was incorrectly removed.  Regions still have `show`, `empty`, and _technically_ `destroy` (though likely not used very often at the moment) events triggered on themselves.

**Comment by scott-w** [comment]
I've commented on #3152 - basically, the question we need to answer is how much we intend the `Region` class to be exposed  and used publicly.

**Comment by paulfalgout** [comment]
These events are in the docs on `master` now.
