### ISSUE TITLE
 Marionette Inspector

### ISSUE THREAD

**Issue by fengyuchenglun** [marionettejs/backbone.marionette#3158]
marionettev3 can inspect by Marionette Inspector - Chrome Extension？
![image](https://cloud.githubusercontent.com/assets/11927244/18167192/c8873b9a-7081-11e6-9197-5ce8b21183b8.png)

**Comment by scott-w** [comment]
Hi @fengyuchenglun, thanks for this.

Currently, Marionette.Inspector doesn't support Marionette 3. I've created marionettejs/marionette.inspector#313 to track these issues.
