### ISSUE TITLE
No "before:render" or "render" events when showing view in region

### ISSUE THREAD

**Issue by DenMesh** [marionettejs/backbone.marionette#3162]
### Description

Consider the following situation. There is a region attached to an existing DOM tree so that the region's "el" has some child nodes. Then a view is attached to the region, with "el" property set to an immediate child of the region's element and "template" property set to false. According to the docs (View => Managing an Existing Page) it should fire "render" and "before:render" events if shown in the region, even though no actual rendering happens. This is not so. According to the code, if there is an "el" property, the "_isRendered" property is set to true (view mixin, line 58) and if the "_isRendered" property is true, then the view's "render" method is never called (region, line 81).

### Environment

1. Marionette version: 3.0.0
2. Backbone version: 1.3.3
3. Additional build tools, etc: Webpack

**Comment by scott-w** [comment]
Hi @DenMesh, thanks for reporting.

I understand correctly:

```javascript
var MyView = Mn.View.extend({
  el: '#my-selector',
  template: false,

  onRender: function() {
    console.log('this will never fire');
  }
});

var app = new Mn.Application({...});
app.getRegion().show(new MyView());
```

The `render` event shouldn't fire in this case because no rendering happens. Is that correct?

**Comment by DenMesh** [comment]
Exactly this, yes.

**Comment by scott-w** [comment]
Thanks, I'll update this ticket as an issue with the docs.

**Comment by paulfalgout** [comment]
I don't think this is a bug.  In fact I find with v3 there is extremely little use-case for `template:false` If you never intend to render this view because the DOM exists and the template is false, use `initialize`  v3 was modified so that the constant unwanted re-rendering was removed.

**Comment by DenMesh** [comment]
Never said it was a bug. It is an inconsistency between the docs and the code. Namely, 

> Though the View has no template,
you can still listen to the `before:render` and `render` events that will fire
as usual _when render is called_ - or when you execute `region.show(view)`.

(emphasis mine)

**Comment by scott-w** [comment]
Ahh that was my bad, I'll take the bug label off
