### ISSUE TITLE
templateContext being applied in '1-off' fashion

### ISSUE THREAD

**Issue by DerHowie** [marionettejs/backbone.marionette#3163]
### Description

 I am attempting to introduce a few additional props to the context of my handlebars templates on the childViews of a collectionView. 

```js
var aCollectionView = Mn.CollectionView.extend({
  childView: Mn.View.extend({
    template: hbsTemplate,
    templateContext: {
      thing: null
    },
    ...
    populateTemplateContext: function () {
      this.templateContext.thing = something === anotherThing;
    },
    ...
    onRender: function () {
      this.populateTemplateContext();
    }
  });
}); 
```

### Expected behavior

I should have access to 'thing' in my templates' context.

### Actual behavior

The additonal props I am setting in templateContext are being applied and I have the ability to access them, but they are being applied 1 position in the index of my collection's childViews too high.

for example: if I conditionally render a div depending on the value of templateContext's prop I am seeing this behavior:

--- I return {thing: true}, {thing: true}, {thing: true} to my templates respectively, but see... ---
templateOne: div doesn't show up,
templateTwo: div appears,
templateThree: div appears

In addition to this, which is what has given me the '1-off' theory...

--- I return {thing: true}x10 + {thing: false} at the end of the collection ---

templateOne: div doesn't show up,
templateTwo - templateEleven: div appears

### Environment

1. Marionette version: 3.0.0
2. Backbone version: 1.3.3
3. Handlebars version: 4.0.5

**Comment by scott-w** [comment]
This is because `onRender` is fired _after_ `templateContext` is computed meaning `this.thing` will always be `null` at the time of render.

A better way might be to do:

```javascript
var aCollectionView = Mn.CollectionView.extend({
  childView: Mn.View.extend({
  template: hbsTemplate,
  templateContext: function() {
    var something = this.getSomething();
    var anotherThing = this.getAnotherThing();
    return {
      thing: something == anotherThing
    };
  }
}); 
```

**Comment by JSteunou** [comment]
To second that ; Marionette events are always prefixed with `before` when it is fired  *before* the event (like `onBeforeDestroy`), and with no prefix it is always *after*.

**Comment by paulfalgout** [comment]
This looks resolved to me. Are there other questions?
