### ISSUE TITLE
Lint for import spacing without alignment

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3166]
At one point we were aligning imports
```js
import _                from 'underscore';
import backbone from 'backbone';
```
etc

But as we were doing significant changes on v3 we were getting more merge conflicts than necessary, and a deep git blame etc from maintaining the alignment.  So in gitter it was decided at the time to no longer align them.  But we haven't fixed it or linted for it, so it is hard to know what to do.

**Comment by RomanovRoman** [comment]
#3241 fix overall spaces for now, but it have some options (if you need only import formatting).
