### ISSUE TITLE
Fix doc linter warnings

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3167]
This should be a quick fix.  It isn't breaking anything but it is loud in gulp.

If you run `gulp lint` the issue is easy to see.

**Comment by clickclickonsal** [comment]
I can do this fix, but the develop branch is not up to date with master. 
I have submitted the pull request because of this. https://github.com/clickclickonsal/backbone.marionette/tree/fix-lint-errors

**Comment by paulfalgout** [comment]
👏 Good deal. Thanks!  I manually merged this on `master` it'll get added to next when we roll `v3.1` shortly

**Comment by clickclickonsal** [comment]
Awesome! Thanks. I want to help contribute more, how should I submit my pull requests for patches?
