### ISSUE TITLE
Remove AppRouter and make it an external lib

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3169]
`AppRouter` is entirely optional. Many users don't use it, and there are many great alternatives. Personally I do not believe Marionette needs a single sanctioned router, but whether or not another router is added, `AppRouter` can be removed.

There may be some concern that Marionette is incomplete as a library without a router, but I think backbone's router is just as good of a starting place as `AppRouter`.  Once someone needs to solve additional problems in routing, they can explore the many alternative options, and hopefully we can provide food recipes for some.

**Comment by JSteunou** [comment]
I have split feelings about this. On the one hand I totally agree with you, on the other hand appRouter brings bindings with Controller and `onRoute` event that are useful and a good no brain starter for beginners. There is a lot to learn when starting with a fw/lib (even if Mn is far away from the hardest to learn) and adding more stuff to learn / setup could be a drag. But you also can argue that learning about appRouter & Controller is more stuff to learn... Having beginners PoV could help, mine might be thwart from being use to use appRouter.

**Comment by paulfalgout** [comment]
My biggest thought behind this is that many people may not use this router.  And I suspect if we made it an external lib that less people would use it.  So while this router might be better than Backbone's, it may not be the best router for someone's app, but by including it in the lib it seems like the opinion of Marionette is that you should use this router.  By making it external we can still support it (to some degree router issues become easier to support) and we can offer other options as well in Mn documentation.

**Comment by denar90** [comment]
I'm 👍  for deprecating it in v4. Moving it in separate repo might give it second wind. First version probably will be the same as it is right now but later we can make a lot of improvements. @jmeas made good list https://github.com/jmeas/router-comparison about what was missed in Backbone router, so our one can fill empty gaps.

**Comment by paulfalgout** [comment]
As part of this work wee need to consider:

https://github.com/marionettejs/backbone.marionette/issues/2280
https://github.com/marionettejs/backbone.marionette/issues/2092
