### ISSUE TITLE
onAddChild callback params changed, never noted in Changelog.

### ISSUE THREAD

**Issue by KeyHui** [marionettejs/backbone.marionette#3170]
Before:

``` javascript
{
    onAddChild: function(childView) {}
}
```

Now:

``` javascript
{
   onAddChild: function(currentView, childView) {}
}
```

Have other function params changed ?

**Comment by scott-w** [comment]
Thanks for this @KeyHui, I've updated your message with code blocks. There's likely a gap in our documentation in the arguments passed to event handlers here.

**Comment by paulfalgout** [comment]
This actually true for all events.  All view events pass itself as the first argument now.  So also new for `add:region` `remove:region`

**Comment by scott-w** [comment]
I'm thinking I'll document this in the tables for each event as a third column. I'll get a PR in for you guys to have a look over and see how it looks.
