### ISSUE TITLE
Behavior.getEvents() incompatible with lodash 4.x

### ISSUE THREAD

**Issue by bazineta** [marionettejs/backbone.marionette#3177]
The _.reduce() call in Behavior.getEvents() needs a _.bind in order to be compatible with lodash 4.x; at the moment, it's using the old-style 'this' final parameter.

**Comment by paulfalgout** [comment]
Good find.  It'd been fixed and is waiting release. https://github.com/marionettejs/backbone.marionette/pull/3159  We'll probably release a 3.1 including this bugfix very shortly.
