### ISSUE TITLE
CollectionView::getEmptyView removed in v3

### ISSUE THREAD

**Issue by ChristophWurst** [marionettejs/backbone.marionette#3193]
### Description

 1. The method was removed, but apparently that was not documented in the upgrade docs.
 2. Add it to the upgade doc to help other devs.
 3. The method can be replaced by `emtpyView`, see https://github.com/nextcloud/mail/pull/81/commits/a2444f9dbf4227cb2c2567823cb9a4dbb8ae9ef1

### Environment

1. Marionette version: v3.0.0
2. Backbone version: v1.3.3
3. Additional build tools, etc:

**Comment by paulfalgout** [comment]
We merged a similar PR about `getChildView` missing from the upgrade guide.  The upgrade guide is incomplete and only covers the major changes.  The complete list is on the upgrade tools github https://github.com/marionettejs/marionette-v3-compat

That said I'm sure someone would merge a PR for this.  Here's the previous related PR https://github.com/marionettejs/backbone.marionette/pull/3191
