### ISSUE TITLE
Compatibility issue with Lodash 4.x 

### ISSUE THREAD

**Issue by gusost** [marionettejs/backbone.marionette#3196]
### Description

Calling `reorder` on a collection view.

### Expected behavior

The dom should reorder according to the new order 

### Actual behavior

Crashes because of use of `_.contains` in reorder
https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L215

`contains` was removed in favour of `includes` in lodash 4

### Environment

1. Marionette version: 3.0
2. Backbone version:1.3.3

**Comment by paulfalgout** [comment]
As luck would have, this line has already change in `v3.1`.  🎉
