### ISSUE TITLE
Add a one-time event between attach and dom:refresh

### ISSUE THREAD

**Issue by bazineta** [marionettejs/backbone.marionette#3197]
### Description

I have a top-level view that acts as a container for a set of subviews. In simplistic terms, there's a chart (Highcharts) and a table view as immediate children. These child views are provided with the container view's collection; each is responsible for displaying the collection in a view-specific manner.

Upon completion of the startup of this view, a 'select' event is triggered on the collection, which causes the chart to select the associated data point, and the table to select the associated row.

Because some of the views in this hierarchy are dependent on being attached, e.g., the chart must be attached before the select can occur, it's important for the top-level container view to know when all of its descendants are attached, as triggering the select event on the collection must occur only after they have all attached. Some of the views dependent on being attached may be quite some way down from the container view; they're not necessarily immediate children of it.

At present, it seems the only way to accomplish this is to do so in the top-level container view's onDomRefresh, as that event will occur after all descendants are attached; the 'attach' event in the container view is too early, as it will occur _before_ the attach of its descendants.

However, in that the dom:refresh event is not one-time as the attach event is, logic there must be wrapped in a once.

I think it would be handy in general for a given view to know that anything below it is, in fact, ready to go, so to speak, and thus having a one-time event issued upon that state would be helpful, e.g.

```
function handleAttach() {
    triggerMethodChildren(this, 'attach', shouldAttach);
    triggerMethodOn(this, 'dom:ready', this);
    triggerDOMRefresh(this);
}
```

The event name here is debatable; I've chosen one that illustrates the intent, i.e., 'The DOM below you is now completely ready in all respects, and any action you take at this point should be safe in terms of your descendants' DOM requirements.'

### Environment

1. Marionette version: 3.1-pre
2. Backbone version: 1.3.3
3. Additional build tools, etc: So, so many....

**Comment by rafde** [comment]
Can you provide a fiddle to demo what you have now?
It'd be easier to give you a response using the current events that trigger, if possible.

**Comment by bazineta** [comment]
So, to clarify, what you're looking for here is a fiddle that demonstrates that (a) the attach event in a view fires before that of any of its subviews and (b) there is no other event between attach and dom:refresh?

**Comment by rafde** [comment]
a)

**Comment by bazineta** [comment]
https://jsfiddle.net/ne1af3b7/1/

If you are simply opposed to this, just say so and close the issue; there's no value in debating something that is simply not worth considering.

**Comment by rafde** [comment]
I'm trying to understand the validity of this issue.
I am not the only one who chime in.

**Comment by blikblum** [comment]
While at the time parent attach event is fired the children attach events did not fire yet, the children DOM nodes are effectively attached. See https://jsfiddle.net/ne1af3b7/2/

I can see the issue if there are some initialization done in children attach events.

@rafde proposition seems clear and straight enough but this issue raises the question of the order of attach events. 

Is the current order of attach event firing, from parent to children, by design?
It should be better to go from children to parent?

I could not find in the docs.
Also the spec does not seems to test the order

**Comment by bazineta** [comment]
The children are effectively attached, yes, but they don't know that yet. A child who is waiting for an attach even in order to do something that is metrics-dependent is, at that point, still in an indeterminate state from its own perspective.

So, to summarize so far:

1. Events happen to fire top-down; events in a parent will always fire before those in a child.
2. However, this is an undocumented implementation detail; a view should make no assumptions about the overall state of the DOM during any event prior to dom:refresh.
3. There is by design no overall dom ready event; a view should use a once dom:refresh handler to determine this state.

**Comment by rafde** [comment]
> Events happen to fire top-down; events in a parent will always fire before those in a child.

With the exception of `dom:refresh`

https://jsfiddle.net/ne1af3b7/3/

It fires a bit jagged, bottom up.

**Comment by paulfalgout** [comment]
I kind of doubt that this use case is super common.  
I think the `once` on `dom:refresh` seems ok.  
I'm less excited about adding another event that gets auto-proxied everywhere all the time even when it isn't being listened to. If we weren't doing all of the event proxying, adding an event wouldn't feel as bad, but in the meantime my preference is to avoid it.
