### ISSUE TITLE
Use Node v6

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3199]
The blocker for moving from Node v4 is https://github.com/marionettejs/travis-ci-setup/issues/5

Now currently in v3 we aren't _really_ using the matrix as we're simply testing what's there.. we aren't yet testing Lodash and there haven't been new releases on _ or Bb to worry about.. so we could just drop it for now.. eventually I'd like to get back to testing all versions of libs that we support..  but since we aren't now, maybe it's best to drop the matrix and go to v6 and figure that out later?

**Comment by paulfalgout** [comment]
Our dependencies will need to be updated.  Things currently break in node 6

**Comment by ahumphreys87** [comment]
fixed via #3234
