### ISSUE TITLE
Allowing smooth transition in region when changing layout

### ISSUE THREAD

**Issue by jniemin** [marionettejs/backbone.marionette#320]
I have a single page app that have multiple pages. The main view consist of header, content and footer regions. My different pages that are inside content region are defined as layouts. To provide smooth transition between different layouts normal region.show() and then override open() is not enough. As in this case the previous layout will be closed before showing the new one. What I created was custom swap() function. Which first prepends layout to background and then I use transition to change old view to new one. This allows smooth transition between views. I can imagine that this is something maybe other could be use. I'll provide my code here, but I know that it is not perfect and for example transition should be defined maybe as a function parameter. Also not sure if this closes current view correctly.

```
var ContentRegion = Backbone.Marionette.Region.extend({
  el: "#content",
  swap : function(view){
    if(this.currentView === undefined){
      this.show(view);
    }else{
      view.render();
      this.$el.prepend(view.el);
      view.trigger("show");
      var that = this;
      this.currentView.$el.fadeOut(400, function(){
        that.currentView.close();
        that.trigger("show");
        that.currentView = view;
     });
   }
}
```

**Comment by marcinkrysiak1979** [comment]
I've written the following marionette plugin that adds 4 kind of transitions. There can be easily added more transition types.

https://github.com/marcinkrysiak1979/marionette.showAnimated

**Comment by jasonLaster** [comment]
Thanks @marcinkrysiak1979
