### ISSUE TITLE
Support childViewEventPrefix: false

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3201]
I believe that the magic auto-proxying events from children to parent views is bad.  It is inconsistent between `View` and `CollectionView` (CVs handle `trigger`, but V only handled `triggerMethod`) https://github.com/marionettejs/backbone.marionette/issues/2464

And we have issues with too much bubbling. https://github.com/marionettejs/backbone.marionette/issues/2667

The auto-proxying is also noisy.  It is throwing many, many events that are most likely never listened to.  And now in v3 we have `childViewEvents` and `childViewTriggers` which very easily allow for explicit ways to bubble events.

Beyond that, if you are naming your events in the same manner as you would elsewhere in Marionette, `childViewEvents` and `childViewTriggers` can be _dangerous_ when mixed with auto-proxying.

```js
const MyView = Mn.CollectionView.extend({
  childViewEventPrefix: 'user',
  childView: MyUserView,
  childViewEvents: {
    'select': 'onUserSelect'
  },
  onUserSelect() {
    console.log('This will get called twice!');
  }
});
```
https://jsfiddle.net/marionettejs/f5ndtmbe/

**Recommended change**
If we support passing `false` to `childViewEventPrefix` this could prevent the auto-proxying. 
In `v3.x` we could also add a feature flag that makes `false` the default instead of `childView`.
Then in v4 we could discuss making the flag false by default.

**Comment by JSteunou** [comment]
:+1:

**Comment by scott-w** [comment]
I agree, when I re-read my code-bases full of `onChildviewSomething` all I see is a total mess of methods proxying other methods and I can't pull it together. I think we should be nudging users to using `childViewEvents` and `childViewTriggers` and potentially start deprecating the magical stuff.

**Comment by blikblum** [comment]
> In v3.x we could also add a feature flag that makes false the default instead of childView.
Then in v4 we could discuss making the flag false by default.

Agree. Just would consider removing auto proxying feature completely in v4
