### ISSUE TITLE
Why CompositeView cannot trigger childView onRender callback?

### ISSUE THREAD

**Issue by KeyHui** [marionettejs/backbone.marionette#3206]
Why CompositeView cannot trigger childView onRender callback?

ChildView must be change to onAttach callback?

**Comment by paulfalgout** [comment]
Please use https://jsfiddle.net/marionettejs/adhv48ky/ to make an example of your issue.

**Comment by paulfalgout** [comment]
Closing for now.  If this is still an issue we can re-open.
