### ISSUE TITLE
CollectionView ui hash

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3208]
So CollectionView… it’s a Backbone.View.. so it has `events` by default.. which is a little odd, but I guess you can add an `events` hash that applied to all children.. you can also then of course do this with `triggers`.. _however_ we don’t ever bind the `ui` hash of a `CollectionView` 

despite never doing it (and we never have) all of the code for that is in there.. you can manually call `bindUIElements`.. but even if we _did_ call it on `render` we definitely don’t do any work to maintain those bindings as we filter or add children or that kind of thing.  And I really doubt we want to.

And so CollectionView also has behaviors.. but again.. no ui bindings..  

I don’t really know if ui elements on a CollectionView are a great idea.. and previously it was decided against: https://github.com/marionettejs/backbone.marionette/issues/584   _however_ if we don’t do ui.. but keep triggers and behaviors we should document the caveat..  but then should we have `triggers` without `ui`?  Doesn’t make much sense except that we can't get rid of `events`...  

This came up again and was nearly implemented here: https://github.com/marionettejs/backbone.marionette/pull/1507

Now I pretty much agree that `ui` doesn't make any sense on a `CollectionView`.. but then I wonder if we should pull it out of the class.  And if `ui`... `triggers` too?  The same logic for the reasons not to support `ui` apply to `triggers`.  But then _behaviors_?  I can still see reasons to support behaviors, but they will only partially work.

I'm mainly opening this issue to ask: 
**How do we document this currently.**
**What can/should we remove or implement?**

If we are removing it, it isn't currently documented in v3 that it should work.. should we consider it breaking?  To some degree it doesn't really hurt much to have it in there. except that it is unsupported, partially broken functionality.

**Comment by JSteunou** [comment]
Looking at my code base, I would only keep behaviors to CollectionView

**Comment by scott-w** [comment]
From my perspective, it could be safe to consider it breaking. Part of the reason I removed chunks of documentation was to give us a chance to remove things after v3 was released. In this case, the feature itself was never documented at all. 

I agree with @JSteunou that Behaviors could be useful in CollectionView (and I'm sure I make use of them somewhere).

**Comment by denar90** [comment]
Talking about behaviors. I haven't faced situation of using it with CollectionView (CV). 
@JSteunou in most cases CV has parent View, is there are any case of using behaviors in scope of it instead of using behaviors in CV?
Another thing, if we are getting rid of ui/triggers/behaviors, do we need CV at all? I'm saying, maybe we can provide some API or smth to manage rendering collection of views in scope of just View class?

**Comment by paulfalgout** [comment]
I personally like breaking up a view by childView and it's parent collectionView. I don't think that ui/triggers/behaviors changes the value of CollectionView to me.

**Comment by scott-w** [comment]
I find the `CollectionView` nicely handles lists of information in a way that `View` doesn't handle as cleanly; at least at a conceptual level.

The reasons that I can think to support `ui` `triggers` and `behaviors`:

* `ui` - reference DOM nodes in each item in the collection.
* `triggers` - act on things happening inside a collection item
* `behaviors` - share collection-related logic

Of the three, I can only see a use for `behaviors`. The other two feel better covered by having the `ui` and `triggers` captured at the individual view and, if you want to handle it in the `CollectionView` just push it up with all the context you need.

From the `behavior` perspective, I can see something like the following being helpful:

```js
const SelectBoxBehavior = Mn.Behavior.extend({
  ui: {
    checkbox: '.select-action'
  },

  events: {
    'click @ui.checkbox': 'selectItem'
  },

  selectItem() {
    this.figureOutIfSelectedAndRender();
    this.triggerMethod('select:item', this.view, this.view.model, this.getNewSelectedStatus);
  }
});

const SelectMultipleBehavior = Mn.Behavior.extend({
  childViewEvents: {
    'select:item': 'updateSelectedList'
  },

  updateSelectedList(view, model, selected) {
    if (selected) {
      this.addToSelectedList(view, model);
    }
    else {
      this.removeFromSelectedList(view, model);
    }
  },

  onBeforeAddChild(view, child, model) {
    if (this.itemIsSelected(child, model)) {
      this.setItemSelectedOnChild(child, model);
    }
    else {
      this.setItemUnselectedOnChild(child, model);
    }
  }
});
```

Granted I've probably made a bunch of errors, the idea is that you may want to manage the selection status as part of the `CollectionView` and its attached `Behavior` as opposed to creating a parent view that manages it. You might have a model backing it that is going to be synchronised with a server somewhere.

**Comment by paulfalgout** [comment]
Ok I think I just ran into a valid use case for `triggers` on a `CollectionView`.

I have a collectionView where each child is a row.. and that row is a collectionView where each child is a column.  On the row collectionView I added a:
```
triggers: {
  'click': 'select'
}
```
And in the parent view I'm listening for a row select event.  So I think `triggers` is perfectly valid for the `$el`.. and I'm not sure how I'd do this differently.  However attempting to do anything sort of selector wouldn't work and it would be hard to determine why.  It's probably down to documenting and figuring out what could be done manually with `bindUIElements` though I still think it would be deficient and using `ui` on children is a bad idea..

**Comment by paulfalgout** [comment]
Ok after messing with the new collectionview and playing with what it would mean to "roll your own compositeview" I think `bindUIElements` is important to keep around.  With the new collectionview it _could_ actually work for children too.. I'm just not sure that's what is wanted.  I think simply documenting that ui elements are not bound automatically on collectionViews is probably the best plan.
