### ISSUE TITLE
Region el is not emptied when showing a second view

### ISSUE THREAD

**Issue by blikblum** [marionettejs/backbone.marionette#3210]
### Description

When a view is show in a region that is holding a previous view instance,  the region element is not emptied. Instead, the old view element is removed and and the new view element is appended.
This can lead to problems when a element is added to the region element after the view is show.
This behavior changed in V3  compared with V2 

In region document (http://marionettejs.com/docs/master/marionette.region.html), the described attachHtml implementation is different from the actual:

Mn.Region.prototype.attachHtml = function(view){
  this.$el.empty().append(view.el);
}

### Expected behavior

The region element should be emptied before showing another view

### Actual behavior

https://jsfiddle.net/98u073m0/31/

### Environment

1. Marionette version: 3.0
2. Backbone version: 1.3
3. Additional build tools, etc: Webpack

**Comment by scott-w** [comment]
Just so I understand, the issue is that custom HTML attached to the region's `$el` (not the view's `$el`) isn't removed.

I've just had a play with the fiddle and the HTML *inside* the view is definitely removed. The question we need to decide on then is whether we want to support this behaviour or whether the documentation is now incorrect and should change.

**Comment by blikblum** [comment]
> Just so I understand, the issue is that custom HTML attached to the region's $el (not the view's $el) isn't removed.

Yes

The issue is due to `empty` method not removing extra added elements:
See https://jsfiddle.net/98u073m0/32/

The actual usage is at https://bitbucket.org/blikblum/sharemonitor/src/e943c2c15c4e827f0b5eeb789c85a5a1123353e2/clients/ionic-mn/scripts/application.js?at=master&fileviewer=file-view-default#application.js-22

After the view is show i need to setup the scroll component that adds a element to hold the scrollbar, but each time a new view is show a new scrollbar element is added

I will play with workarounds and report later

**Comment by paulfalgout** [comment]
Yeah I think if someone is adding DOM manually outside of the marionette view lifecycle, then it's best in those instances to find a way to clean it up manually.  Here's a very specific solution... though you could just add an `$el.empty` inside this particular region's onEmpty.

https://jsfiddle.net/marionettejs/98u073m0/33/

I think it's better to make sure marionette can optimize the main case and have well placed events and hooks for adding and cleaning up anything extraneous.

**Comment by blikblum** [comment]
I fixed in my end by removing the added element

Anyway i think that a update in region docs is in order given that the attachHtml implementation described in it, suggest another behavior.

Also a note in upgrade guide is worth considering that behavior changed compared to V2
