### ISSUE TITLE
this.getUI throws uncaught TypeError

### ISSUE THREAD

**Issue by JustinLivi** [marionettejs/backbone.marionette#3217]
### Description

 I'm using Marionette 3.0.0 and Backbone 1.3.3 
According to the [documentation](http://marionettejs.com/docs/v3.0.0/marionette.view.html#defining-ui), "To define your ui hash, just set an object of key to jQuery selectors to the ui attribute of your View". However, within the view `this.getUI` throws an uncaught TypeError on line 893 of Marionette because `this._ui` is undefined.

### Actual behavior

See [this jsfiddle](https://jsfiddle.net/91ow47sp/2/) for demonstration (click the test button to throw error)

### Solutions

Only by [stepping backwards](http://marionettejs.com/docs/v2.4.7/marionette.view.html#viewbinduielements) in the docs to 2.4.7 was I able to determine that adding `this.bindUIElements();` to my initialize method could (and indeed does) fix the issue.

[jsfiddle](https://jsfiddle.net/91ow47sp/3/)

I'm not sure if requiring the `bindUIElements` invocation is the intended behavior, or if this is a bug. The docs are otherwise super detailed and helpful so if it's the intended behavior then the docs for 3.0 should probably be updated to reflect this.

**Comment by paulfalgout** [comment]
`render` calls `bindUIElements` among other things.  

https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.view.md#rendering-a-template

> If you want to add extra behavior to your view's render, you would be best off doing your logic in the `onBeforeRender` or `onRender` handlers.
