### ISSUE TITLE
Support yarn

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3229]
https://code.facebook.com/posts/1840075619545360

Probably should support the new shiny if its easy..

**Comment by denar90** [comment]
Here my results of last Marionette.js v3.1. 
`npm -v` - 2.15.9
`yarn version` - v0.15.1

### Clean cache
```
npm cache clean
time npm i
```
vs
```
yarn cache clean
time yarn
```

|      |    Npm    |    Yarn   |
|------|:---------:|:---------:|
| real |  5m2.069s | 1m40.364s |
| user | 3m18.796s | 1m24.774s |
| sys  | 1m23.261s | 0m47.342s |


### With cache

`time npm i` vs `time yarn`

|      |    Npm    |    Yarn   |
|------|:---------:|:---------:|
| real | 2m54.259s | 1m13.979s |
| user | 2m43.205s |  1m2.717s |
| sys  |  1m0.757s | 0m39.589s |

Pretty good results as for me.

**Comment by rafde** [comment]
I am not sure what there is to support. Yarn is a CLI client that works with NPM registry and bower. It doesn't look like MarionetteJS needs to register with yarn's registry.

**Comment by paulfalgout** [comment]
Yeah I think this is safe to close.  Put it up moments after the post, when everyone was having nervous shakes and giggle like school children.

**Comment by JSteunou** [comment]
I'm very surprised by your results with npm clean install. I understand better now all the fuzz with Yarn.

At work I get pretty much the same results between Yarn & npm but that's because we have a local private repository with cache on our network.

**Comment by blikblum** [comment]
We should consider storing yarn.lock into SCM: https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all

**Comment by paulfalgout** [comment]
Agreed

**Comment by paulfalgout** [comment]
Also travis caching: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Caching-with-yarn
