### ISSUE TITLE
Update homepage for package.json and bower.json

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#3239]
### Description

Just noticed that we have inconsistency in our package.json and bower.json regarding `homepage` property.

https://github.com/marionettejs/backbone.marionette/blob/master/bower.json#L4
https://github.com/marionettejs/backbone.marionette/blob/master/package.json#L5

We should set it with on either `https://github.com/marionettejs/backbone.marionette` or `http://marionettejs.com/` value.

**Comment by scott-w** [comment]
I vote `http://marionettejs.com`
