### ISSUE TITLE
Don't return this for functions meant to be overridden

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3242]
Example `View#attachElContent`

This function is for overriding if you want to attach html differently.  It is not meant for calling directly.  As such it has a `return this` in it which is misleading and confusing and isn't used internally.  When overriding the user should not be worried about chaining.. particularly when you shouldn't use this function this way to begin with.

https://github.com/marionettejs/backbone.marionette/blob/v3.1.0/src/view.js#L184

**Comment by rafde** [comment]
Sounds good since what's considered public which returns is unsafe to rely on when used internally.

**Comment by siliconjohn** [comment]
Are there other functions besides the above example that are meant to be overridden? I can change all of them but the example is the only one I have found.

**Comment by paulfalgout** [comment]
I have not really looked. It is possible it is the only example.
