### ISSUE TITLE
Document noConflict method

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#3249]
We should add some info about `noConflict` method. Knowing that it's possible to use use 2 different versions of Mn might help people who doesn't want to migrate their old apps.

**Comment by aeksco** [comment]
I'd be happy to write the documentation. Should this be an addition to ```docs/marionette.functions.md```?

We may also want to make a note about ```noConflict``` in ```docs/upgrade.md```.

**Comment by paulfalgout** [comment]
Yeah I'd be ok with it in `functions.md`.. makes sense..  This method was added for 2.0 I think though.. so not sure upgrade needs to be a part of this?  Guess it could be, but it's significantly old.. so I dunno if people will read back that far.  Related to this is `Marionette.VERSION` which I don't believe is documented either.

**Comment by aeksco** [comment]
Good good - I'll make the addition to ```marionette.functions.md```.

A reference in ```upgrade.md``` could be a helpful tip for those upgrading transitionally, *i.e.* running two v2 and v3 in one application. Something like:

```markdown
Where possible, we will document how to make the changes in Marionette 2.x so
that your applications can continue to work and to ease the burden of upgrading
to Marionette 3.

You can run Marionette 3 alongside Marionette 2 with Marionette.noConflict().
```

Perhaps it would make the most sense to consolidate ```docs/marionette.features.md``` into a new file, ```docs/configuration.md``` - to document ```Marionette.FEATURES```, ```Marionette.VERSION```, and ```Marionette.DEV_MODE``` - which is also missing documentation if I'm not mistaken.

Thoughts?

**Comment by paulfalgout** [comment]
cool with the `upgrade.md` note.

a `configuration.md` is certainly interesting.  @scott-w ?  In addition to those three, the other things that are "configuration" are the feature flags, behaviors lookup (though deprecated), and the renderer. Those things are documented in their own places, but could be mentioned and linked to from here.

**Comment by denar90** [comment]
@aeksco are you still interested in making PR for this?

**Comment by aeksco** [comment]
@denar90 I am! I was waiting to hear some more information from @scott-w. I've got some time today - I can get a PR in for review shortly and we can continue the discussion there.

**Comment by scott-w** [comment]
Sorry, I completely missed @paulfalgout comment! I can get behind a central configuration document if you want to get something in @aeksco

**Comment by aeksco** [comment]
PR just opened for this. Apologies for the delay - the semester has kept my time more tied up that I'd like. 

I ended up keeping the separate document for ```Marionette.FEATURES``` since there were additions to that documentation since our discussion here. I'm open to bringing ```FEATURES``` into the new ```marionette.configuration.md``` document, but we can address that in a separate PR if needed.
