### ISSUE TITLE
Add lang linter for docs

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#3265]
Sometimes errors in spelling might appear, it will be nice to get to know about them without disturbing code reviewer, other then that reviewers are people too.
I propose to use either https://github.com/btford/write-good or another tool as additional checking.

**Comment by nlhuykhang** [comment]
I made a Gulp plugin for write-good [here](https://github.com/nlhuykhang/gulp-write-good).

Have a look at the plugin. If the plugin is good, I can make a PR to use it in the docs linting process.
