### ISSUE TITLE
New line before child element (CollectionView Rendering)

### ISSUE THREAD

**Issue by letoss** [marionettejs/backbone.marionette#3270]
### Description

Hello Marionette team.

I was wondering if there is a way to manipulate a little bit the way CollectionViews insert their child view.
I noticed that the Collection View insert its children one after other.
```
<div class="attachments-container"><div class="attach-grid">hello</div><div class="attach-grid">hello</div><div class="attach-grid">hello</div><div class="attach-grid">hello</div><div class="attach-grid">hello</div></div>
```
I dealing with css because if this. I'm trying to justify my content but the way that I found to do this is not working because of the template.

Is there a way to insert a break line before each child?

### Expected behavior

I think this should be done by default (inserting new break line). Because this is how the template should looks like.
```
<div class="attachments-container">
  <div class="attach-grid">hello</div>
  <div class="attach-grid">hello</div>
  <div class="attach-grid">hello</div>
  <div class="attach-grid">hello</div>
  <div class="attach-grid">hello</div>
</div>
```

### Environment

1. Marionette version: 3.0.0
2. Backbone version: 1.3.3

**Comment by scott-w** [comment]
Hi @letoss, do you have a visual example of the output you want vs the output you're getting? Perhaps a screenshot, or even just showing us the CSS you're using so we're able to get an idea of the bigger picture would be really helpful.

Best regards,
Scott

**Comment by letoss** [comment]
@scott-w Sure!

This is the auto-generated HTML by Marionette Collection View. Check that the red circle is showing it. Also, check that there are no new lines after each <div>
![bad_html_console](https://cloud.githubusercontent.com/assets/4682820/20626273/67f9391e-b2f7-11e6-8e81-2c46952de611.png)

This is how the template looks:
![bad_html_view](https://cloud.githubusercontent.com/assets/4682820/20626283/75b6ee98-b2f7-11e6-869b-475dbf71d4ed.png)

Now, after modifying by hand the HTML, this is (for me) how it's supposed to be formatted:
![well_html_console](https://cloud.githubusercontent.com/assets/4682820/20626301/92c0bcd0-b2f7-11e6-99cc-51476ed50cc7.png)
This is the view:
![well_html_view](https://cloud.githubusercontent.com/assets/4682820/20626304/9a75ee64-b2f7-11e6-8aac-63eeef2c1144.png)

Does it make sense? The problem is that Marionette is inserting the <div> from the Item view without inserting new break lines or even a space.

Is there a way to make it work now? Because I need to do it.

**Comment by scott-w** [comment]
Hi @letoss, thanks for that, it's a bit help. Normally I'd recommend using CSS to split the elements visually.

However, it's possible you could use https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L691 to forcibly add a `' '` after each `</div>`.

Hope that helps,
Scott

**Comment by letoss** [comment]
@scott-w This totally works. I did this:
```
collectionView.$el.append(' ');
collectionView.$el.append(childView.$el);
```
I'm afraid of this implementation because of this comment in the source code 
```
// buffering happens on reset events and initial renders
// in order to reduce the number of inserts into the
// document, which are expensive.
```
I think in this case I can live with it because this Collection View in particular shouldn't be to big. But I don't know.

Thanks for your help.

**Comment by paulfalgout** [comment]
The current CollectionView has multiple ways of appending unfortunately, but that'll be changing soon enough with a newer implementation.

Regardless, I'd highly recommend a solution that does not require white-space in your HTML.  It is unusual to _want_ the whitespace.

**Comment by letoss** [comment]
@paulfalgout I totally agree with you. The problem is that I need to justify my Item views. Check this SO post for more references http://stackoverflow.com/a/27679362

**Comment by paulfalgout** [comment]
@letoss do models get added to your collection after the collectionView is rendered?  this is when you'll run into issues with the current CollectionView

**Comment by paulfalgout** [comment]
I think this is mostly resolved?  We can reopen it if not.

FWIW once https://github.com/marionettejs/backbone.marionette/pull/3244 is in, assuming it all goes well, adding this functionality will be easier and more consistent.
