### ISSUE TITLE
Default templateContext

### ISSUE THREAD

**Issue by jonas-db** [marionettejs/backbone.marionette#3271]
Is there a way to set some default templateContext that is used for all views, instead of manually adding?

If not, this seems to be an interesting feature.

**Comment by scott-w** [comment]
While not explicitly related to providing a default `templateContext`, you could use [the `Mn.Renderer`](https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.renderer.md#custom-template-selection-and-rendering) and set defaults in the `data` argument if they're not already provided.

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/issues/2164 I think this is what you're after.  I'd like to see it as well.

**Comment by paulfalgout** [comment]
Going to close this in favor of #2164
