### ISSUE TITLE
_onCollectionUpdate needs to check if changes is undefined before using it

### ISSUE THREAD

**Issue by OS-Chris** [marionettejs/backbone.marionette#3275]
Before using 'changes' in the _onCollectionUpdate function, you need to make sure it's not undefined. A simple 'if (changes) { ... }' statement wrapped around it's use fixes the issue. 

1. Marionette version: 3.1.0
2. Backbone version: 1.2.3

**Comment by paulfalgout** [comment]
Marionette doesn't technically support Bb 1.2.3 which is the issue here.  In 1.3.x there is _always_ a changes.  Moving forward the changes will be a large performance boost and a newer versions of collectionview will depend on it's usage.  I don't think we can reasonably support under `1.3.3`.
