### ISSUE TITLE
Clarify templateContext

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3276]
Oversaw a discussion on the Gitter channel where the documentation of `templateContext` and how it works with functions wasn't as clear as it could be. It was assumed the following wouldn't work:

```js
templateContext: function() {
  return {
    foo: this.foo
  };
}
```

When in fact it would because the binding to the serialised data happens after this function is called.

**Comment by JSteunou** [comment]
I think it also could depend on the template engine you are using.

**Comment by scott-w** [comment]
True, I think in this instance it's best to make sure the documentation covers the standard template engine first. Do we know of any popular alternative engines?
