### ISSUE TITLE
CollectionView._getRemovedViews and modelless child view

### ISSUE THREAD

**Issue by ardi-n** [marionettejs/backbone.marionette#3278]
When collection reset() is called the view rendering it is updated. But _getRemovedViews finds removed views by removed models. When an arbitrary child view without a model is added to the view that method throws an error.

Here's a proof: https://jsfiddle.net/d5shn4nu/

**Comment by paulfalgout** [comment]
This is fixed in the next CollectionView https://github.com/marionettejs/backbone.marionette/pull/3244 but this probably needs to get fixed in the current one.
