### ISSUE TITLE
Build tests are failing

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3279]
> Hi, the latest "next" branch appears to not be building. It's throwing a bunch of mocha errors with the Behavior mixin. Is it just me?

I believe this is not a code issue, but related to the spec refactoring.. now that the specs are importing only the units they're testing.. testing the full build may not be feasible.  Thoughts?

cc: @denar90

**Comment by denar90** [comment]
@paulfalgout agree we are not able to test all build right now... If we have some broken functionality after build (some config/rollup/babel etc problems) how will we detect them? So I have doubts, should we get back to previous approach? Thoughts?

**Comment by paulfalgout** [comment]
I think while running all of the unit tests on the build was convienent, most of the tests weren't useful..  the issue with a broken build is an integration one.. all the unit tests would still pass.  I think we should can the build test for now and either rely on the upcoming performance tests as a safety net or maybe add some cypress testing or something and possibly move all testing that isn't strictly unit testing to a different system that uses the build?  I dunno.  Breaking up the tests is correct, and I don't want to hamper that because we have a cheap solution to test the build.

**Comment by denar90** [comment]
@paulfalgout I think do it every release will be annoying. I'll look at it, maybe we can do smth smart 💡

**Comment by paulfalgout** [comment]
Yep, but the build tests are a recent addition so not a huge loss.

**Comment by denar90** [comment]
@paulfalgout would you like rather concentrate on tests refactoring then on fixing this issue?

**Comment by paulfalgout** [comment]
I think so.. I mean we can't build at all without doing something, but I think unless there is an easy solution, we should just disable it for now..  I don't think it should get in the way of better unit tests.
