### ISSUE TITLE
Expanding Behavior Reusability

### ISSUE THREAD

**Issue by chungmeow** [marionettejs/backbone.marionette#3280]
This isn't really an issue but rather a feature suggestion.. in addition this is my first time creating a story and I'm not entirely sure if this is the right audience nor am I confident I am addressing my concerns in an appropriate manner.

Case 1:
In order to reuse a behavior, we're forced to create a config hash that will be used to reference an options dynamically. ie. The behavior RowsAddDeletable.js adds and deletes rows based on add and delete button events. An id attribute is found in the section where the button event had occurred and would be used as a key to access the options associated with that section: ```this.view.behaviorConfigOptions[$(e.currentTarget).data('row_id')].addTemplate```
In this example, we are trying to determine which handlebars.partials.template will be used to add a row for a specific section.

Case 2:
I wish to create a base behavior that would be reused in order to build complex versions of that base behavior within the same view. Generally a nested approach would seem reasonable by creating two complex ('child') behaviors and implementing the base behavior by defining the base behavior in each of the complex behaviors. Issues may be occurring since the base behavior is assigned twice, once for each child behavior. 

```js
var TableSortable= Mn.Behavior.extend({
    onSort: function (th$) {
        ..
    }
})

var child1 = Mn.Behavior.extend({
    ui: {
        sortFormerData: '#formerData th.sort'
    },
    events: {
        'click @ui.sortFormerData': 'sortFormer'
    },
    behaviors: function () {
        return {
            TableSortable: {
                behaviorClass: TableSortable,
                viewTemplate: viewFormerData,
                editTemplate: editFormerData
            }
        }
    },
    sortFormer: function (e) {
        e.preventDefault();
        var th$ = $(e.currentTarget);
        this.view.triggerMethod('sort', th$);
    }
})

var child2 = Mn.Behavior.extend({
    ui: {
        sortCurrentData: '#data th.sort'
    },
    events: {
        'click @ui.sortCurrentData': 'sortCurrent'
    },
    behaviors: function () {
        return {
            TableSortable: {
                behaviorClass: TableSortable,
                viewTemplate: viewCurrentData,
                editTemplate: editCurrentData
            }
        }
    },
    sortCurrent: function (e) {
        e.preventDefault();
        var th$ = $(e.currentTarget);
        this.view.triggerMethod('sort', th$);
    }
})
```

I just thought it would be great to be able to reuse behaviors in such a way or even if we can define two TableSortables within a view's behaviors hash with different options.

**Comment by rafde** [comment]
This reads to me as something that a CollectionView should handle. You can add and remove and sort and filter.

**Comment by scott-w** [comment]
I've just updated your post to include the `js` for formatting your code.

**Comment by scott-w** [comment]
OK so reading your code, I think what you're wanting to do is:

1. Take a "base" behaviour (specific sorting action in this case)
2. Add that behaviour to another behaviour or view multiple times
3. For each instance of that behaviour, provide different arguments to get custom behaviour

Am I right in assuming you want to replace your code above with the following:

```js
var TableSortable= Mn.Behavior.extend({
    onSort: function (th$) {
        ..
    }
});

var View = Mn.CollectionView.extend({
    behaviors: {
        FormerSort: {
            behaviorClass: TableSortable,
            viewTemplate: viewFormerData,
            editTemplate: editFormerData
        },
        CurrentSort: {
            behaviorClass: TableSortable,
            viewTemplate: viewCurrentData,
            editTemplate: editCurrentData
        }
    }
});
```

Is this accurate?

**Comment by paulfalgout** [comment]
@scott-w 's example is the best one.  I think you'd just add `sortSelector` to the options passed to the behavior for the `ui`.  There is a lot of duplication between the two behaviors.  One can to do the job of all 3 by passing it a selector.

**Comment by chungmeow** [comment]
@rafde - I agree however, in this particular case we're dealing with a list of values in a single model

@scott-w - That's correct! Since I'm using v2.2.0 (next sprint we'll be upgrading to 3.1.0), I'm not entirely sure defining the same behavior twice within the hash is currently available to me. Another use case would be in case 1 with ```RowsAddDeletable``` behavior where a user can, from a single model, add/remove rows or rather, a set model attributes. The caveat is there are groups of these attributes requiring different templates hence, the necessity of declaring the same behavior multiple times within the view's behaviors hash while using a unique key.

@paulfalgout - thanks for your help thus far! Are we saying that @scott-w 's solution, with the ```sortSelector```, can be implemented? i've seen this solution before however, since i've been using v2.2.0 for the past year, i feel like all i've been doing was working around these features and building custom ones..

**Comment by chungmeow** [comment]
Here's another case:

I have a ShelfAddRemovable behavior that adds a table row to display additional details and is also removed by a toggle button. I also have a complex/nested behavior that incorporates ShelfAddRemovable, adds a table row for searching values and then is removed when a result is found. Templates are defined and passed through the options hash.

Since ShelfAddRemovable is essentially declared twice on the view, conflicts occur where the behavior ShelfAddRemovable declared on the view take precedence over the ShelfAddRemovable declared on the nested behavior. In other words, when triggerMethod is used within the nested behavior to add a row, the template defined on the view's behavior options hash will be referenced rather than the template defined within the nested behavior.

**Comment by scott-w** [comment]
Hi @chungmeow, I've read the above comment a few times and I'm struggling to picture it. Would it be possible to post some code or even a couple of screenshots/wireframes showing what you're trying to achieve?

**Comment by chungmeow** [comment]
@scott-w sure!

```
var ShelfAddRemovable = Mn.Behavior.extend({
    onAddShelf: function (row$) {
        var shelfRow$ = $(Mn.Renderer.render(ShelfTemplate, {}));
		shelfRow$.append($(Mn.Renderer.render(this.getOption('subTemplate'), {})));
		row$.after(shelfRow$);
    },
    onRemoveShelf: function(row$) {
		..
	}
});

var EntitySearchable = Mn.Behavior.extend({
	behaviors: function () {
		return {
			ShelfAddRemovable: {
				behaviorClass: ShelfAddRemovable,
				addShelf: this.getOption('addElement'),
				deleteShelf: this.getOption('submitElement'),
				subTemplate: SearchTemplate
			}
		}
	},
	onRenderEntitySearch: function (row$) {
		..
	}
});

var ContentView = Mn.ItemView.extend({
    behaviors: {
        ShelfAddRemovable: {
            behaviorClass: ShelfAddRemovable,
			addShelf: '#edit',
			deleteShelf: '#save',
            subTemplate: EditTemplate,
			
        },
        EntitySearchable: {
            behaviorClass: EntitySearchable,
            addElement: '#open',
			submitElement: 'button.go'
        }
    }
});
```

**Comment by paulfalgout** [comment]
I think using behaviors to modify the dom, other than possibly handling state classes is not ideal. It will introduce so many possible edge cases where the views can no longer be aware of its own state.

**Comment by chungmeow** [comment]
I apologize for the late response..

Its unclear how a view can lose track of its own state if the behavior only manipulates the template the view is associated with. Wouldn't the state of the view associated with a region essentially be governed by the layout?

I'm afraid what you're telling me is that behaviors are limited and are not capable of extracting reusable complexities out of our views.

**Comment by paulfalgout** [comment]
The behavior in the example appended html inside the view that the view is unaware of.  There are few instances in which it is a good idea to add additional html with jquery outside of a view's own render (or through a view's region).

I'd say behaviors are best when you want to add functionality, that if merged with a view, would have to have the view's `ui`, `events`, `triggers`, `modelEvents`, `collectionEvents`, or handlers merged with the mixin.  In that way they are very good at extracting reusable complexities.  Otherwise you can just `_.extend` methods onto the view's prototype.

Having multiple complex abstractions that mutate shared state or DOM is less than ideal.  Singular data flows and single responsibility are better. Behaviors are useful, particularly when they have simple I/O and no side-effects.
