### ISSUE TITLE
Test the build

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3282]
Related: https://github.com/marionettejs/backbone.marionette/issues/3279

Improvements to the test files made testing the build less than trivial.  So at the moment it is untested. 😿

**Comment by denar90** [comment]
@paulfalgout what do you think about this idea? If we will have some layer where classes/modules will be exported like:

`layer.js` (have to think about better name)
```js
import Error from '../../src/error';
import Behavior from '../../src/behavior';
...

exports {
  Error: Marionette.Error | Error
  Behavior: Marionette.Behavior | Behavior
  ...
}
```

They we will imported in `behaviors.spec.js`

```js
import {Error} from 'layer';
import {Behavior} from 'layer';
...
```

But using this way we will have problems with Mixins and other stuff, they are not in `Marionette`. But if we can't import them, aren't they kinda private stuff. Shouldn't we test only public stuff which is part of `Marionette`?

**Comment by paulfalgout** [comment]
I do think that's the root of the issue..  when unit testing we want to test each module as it's own unit.. and we only want to test the public API of the _module_ regardless if that API is public API for Marionette itself.  When testing the library as a whole, we don't care about the unit tests.  We want to know if the units integrated together work. Right now we're writing more unit tests that are less integration tests..  regardless the only reason we ran the whole test suite before was because it was convenient and easy.  I am wondering if we should consider not doing _any_ integration tests in mocha and instead pulling them out into something like cypress.io.  Then we could run cypress against the build.  If we're testing if 2 modules work together, we should be able to test all of them together.  Plus Cypress would make for some interesting example code.  But we're a long way off.  All that said, I don't personally want to figure out a way to get the unit tests to work on the build the way were doing.

**Comment by denar90** [comment]
Sa far as I know cypress.io is not available for everyone. We can get only early access (after using it I can say that it's awesome), but it will not work with CI now. Hence we have to wait...

**Comment by paulfalgout** [comment]
I think it will work with ci now.  At least people are talking about the headless version now..  In any case, Brian is a previous core member, so we can probably get it setup.  We'd have to try it, but I _think_ the headless node version will run the tests for anyone without beta access and can just be setup as a devDependency.  I think right now it is just the gui that is closed to the beta users.. We can probably make a quick test and PR something to see if travis'd run it, but I _think_ it will now.

**Comment by denar90** [comment]
Cool if we can do this!

Another think that we have to refactor current tests and build integration one simultaneously, not to lose some age cases which are already covered.

**Comment by paulfalgout** [comment]
Check out #3287.  Seems to work.. without the GUI it will still make screenshots and record an entire video of it going through the tests in the GUI by running `npm run-script cypress`   So that's kinda cool.. you don't _have_ to have Cypress gui to add tests (though way, way easier if you do have it).
