### ISSUE TITLE
getRegion should render an unrendered view

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3294]
You can certainly call render, but I don't know the value of `getRegion` erroring if the view hasn't been rendered.  I don't _think_ I would consider this breaking.

```js
const myApp = Mn.Application({
  region: '#app-hook',
  onStart() {
    const rootLayout = new MyLayout();

    rootLayout.isRendered(); // false
    rootLayout.showChildView('header', new MyHeader());
    rootLayout.isRendered(); // true
    rootLayout.showChildView('side-bar', new MySide());
    rootLayout.showChildView('main', new MyPreloader());

    // by pre-rendering and showing children this is a single html attach
    this.showView(rootLayout);  
  }
});

myApp.start();
```

https://jsfiddle.net/adhv48ky/4/

**Comment by scott-w** [comment]
I like this - it should make Marionette easier for newcomers as well. A common error I see with people new to Mn (and one I made myself) is showing views in a region whose parent hasn't been rendered yet.
