### ISSUE TITLE
Collection _updateIndices - decrementing

### ISSUE THREAD

**Issue by mmszymczak** [marionettejs/backbone.marionette#3298]
### Description

The problem occurs after the update to 3. Namely, when I want to extend the collection with additional elements it okey, but when I want to roll back the additional elements the indexes are badly decremented.
Removing items from the collection updates indices, current indexes collection of elements should be reduced by the length of additional elements, not one.

### Expected behavior

```js
_updateIndices: function _updateIndices(views, increment) {
  if (!this.sort) {
    return;
  }

  var view = _.isArray(views) ? this._findGreatestIndexedView(views) : views;

  // update the indexes of views after this one
  this.children.each(function (laterView) {
    if (laterView._index >= view._index) {
      laterView._index += increment ? 1 : -views.length;  // here
    }
  });
},
```

### Actual behavior

```js
_updateIndices: function _updateIndices(views, increment) {
  if (!this.sort) {
    return;
  }

  var view = _.isArray(views) ? this._findGreatestIndexedView(views) : views;

  // update the indexes of views after this one
  this.children.each(function (laterView) {
    if (laterView._index >= view._index) {
      laterView._index += increment ? 1 : -1;  // here
    }
  });
},
```

### Environment

1. Marionette version: 3.1.0
2. Backbone version: 1.3.3

_Edited to improve code format for better visibility: @paulfalgout_

**Comment by paulfalgout** [comment]
@rafde this might be something we could fix on the current.  https://github.com/marionettejs/backbone.marionette/pull/3244 should ultimately cover this case.

**Comment by rafde** [comment]
@mmszymczak please provide a jsfiddle that we can use a reference. It will help when creating the test to fix this issue.
@paulfalgout I'll apply a fix some time soon.

**Comment by rafde** [comment]
I guess no need for a demo since the test fail when I made the change. gonna have to look into the issue later.

**Comment by iksemot** [comment]
Hi guys,

Please see following example for the described behaviour: https://jsbin.com/lometiwipi/edit?html,js,output

**Initial state:**
There are two simple collections: "123" and "ABC".
"123" is displayed

**Steps to reproduce**
Click "Add" to add "ABC" between elements "2" and "3";
Click "Remove" to remove "ABC",
Click "Add" again

**Expected behaviour**
"ABC" should be added between elements "2" and "3"

**Actual behaviour**
"ABC" is added at the end of the list

**Comment by rafde** [comment]
Thanks iksemot. I manage to replicate it via testing. Looking into solving it.
