### ISSUE TITLE
onBeforeAddChild, first argument redundant or not?

### ISSUE THREAD

**Issue by doodlemeat** [marionettejs/backbone.marionette#3299]
Hi, not really an issue but a question.

CollectionView has a **onBeforeAddChild** method that is triggered whenever an item is added to the collection. But from what I can see in the source code, the arguments on **onBeforeAddChild** is its own collectionView and then the child.

The collectionView argument should not be necessary since it can be reached with _this_ 
I noticed it when upgrading from v2.4.7 to the latest.

**Comment by scott-w** [comment]
Hi @doodlemeat, this is an update to the way events are handled in Marionette to always pass the `view` into the first argument. This lets you, for example, do:

```js
const MyView = View.extend({
  childViewEvents: {
    'before:add:child': 'doSomething'
  },

  doSomething(collectionView, child) {
  }
});
```

This was so handling `childViewEvents` has a lot less magic than it used to (where listening to child events would add extra arguments).

**Comment by paulfalgout** [comment]
Yep.  In v3, literally anytime `this.triggerMethod` is called internally it passes itself as the 1st argument.  It isn't needed like 10% of the time, but consistency won.
