### ISSUE TITLE
backbone.marionette.js:19Uncaught TypeError

### ISSUE THREAD

**Issue by cnobile2012** [marionettejs/backbone.marionette#3300]
I get this exception when loading the library before it is even used for anything.

backbone.marionette.js:19Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at backbone.marionette.js:19
    at backbone.marionette.js:14
    at backbone.marionette.js:15

This happens with ```jquery-3.1.1``` and ```Backbone.js 1.3.3```.

**Comment by scott-w** [comment]
Are you loading Marionette with a `script` tag? If so, you'll need to include either `underscore` or `lodash` above `backbone`.

**Comment by cnobile2012** [comment]
This what I'm loading and the order.

    <script src="{% static 'vender/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'vender/js.cookie-2.0.4.min.js' %}"></script>
    <script src="{% static 'vender/lodash.min.js' %}"></script>
    <script src="{% static 'vender/backbone-min.js' %}"></script>
    <script src="{% static 'vender/backbone.mutators.min.js' %}"></script>
    <script src="{% static 'vender/backbone.marionette.min.js' %}"></script>

**Comment by scott-w** [comment]
Aha, I see. You also need `backbone.radio.min.js` in your `vender` directory.

**Comment by paulfalgout** [comment]
Yeah.. unfortunately this is rollups module loader erroring.  I'd love to introduce a better way to handle this.. in fact radio isn't a necessary dependency unless you use it explicitly.. but I haven't found a way to work around this in rollup.  In any case, what @scott-w suggested should definitely fix this.

**Comment by cnobile2012** [comment]
Your fix works if you load like this:

    <script src="{% static 'vendor/backbone.radio.js' %}"></script>
    <script src="{% static 'vendor/backbone.marionette.min.js' %}"></script>

What happened to the ```min``` version of ```backbone.radio.js``` it's not in the tarball you have for download. The ```map``` file is there but no ```min``` file.

**Comment by scott-w** [comment]
@paulfalgout should we open a separate issue for that?

In the meantime @cnobile2012, you should be able to get the .min file at https://github.com/marionettejs/backbone.radio/tree/master/build

**Comment by paulfalgout** [comment]
Yep on the radio repo
