### ISSUE TITLE
filter doesn't provide right index

### ISSUE THREAD

**Issue by hhwangcocora** [marionettejs/backbone.marionette#3303]
### Description

"setFilter" doesn't provide right "index" value to the collection.
line 8 will get the index of the child to the **filtered models**, instead of the original collection, or the sorted collection.
Thus, when line 11, "this._shouldAddChild" uses that index to call into my filter function, the index is not right.

```

1.   // Handle a child added to the collection
2.   _onCollectionAdd(child, collection, opts) {
3.     // `index` is present when adding with `at` since BB 1.2; indexOf fallback for < 1.2
4.     let index = opts.at !== undefined && (opts.index || collection.indexOf(child));
5. 
6.     // When filtered or when there is no initial index, calculate index.
7.     if (this.filter || index === false) {
8.       index = _.indexOf(this._filteredSortedModels(index), child);
9.     }
10. 
11.     if (this._shouldAddChild(child, index)) {
12.       this._destroyEmptyView();
13.       this._addChild(child, index)
14.     }
15.   },

```

Proposed solution:
Change line 11 to be ` if (this._shouldAddChild(child, _.indexOf(this.collection.models, child))) {`

This solution will make sure the "index" parameter of the "setFilter" function is always index to the original collection. Since line 13 expects the "index" to be index to sorted filtered models, I'm not gonna change line 8.

### Expected behavior

A consistent "index" value for the "setFilter" function

### Environment

1. Marionette version: v3.0.0, should still be there in latest version (v3.1.0)
2. Backbone version: doesn't matter
3. Additional build tools, etc: doesn't matter

**Comment by rafde** [comment]
using collection's model doesn't match the index of the collection view, which is what the index refers to.
If you want the index of the model from the collection, why not call `this.collection.indexOf(this.model)` where you need it instead?

**Comment by hhwangcocora** [comment]
The function declaration says "setFilter(function(child, index, collection)", where I think it's fairly straightforward that "index" is the index to the "collection". 
If it's not, then I'd expect extra documentation.

What's the real problem here is, filter function is called multiple times after set filter call, and during that many times of executions, sometimes the index indexing filtered collection, and sometimes  original collection. 

Since the "index" parameter is part of the pulic interface, it should at least has a consistent meaning across all executions. And whichever meaning it's chosen, it deserves a good document.

**Comment by rafde** [comment]
> The function declaration says "setFilter(function(child, index, collection)", where I think it's fairly straightforward that "index" is the index to the "collection".
If it's not, then I'd expect extra documentation.

Indeed, that's a fair point. The docs should be updated to reflect the actual value that `index` is suppose to represent.
Thanks for pointing that out. Any change of submitting a PR for this change?

**Comment by hhwangcocora** [comment]
I'll post a PR soon. I'm going to fix the problem such that "index" is the index to the collection (without filter or sorting).

**Comment by paulfalgout** [comment]
CollectionViews do not necessarily sort with a collection so it is not guaranteed that the indexes will be in sync or even have the same lengths (ie: `addChildView`).  The index should be the index of the CollectionView's `children` and not the Collection.  In fact a collectionview does not even need a collection to function and I don't think it should need one to filter its children.

**Comment by hhwangcocora** [comment]
>  The index should be the index of the CollectionView's children and not the Collection

The document from http://marionettejs.com/docs/master/marionette.collectionviewadvanced.html#collectionviews-filter  says otherwise: 

> CollectionView allows for a custom filter option if you want to prevent some of the
> underlying collection's models from being rendered as child views.

So I still believe that the filter works on the collection instead of CollectionViews children views.
Also according to the above link, the "child" parameter in **function (child, index, collection)** interface is a child model of the collection, there is no reason that the "index" is the index of the CollectionView children views

**Comment by paulfalgout** [comment]
The index of the model in the collection is irrelevant to the index of the models for the filter or the collectionview.  Yes they _can_ be in sync, but they certainly don't have to be:

https://jsfiddle.net/f9psnckw/

If the model's index in the collection is useful for a particular use-case `this.collection.indexOf(child);` is the way to get it.

I agree that the current collectionview does a bad job of representing the children here, it is mostly creating an abstract array to work with, but it is _not_ equivalent to the collection.

In an upcoming version of Mn's CollectionView this should be much improved: https://github.com/paulfalgout/backbone.marionette/blob/9742cb55833c9bf995a58603997a068fd2bd23a5/src/next-collection-view.js#L432

**Comment by paulfalgout** [comment]
We can always add a doc, but I'm considering this resolved in https://github.com/marionettejs/backbone.marionette/pull/3244
