### ISSUE TITLE
Docs search

### ISSUE THREAD

**Issue by nadalfederer** [marionettejs/backbone.marionette#3304]
### Description

 1. After each search on the main page http://marionettejs.com/ I can only search again by navigating and clicking on marionette logo and go again on the main page, click again on the search button and only after that search again. It is actually pretty boring after several days. 
 2. A summary of the proposed solution: put header tag on each page.

Maybe it is not an appropriate issue, but think it will improve UI

**Comment by paulfalgout** [comment]
This issue is probably better opened on https://github.com/marionettejs/marionettejs.com/issues

I know one of the challenges with the docs is that it is auto generated from the markdown on github, but I would definitely enjoy improved docs!

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/marionettejs.com/issues/53
