### ISSUE TITLE
Deprecate template: false

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3307]
`template: false` is a terrible API.  It is a hack that in v2 short-circuited the rendering process so that people could attach views to existing DOM, but could kick-start the view's lifecycle by calling render.

In v3 you can attach views to existing DOM, but you should _not_ need to call render to get the view setup.  Calling render on an already rendered view doesn't make sense.  You should only call `render` if you intend to render a template into the view's el and we shouldn't hack solutions for other purposes.

Today, `template: false` has very little value other than confusing people and perpetuating the hack.  I use it occasionally when I'm lazy in a js fiddle.. but even then it is entirely unnecessary.  Simply:
```js
var myView = new Mn.View({ template: _.noop });
myView.render(); // doesn't crash / doesn't render anything
```

Of course anyone using `template: false` to attach a view to existing DOM would have to switch to passing the view the DOM element.. so it could certainly be a less-than-ideal breaking change for some people..  Hence the deprecation... no need to remove it right away.

**Comment by scott-w** [comment]
I think that's a good call - it'll let us remove the special case for checking `false`. We could start with the documentation for 3.2 or 3.3 and add a simple warning in the code itself.

**Comment by paulfalgout** [comment]
Good point.. I removed the `major` label since it's certainly not breaking just to deprecate it.

**Comment by JSteunou** [comment]
If you do not use `template: false` on an existing DOM element, do you still have to call `render` ?

**Comment by JSteunou** [comment]
Nice! So indeed, what are the use cases for a `template: false` anymore?

**Comment by paulfalgout** [comment]
_Maybe_
```js
const MyEmptyTextarea = Mn.View.extend({
  tagName: 'textarea',
  template: false
});
```
but even then.. I dunno if it is worth keeping around as 
```js
const MyEmptyTextarea = Mn.View.extend({
  tagName: 'textarea',
  template: _.noop
});
```

**Comment by bazineta** [comment]
To answer @JSteunou, at least in my own experience it's useful when a View is being used as a proxy for a jquery plugin. For example, it can be handy to pass a Collection to a View that's proxying a bootstrap-select, informing the select of the items it should display. The view really just deals with this.$el, so there's no template, and one gains the benefit of being able to automatically destroy the select plugin in onBeforeDetach for leak avoidance.

**Comment by blikblum** [comment]
@bazineta does `template: _.noop` works in this use case?

**Comment by bazineta** [comment]
@blikblum Yes, it does, just as false did previously.

**Comment by JSteunou** [comment]
@bazineta nice way to deal with such plugin, I like the idea!
