### ISSUE TITLE
v3.2 Changelog and bump & build

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3313]
We should double check that all the 3.2 stuff is correct on the milestone:

https://github.com/marionettejs/backbone.marionette/milestone/39

**Comment by paulfalgout** [comment]
We might want to wait on https://github.com/marionettejs/backbone.marionette/issues/3314

**Comment by JSteunou** [comment]
Good to go ;)

**Comment by rafde** [comment]
Waiting on bump and build.
