### ISSUE TITLE
the custom "viewComparator" of CollectionView changes the collection order

### ISSUE THREAD

**Issue by greguz** [marionettejs/backbone.marionette#3314]
### Environment

Marionette v3.1.0
Backbone v1.3.3
Browserify v14.1.0

### Problem

When a custom "viewComparator" is specified, every time the view is rendered, it changes the order of the array "models" under the collection.

### Solution (tested)

Clone the "collection.models" array inside the function "_filteredSortedModels" before sort the array.

### Code

```javascript

Marionette.CollectionView.prototype._filteredSortedModels = function (addedAt) {

  if (!this.collection || !this.collection.length) return [];

  var viewComparator = this.getViewComparator();

  // this line is the fix
  var models = this.collection.map(function (model) { return model; });

  addedAt = Math.min(Math.max(addedAt, 0), models.length - 1);

  if (viewComparator) {

    var addedModel = void 0;

    if (addedAt) {
      addedModel = models[addedAt];
      models = models.slice(0, addedAt).concat(models.slice(addedAt + 1));
    }

    models = this._sortModelsBy(models, viewComparator);

    if (addedModel) {
      models.splice(addedAt, 0, addedModel);
    }

  }

  models = this._filterModels(models);

  return models;

};
```

**Comment by paulfalgout** [comment]
This might be a late candidate for 3.2  @rafde?

@greguz interested in a PR?  FWIW I think I'd lean towards just a `_.clone(models)` inside the `_sortModelsBy` function.  I don't think that function should mutate the array since we're using the return value.

**Comment by paulfalgout** [comment]
Another reason this belongs in `_sortModelsBy` is that out of the 3 (2ish) sort types, only 1 of them is causing the issue.  `Array.prototype.sort` mutates the data, but `_.sortBy(models...` is ok.

https://jsfiddle.net/37huLw61/

**Comment by rafde** [comment]
![out](https://i.ytimg.com/vi/s1YqTcJSPFA/hqdefault.jpg)

**Comment by rafde** [comment]
`this.collection.toArray()` should do it. I'll give it a try. I won't say when since I keep flaking out.

**Comment by greguz** [comment]
i'll make a PR

**Comment by rafde** [comment]
thanks @greguz

**Comment by greguz** [comment]
I've created a PR.
Now what i have to do ?

**Comment by paulfalgout** [comment]
@greguz thanks for finding, reporting and resolving this issue!  Would love to have your future involvement if you're interested.
