### ISSUE TITLE
region.show() not rendering Backgrid view

### ISSUE THREAD

**Issue by DavidUnzue** [marionettejs/backbone.marionette#3322]
### Environment
Marionette version: 3.2.0
Backbone version: 1.3.3
Backgrid version: 0.3.7
Build tool: browserify

### Description
I'm trying to integrate [Backgrid](http://backgridjs.com/) into a Marionette application. I want to show a Backgrid Grid, which is a view inheriting from Backbone.View, into a region of a Marionette view like this:
```javascript
var backgridView = new BackgridView({collection: myCollection});
mainRegion.show(backgridView);
```

### Expected behavior
The `.show()` function should trigger `render()` on `backgridView` and then attach it to the DOM.

### Actual behavior
`render()` is not being triggered on `backgridView`. The view will be attached to the DOM but won't be properly rendered before that, so that it won't show up on my application.

### Detailed issue description
In a nutshell: my `backgridView` is having the property `_isRendered` set to `true`, so that Marionette is preventing the view to be rendered (see [here](https://github.com/marionettejs/backbone.marionette/blob/master/src/region.js#L100)):
```javascript
_renderView(view) {
    if (view._isRendered) {
      return;
    }

    ...

    view.render();

     ...
 }
```

Now I was wondering, since a Backgrid view inherits from Backbone.View, why is it having the property `_isRendered` at all? And this is why:
When I do 
```javascript
mainRegion.show(backgridView);
```
then Marionette is doing this with my view (see [here](https://github.com/marionettejs/backbone.marionette/blob/master/src/region.js#L57)):
```javascript
view = this._getView(view, options);
```

Now the `_getView` function does the following (see [here](https://github.com/marionettejs/backbone.marionette/blob/master/src/region.js#L169-L171)):
```javascript
if (view instanceof Backbone.View) {
  return view;
}
```
So it checks if my View is just a plain Backbone view (a child of Backbone.View), and if that is the case, it leaves the view as it is. Otherwise, Marionette will do the following (see [here](https://github.com/marionettejs/backbone.marionette/blob/master/src/region.js#L173-L175)) and create a new Marionette view out of my view:
```javascript
return new View(viewOptions);
```

Now the thing is that my `backgridView` is actually an instance of Backgrid.Grid, which is again a child of Backbone.View. That means that `backgridView`, although being ultimately a backbone view, is not a direct child of Backbone.View. Because of that, the code:
```javascript
if (view instanceof Backbone.View) {
```
won't return true and my `backgridView` will be transformed into a Marionette view, which is then setting the property `_isRendered` to true here:
```javascript
// Overriding Backbone.View's `setElement` to handle
// if an el was previously defined. If so, the view might be
// rendered or attached on setElement.
setElement: function setElement() {
  var hasEl = !!this.el;

  Backbone.View.prototype.setElement.apply(this, arguments);

  if (hasEl) {
    this._isRendered = !!this.$el.length;
    this._isAttached = isNodeAttached(this.el);
  }

  if (this._isRendered) {
    this.bindUIElements();
  }

  return this;
}
```

Now the question is why `_isRendered` is true by default on a view that is not yet rendered.

**Comment by scott-w** [comment]
Hi @DavidUnzue and thanks for the really detailed report. I don't know Backgrid very well, but it looks like `view.el` and `view.$el` are getting set to a value either as part of Backgrid or as part of `getViewOptions`.

Can you attach a debugger and check the value of `this.$el` and `this.el` when Marionette is trying to attach your view?

**Comment by paulfalgout** [comment]
@scott-w beat me to it, but I agree it looks like `backgrid` is rendering something into the view's `el`, during `setElement` and _prior_ to `render` being called.

One thing we could do to support this is to attempt to internally use `isRendered()` and `isAttached()` falling back to the flags when the methods aren't defined so that they could be overridden.. then in backgrid's view isRendered could be overridden are return true for whatever check need to be done to know when it is rendered vs only partially rendered.

In the meantime it sounds like this is the work around
```js
var backgridView = new BackgridView({collection: myCollection});
// _isRendered is true at this point so we must for a render
backgridView.render();
mainRegion.show(backgridView);
``

**Comment by DavidUnzue** [comment]
@scott-w @paulfalgout yes there is content on both `view.el` and `view.$el` during `setElement`.

For the moment I will stick to the workaround of manually calling `render()` on the backgrid view.

**Comment by paulfalgout** [comment]
I think the best way to "solve" this is to better document how Marionette view and region determine if a view is already rendered
