### ISSUE TITLE
Sub Application

### ISSUE THREAD

**Issue by nadvi** [marionettejs/backbone.marionette#3325]
As-salamu-alikum

Zazakallah khair for showing interest on my post.

I am very new to marionette as well as backbone.I am also very weak in programming as well as in English.

Would you like to explain the sub application concept in marionette in a single page blogging site prospective?I will  grateful to you.

Zazakallah khair again for reading my post by spending your valuable time with passion.

Allah hafiz

Nadvi.

**Comment by scott-w** [comment]
Hi @nadvi and thanks for opening this issue. Are you looking for a way to break an application into sub modules with their own URL and route structures?

This feels like something we could put on the blog.

**Comment by nadvi** [comment]
Zazakallah khair for showing interest on my post.

Yes scott-w  I want to break the application into subapplication with their own URL, route structure, model, view, controller.

Zazakallah khair again for responding my post by spending your valuable time with passion.

Allah hafiz

Nadvi.

**Comment by paulfalgout** [comment]
Here's a good start https://medium.com/blog-marionettejs/charting-a-route-to-victory-e4eed1abfad4

Also https://gitter.im/marionettejs/backbone.marionette is a great place to ask these kinds of questions
