### ISSUE TITLE
How does an AppRouter attached to an application

### ISSUE THREAD

**Issue by nadvi** [marionettejs/backbone.marionette#3329]
As-salamu-alikum

Zazakallah khair for showing interest on my post.

I am very new to marionette as well as backbone.I am also very weak in programming as well as in English.

Would you like to explain the how to attach an AppRouter to an application?I will grateful to you.

Zazakallah khair again for reading my post by spending your valuable time with passion.

Allah hafiz

Nadvi.

**Comment by scott-w** [comment]
Hi @nadvi - in this case, it doesn't need to be "attached" so much as "instantiated". I've built an example application at https://github.com/scott-w/reps-js/blob/master/app/driver.js - check out the `processRoutes` function for how I've done this.

**Comment by nadvi** [comment]
Zazakallah khair for responding mys issue.

I am very weak in programming and what I have understood from your example is that,  Marionette.Application has a public variable router and we have to register our router definition to it.
Is it right? If I am not right please correct me.

Zazakallah khair again for your kind response. 

Allah hafiz

Nadvi.

**Comment by scott-w** [comment]
Hi @nadvi, that's not quite correct. You don't _need_ the `router` variable to remain at all. Once the routes are processed, it's the `Backbone.history.start()` that causes the router to determine where to send the user.

**Comment by nadvi** [comment]
Zazakallah khair for responding mys issue.

I am very weak in programming and what I have understood from your example is that,  Marionette.Application has a public variable router and we have to register our router definition to it.
Is it right? If I am not right please correct me.

Zazakallah khair again for your kind response. 

Allah hafiz

Nadvi.

**Comment by nadvi** [comment]
Zazakallah khair for responding mys issue.

I am very sorry that I could not convey my thought to you.Please pardon me.I am very weak in english. My concern is how my AppRouter definition i.e
```
var MyRouter = Marionette.AppRouter.extend({
  controller: EmailController,
  // "someMethod" must exist at controller.someMethod
  appRoutes: {
    'email': 'listEmails',
    'email/:email': 'showEmail'
  }
});
```
will be called and execute so that I can debug and design my code.

Zazakallah khair again for your kind response.

Allah hafiz

Nadvi.

**Comment by scott-w** [comment]
Hi @nadvi that all looks fine to me, you should just be able to do:

```js
var application = new Marionette.Application({
  onStart: function(options) {
    this.myRouter = new MyRouter();  // Using your MyRouter class
    Backbone.history.start();
  }
});

application.start();
```

If you want to make debugging easier, you can always do `window.application = ...` so you have access to it but that's not necessary.

**Comment by paulfalgout** [comment]
And `EmailController` doesn't need to be anything more than:
```js
var EmailController  = {
  listEmails: function() { ... },
  showEmail: function(email) { ... }
};
```

**Comment by paulfalgout** [comment]
This is also a great question for https://gitter.im/marionettejs/backbone.marionette

**Comment by nadvi** [comment]
Zazakallah khair again for your kind response.

Allah hafiz

Nadvi.
