### ISSUE TITLE
lintspaces shows EOL warnings on windows

### ISSUE THREAD

**Issue by blikblum** [marionettejs/backbone.marionette#3330]
### Description

 1. When developing  on windows and running the Mn tests, ~~ESLint~~(lintspaces) emit thousands of "invalid EOL" warnings

### Expected behavior

It should run without errors both on windows and unix

### Environment

1. Marionette version: next
2. Backbone version: 1.3.3
3. Additional build tools, etc: windows 10

Possible solutions:
- ~~Disable linebreak-style rule: http://eslint.org/docs/rules/linebreak-style~~
- Configure git to enforce lf on windows: https://help.github.com/articles/dealing-with-line-endings/ 
Something like: https://github.com/heroku/cli/blob/master/.gitattributes

**Comment by paulfalgout** [comment]
We can disable the rule, but probably `.gitattributes` would be good.  Here's what react is doing FWIW https://github.com/facebook/react/blob/master/.gitattributes

But also we are using `.editorconfig` which if using that should fix it for those utilizing it I would think.

**Comment by blikblum** [comment]
The Facebook config is equal to our current setup: the linebreak matches the default from OS

**Comment by paulfalgout** [comment]
maybe we just disable the rule..  I'm not sure what the issue is, if any, if there are mixed line breaks?

**Comment by blikblum** [comment]
No. Git handles it automatically

**Comment by blikblum** [comment]
After digging into inners of build system, found that the culprit is lintspaces and not eslint
