### ISSUE TITLE
Consider publishing a ES6 module build through pkg.module

### ISSUE THREAD

**Issue by blikblum** [marionettejs/backbone.marionette#3340]
### Description

 1. Add a  ES6 module build through pkg.module
 
### Expected behavior

Distributes an optional build that leverages benefits of ES6 modules like tree shaking. See https://github.com/rollup/rollup/wiki/pkg.module  

### Actual behavior

Only umd module is published

**Comment by pglewis** [comment]
PR for consideration: #3384
