### ISSUE TITLE
Uncaught TypeError: this._setOptions is not a function  at Object.constructor [as Region] (backbone.marionette.js:1285)

### ISSUE THREAD

**Issue by nadvi** [marionettejs/backbone.marionette#3342]
As-salamu-alikum

Zazakallah khair for showing interest to my post.

I am new to marionette and very poor in programming.Suddenly I get the following error in chrome with the following code.
```
define(function (require) {
        'use strict';
        var options = { region: new require('mt').Region({ el:$('body')})};
        console.log(options);
    },
    function ( err ) {
        var failedId = err.requireModules && err.requireModules[0];
        console.log("In err " + failedId);
        console.log(err);
    }
);
```
> Uncaught TypeError: this._setOptions is not a function
>     at Object.constructor [as Region] (backbone.marionette.js:1285)
>     at driver.js:5
>     at Object.execCb (require.js:1693)
>     at Module.check (require.js:881)
>     at Module.<anonymous> (require.js:1136)
>     at require.js:134
>     at require.js:1186
>     at each (require.js:59)
>     at Module.emit (require.js:1185)
>     at Module.check (require.js:936)
> constructor @ backbone.marionette.js:1285
> (anonymous) @ driver.js:5
> execCb @ require.js:1693
> check @ require.js:881
> (anonymous) @ require.js:1136
> (anonymous) @ require.js:134
> (anonymous) @ require.js:1186
> each @ require.js:59
> emit @ require.js:1185
> check @ require.js:936
> (anonymous) @ require.js:1136
> (anonymous) @ require.js:134
> (anonymous) @ require.js:1186
> each @ require.js:59
> emit @ require.js:1185
> check @ require.js:936
> (anonymous) @ require.js:1136
> (anonymous) @ require.js:134
> (anonymous) @ require.js:1186
> each @ require.js:59
> emit @ require.js:1185
> check @ require.js:936
> (anonymous) @ require.js:1136
> (anonymous) @ require.js:134
> (anonymous) @ require.js:1186
> each @ require.js:59
> emit @ require.js:1185
> check @ require.js:936
> enable @ require.js:1173
> init @ require.js:786
> callGetModule @ require.js:1200
> completeLoad @ require.js:1587
> onScriptLoad @ require.js:1714       
 
I do not understand what mistake I have done. Would you like to help me to find out  the problem.
Please help me.I will be grateful to you.

Zazakallah khair for reading my post.    

Allah-hafiz

Nadvi

**Comment by paulfalgout** [comment]
I don't think this is enough code to help debug the problem.
Please use https://jsfiddle.net/marionettejs/adhv48ky to reproduce the error if possible
