### ISSUE TITLE
Automatic template definition

### ISSUE THREAD

**Issue by emilos** [marionettejs/backbone.marionette#3351]
### Description

 Currently to define a simple layout view you can do the following:

```javascript

Mn.View.extend({
    regions: {
        header: ".header-region",
        content: ".content-region",
        footer: ".footer-region"
    },
    template: _.template(`
        <div class="header-region"></div>
        <div class="content-region"></div>
        <div class="footer-region"></div>
    `),
    onRender: function () {
        this.showChildView("header", new HeaderView());
        this.showChildView("content", new ContentView());
        this.showChildView("footer", new FooterView());
    }
});
```

I use the pattern above quite often (the only difference is that I compile the templates server side) and I'm curious if it would be reasonable to define the view  in a slightly different way:

```javascript

Mn.View.extend({
    regions: [
        "header",
        "content",
        "footer"
    ],
    onRender: function () {
        this.showChildView("header", new HeaderView());
        this.showChildView("content", new ContentView());
        this.showChildView("footer", new FooterView());
    }
});
```

This could remove some of the boilerplate at the runtime cost / slightly bigger lib size, should be 100% backwards compatible too. I'd be happy to contribute if this makes sense.

**Comment by paulfalgout** [comment]
I think that might be something to add to [labs](https://github.com/marionettelabs) at first.
I'm not certain about the API for core necessarily.  I agree it's a common pattern, but it won't always be true that no other markup is needed in the template, which reduces the usefulness IMO.

Marionette is currently heading towards abstracting region a bit so that you could do this:
```js
Mn.View.extend({
    template: _.template(`
        <div class="header-region"></div>
        <div class="content-region"></div>
        <div class="footer-region"></div>
    `),
    onRender: function () {
        this.showChildView(".header-region", new HeaderView());
        this.showChildView(".content-region", new ContentView());
        this.showChildView(".footer-region", new FooterView());
    }
});
```

At one point I was playing with an ES6 tagged template literal for doing something like:
```js
Mn.View.extend({
  template: mnx`
   <region name="header">
   <region name="content">
   <region name="footer">
  `,
    onRender: function () {
        this.showChildView("header", new HeaderView());
        this.showChildView("content", new ContentView());
        this.showChildView("footer", new FooterView());
    }
});
```
Although I had also considered:
```js
Mn.View.extend({
  template: mnx`
   ${ { view: new HeaderView(), regionName: 'header' } }
   <region name="content">
   <region name="footer">
  `,
    onRender: function () {
        this.showChildView("content", new ContentView());
        this.showChildView("footer", new FooterView());
    }
});
```
But this stuff would also probably never see core.

**Comment by JSteunou** [comment]
The main issue is that not everyone declare regions the same way. Some use classes other data attribute... Marionette does not enforce a way that is why you have to manually map regions. But if you always use the same way you can easily extends Marionette to not repeat yourself. For example I wrote an autoregion plugin that auto add all node with data region attribute in the view regions hash property.
