### ISSUE TITLE
CollectionView doesn't bind elements UI on render function

### ISSUE THREAD

**Issue by rodro7** [marionettejs/backbone.marionette#3378]
### Description

 1. When I want to set ui elements in a CollectionView in order to perform a DOM manipulation I can't because CollectionView doesn't call bindUIElements on render function. I don't really know if it is a desired behavior or an issue. If it's a desired behavior I would like to know why in order to use it in a correct way.

 2. Modify render function and destroy function in order to support bindUIElements/ unbindUIElements

### Environment

1. Marionette version: v3.2.0

**Comment by paulfalgout** [comment]
the usecase for binding ui elements are generally to support the ui of the view itself and not the children.  ie: when you have a view with regions you expect the view to be bound to it's own elements, but not necessarily that the child views would also get bound to the parent if they shared a similar selector.
The collectionview has no template and therefore does not account for the typical use-case of binding ui.  If we were to add the bind at the same place as a regular view it would never bind to anything as the children would be add after binding.

https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.collectionviewadvanced.md#binding-ui
