### ISSUE TITLE
Backbone.View.remove is not called by Marionette.View.destroy

### ISSUE THREAD

**Issue by blikblum** [marionettejs/backbone.marionette#3379]
### Description

Starting from https://github.com/marionettejs/backbone.marionette/commit/1459e746ebea3f57d6ab2f7d7e6a14880becf83c#diff-9e0fc915cc771da1abb32dc1d433cf7a `Marionette.View.destroy` does not calls `Backbone.View.remove` anymore.

Functionality wise there's no loss but can affects libraries that monkey patch `Backbone.View.remove` like stickit

Re-adding call to `remove` will require a non trivial refactoring

### Expected behavior

If doable, call `Backbone.View.remove` otherwise document this change

### Actual behavior

`Marionette.View.destroy` does not calls `Backbone.View.remove`

### Environment

1. Marionette version: 3.x
2. Backbone version: 1.3.3

**Comment by paulfalgout** [comment]
calling `remove` will `stopListening` prior to things that are potentially listening.

**Comment by paulfalgout** [comment]
specifically https://github.com/marionettejs/backbone.marionette/blob/master/test/unit/utils/view.spec.js#L24
or
https://github.com/marionettejs/backbone.marionette/blob/master/test/unit/view.child-views.spec.js#L241

depending on where `remove` would be called.

**Comment by blikblum** [comment]
One alternative is overriding `_removeElement` with a noop so basically we could call in place of stopListening

**Comment by blikblum** [comment]
Closing as no relevant anymore
