### ISSUE TITLE
Inconsistent view lifecycle events

### ISSUE THREAD

**Issue by jmory** [marionettejs/backbone.marionette#3382]
### Description

Currently the order of the view lifecycle events
differs if we show a view 'directly'
in a region or the view is shown in a region
by some parent view.

#### Case 1
```
const region = new Marionette.Region({el: document.querySelector('...')});
region.show(new MyView());
region.empty();
```

will result in a lifecycle event sequence of

* before:render
* render
* before:attach
* attach
* before:destroy
* before:detach
* detach
* destroy

#### Case 2

```
const ParentView = Marionette.View.extend({
  onRender() {
  	this.showChildView('childViewRegion', new MyView());
  }
});
region.show(new MyParentView());
region.empty();
```

will result in a lifecycle event sequence of

* before:render
* render
* before:attach
* attach
* before:detach
* detach
* before:destroy
* destroy

### Expected behavior

The order of the view lifecycle events should always be the
same, no matter if the view is shown directly in region or
shown by another view in a region.

Apart from being inconsistent, triggering `before:destroy` AFTER
the view's el is already detached from the DOM can make it hard to
do proper cleanup in the `onBeforeDestroy` hook if we need the
view's el to be still attached to the DOM at this point.

Since this behavior is documented (https://marionettejs.com/docs/v3.3.1/viewlifecycle.html#view-destruction-lifecycle)
I'm curious about the motivation/reason for this behavior. 

### Example

https://codepen.io/jmory/pen/zweOOj

### Environment

1. Marionette version: 3.3.1
2. Backbone version: 1.3.3

**Comment by paulfalgout** [comment]
> The order of the view lifecycle events should always be the
same

I disagree.  The view events should reflect what is happening to them.  When you destroy a single view it will start it's destroy (`before:destroy`) As part of the destroy process it will detach itself from the DOM (`before:detach`, `detach`) and then the destroy will be complete (`destroy`)

For a parent view it will detach itself first and then destroy the children.  When the parent view detaches, all of the childviews down the tree will also receive the detach events.  If it destroyed the children first they'd be individually removed from the DOM prior to the parent.. so _many_ DOM changes instead of 1.  But FWIW a view is detached during it's destroy only if it is currently attached, which is by no means a requirement.

Therefore if you need to clean up something while the view's `el` is in the DOM prior to its removal use `onBeforeDetach` always.  If you need to clean up something _within_ the view's el use `onDomRemove` and if you need to clean up something add in `initialize` unrelated to the DOM use `onBeforeDestroy`.

**Comment by rafde** [comment]
Also, the order of the events is the most performant.
On create, having the view render before it's attached to the document is better than attaching the view first, then rendering the view.
On destroy, it's better to remove the view from the document then destroy the view.

**Comment by jmory** [comment]
Thank you for the quick reply, makes sense to me. Is there a way to determine in `onDetach` if
the event was triggered because the region was emptied, e.g. by calling `region.empty()`, or if the parent view was just detached but not destroyed, e.g. by calling `region.detachView()`?

**Comment by rafde** [comment]
@jmory https://marionettejs.com/docs/master/viewlifecycle.html#empty-region-events

**Comment by paulfalgout** [comment]
What is the use case? Whether destroyed or detached the region is emptied.

**Comment by jmory** [comment]
Sorry for the late reply.

In my project we have a view that uses a 3rd party library to show
a video player. When we dispose the player we need the view's ```el```
to be in the DOM.

This player view is passed by a controller to different view's that will
show it in one of their regions. E.g. the video is shown in a lightbox when the user
clicks a specific button on the player. When passing the player from one view to
another it is detached (without destroying it) from one region and shown in a different
region. At some point the two views showing the player are destroyed, e.g. when the user
navigates to different page)

This means i can't just do the cleanup in `onBeforeDetach` because
it is triggered in both cases: 

* When we detach the player when we move
it between different views  we don't want to dispose player in ```onBeforeDetach```.

* When we finally destroy all the views we wan't to dispose the player in ```onBeforeDetach```.

**Comment by blikblum** [comment]
In before:destroy set a isDestroying flag

**Comment by paulfalgout** [comment]
Hmm this is interesting..  kind of is this the final detach..  @blikblum that'd only work for destroying itself, but not for when the parent detaches prior to destroying its children.

I think you'd probably want to do this like:
```js
onBeforeDestroy() {
  this.destroyPlayer();
},
destroyPlayer() {
  if(!this.isAttached()) return;
  myPlayer.destroy();
}
```
then in the parent:
```js
onBeforeDetach() {
  this.getChildView('player').destroyPlayer();
}
```
I assume the parent is the one who knows when to detach the player view so it seems reasonable that it would know if it needed to also clean it up.

**Comment by jmory** [comment]
@blikblum @paulfalgout Thanks for the suggestions, extending the player view api to destroy the player and calling it from the parent view is the route I'll go.
