### ISSUE TITLE
Alias doesn't work

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3396]
The current footer added by rollup for the alias `this.Marionette && this.Mn = this.Marionette;` doesn't work.  backbone handles the "root" like so:
```js
var root = (typeof self == 'object' && self.self === self && self) ||
            (typeof global == 'object' && global.global === global && global);
root.Marionette && root.Mn = root.Marionette;
```

Meh I think the issue is simply `this && this.Marionette && (this.Mn = this.Marionette);`

**Comment by rafde** [comment]
resolved be #3407
