### ISSUE TITLE
NextCollectionView addChildView does not add child to a specified index like CollectionView can do

### ISSUE THREAD

**Issue by nnnoel** [marionettejs/backbone.marionette#3406]
### Description

Here is a fiddle https://jsfiddle.net/zr8gn69g/22/

If the fiddle loses state, you can copy paste the code from here https://www.dropbox.com/s/y4qwqu6fu4zn7oh/code.txt?dl=0

I'm using a NextCollectionView and adding a specific child view at the beginning and at the very end of the collection view. I also have a collection that I'm instantiating it with and I'm calling `addChildView`, on render, to specify child views, which are outside of the collection entirely, at index 0 (the beginning) and at index -1 (the very end).

This works perfectly fine with a regular CollectionView, but not with a NextCollectionView

I understand that NextCollectionView is still somewhat in beta, but wanted to point this out as this is something I'm working with at the moment.

### Environment

1. Marionette version: v3.3.1
2. Backbone version: v1.3.3

**Comment by paulfalgout** [comment]
Yep so by default `NextCollectionView` sorts by the collection.  In v3.x this can be avoided by setting `viewComparator` to `_.noop`, but `viewComparator: false` is coming to v3.4 https://github.com/marionettejs/backbone.marionette/pull/3387

This same thing would happen to a regular CollectionView if something cause a `sort`, but the current collectionview is more inconsistent, so it is possible to create scenarios that don't run into caveats.

I _think_ this is resolved for v3.4 in particular, but let me know if you think it isn't addressed.  And thanks for posting the issue!

**Comment by nnnoel** [comment]
Thanks for pointing that out. In addition to nooping the view comparator, removing the negative index like you suggested resolved this issue. Much appreciated
