### ISSUE TITLE
viewFilter function for lodash users

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3412]
### Description

For `NextCollectionView`, the behavior of `viewFilter` differs depending on whether you have lodash or underscore because of the difference in the `partition` API.

The lodash `partition` function is incompatible with Underscore's by not passing `index`/`key` or `collection` in as its 2nd third arguments. This means `viewFilter(view, index, children)` when using Underscore is `viewFilter(view)` when using lodash.

To fix this, we should put a note in the docs for lodash users where the workaround is to do `this.children.findIndexByChild(view)` and `this.children` is still accessible anyway.

### Environment

1. Marionette version: v3.3.1
2. Backbone version: v1.3.3
3. Additional build tools, etc: lodash

**Comment by paulfalgout** [comment]
Note that the use-case for index in filtering is probably limited as well.  Most of the time someone will probably filter off of data on the model, or maybe even the view.

**Comment by scott-w** [comment]
I don't think it's a common thing, it's just something I encountered where the docs didn't reflect what was happening =)

**Comment by bazineta** [comment]
Glancing through the documentation for both libraries, it seems to me that if one wanted a common works-anywhere solution for this, it'd have to be `_.reduce`.

**Comment by paulfalgout** [comment]
hmm I think `_.reduce` would be a fairly unfortunate change.  The benefit of `partition` in both libraries is that there is a single loop that requires the user to return a truthy/falsey result as you would expect with a filter handler that then returns both the views to filter in and out.  With reduce we'd be requiring the user to build some other data structure and it would be much less like a filter.

**Comment by bazineta** [comment]
Just basically musing on the intersections between the two libraries; in short, no matter what happens in lodash, all paths lead to `_.reduce` eventually. In this case, the memo object passed in would be an object or array tuple, one for the keepers, one for the others, such that it'd be one loop only.

It'd require some effort to deal with the predicates, but it seems as if it'd be doable such that the user would still see exactly the same predicate API that `viewFilter` has now. If interested, I could take a crack at it, which would avoid having to dual-path the documentation if it works. If you're ok with dual-path documentation, that's ok with me as well.

**Comment by paulfalgout** [comment]
if the `viewFilter` api does not change for the user and there is no performance hit on large lists, I'm ok with a change

**Comment by bazineta** [comment]
@rafde Given what you're keeping an eye on in Lodash 5, do you thing this is still a good path to go down?

**Comment by bazineta** [comment]
Seems as if the stuff that's slated to change so far in 5 isn't a concern at present for this, from what I can see, anyway, i.e., doesn't look like the API of `_.reduce` will change, and `_.matches` is still slated to be present. Given that most of the heavy lifting is already done in `_getFilter`, what I was thinking of is along the lines of replacing this:
```javascript
const filteredViews = _.partition(this.children._views, _.bind(viewFilter, this));
```
with something like this:

```javascript
const filter        = _.bind(viewFilter, this);
const filteredViews = _.reduce(this.children.views,
                        function(result, view, key, collection) {
                          (result[filter(view, key, collection) ? 0 : 1]).push(view);
                        }, [[],[]]);
```
This is a quick and naive chunk'o'code that I'd still need to test, but along those lines.

**Comment by paulfalgout** [comment]
This looks fine to me.  Essentially what underscore is doing http://underscorejs.org/docs/underscore.html#section-48

It might even be a little faster since there's no need for the predicate here since that's in `_getFilter`

yep.. and with each it's even faster https://jsperf.com/custom-partition/1 but `_.reduce` is perhaps nicer

**Comment by bazineta** [comment]
So, @paulfalgout, `NextCollectionView` being your baby, and the change being very small, at this point I  think it'd probably be best for me to step aside and say, 'well, that's how I'd do it, then we don't need to modify the documentation at all'.
