### ISSUE TITLE
Behavior this.options is always empty

### ISSUE THREAD

**Issue by JSteunou** [marionettejs/backbone.marionette#3414]
When a view passes options to behaviors, those should be set in the options property of the behavior. This is no more the case in 3.4

3.3 https://jsfiddle.net/7z8wxrdo/2/
3.4 https://jsfiddle.net/7z8wxrdo/3/

**Comment by JSteunou** [comment]
ok find why @paulfalgout 

https://github.com/marionettejs/backbone.marionette/commit/b2ad46f9c8930be98735387b30602ecfdd98bdd2#diff-e5931bcc4ee3beb1f1bcb2460133d657 introduce regression because at this loc we give 2 parameters https://github.com/marionettejs/backbone.marionette/blob/master/src/behavior.js#L41

**Comment by paulfalgout** [comment]
Good find.  Unfortunate missing test case.  I think though rather than reverting we should do `this._setOptions(_.extend({}, this.defaults, options))` so that only behaviors get a slightly perf hit instead of every class.  Thoughts?  Want to open a PR @JSteunou

**Comment by JSteunou** [comment]
Yep, have a little time and I like your idea
