### ISSUE TITLE
Child view region issue of v3.4.1

### ISSUE THREAD

**Issue by JounQin** [marionettejs/backbone.marionette#3424]
### Description

 When there is an unused region in childView of collectionView, it will try to replace elements outside of collectionView!

### Expected behavior

Should only find region in childView rather than outside of collectionView

### Actual behavior

https://jsfiddle.net/JounQin/L8vrbsdd/

### Environment

1. Marionette version: 3.4.1
2. Backbone version: 1.3.3
3. Additional build tools, etc: none

**Comment by paulfalgout** [comment]
So.. I do think there's likely an over-selective region issue here.. unfortunately fixing it will be breaking.  This will ultimately be resolved with a solution like: https://github.com/marionettejs/backbone.marionette/issues/3417

**Comment by JounQin** [comment]
@paulfalgout It actually works on v3.3.1

https://jsfiddle.net/ayju8k3h/1/

**Comment by JSteunou** [comment]
solved by #3425 which will be out with 3.4.2
