### ISSUE TITLE
Better support for renderer that modifies the DOM directly

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3450]
`_renderTemplate` should not attach content if the renderer does not return html.
```js
    const html = this._renderHtml(template, data);
    if (html) { this.attachElContent(html); }
```
This will allow for a custom renderer to update the el directly and not return an html string.

https://github.com/marionettejs/backbone.marionette/blob/master/src/view.js#L153

**Comment by JSteunou** [comment]
It actually works without this by luck because returning `undefined` make attachElContent doing nothing. (With the Dom Api jquery style, you have to implement it the same in native)
`if (html)` is a bit aggressive, because empty String could be a valid returned html content.

**Comment by paulfalgout** [comment]
Ah so you're correct it would have to check if html is not undefined.  I still think that is an improvement over the renderer having to deal with that check.

**Comment by JSteunou** [comment]
agreed
