### ISSUE TITLE
Document removal of `triggerMethodOn`

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3454]
Ticket #3446 removes the `triggerMethodOn` from being called on Backbone.View and replaces it with a specific mixin to allow us to handle this.

We need to be document this in both the upgrade notes and a breaking change and in a section for handling non-Marionette Views.

**Comment by paulfalgout** [comment]
I think we need a single documentation ticket for v4.  Otherwise we're going to have dozens of these as we start merging.

**Comment by paulfalgout** [comment]
Added to the documentation issue
