### ISSUE TITLE
v4 Changes Documentation

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3461]
Following #3454 I've created this ticket to track all the major changes to the API from v3 to v4. Add items here and tick off items as the documentation gets completed:

* [ ] `Behavior#defaults` removed in favour of `Behavior#options`
* [ ] Removal of `behaviorLookup`
* [ ] Removal of `triggerMethodOn` https://github.com/marionettejs/backbone.marionette/issues/3454
* [ ] childViewEventPrefix is now `false` by default
* [ ] TemplateCache was removed by default (remove template: '#some-selector')
* [ ] View related docs should be addressed regarding the render-template mixin being available to both (all) views

**Comment by paulfalgout** [comment]
whoever picks this up should double check the milestone https://github.com/marionettejs/backbone.marionette/milestone/33

**Comment by paulfalgout** [comment]
We also need to go through the inline comments.  I've seen a few referring to the Marionette.Renderer and there's probably others.

**Comment by paulfalgout** [comment]
we should address this https://github.com/marionettejs/backbone.marionette/issues/3562

**Comment by paulfalgout** [comment]
@marionettejs/marionette-core thoughts on code samples for v4 docs.  Are we keeping `var Mn = require('backbone.marionette');` or should we start moving to ES6 `const { MnObject } from 'backbone.marionette';`?

**Comment by JSteunou** [comment]
I would prefer `import from` statement

**Comment by bazineta** [comment]
I would also prefer import, if only for the public service of raising awareness that there's now better ways to do things among those who would not otherwise know.
