### ISSUE TITLE
Vote on new Object name

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3481]
Replaces https://github.com/marionettejs/backbone.marionette/issues/3429

We have to rename `Object` for ES6 exports to work https://github.com/marionettejs/backbone.marionette/pull/3393

`Object` will also unlikely be the base for any class in v4 https://github.com/marionettejs/backbone.marionette/pull/3437

So we need a new name for `Object`  👍 or 👎 the following  (or add a better idea)

@marionettejs/marionette-core and anyone interested

**Comment by paulfalgout** [comment]
MnObject

**Comment by paulfalgout** [comment]
MarionetteObject

**Comment by paulfalgout** [comment]
Obj

**Comment by jmeas** [comment]
Thingamabobber

😉
