### ISSUE TITLE
Reimplement template:false

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3484]
`template:false` was deprecated mostly because of its misuse.  It was initially added so that view's that were pre-rendered could have `onRender` events for attaching children without wiping the pre-existing html.  However in v3 views supported being rendered upon instantiation and thus users should not render a view if they do not want it rendered.  There is a use-case however when the only thing you want from the view is the `el` and there is nothing to render into the view itself.  This is by far the best use for `template: false`.  However I personally think that keeping it around is problematic as it support a bad pattern for setting up children in views.

I would support `template: false` if it prevented `render` events from occurring.  If there is no template, no rendering is occurring.  `template: false` should effectively no-op the render method.  If there is no template then there's no need to re-bind ui either, nor is there any use for render events, so this would in fact support a more performant template-less view better than the current implementation _and_ it would prevent the bad pattern.

@marionettejs/marionette-core thoughts?

Related: https://github.com/marionettejs/backbone.marionette/pull/3470#discussion_r141997852

**Comment by bazineta** [comment]
Only the render event? Looking through my own stuff, there are many cases that use `template: _.noop` but still depend on the render event; presumably these could be refactored to the attach event.

In general, our use of `template: _.noop` is either as a wrapper for a jQuery plugin, where we're depending on things like `onBeforeDetach` for leak elimination, or it's in places where there really is no template, e.g., where `className` is used, and there's actually no template required.

**Comment by paulfalgout** [comment]
`attach`/`detach` would be the correct events in those circumstances as they deal with when the `el` is in the DOM.  `render` is specifically about when content is put in the `el` which in the cases you describe there isn't.   Granted `_.noop` would still work as you've described.

**Comment by JSteunou** [comment]
I am in favor of template : false or either undefined. _.noop is such a pain to write and to explain why... My use cases are mostly for tiny views with just tagName & className so having to write that _.noop thing each time...  Frustrating

**Comment by bazineta** [comment]
I agree; gladly would I trade having to visit all my code again if it meant returning to `false` instead of `_.noop`.

**Comment by bazineta** [comment]
Figuring this was worthy of real data, in my codebase there were 31 uses of `template: _.noop` in 27 files. Of these, 12 files were using either the `render` event or `onRender` function; the rest were all using `attach`.

In practically every case, the only interaction was with the `el`, and thus everything being done in the render could be pushed to the constructor (we're a CS shop).

Our non-template codebase is 749 files, so in our case, while we certainly use template-less views, it's obviously not terribly common for us; our usage is for the most part either trivial views (e.g., a `span`, or a `li`) comprising a Bootstrap menu component of some type, or where we're using the View to wrap a jQuery plugin, e.g., one common use was to render a `Collection` using a bootstrap-select, using `onDestroy` to prevent leakage of the plugin.
