### ISSUE TITLE
Exception while rendering the regions in 'show'

### ISSUE THREAD

**Issue by badrinathvm** [marionettejs/backbone.marionette#3486]
### Description

 Not able to render the sub views seeing an exception, I have regions trying to display those regions on OnStart method , throws below exception 

 App.js:30 Uncaught TypeError: Cannot read property 'show' of undefined
    at child.onStart (App.js:30)
    at child.triggerMethod (backbone.marionette.js:137)
    at child.start (backbone.marionette.js:3078)

code is 

export default  Marionette.Application.extend( {

    regions:{
        form: '#form',
        list: "#list"
    },

    initialize: function(options) {
        console.log('Initialize');
    },

    onStart: function( options ) {
        
        this.users = new Users();

        this.form.show(new FormView({collection: this.users}));  //exception here 
        this.list.show(new UsersView({collection: this.users}));

    }

});

Any help is appreciated .

### Expected behavior

Sub Views should get rendered.

### Actual behavior

facing exception not rendering the views

### Environment

1. Marionette version: 3.0
2. Backbone version:  1.3
3. Additional build tools, etc:

**Comment by blikblum** [comment]
In v3 regions are not set as view properties anymore 

Try:
   ```
this.getRegion('form').show(new FormView({collection: this.users})); 
   //or
   this.showChildView('form', new FormView({collection: this.users})); 
```

**Comment by paulfalgout** [comment]
That should solve the problem, but certainly let us know if there's something else.  I would also highly recommend posting issues like this to gitter: https://gitter.im/marionettejs/backbone.marionette
