### ISSUE TITLE
Do model/collection need to be cloned (when serialized) to render?

### ISSUE THREAD

**Issue by nlhuykhang** [marionettejs/backbone.marionette#3500]
### Description

I was having performance issue with my project, so I spent time looking into Marionette code hoping to find out some ways to optimize performance. I found out that by default a view will [shallow clone models during serialization before rendering](https://github.com/marionettejs/backbone.marionette/blob/v3.3.1/src/view.js#L56-L80). My concern is that if these models are only used for rendering, why do we need to clone them? given that clone is an expensive operation

### Expected behavior

For future version, Should we just return `model.attributes` without cloning? If application developers need to modify models, they can clone themselves.

### Environment

1. Marionette version: 3.3.1
2. Backbone version: 1.3.3

**Comment by paulfalgout** [comment]
Good catch. Interestingly enough they will not be cloned for v4. https://github.com/marionettejs/backbone.marionette/blob/next/src/mixins/template-render.js#L60

I think this was somewhat legacy regarding how `templateHelpers` used to be attached directly to the return of the `serializeData`.  Now we're extending onto an empty object, which doesn't remove the cost entirely, but it should be much cheaper..  however I'm looking into simply returning the serialized data if `templateContext` isn't defined which would be an additional improvement.

This was a breaking change if even minor so it had to wait for v4, but I would imagine in a majority of cases, back-porting whats on the `next` branch will not be breaking.
