### ISSUE TITLE
Deprecate multiple handlers

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3503]
Marionette allows users to set handlers as string names of methods which I think is useful as in:
```js
  modelEvents: {
    'change': 'render'
  }
```
But it also allows multiple handlers such as:
```js
  modelEvents: {
    'change': 'render onChange onModelChange'
  }
```
This to me seems like an unnecessary shortcut that keeps us from further simplifying event creation.

**Comment by JSteunou** [comment]
Always found this a bad practice. I prefer having one callback like `onChangeFoo` calling multiple methods if needed.
