### ISSUE TITLE
Destroyed behaviors keep view events and triggers

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3506]
Right now if you destroy a behavior it will remove itself from the view's proxy so view events won't trigger on the behavior, but handlers setup on the behaviors `events` and `triggers` will still handle

Since the events and triggers are namespaces with a unique namespace it would be hard to extract these.  

I could see fixing this a couple of ways.  One we can give the namespaces a predictable name based perhaps on the behavior's `cid`.  This doesn't seem hard and easy to implement removal _however_ we'd be calling `undelegate` I assume with simply a namespace to remove the events and I don't know if the native variety of Mn could handle that.  @blikblum 

So the other option?  if a behavior is destroyed on the live view we could run re-run `delegateEvents` (which will undelegate prior to re-delegating by default)  This is probably much less performant, but it's simple.

Also this feels bugish and we do have another v3.4.x to release it looks like.. 

Thoughts?

**Comment by blikblum** [comment]
> Right now if you destroy a behavior it will remove itself from the view's proxy so view events won't trigger on the behavior, but handlers setup on the behaviors events and triggers will still handle

Any example of this bug?

> I could see fixing this a couple of ways. One we can give the namespaces a predictable name based perhaps on the behavior's cid.

I think is doable and something i was looking into more as a performance than a bug fix.

BTW: The only purpose of namespace is avoiding key collision when building the events hash. It could be removed at all.

> I don't know if the native variety of Mn could handle that

I have to double check. But last time i looked should be handled by Mn.Native out of box

**Comment by paulfalgout** [comment]
> The only purpose of namespace is avoiding key collision when building the events hash.

I think collision avoidance is necessary for behaviors, but this would introduce a new use case using namespacing for removing only the destroyed behavior events/triggers

https://jsfiddle.net/3p35cbL8/1/
