### ISSUE TITLE
unbindEvents and unbindRequests shouldn't require the bindings hash

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3507]
Currently in order to effectively unbind events or requests you must reproduce an identical bindings hash.  This can lead to leaks such as:
```js
myRequests() {
  return {
    'foo'() {
        console.log('I am an anon handler that will never be cleaned up');
    }
  };
},
initialize(options) {
  this.channel = options.channel;
  this.bindRequest(this.channel, _.result(this, 'myRequests'));
},
onBeforeDestroy() {
  this.unbindRequest(this.channel, _.result(this, 'myRequests'));
}
```
outside of calling `options.channel.stopReplying(null, null, this);`
there is no way to clean up the bound requests.
the unbind functions should allow for `this.unbindRequest(this.channel);`
This would allow for a fail safe way to unbind everything on the view.

Also I think having the bind functions call the unbind is a false sense of security and could probably be avoided in v4.

This doesn't allow for automatic clean up of bound requests when an element is destroyed.  We should add special documentation here as events _are_ automatically cleaned up by nature of a regular destroy without needing to unbind.

**Comment by blikblum** [comment]
> the unbind functions should allow for this.unbindRequest(this.channel);

The way i see this feature  implemented is storing some info in the instance (`this`) at bind call and retrieving later at unbind call. 
It introduces complexity in a feature that at minimum, its usage is questionable (requests at views).

The way i see implemented is something like
```
this.boundRequestInfo = this.bindRequest(this.channel, _.result(this, 'myRequests'));
```
later

```
this.unbindRequest(this.channel, this.boundRequestInfo);
or
this.boundRequestInfo() //a destroy function
```

>  as requests are automatically cleaned up by nature of a regular destroy without needing to unbind.

Do you mean events?

**Comment by paulfalgout** [comment]
> Do you mean events?

yep edited

returning a specific unbind is interesting.  I like it better as a destroy function as I think there is value in keeping the `unbindRequest` arguments the same.  I also think that `this.unbindRequests(this.channel);` should also remove everything from the instance,  but that's much more dramatic than `this.boundRequestInfo();` which is precise.

It is notable to mention that this issue will be true for _every_ class in Mn, though probably the most problematic use case will be views.

**Comment by blikblum** [comment]
>  I also think that this.unbindRequests(this.channel); should also remove everything from the instance, but that's much more dramatic than this.boundRequestInfo(); which is precise.

I was thinking that `bindRequests` could add destroy event handler with the cleanup function. This way there's no need to do housekeeping in the instance and no need to user unbind manually

**Comment by paulfalgout** [comment]
are you considering this only for `bindRequests`?

**Comment by blikblum** [comment]
It needs in `bindEvents` ? Is not removed at destroy already?

**Comment by paulfalgout** [comment]
I feel like there are 2 issues.. how to clean up on destroy of the parent obj and how to clean up during the life of the obj.

Well this is essentially what `radioRequests` is doing now https://github.com/marionettejs/backbone.marionette/blob/master/src/mixins/radio.js#L46

So I think that works for request clean up, however we do need to realize that there may be many channels bound to a single item, _but_ we could probably setup a single handler that could look through an array of channel names or something.  since `Radio.channel('name').channelName === 'name'`

However it is certainly possible to have leaks during the lifecycle of the object which is just as problematic for events and requests, so whatever we do for that should be the same for both.

**Comment by blikblum** [comment]
> However it is certainly possible to have leaks during the lifecycle of the object

Before trying to make the fix, we should create a reasonable use case / test so we can evaluate all alternatoves

**Comment by bazineta** [comment]
A use case that we encounter in our application is, in short:

- A deep or complex view hierarchy exists.
- Views at an arbitrary location in the hierarchy must obtain information from elsewhere in the hierarchy.
- These views are unaware of exactly where this information comes from, only that they may request it.
- An anonymous channel is created by the top-level view, and is passed to subviews, typically recursively down the hierarchy, via dependency injection.

For this case, an anonymous channel works well; it acts as a bus, and the views are decoupled, really depending only on the bus.

**Comment by JSteunou** [comment]
Got kind of the same use case than @bazineta

**Comment by paulfalgout** [comment]
I'm wondering if we can introduce a small fix for a v3.5 here, but then introduce any breaking fixes in a v4?  

It does seem to me that it is difficult to use `bindRequests` in particular outside of the context of `radioRequests` without introducing some sort of leak, so it seems useful to provide _some_ method for fixing that.. even if the ideal solution is a better breaking one for v4.

**Comment by blikblum** [comment]
> A use case that we encounter in our application is, in short:

Its clear the leak with `bindRequests` and there are no doubt of the need to avoid it. 

I'd like to see a reasonable use case when `bindEvents` leaks

> I'm wondering if we can introduce a small fix for a v3.5 here, but then introduce any breaking fixes in a v4?

I consider this as a bug so a candidate for 3.x. The proposed change (attach a cleanup destroy event handler) should not be breaking change

**Comment by paulfalgout** [comment]
```js
const MyLeakyView = Mn.View.extend({
  rateEvents() {
    const base = this.model.get('base');
    return {
     'change:rate'() {
          this.model.set('currentRate', base + rate);
      }
    };
  },
  setCurrentRate(rateModel) {
    // this undelegate would still be leaky
    // the user would have had to store the results of rateEvents the first time
    // notably mn does not store the results of modelEvents or collectionEvents
    // this.undelegateEvents(this.currentRate, _.result(this, 'rateEvents'));
    this.currentRate = rateModel;
    // this delegate will actually call undelegate, but to what use?
    this.delegateEvents(this.currentRate, _.result(this, 'rateEvents'));
  }
});

const myLeakyView = new MyLeakyView({ baseModel });

const myRatesView = new MyRatesView({ collection });

// Every calling of `setCurrentRate` will orphen handlers until myLeakyView is destroyed
myRatesView.on('childview:select', ({ model }) => {
  myLeakyView.setCurrentRate(rateModel);
});
```

**Comment by blikblum** [comment]
The example should use  `bindEvents`?

**Comment by paulfalgout** [comment]
fixed

**Comment by bazineta** [comment]
In one of our C++ based transactional systems, we have a situation where on shutdown, various objects must be cleaned up in a specific order. In order to deal with that, there's a registry where callers can push a cleanup method (basically anything callable as a `std::function<void()>`, and on shutdown the registry will pop the methods and call them in priority order. Callers can replace or delete handlers if required if their needs change during runtime.

This seems like a similar case, where a solution might be maintaining a per-view collection of tuples, storing the results of `rateEvents` so that during destroy they could be automatically dealt with.

Along those lines, something like that in a generic way might be a handy thing; that is, there are a lot of things that leak if you don't deal with them properly, e.g., jQuery plugins that, if you don't call a 'destroy' method, usually in `onBeforeDetach`, generate leaks. It's not uncommon to forget to do that, since often you're instantiating the plugin in onRender, but neglect to deal with the destroy portion, since it's somewhere distant in the code. If instead you can instantiate and then immediatelyregister a cleanup handler in the same spot, it's harder to make that mistake and easier to see that you've got it right.

I don't want to muddy the waters with that last point; just pointing out that a solution might be a solution for what is a general and very annoying set of problems.

**Comment by blikblum** [comment]
To handle the @paulfalgout use case and keep the same pattern usage for `bindRequests` and `bindEvents` i think the best way is to return a cleanup function.

**Comment by paulfalgout** [comment]
I agree, but that is breaking so I'd leave that to a v4 issue.

In the meantime a `this.unbindEvents(someEntity)` would go a long way to helping solve the problem... probably more so in relation to `this.unbindRequests`

**Comment by paulfalgout** [comment]
We should probably open a new issue or issues regarding returning a destroy method or caching or whatever.
