### ISSUE TITLE
Render collection view children asynchronously

### ISSUE THREAD

**Issue by nlhuykhang** [marionettejs/backbone.marionette#3509]
### Description

I have perf issue with my current project. At some points, one page needs to render up to few thousands views. When this happens, the page hangs up and takes a while to show something on screen. This is to be expected, but I am not in the position to change the business logic so I go on to optimize the code. I find out that I could partially do async rendering with collection view, e.g. render some views normally, and asynchronously for the rest. I override the `addChildView` method to achieve that:

```
addChildView: function addChildView(view, index) {
  this.triggerMethod('before:add:child', this, view);
  this._setupChildView(view, index);

  // Store the child view itself so we can properly remove and/or destroy it later
  if (this._isBuffering) {
    // Add to children, but don't update children's length.
    this.children._add(view);
  } else {
    // increment indices of views after this one
    this._updateIndices(view, true);
    this.children.add(view);
  }

  // this is the change I made
  if (index < 10) {
      this._renderView(view);
  } else {
      setTimeout(() => {
          this._renderView(view);
      }, 100);
  }

  this._attachView(view, index);
  
  this.triggerMethod('add:child', this, view);

  return view;
},
```

With this modification the first 10 item views is rendered normally, the rest is deferred to render after 100ms but their `div` wrapper is still attached normally. The impact on perf is huge. I test with 1000 items, the update version takes 1/3 time to display something on screen and haft time to fully rendered.

But I also think this comes with some drawbacks, the only thing I think of is if I the collection view listen on `add:child`, `before:attach`,  `attach` to manipulate the item view DOM, it will fail to do that because these events are fired prior to actual render. Lucky that my project do not rely on these events, so the update is still good.

My concern is if I miss something that this update affects. I want to know your opinion on this.
### Environment

1. Marionette version: 3.3.1
2. Backbone version: 1.3.3

**Comment by paulfalgout** [comment]
I would first suggest trying `NextCollectionView`  as `CollectionView` is unlikely to change at this point.  2nd if the issue is with the initialization of the collectionview you can render them async by adding the views to a separate collection:
```js
var MyCollectionView = Mn.NextCollectionView() {
  initialize({ collection }) {
    this.collection = new Backbone.Collection();
    var index = 0;
    var intv = setInterval(() => {
      var add = collection.slice(index, index += 100);
      if (!add.length) {
        clearInterval(intv);
        return;
      }
      this.collection.add(add);
     }, 100);
  }
});
```
or something like that.  rather than making the render itself async, add the children async?

**Comment by JSteunou** [comment]
Going to say the same about buffering at the collection level rather than collectionview

**Comment by paulfalgout** [comment]
ok let's reopen if this needs further discussion
