### ISSUE TITLE
problem in extend

### ISSUE THREAD

**Issue by Prasadu112** [marionettejs/backbone.marionette#3510]
I have a problem in loading this program
output:"" Uncaught TypeError: Cannot read property 'extend' of undefined""

here is the code
var BookStoreApp=new Backbone.Marionette.Application();

// creating a controller

var BookStoreController=Backbone.Marionette.Controller.extend({
    displayBooks:function(){
        console.log("I will display books");
    }
});
//creating a router
var BookStoreRouter=Backbone.Marionette.AppRouter.extend({
    controller:BookStoreController,
    appRoutes:{
        "":"displayBooks"
    }
});

//Initialize the application "bookStoreApp"

BookStoreApp.addInitializer(function(){
    var bookStoreController=new BookStoreController();

    var bookStoreRouter=new BookStoreRouter({controller:controller});
    console.log('Message from the addInitializer Methos');  
});

// on the app event

BookStoreApp.on("initialize:after",function(){
    if(Backbone.history){
        Backbone.history.start();
    }
    console.log("message from initialization: after Method");
});

BookStoreApp.start();

**Comment by JSteunou** [comment]
That's *normal* there are not Controller objects anymore (v3)

**Comment by Prasadu112** [comment]
how to solve it then?

**Comment by JSteunou** [comment]
Just do not use Controller anymore. You can create your own kind of Controller by using Object 

Also see https://marionettejs.com/docs/v3.0.0/upgrade.html and the upgrade tool
