### ISSUE TITLE
App.addRegions({...}); used to work in v2.x, not working in v3.x

### ISSUE THREAD

**Issue by singhvijayy** [marionettejs/backbone.marionette#3517]
In backbone.marionette.js v2.x, I could write -

```
var App = new Mn.Application();

App.addRegions({
    region1: "#divname",
   ...
});
```

And, I could simply say -
 ```
App.region1.show({...});
``` 

But now in v3.x, this is no longer the case. 

Please add this functionality in v3.x, it allows ```.show()``` to be conveniently used anywhere!

Thanks.

**Comment by paulfalgout** [comment]
RegionManager was removed from Application in v3 after being deprecated in 2014 https://github.com/marionettejs/backbone.marionette/pull/2069
Here's more information about it's removal https://github.com/marionettejs/backbone.marionette/issues/2129

Application now has a single region so a layout can be added to handle multiple regions.

Regions are no longer attached by name to the parent object for a multitude of reasons, but keeping regions behind a `getRegion` allows for performance improvements that cannot be done if regions are immediately available after initialization.

But if you really want the functionality you've described you can add it
https://jsfiddle.net/ozhcqmuo/
```js
const App = Mn.Application.extend({
  region: '#main',
  regions: {
     foo: '#foo',
     bar: '#bar'
  },
  _setRegions() {
    const view = new Mn.View({ el: '#main' });
    
    this.showView(view, { replaceElement: true });
    
    const regions = _.result(this, 'regions');
    view.addRegions(regions);
    
    _.each(regions, (region, regionName) => {
      this[regionName] = view.getRegion(regionName);
    });
  },
  initialize() {
    this._setRegions();
  }
});
```
for
```html
<div id="main">
  <div id="foo"></div>
  <div id="bar"></div>
</div>
```

Easy to add the API you want without screwing up the code base doing so.
