### ISSUE TITLE
model/collection events bound in initialize are removed in 3.5.0

### ISSUE THREAD

**Issue by wvankuipers** [marionettejs/backbone.marionette#3527]
### Description

When using the sync event on a collection there will be race condition caused by [this line](https://github.com/marionettejs/backbone.marionette/blob/af1e5f69f9b109dacbb82b98341e1f8afbccf7d2/src/common/bind-events.js#L73)

As the binding is not yet there (due to the fact that the sync could be in progress I guess?) the stopListening method is triggered incorrectly and when the sync is completed the event will not get triggered. 

### Expected behavior
Example code:
```
    this.listenTo(
        Collection,
        'sync',
        this.handleSync
    );
```

The method `this.handleSync` should be triggered when the sync is completed

### Actual behavior

If the call for the sync takes to long `this.handleSync` will never be fired. Future sync events will also be ignored. Adding a timeout will fix this:

```
setTimeout(() => {
      this.listenTo(
        Collection,
        'sync',
        this.handleSync
    );
}, TIMER_VALUE_LARGER_THAN_REQUEST_TIMEOUT);
```

Removing the [problematic line](https://github.com/marionettejs/backbone.marionette/blob/af1e5f69f9b109dacbb82b98341e1f8afbccf7d2/src/common/bind-events.js#L73) will also resolve the issue.

### Environment

1. Marionette version: 3.5.0
2. Backbone version: 1.3.3

**Comment by paulfalgout** [comment]
Yep ok.  legit bug.  FWIW it is unrelated to `sync`  if you want to get around this in a current project use `collectionEvents: {}` and `modelEvents: {}` if any listener is added in `initialize`

What is happening here is that `delegateEntityEvents` is happening after the `initialize` as it should, and the first thing delegate does is undelegate.. and previously to v3.5 calling undelegate with no bindings was a noop.. but now it removes any events added in `initialize`

Actually for your use case @wvankuipers it probably makes sense to use `collectionEvents` anyhow.  Try this:
```js
initialize: function() {
//    this.listenTo(
//        Collection,
//        'sync',
//        this.handleSync
//   );
},
collectionEvents: {
  'sync': 'handleSync'
}
```

**Comment by attenzione** [comment]
@JSteunou maybe it's better to have opened issue, while fix isn't released? I almost created the same issue :)

**Comment by paulfalgout** [comment]
Github general pattern is to close issue on merge

**Comment by JSteunou** [comment]
@attenzione gitlab auto close related issue (base on title or description matching things like "fixes #XXXX" ) on merge.

**Comment by attenzione** [comment]
yeah, I know, we use same pattern :|
