### ISSUE TITLE
Access view in viewComparator

### ISSUE THREAD

**Issue by DonJulio666** [marionettejs/backbone.marionette#3546]
### Description

I have a question regarding sorting collection view items. I'm using the viewComparator to sort the values in the collection which works very well. But we have "enum" Values which are resolved in an human readable format in our handelbar template via an helper. In this case the user gets an wrong sorted table (for him). So for example in the model we have an attribute with value "X" but in the table row "A" is displayed for the value "X".

### Expected behavior

A way to access the view in the viewComparator to get the viewed values for the compare function

### Environment

1. Marionette version:  3.2.0
2. Backbone version: 1.3.3

**Comment by JSteunou** [comment]
Why not having a computed field value in the model, or another model in the view (state model) for the *displaying field* in order to sort on it and using it inside your template? (thus removing the need of an hbs helper)

**Comment by paulfalgout** [comment]
`viewComparator` of `NextCollectionView` which will be the v4 `CollectionView` iterates over the views instead of the model for reasons similar to this.

**Comment by blikblum** [comment]
Try NextCollectionView. Afaik it passes view instance to comparator

**Comment by JSteunou** [comment]
Or what they just said, better idea :D
