### ISSUE TITLE
 Behavior ui hash conflicts with that of the parent View, which contradicts the docs

### ISSUE THREAD

**Issue by voltel** [marionettejs/backbone.marionette#3562]
## 1. The problem
[In the docs](https://marionettejs.com/docs/master/marionette.behavior.html#using-ui) there's a statement and a ["live example"](https://jsfiddle.net/marionettejs/xoy56gpv/) that are contradictory to each other:
**The statement:** 
> If your ui keys clash with keys on the attached view, references within the behavior will always use the definition on the behavior itself.

**The reality:**
If the ui hash on the Behavior clashes with the ui hash on the View for some keys, the latter (the View) takes precedence, as if no Behavior's definition existed. It happens silently, w/o errors or warnings. 
To clarify the problem [I forked a JSFiddle of the example provided ](https://jsfiddle.net/voltel/kn4ajrw2/)and played with it - please, use it to better understand the problem I encountered. 

##  2. A summary of the proposed solution
- Change the docs to align with current functionality, or
- Trigger warnings/errors at ui keys (names) clashes, or
- Change implementation of the inheritance to provide Behavior's ui hash precedence.

##  3. A description of how this solution solves the problem, in more detail than item #2
None
## 4. Any additional discussion on possible problems this might introduce, questions that you have related to the changes, etc.
None 

### Expected behavior
That which is described in the docs (see the statement above). 

I would be happy to find the formalized specification of the current Marionette API (with functions/methods, types and description of parameters they take and expected results). The PDF of such document would also be of help. 
The [docs](https://marionettejs.com/docs/current/ ) with "live examples" are a great way to learn, but more formal documents would be of great help. I'm new to the framework, and maybe I just overlooked some resources, so please forgive me my ignorance in this case (would still appreciate a link). 

### Actual behavior
With name clashes, the ui hash of the Behavior is ignored. As a result, the events bound in the Behavior never fire.

> If possible, please create a small demo that demonstrates the issue.

Here it goes: [https://jsfiddle.net/voltel/kn4ajrw2/](https://jsfiddle.net/voltel/kn4ajrw2/)

### Environment
1. Marionette version: 3.5.1
2. Backbone version: 1.3.3

**Comment by paulfalgout** [comment]
It looks like this behavior was specifically addressed and changed in v3, but the documentation was not aligned to match:  https://github.com/marionettejs/backbone.marionette/issues/2266 and https://github.com/marionettejs/backbone.marionette/pull/2308

**Comment by voltel** [comment]
Thanks a lot! Now I understand better why it happens the way it happens. But, may I cautiously suggest that threre's probably a better way. 
I think, there should be **a mechanism of mapping ui elements** of the parent View to ui elements used in the Behavior. 
This behavior would be similar to a plugin in the way that once written, the Behavior hardly ever has to be looked into. I'd like to have an opportunity to assign two or three different Behaviors to the same View's ui element. 
For example, one Behavior may close the modal window/form when some button is clicked (e.g., of class "close"), and the other Behavior may log some information exactly on pressing the same button. If internally these Behaviors use different ui keys (e.g. 'btn_close' and 'btn_exit'), we will have to duplicate these keys/names in the parent View's ui in order to assign Behaviors to the same element on the page - which is not optimal. 
So my suggestion is to provide a built in mechanism of mapping ui hashes if needed. To illustrate the idea, I created [a little example here](https://jsfiddle.net/voltel/8pjjwvxo/). Maybe, this idea is worth a consideration? Please, share your opinion.

```JavaScript
  mapUI: function(options) {
  	// unless specified in parent View, the defaults will be taken from Behavior's ui hash
    if (options.uiMap) {
    	var parent_view_ui_key, parent_view_ui_selector;
    	for (key in options.uiMap) {
      	if (key in this.ui) {
          parent_view_ui_key = options.uiMap[key].substr(4); // taking away "@ui." prefis
          parent_view_ui_selector = this.view.ui[parent_view_ui_key];
          this.ui[key] = parent_view_ui_selector;      
        }//endif				
      }//endfor			
    };
  }
```

By the way, I was intrigued by the comments in #2308 where @stephanebachelier volunteered to align the docs.

**Comment by paulfalgout** [comment]
In general I'm resistive to adding to the API when the implementation can be added via public API as easily as you've shown here.  Would work well as a 3rd party plugin as well.
```js
import { Behavior } from 'backbone.marionette';
import uiMap from 'mn-behavior-uimap';
// Add uiMap to all behaviors
Behavior.prototype.uiMap = uiMap;
```

However in a possible alternate option it might be reasonable to suggest something similar to [`mixinTemplateContext`](https://github.com/marionettejs/backbone.marionette/blob/next/src/mixins/template-render.js#L35):
```js
constructor(options) {
  ...
  this.ui = this.mixinViewUI();
  ...
},
// Override this to determine how the behavior ui hash is built
mixinViewUI() {
  return _.extend({}, _.result(this, 'ui'), _.result(view, 'ui'));
}
```
