### ISSUE TITLE
CollectionView doesn't show new Views added with addChildView after some of the Views .destroy() themselves

### ISSUE THREAD

**Issue by voltel** [marionettejs/backbone.marionette#3563]
### 1. The problem 
I was playing [in JSFiddle ](https://jsfiddle.net/voltel/yw8hkp1o/) with some Radio notification scenarios, where CollectionView would comprise individual Views with messages. This CollectionView is not linked to Backbone.Collection, [the approach described here](https://marionettejs.com/docs/master/marionette.collectionviewadvanced.html#collectionviews-addchildview). I wanted individual messages to dismiss themselves either after pressing the &times; button of class ".close", or automatically, after some time delay (5 sec). 
**The problem** presented itself in this way:  when the view is destroying itself with `` self.destroy(); ``, the CollectionView stops showing newly added child views, though they're obviously added to the collection since ``CollectionView.length `` property is changing. I guess, the ``self.destroy();`` doesn't initiate a proper removal of a View from its parent CollectionView. Maybe, it's a feature (and then, please accept my apologies for bothering you); otherwise it's a bug or suggestion for improvement. My guess is supported by the solution I tried, when triggering the event and bubbling it to the parent CollectionView, I first manually remove the child View from the CollectionView by `` this.removeChildView(childView); ``, and only then destroy the child View with ``  childView.destroy(); ``.

### 2. A summary of the proposed solution
To ensure, that destroying the child View with ``.destroy()`` also safely/properly removes it from the parent CollectionView, including the cases when CollectionView is not based upon the Backbone.Collection of Models (added manually with `` .addChildView() `` method on the CollectionView, see below). 
``` JavaScript
        // manually populate the CollectionView of the Region 
        let viewMessages = this.getRegion('messages').currentView;
        viewMessages.addChildView(view, 0); 
```
### 3. A description of how this solution solves the problem, in more detail than item #2
When commenting out the `` self.destroy(); `` line of code and triggering the event that bubbles up to the parent CollectionView (`` self.trigger('dismiss', self); ``), the handler manually removes the child view from the collection and destroys it: 
``` JavaScript 
/**
 * This CollectionView is populated by ViewMessage objects created in another place 
 * (they are not linked to Backbone.Collection). This is a container view for 
 * individual ViewMessage objects, each of which contains some notifinacation/message
 */
const ViewMessages = Mn.CollectionView.extend({
    childViewEvents: {
        'dismiss' : 'dismissChildView',
    },
    dismissChildView(childView) {
        //console.log("Collection length before: " + this.children.length);
        this.removeChildView(childView);
        //console.log("Collection length after: " + this.children.length);
        childView.destroy();
    }
});
```
After this procedure of child view removal/destroy, the newly added child views are properly displayed when added to the CollectionView (as opposed to the problem, when they don't show up).

### 4. Any additional discussion on possible problems this might introduce, questions that you have related to the changes, etc.
None

### Expected behavior
To see the expected behavior, please comment out line with `` self.destroy(); `` in ViewMessage::dismissMessage()  method. As a result, after the first child views are destroyed, and the container is empty, one can easily add new notification views to the container. And for this, one doesn't have to `` .removeChildView() `` manually, but may rely that the `` View.destroy() `` will take care of its containing parent CollectionView. 

### Actual behavior
To see the "problematic" behavior, please [visit the JSFiddle here ](https://jsfiddle.net/voltel/yw8hkp1o/)and make sure that the line of code where the view is attempting to destroy itself in uncommented (functioning) `` self.destroy(); ``. This is when the problem introduces itself. The first one-two-three notifications are shown fine, but after they disappear (clicked the ".close" button or after the 5 sec delay), the newly added messages/notifications Views are not displayed at all. 

If possible, please create a small demo that demonstrates the issue.
[https://jsfiddle.net/voltel/yw8hkp1o/](https://jsfiddle.net/voltel/yw8hkp1o/)

### Environment

1. Marionette version: 3.5.1
2. Backbone version: 1.3.3
3. Additional build tools, etc: bootstrap.css v.4.0, animate.css v.3.5.2

**Comment by paulfalgout** [comment]
Use `NextCollectionView`  It is replacing `CollectionView` in v4 which will have a release candidate shortly.  It solves many of the edge case problems of `CollectionView` that could not be solved without breaking changes.
