### ISSUE TITLE
Rename BackboneViewMixin to Events

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3567]
https://github.com/marionettejs/backbone.marionette/pull/3566#issuecomment-350265001
tl;dr
It is a mixin for `triggerMethod`.  I doubt that will change. `Marionette.Events` is one of the APIs that will be necessary to reduce or remove dependency on backbone.

**Comment by taburetkin** [comment]
just want to share
when i work on marionette google maps i faced with some trouble
`Backbone.Events` has deprecated `unbind` and `bind` methods which are conflicted with google event system, while `on` and `off` are not.
so, if there will be changes in Marionette.Event maybe its possible to skip deprecated methods of Backbone.Event ))

**Comment by blikblum** [comment]
The initial idea of BackboneViewMixin is to add all necessary methods to support Backbone.View instances without checks inside Mn code. Basically two methods were being specially handled: `triggerMethod` and `destroy`. The former was moved to BackboneViewMixin. The `destroy` move, which would allow to remove destroyView interface,  was not done.

Assuming that in v5 we will not support Backbone.View i'm fine with the rename but i still don't think changing trigger behavior is a good idea.
