### ISSUE TITLE
Remove support for vanilla Backbone.View

### ISSUE THREAD

**Issue by blikblum** [marionettejs/backbone.marionette#3572]
### Description

 1. Currently Mn v3 supports vanilla Backbone.View out of box and v4 supports though BackboneViewMixin

### Expected behavior

Do not support vanilla Backbone.View in next release and remove related code

Related #3567

**Comment by paulfalgout** [comment]
I am unsure about this.  A Backbone.View does so very little that it doesn't seem impossible to support it.. There are plenty of people who use Backgrid or other Bb related views that this would be a major shift for our current base.  But what does it mean to "support" a view with Mn?  Currently we make any Bb View feel and act like a Marionette View.  That may not be necessary.  I would also be interested in some sort of external plugin possibly that could continue support for a while and at least allow someone to potentially keep up that plugin if they needed it across additional versions.

**Comment by blikblum** [comment]
> There are plenty of people who use Backgrid or other Bb related views that this would be a major shift for our current base

There are two solutions:

- A High Order Marionette View could be used as proxy for BB views

- Make BackboneMixinView have all necessary code to support a BB View

> Currently we make any Bb View feel and act like a Marionette View. That may not be necessary

What part? `supportsViewLifeCycle`?

**Comment by paulfalgout** [comment]
Yeah essentially stop triggering additional events on the view.. if they want `onRender` put it in their `render` and if they want `onDestroy` make a `destroy` and we can do essentially `(view.destroy || view.remove)();`
