### ISSUE TITLE
Triggers do not pass event arguments

### ISSUE THREAD

**Issue by taburetkin** [marionettejs/backbone.marionette#3579]
### Description

 triggers do not pass events arguments

### Expected behavior

i think all arguments should be passed to the handler

### Actual behavior

handler receives two arguments: view instance and event object

### codepen
here is an illustration, please check console log
https://codepen.io/dimatabu/pen/godBMm

after pushing the button i am triggering custom event with some addition arguments and trying to handle it in the view
i am using 3 methods
1 - through events hash, 
2 - through native jQuery on handler
3 - via triggers in the view

1 and 2 are working as expected, handlers called with all passed arguments
but in triggers approach any additional arguments of the event is missing

### Environment

1. Marionette version: v3.5.1
2. Backbone version: 1.3.1

**Comment by paulfalgout** [comment]
hmm @marionettejs/marionette-core 

I think this'd just be an `...args` in the `buildViewTrigger` 

I dunno if it is worth the perf to make it consistent TBH.

**Comment by blikblum** [comment]
I would go for consistency. The performance hit of triggers comes from its initialization. We should not have any perf impact with the change

**Comment by bazineta** [comment]
I also think that consistency should be favored in this case.
