### ISSUE TITLE
Roll an alpha v4 release

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3587]
I think aside from https://github.com/marionettejs/backbone.marionette/pull/3582 we could roll and alpha release for v4 to start preliminary testing.

I'm still knee deep in doc changes for v4 and we'll want a proper blog post for a release candidate, but a pre-rc status release would be good so that the extracted libraries could also update with an `npm`able v4 lib.

@marionettejs/marionette-core other than #3582 getting in, anyone object?

**Comment by JSteunou** [comment]
No objection ;)

**Comment by blikblum** [comment]
Time to do it?

**Comment by paulfalgout** [comment]
Yeah.. I am 98% done with an overly large doc update. I will try and have it this week.. Not that the alpha must wait, but that is what I was waiting on.

**Comment by paulfalgout** [comment]
`npm install backbone.marionette@alpha` :tada:
