### ISSUE TITLE
addChildView should support an array of views

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3593]
Currently `addChildView` only handles a single view.  We could modify this to add multiple views which could be done more performant internally and with an easier API.

**Comment by taburetkin** [comment]
```
addChildViews(children = []){

	if (!children.length) { return; }

	let awaitingRender = false;

	while(items.length){

		let item = items.shift();

		if (!_.isArray(args)) {
			args = [args, { index: 0 }];
		}

		//supporting old style addChildView
		let [ view, index, options = {} ] = args;

		if (_.isObject(index)) {
			options = index;			
		} else if(index != null && !('index' in options)) {
			options.index = index;
		}

		options.preventRender = !!items.length;

		if (!isView(view)) { continue; }

		this.addChildView(view, options);
		awaitingRender = options.preventRender;

	}

	if (awaitingRender) {
		this.sort();
	}

}
```

with this implementation i think that
this one
```
this.addChildView( view1, 0 )
this.addChildView( view2, 0 )
this.addChildView( view3, 0 )
```
will be equal to this
```
this.addChildViews([ 
 [view1 , 0],
 [view2 , 0],
 [view3 , 0],
]);
```

**Comment by paulfalgout** [comment]
this.addChildViews([ 
 [view1 , 3],
 [view2 , 2],
 [view3 , 1],
]);

**Comment by taburetkin** [comment]
will be equal to this
```
this.addChildView(view1, 3)
this.addChildView(view2, 2)
this.addChildView(view3, 1)
```
main thing that they both will behave the same

**Comment by taburetkin** [comment]
and in my opinion its bad when you add views by one million years
and now, when the future is almost here and you can add them in one go
you suddenly found that behavior is different, not as usual...
its just a thoughts

**Comment by paulfalgout** [comment]
In that case
```
this.addChildView(view1, 3, { preventRender: true });
this.addChildView(view2, 2, { preventRender: true });
this.addChildView(view3, 1);
```
is pretty good without needing to overcomplicate the library.

**Comment by taburetkin** [comment]
and the one more thing
if there will be own indexer implemented as i offer
then individual indexes became more usefull because with own indexer you can order your views as you wish

**Comment by taburetkin** [comment]
if this is pretty good
```
this.addChildView(view1, 3, { preventRender: true });
this.addChildView(view2, 2, { preventRender: true });
this.addChildView(view3, 1);
```
why you start this issue at all?

i thought that its just for not to write `this.addChildView` 3 times
and in some cases when you render custom views by some automated process you going to implement some kind of `addChildViews` which do it for you.
i mean
```
for(...){ this.addChildView(viewX) }
```
didn't you?

**Comment by taburetkin** [comment]
> ```js
> // Consider a view that already contains 5 children. What will this do?
> this.addChildViews([ 
>  [view1 , 3],
>  [view2 , 2],
>  [view3 , 1],
> ]);
> ```
> 
> I think it will do this:
> 
> * child
> * view 3
> * child
> * view2
> * child
> * view1
> * child
> * child

i think that it will do exactly what does calling 3 times `addChildView` with same order and parameters.

**Comment by paulfalgout** [comment]
Initially this issue was opened because `addChildView` always sorted and filtered (and rendered) for each view. https://github.com/blikblum/backbone.marionette/commit/74450024ffd539cd085c13129312c471ecb8b146 changed that and that commit mentions the possibility of this issue no longer being needed. Then the `preventRender` flag really removed any further concern.

Previously adding multiple views was a perf concern, now that doesn't seem to be true.

I think there's a pretty reasonable argument that this isn't needed. After all:
```js
_.each(
[ 
 [view1 , 3],
 [view2 , 2],
 [view3 , 1],
],
(view, index) => { myColView.addChildView(view, { index, preventRender: true }); }
);
myColView.sort();
```

**Comment by paulfalgout** [comment]
> i think that it will do exactly what does calling 3 times addChildView with same order and parameters.

Indexes should not be fluid within a single function call.  It's ok for three separate calls, but in a single call, 3 should be 3 and not 5.

**Comment by taburetkin** [comment]
you are right about reasons of opening issue
rendering and sorting after each `addChildView` that was unexpected for me when i found that. thats why i started to do something about it.

ok.
thing you demonstrating with `_.each(...` is some kind of `addChildViews`
if you will copy this chunk of code from view to view, i believe its a reason to convert it to a method.
at least i will do that in my views.

i believe that current indexing implementation is broken
at least i do not understand how it works and why i should think about it each time: 'hm.. where appear my just added custom view?'

with own indexer (which is faster than `collection.indexOf(model) as you remember`) its possible to determine the priority of custom view
what should appear first indexes is the same, model view or custom one?
it can be easily done with options: say, `customsFirst: true | false`
and you always will know when your customs should appear
if you say it shoud be on the second possition then it will be there
at this moment you can not guarantee that in all cases

**Comment by paulfalgout** [comment]
An excellent case for making a `IndexedCollectionView` plugin to handle that specific use case.

**Comment by taburetkin** [comment]
:-)
so, now you think that there is no need to make `addChildViews` at all because now this can be done with simple `_.each(..` ?
and i can expect that in future releases `addChildViews` will not be provided?
i am asking because my extension lib already has it and now i am thinking that i should 
1) rename it for avoiding future conflicts
2) leave it because it never appear in marionette
3) or persuade you to add it to marionette (and as i undestand this will not happen :) )

**Comment by paulfalgout** [comment]
This method doesn't seem to be adding unique value that can't be accomplished with the new `preventRender` so for now we'll close this unless someone shows interest.
