### ISSUE TITLE
documentation on getOptions

### ISSUE THREAD

**Issue by birbilis** [marionettejs/backbone.marionette#3596]
> getOption will fall back to the value defined on the instance of the same name if not defined in the options. 

https://marionettejs.com/docs/basics.html

I'm a bit confused with the phrasing here, did it mean to say "to the value of the same name defined on the instance"? In that case, I'd suggest rephrasing it so

Or is it wrong there and it should be instead "to the value of the same name defined on the class" which sounds more likely?

**Comment by birbilis** [comment]
btw, note there is also documentation on getOptions and mergeOptions at
https://marionettejs.com/docs/marionette.functions.html
(I think they're listed in reverse order there, aka mergeOptions first, then getOptions)

**Comment by taburetkin** [comment]
```
let View = Mn.View.extend({
   myProperty: 'prototype value',
   initialize(){
      this.myProperty = 'instance value'
   }
});

let view = new View();
console.log(view.getOption('myProperty')); // will output in the console `instance property`

```

**Comment by birbilis** [comment]
I'd expect it to output 'instance value' (where does 'instance property' come from?). Anyway, please read the question text above again while reading the sample code in that documentation URL. I mean the text is speaking about falling back to instance property but the sample has only code that would hint to falling back to class (prototype) property value

**Comment by birbilis** [comment]
copying that code sample below:

````
var Mn = require('backbone.marionette');

var MyView = Mn.View.extend({
  className: function() {
    var defaultClass = this.getOption('defaultClass');
    var extraClasses = this.getOption('extraClasses');
    return [defaultClass, extraClasses].join(' ');
  },
  defaultClass: 'table'
});

var myView = new MyView({
  model: new MyModel(),
  extraClasses: 'table-striped'
});
````

**Comment by birbilis** [comment]
and in any case, I think the text "value defined on the instance of the same name if not " need rephrasing for better understanding

**Comment by taburetkin** [comment]
sorry for that `instance property`, i don't know what about i am thinking when i wrote that comment :)

**Comment by paulfalgout** [comment]
It is the value defined on the instance, though defining things on the class become instance values upon instantiation so class definition is also true.

```js
const View = Mn.View.extend({
   classVal: 'class value',
   initialize(){
      this.instanceVal = 'instance value'
   }
});
const view = new View({ optVal: 'option value'});

view.getOption('instanceVal'); // instance value
view.getOption('classVal'); // class value
view.getOption('optVal'); // option value

const view2 = new View({ instanceVal: 'foo', classVal: 'bar', optVal: 'baz' });
view.getOption('instanceVal'); // foo
view.getOption('classVal'); // bar
view.getOption('optVal'); // baz
```

**Comment by birbilis** [comment]
this is much nicer sample I think since it make it clear that instance values would be values defined at initialize() - I didn't understand (in the context of that doc sample) how they would be defined at new since one was defining options there instead. Anyway that phrase needs to say "to the value of the same name defined on" which is more clear (and could say ...on the instance or class and maybe have that better sample)

another thing is why have extra doc and samples for getOptions/mergeOptions if they're already defined in functions. Maybe just point to some bookmark in the functions page, but should first review I guess the text/samples in that page if it's ok or too complex for the context of basics (which would justify having separate / more advanced text and samples there)

**Comment by paulfalgout** [comment]
on the second point.. I'm working on the docs for v4 right now and I've done what you're suggesting.  We have a lot of duplication in the docs right now, and I'm hoping to reduce it quite a bit.  I will take a look at the language there and the code sample and see if what I've got needs to be clarified re: your suggestion as well.  Thanks!  Better docs on the way soon.

**Comment by birbilis** [comment]
thanks, have also done a pull request for some other sample code fix (if I understood that doc part right) and have submitted at least one more issue (for now) on the current docs
