### ISSUE TITLE
Template doc

### ISSUE THREAD

**Issue by birbilis** [marionettejs/backbone.marionette#3599]
at
https://marionettejs.com/docs/v3.0.0/template.html 
it writes:

> Model/Collection Rendering Rules
> 
> Marionette uses a simple method to determine whether to make a model or collection available to the template:
> - If view.model is set, *the attributes from model*
> - If view.model is not set, but view.collection is, set items to the individual items in the collection
> - If neither are set, an empty object is used
> The result of this is mixed into the templateContext object and made available to your template. Using this means you can setup a wrapper View that can act on collectionEvents but will render its model attribute - if your model has *and* items attribute then that will always be used.

the italics ones need rephrasing I think:
1) where is the verb in "the attributes from model"? Did it mean to say "... are used"?
2) "and" should be "an"

**Comment by birbilis** [comment]
strange, I see this is a 3.0.0 url, not sure how I had ended up there, possible have been revised by now

**Comment by paulfalgout** [comment]
rewritten in v4 docs
