### ISSUE TITLE
Renderer doc mentions TemplateCache object without link

### ISSUE THREAD

**Issue by birbilis** [marionettejs/backbone.marionette#3600]
https://marionettejs.com/docs/v3.0.0/marionette.renderer.html
writes:

> By default, the renderer will take a jQuery selector object as the first parameter, and a JSON data object as the optional second parameter. It then uses the TemplateCache to load the template by the specified selector, and renders the template with the data provided (if any) using underscore templates.
>
> If you wish to override the way the template is loaded, see the TemplateCache object.

those two TemplateCache mentions should point to https://marionettejs.com/docs/v3.0.0/marionette.templatecache.html but they're not links

btw, at that specific page if I press Impove this page I'm taken to Github, but this time (it worked at other page earlier today) I can't edit the file. Also if I choose there another branch as GitHub suggests, I immediately get a 404 error

**Comment by scott-w** [comment]
Hey, thanks for filing these issues. As you’ve seen, some of the issues have been fixed and are waiting on a new build for the website.

If you haven’t already, pop into the Gitter channel and the guys there may be better able to help with getting the fixes live.

**Comment by paulfalgout** [comment]
This is handled in the v4 docs
