### ISSUE TITLE
Should setElement throw an error on already rendered views?

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3606]
Whether it is `View` or `CollectionView`, both have [`setElement`](http://backbonejs.org/#View-setElement) from backbone which allows the user to change the `el` of the view.  In backbone, view's are barebones, so you're on your own to deal with the caveats of changing the view's `el`.  In Marionette, I don't know what recourse you have.  

If you call `setElement` on any rendered view that has children (either in a `region` or in the `children` of a `CollectionView`) the child views won't understand or be aware of the change to the parent.. there's no detaching or clean up if with a subsequent render as clean up occurs on the wrong `el` and the view no longer has access to the previous one.  

Additionally if you've used `replaceElement` on a region you might really be in trouble if the view dropped that `el` without removing listeners.  

I honestly don't know how to successfully call `setElement` on a Mn view after it is rendered.  It seems to me we either should throw and error, or possibly destroy children and detach the view's current el as the first thing `setElement` does if the view is already rendered.

Thoughts?

**Comment by paulfalgout** [comment]
I'm leaning toward having `setElement` doing more of the work of the constructor.  `setElement` is essentially reconstructing an existing view, so to fully support it, Marionette would likely need to properly clean up existing children and reinstantiate regions, children, behaviors and empty regions as if the view was just constructed.   For at least behaviors, instantiating them after the Bb `setElement`, but before the view `initialize` will allow for the behavior to be aware of the view's `el` at instantiation which would be a plus although not necessary, but then the behaviors `onInitialize` event becomes less useful...   However, even if `setElement` worked flawlessly, I don't see why at this point it isn't just as reasonable (and possibly cheaper) to simply instantiate a new view.  So many possible caveats...

**Comment by blikblum** [comment]
I would not support changing el on the fly through setElement, as you said, is better to create a new view instance.

I would just document it instead of throwing an error

**Comment by ribeiropaulor** [comment]
I agree with @blikblum .
