### ISSUE TITLE
CollectionView does not consider the childViewContainer when rendering empty

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3610]
For v4 `CollectionView` can render children inside of a selector on a template.

However the `emptyRegion` still uses the `el` of the view and not the container.

This is complicated as the empty region is created once at instantiation and there's not a reasonable way to currently update the selector on render.

**Comment by adriantrunzo** [comment]
We just ran into this issue while rendering filterable tables:

```
const MyTableView = CollectionView.extend({
  tagName: 'table',

  childView: MyRowView,
  childViewOptions: { ... },
  childViewContainer: 'tbody',

  emptyView: MyEmptyView,
  ...
})
```

If a particular filter hides all children, the emptyView will show at the `el` level and wipe out the `childViewContainer`. Thus, after another call to `filter()` that results in views to be shown, the collection view cannot actually attach the children and the view is just blank.

Can the empty region just use the `childViewContainer` element if it is specified? That seems the most logical behavior. Further flexibility could be achieved by allowing for an `emptyViewContainer` property that would be the empty region `el`. Similar to `childViewOptions` and `emptyViewOptions`, if `emptyViewContainer` is not defined, the empty region would fallback to `childViewContainer` and then to the view `el`.

I am happy to help out with a pull request if we can agree on a good solution.

**Comment by adriantrunzo** [comment]
Could CollectionView just throw an error in that case? When would it be useful to nest those containers?

**Comment by paulfalgout** [comment]
nested containers will increase the complexity and performance of the collectionview.  I can't see a good use case for it that couldn't be handled better by a regular view/region and collectionview.  So I don't see the point of an error either if `emptyViewContainer` !== `childViewContainer` there are significant problems as we have currently.

**Comment by avipinto** [comment]
Till 4.0.1 is out, "fixed" this bug the following way:
```   emptyView: function() {
    if (!this.fixedEmptyOnChildViewContainer) {
            this.fixedEmptyOnChildViewContainer = true;
            this._emptyRegion = new Mn.Region({ el: this.$(this.childViewContainer).get(0), replaceElement: false });
            this._emptyRegion._parentView = this;
        }
        return EmptyView;//my regular emptyView
    },
```
