### ISSUE TITLE
v4 alpha issues

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3613]
@marionettejs/marionette-core 

Initially trying v4 I'm seeing two main complications.  
1. `import Marionette from 'backbone.marionette';` no longer works.  If you need this same functionality it must be `import * as Marionette from 'backbone.marionette';`
  Maybe that's as best as we can do to keep it ES6, but it's a pain none-the-less for older code bases
2. Removing `Mn.Object` for `Mn.MnObject` breaks a few of my other marionette libs that haven't updated yet.  I don't see a good work around for this other than those other libs updating.  In the interest of allowing for a transition I think we should export `MnObject` as `Object` scheduled for removal in v5.

**Comment by JSteunou** [comment]
1. why not export a default that would be the all Marionette object ?
2. Either v4 is fully breaking or just transitioning and maybe we should export both name

**Comment by paulfalgout** [comment]
@blikblum regarding changing the export https://github.com/marionettejs/backbone.marionette/pull/3447/files#diff-ca086dc93aa3edbb8b8c7b8fb37f1407R9
Do see it as a big issue to export everything also as the `default` for v4 so that libraries can transition over?  Simple libs that rely on Marionette break because of this change.  I think a transition release will help with upgrading.

**Comment by blikblum** [comment]
Exporting as default kills any chance of treeshaking but its not working anyway due to how the classes are defined (extending the prototype).

So although is pretty [easy](https://github.com/blikblum/marionette.routing/commit/07e69d00bb4b9fb4778335fd4632208a2bd047c4) the migration, i dont see big problems on doing it

**Comment by paulfalgout** [comment]
Good deal.. yeah I'm unsure if treeshaking is all that useful for Marionette anyhow.  I suppose you could shake out `CollectionView` if you had a particular use case.. or maybe `MnObject` but almost everything else is a dependency of everything else.

And I agree it is an easy transition.. my main concern is for people who have dependencies that are slow to update.  They may not break on any of the other APIs in the upgrade, but not exporting a default is _guaranteed_ pretty much to break everything currently existing.  So I'm hopeful that re-adding the default export only for v4 (and exporting `Object` on the default) will make that transition easier.

**Comment by umeboshi2** [comment]
Adding events to views will be somewhat troublesome for my code.  Thanks for the heads up! :)

**Comment by paulfalgout** [comment]
I should personally be confident in `alpha` by next week after a broad test on my live project.  Afterwards I'll attempt to move forward with a `beta` release along with updating the externalized libs, so that this can go more public.

**Comment by paulfalgout** [comment]
All tests and manual qa passed.  I'm traveling internationally tomorrow, but I'll pick this up next week.  Doesn't seem like there's much to do other than a bit more docs and the import business
