### ISSUE TITLE
Does marionette support OOPIF?

### ISSUE THREAD

**Issue by Swordyjohn** [marionettejs/backbone.marionette#3626]
I am attempting to get the html of an iframe with Puppeteer (specifically a reCaptcha iframe) and I cannot access it since out of process iframes are not supported, is this supported in marionette?

**Comment by paulfalgout** [comment]
I think you want the library https://firefox-source-docs.mozilla.org/testing/marionette/marionette/index.html  This is a javascript frontend framework.
