### ISSUE TITLE
Error: "Cannot read property 'idAttribute' of undefined" in collection

### ISSUE THREAD

**Issue by avasuro** [marionettejs/backbone.marionette#3627]
--------------------------------------------------------------------------------------------------------------------------------------
### Sorry, just noticed that it's a Backbone bug, so this issue is not relevant to Marionette.
--------------------------------------------------------------------------------------------------------------------------------------

### Description

 1. If I create new collection class, that extends Backbone.Collection, and define it's "model" property as a function which returns instantiated model - then on collection constructed error "Cannot read property 'idAttribute' of undefined" is thrown. That's because class methods has no property "prototype", which is used in Backbone.Collection.prototype.modelId method.
 2. Check that prototype exists in model constructor

### Expected behavior

No error thrown if collection has property "model" defined as class method.

### Actual behavior

Error "Cannot read property 'idAttribute' of undefined" thrown.
Here is an example: https://jsfiddle.net/e1ybjmw3/

### Environment

1. Marionette version: 4.0.0
2. Backbone version: 1.3.3
3. Additional build tools, etc: no build tools (that's important, because if babel used all works fine)

**Comment by paulfalgout** [comment]
ayep  backbone

**Comment by paulfalgout** [comment]
I don't think that attribute can be defined as a function
