### ISSUE TITLE
Broken Behavior class in 4.0.0

### ISSUE THREAD

**Issue by dilame** [marionettejs/backbone.marionette#3632]
### Description

 ```js
export const FooBehavior = Behavior.extend({
  onRender () {
   this.foo = 'bar'
  },
  onDestroy () {
    console.log(this.foo) // undefined
  }
})
```

### Expected behavior

I expect that onDestroy this.foo must be 'bar', not undefined.

### Environment

1. Marionette version: 4.0.0
2. Backbone version: 1.3.3
3. Additional build tools, etc: webpack

**Comment by paulfalgout** [comment]
Can't seem to reproduce the issue: https://jsfiddle.net/jrmq9e4u/

**Comment by paulfalgout** [comment]
If this problem can be reproduced we'll reopen this.
