### ISSUE TITLE
http://marionettejs.com/ is down

### ISSUE THREAD

**Issue by TerryCapan** [marionettejs/backbone.marionette#3633]
### Description

Getting ERR_CONNECTION_TIMED_OUT when trying to load the website.

**Comment by dilame** [comment]
+

**Comment by paulfalgout** [comment]
and it's up

**Comment by TerryCapan** [comment]
The docs link doesn't work.
https://marionettejs.com/docs/current

**Comment by paulfalgout** [comment]
perhaps that's DNS caching at your ISP or browser?  It appears to be ok

**Comment by TerryCapan** [comment]
Might have been. It's working for me now.
