### ISSUE TITLE
Do you need to manually call stopListening in a life cycle hook

### ISSUE THREAD

**Issue by NathanKleekamp** [marionettejs/backbone.marionette#3638]
### Description

I can't tell from the documentation, issues, and reading through the code if Marionette cleans up Backbone's `listenTo` automatically when a view is destroyed. Should I manually call `stopListening` in a life cycle hook if I want to remove the listener?

### Environment

1. Marionette version: 3.5.1
2. Backbone version: 1.3.3

**Comment by paulfalgout** [comment]
Views call `stopListening` on themselves when they are destroyed https://github.com/marionettejs/backbone.marionette/blob/master/src/mixins/view.js#L147
However that's only true for the things view is listening to.  If some other object is listening to the view, destroying the view will not prevent the listeners from occurring.
```js
const fooView = new Marionette.View();
const barView = new Marionette.View();
fooView.listenTo(barView, 'all', function() { console.log(arguments); });
barView.destroy(); // destroy events logged
barView.trigger('foo'); // foo event logged
```
