### ISSUE TITLE
Use Marionette in child windows

### ISSUE THREAD

**Issue by sebamarynissen** [marionettejs/backbone.marionette#3640]
I'm using Marionette in an Electron app, and I am using it to render modals. The  approach I currently have is something like this:

```js
let view = new ModalView();
let child = window.open('', 'name');
let region = new Region({
  el: child.document.body
});
region.show(view);
```

This seems to work correctly, however the "onAttach" method does not get triggered. This is because Marionette checks if the region is present in the DOM using this fragment:
```js
// In region.js
const shouldTriggerAttach = !view._isAttached && this.Dom.hasEl(document.documentElement, this.el) && !this._shouldDisableMonitoring();
```
shouldTriggerAttach evaluates to false because document.documentElement indeed does no contain the regions element because it resides in my child window's document!

As a potential workaround, I propose to solve this by replacing this line by
```js
let shouldTriggerAttach = !view._isAttached;
if (shouldTriggerAttach) {
  const root = this.el.getRootNode();
  shouldTriggerAttach = root instanceof Document && !this._shouldDisableMonitoring();
}
```
Perhaps the most elegant solution is to re-introduce the isNodeAttached method from Marionette v3.x and implement it like
```js
function isNodeAttached(el) {
  return el.getRootNode() instanceof Document;
}
```

If this would be considered a good solution, I'd be happy to file a pull request for this. In any case I guess it's useful to be able to use Marionette in a child window just like we would in the main window.

**EDIT**: I've done some tests and while ```let root = el.getRootNode()``` returns a document element, ```root instanceof Document``` evaluates to ```false``` in a child window, whereas it evaluates to ```true``` in the main window, so the approach above wouldn't work. Don't really understand why though.

**Comment by paulfalgout** [comment]
So we've seen this issue with iframes as well and I think a solution is warranted.  _however_ I don't think it's good to go around `hasEl`  (it would also be breaking to do so)

In fact it might make sense to add the `documentElement` to the DOM API so that the various lines end up being `this.Dom.hasEl(this.Dom.el, this.el)`.

Then it'd be `MyRegionOrView.setDomApi({ el: child.document.documentElement });` and all of the DOM related interactions are stored on the DOM API.  I think this is a good improvement..  it at least removes `document.documentElement` from being hardcoded in Mn code.

_However_ it's not a great solution, because then contextually you'll have to add the special dom api to every region and view used in the alternative documents... however since attachment is determined at instantiation for views, I don't really see a way around it.

**Comment by sebamarynissen** [comment]
Indeed, if we'd have to set the ```documentElement``` manually for each view or region, this would complicate things a lot if we'd use views both in child windows and non-child windows.

This is why I came up with the solution of querying the region's (or view's) element for its root node and then checking whether it's an instance of a ```Document``` which would work both in the child window and in the main window.

An alternative that doesn't go around ```hasEl``` and hence is "less breaking" is
```js
const shouldTriggerAttach = !view._isAttached && this.Dom.hasEl(this.Dom.getDocumentElement(this.el), this.el) && !this._shouldDisableMonitoring();

// In the Dom Api.
const DomApi = {
  getDocumentElement: function(el) {
    let root = el.getRootNode();
    return root instanceof Document ? root : document.documentElement;
  };
};
```
An even more harmless change I guess is
```js
const shouldTriggerAttach = !view._isAttached && this.Dom.hasEl(this.Dom.getDocumentElement(this.el), this.el) && !this._shouldDisableMonitoring();

// In the Dom Api.
const DomApi = {
  getDocumentElement: function(el) {
    return document.documentElement;
  };
};
```
This doesn't really solve the issue, but at least it allows us to override the "global" DomApi to be overridden and implement ```DomApi.getDocumentElement``` ourselves in the way that I explained above.

**Comment by paulfalgout** [comment]
One other complexity is that `getRootNode` is not compatible with any internet explorer or edge.. so what is an alternative that would work?

**Comment by sebamarynissen** [comment]
Ok, I didn't know that. I guess that this would work though:
```js
const DomApi = {
  getDocumentElement: function(el) {
    while (el.parentNode) {
      el = el.parentNode;
    }
    return el;
  }
};
```
Again, my second solution by simply providing
```js
const shouldTriggerAttach = !view._isAttached && this.Dom.hasEl(this.Dom.getDocumentElement(this.el), this.el) && !this._shouldDisableMonitoring();

// In the Dom Api.
const DomApi = {
  getDocumentElement: function(el) {
    return document.documentElement;
  };
};
```
doesn't use finding the root node, but there I could override ```getDocumentElement``` to use ```getRootNode()``` since i'm on electron.

**Comment by taburetkin** [comment]
maybe its possible to operate with element.isConnected to check if its connected or not ?
https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected

**Comment by sebamarynissen** [comment]
Doesn't seem to be supported on IE & Edge unfortunately...

**Comment by taburetkin** [comment]
well, i think its still possible use it
with some kind of fallback
take a look, please
debug view for IE and edge
https://s.codepen.io/dimatabu/debug/BGporW/XBAGRZEWZeOr

and just code pen
https://codepen.io/dimatabu/pen/BGporW?editors=0010

the difference between chrome and ie/edge is 1ms for 10000 iteration for node with 100 parent nodes

and there is also `ownerDocument` property on the node
its not useful in case of checking is element attached or not but it present even in ie and you can check in which context this el is created, maybe it can helps you too

**Comment by taburetkin** [comment]
@sebamarynissen maybe you are right about integration

ps
if you don't mind i will ping you about electron in some far future when it were time to convert my browser mn application to electron :))

**Comment by taburetkin** [comment]
@paulfalgout 
i think DomApi should have own public method `isAttached` and i think it should not use `hasEl` under the hood
```js
setElement(){
   //at the moment
   this._isAttached = this.Dom.hasEl(document.documentElement, this.el);
  //should be
   this._isAttached = this.Dom.isAttached(this.el);
}
```
what do you think?

**Comment by sebamarynissen** [comment]
I fully agree, and this would be the most elegant solution, *however* as @paulfalgout mentioned, this would introduce a breaking change, albeit a minor one.

**Comment by paulfalgout** [comment]
I think the suggestion:
```js
// In the Dom Api.
const DomApi = {
  getDocumentElement: function(el) {
    return document.documentElement;
  };
};
```
is probably the best bet.  It's non-breaking.. almost no perf hit and supports everything.  Solutions for other documents, which seem like a rare case can have a solution catered to the environments supported and is easy to implement.  We'll just need to document the use case.

The hack you worked out is actually pretty reasonable.  Not ideal, but pretty good.

**Comment by taburetkin** [comment]
@paulfalgout 
given el may be from another document and in that case `document.documentElement` will not be document of el

i think it should be
```js
  getDocumentElement: function(el) {
    return el.ownerDocument.documentElement;
  };
```
isn't it?

**Comment by paulfalgout** [comment]
Seems reasonable. Does anyone know why mdn has a ? for safari? https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument

**Comment by paulfalgout** [comment]
Essentially if there is a perf free cross-browser solution we should try it.  But even the documentElement provides a way for a cheap override if needed.

**Comment by taburetkin** [comment]
regardles to this https://quirksmode.org/dom/core/
only ie5 out of the boat

**Comment by paulfalgout** [comment]
While looking into this I've discovered a bug where if the region has a view currently replaced, an incoming view won't get attach events because it checks if the region el (which is swapped out) is currently in the dom, and since it isn't it won't trigger attach.
