### ISSUE TITLE
_renderChildren() is called when remove a child model.

### ISSUE THREAD

**Issue by dzhhh** [marionettejs/backbone.marionette#3646]
### Description

 1. I am working with a great collectionView, that about 10000 childViews in it. But when I destroy some of those childViews, a bad performance produced. Then I check the performance bottleneck of my project. It is because that _onCollectionUpdate() in CollectionView calls the sort() method, then the sort() method calls the filter() method, then the filter() method calls the _renderChildren() method. _renderChildren() method renders all my 10000 childViews, which costs a lot of time. 
 2. When destroy children, not call _renderChildren() method.
 3. As _addedViews, make _removedViews as collectionView attribute in _onCollectionUpdate method, then check _removedViews to judge whether render children or not.

### Expected behavior

Not render all children when remove just one child model.

### Actual behavior

Render all children when remove child model, which costs lont time.

### Environment

1. Marionette version: 4.0.0
2. Backbone version: 1.3.3
3. Additional build tools, etc: webpack

**Comment by paulfalgout** [comment]
It is quite possible that removing a view in many use cases could require either a resort or a refilter.  So in this case I tend to lean towards consistency of behavior on update.  FWIW `_renderChildren` is incorrectly named.. children will only ever be rendered by the collectionview one time, but they'll be re-attached (sort of)  Is `_renderChildren` specifically the bottleneck or is the sort and/or filter?

In this case, I suspect the best way to handle this might be to `myCollectionView.stopListening(myCollectionView.collection, 'update');` and manually handle the updates using `removeChildView` but it depends a lot on your specific use cases.  10k+ collections may require extra effort for optimal performance.  Also if your `collection` never sorts and you're not doing any particular sorting on the view, you might want to consider `viewComparator: false`
