### ISSUE TITLE
Feature Request: Adding Style property

### ISSUE THREAD

**Issue by closebang** [marionettejs/backbone.marionette#3648]
### Idea

Adding a Styles Property for Modular CSS to Marionette.View

### Motivation

When you using Modular CSS, it would be nice to just add a style property, which add the styles automatically to the view as a object, instead of calling TemplateContext and adding it to it.

Instant of:
```
import styles from './styles.ns.css';
import template form './handlebars.tempalte';

export default Mn.View.extend({
  template,

  templateContext: {
    s: styles,
  },
}

```

We would just need to do:
```
import styles from './styles.ns.css';
import template form './handlebars.tempalte';

export default Mn.View.extend({
  template,
  styles,
}

```

**Comment by paulfalgout** [comment]
This seems to be pretty specific to a particular use case.

Perhaps you could do something like:
```js
const originalContext = View.prototype.mixinTemplateContext;

_.extend(View.prototype., {
  mixinTemplateContext(serializedData) {
    const styles = _.result(this, 'styles');
    return originalContext.call(this, _.extend({ styles }, serializedData));
  }
});
```

**Comment by closebang** [comment]
Hey @paulfalgout,
thanks for this advise :)

I just thought, that there is maybe a common need, by seeing for example, that the css-loader
has from stand 18.01.2019 weekly around 5million download, the chance is high that a lot of people maybe use it and would like to avoid to manipulate the core of marionette.
