### ISSUE TITLE
Upgrade to backbone 1.4

### ISSUE THREAD

**Issue by jaapz** [marionettejs/backbone.marionette#3657]
[Backbone 1.4 has been released!](https://github.com/jashkenas/backbone/issues/4028#issuecomment-465259194) Should marionette just work with this new version? Do we need a new marionette release? I see that the package.json pins the version to  ~1.3.3, and I guess this means 1.4 is not yet supported?

**Comment by Borming** [comment]
Marionette should work out of the box with 1.4, it works for us.

**Comment by paulfalgout** [comment]
Marionette has backbone at a peer dependency, so 1.4.0 will work, however npm/yarn will give a peer dependency warning at install.  As backbone has previously had breaking changes in minor updates, we'll probably keep it this way until things are ironed out or are clearly non-breaking.  That said, other than the warning there's no reason I can see why using 1.4 wouldn't work now.  At some point we'll want to update the peer dependency to include 1.4, but not increase it to remove previous versions.

**Comment by jaapz** [comment]
Ok, thanks! I'll update the dependency on my side then and see if it breaks in any unexpected ways.

**Comment by noobiek** [comment]
Hi,

I actually had a problem with this. When I did reinstall of all modules in project, BB 1.4 got installed (yes, i reinstalled without lock file), so Babysitter installed 1.3.3 as a peer dependency, which resulted in having two Backbones 1.3.3 and 1.4 - in some webpack modules it was 1.4 and in others 1.3.3.

So I had to force the 1.3.3 version on BB back and then reinstall Babysitter. So, would be nice to have dep version upped.

Thanks for the tools, anyway!

**Comment by blikblum** [comment]
From where babysitter is coming? It was removed long time ago

**Comment by noobiek** [comment]
Hi,
Sorry for the confusion. I use the separate Babysitter module from npm.
So yeah, I don't use Marionette. I use Bb, Bs and Radio.
Perhaps I should've posted this to the Babysitter repo, but I found this issue and didn't wan't to duplicate. Sorry again.
