### ISSUE TITLE
Browser support clarification needed

### ISSUE THREAD

**Issue by oliverne** [marionettejs/backbone.marionette#3658]
I sometime use Backbone for supporting old IEs (below 11) because of my company customers.
So I'm wondering that the Marionette's browser support is not different from Backbone's.
I saw the test coverage chart (on IE 11) in this repo. and the jQuery as the Marionette's dependency is still in 1.x.
and I know the Marionette has been updating for becoming modern framework.

So clarification of the browser support, especially for old IE would be great for the Backbone users.

**Comment by paulfalgout** [comment]
Marionette is only actively supporting and maintaining the browsers run in the tests.. however I _think_, particularly if you are open to a polyfill or two, both Marionette and Backbone would work back to IE7, but certainly IE9+.

**Comment by oliverne** [comment]
Great! Thank you.
