### ISSUE TITLE
CollectionView does not seem to properly extend View

### ISSUE THREAD

**Issue by amegahed** [marionettejs/backbone.marionette#3693]
### Description

The documentation in the v3 to v4 upgrade guide states "Most features of CompositeView were added to CollectionView and in common cases a class rename is enough. "  However, CollectionView does appear to support the region oriented View methods (i.e. showChildView etc.) like the View or CompositeView.
https://marionettejs.com/docs/master/upgrade-v3-v4.html 

Inspecting the source code, the CollectionView does not contain the RegionsMixin like the View does:
1903.    _.extend(View.prototype, ViewMixin, RegionsMixin);
2810.     _.extend(CollectionView.prototype, ViewMixin);

This problem can be remedied by adding the RegionsMixin to line 2810 above and adding a call to _initRegions in the CollectionView constructor.
2081.     this._initRegions();

Once this is done, we can call the region oriented methods (showChildView etc.) from a CollectionView.   This seems like a trivial change - is there any reason not to do this?

### Environment

1. Marionette version v4.1.2

**Comment by paulfalgout** [comment]
`CompositeView` did not support regions.

The pre-4.0 view class structure was
`BaseView` -> `View`
`BaseView` -> `CollectionView` - `CompositeView`
where `BaseView` didn't do much.  Having the common parent of `BaseView` was a not good. 

What I mean by putting a collectionview inside of a view is not changing the hierarchy. rather:
`myView.showChildView(myCollectionView);`
That will produce the outcome without needing to add all of the region functionality to `CollectionView` which would come with a whole host of side effects.
