### ISSUE TITLE
Official docs are gone

### ISSUE THREAD

**Issue by atl-mk** [marionettejs/backbone.marionette#3710]
Hey, all the official documentation is no longer on the website in the description (https://marionettejs.com/)

Currently looks like:
![image](https://github.com/marionettejs/backbone.marionette/assets/47995834/0f08e137-4bed-4660-afef-8551e1bd8163)

Here's what it used to look like: https://web.archive.org/web/20230730043216/https://marionettejs.com/

**Comment by paulfalgout** [comment]
ayep.. looking into this

**Comment by nmallare** [comment]
> ayep.. looking into this

Any update on this?

**Comment by paulfalgout** [comment]
In the meantime https://devdocs.io/marionette~4/

**Comment by nmallare** [comment]
> @jamiebuilds 👀

LMK if I need to send you $15 for domain renewal :)

**Comment by crantila** [comment]
As I wrote in the [website repo issue 545](https://github.com/marionettejs/marionettejs.com/issues/545), I posted two resources to help people who are still using MarionetteJS and need to read the docs:

1. There's a copy of the "gh-pages" branch of this repository (with some changes) available at my [marionette_website repository](https://github.com/crantila/marionette_website), which you can clone and view on your own computer.
2. Those files have been posted to https://marionettejs.netlify.app so you can view them online too.

Nothing wrong with the devdocs.io site, but my organization has long been thinking of making internal copies of documentation and repositories. This just seemed like the time to actually make a move.

**Comment by tni711** [comment]
> As I wrote in the [website repo issue 545](https://github.com/marionettejs/marionettejs.com/issues/545), I posted two resources to help people who are still using MarionetteJS and need to read the docs:
> 
>     1. There's a copy of the "gh-pages" branch of this repository (with some changes) available at my [marionette_website repository](https://github.com/crantila/marionette_website), which you can clone and view on your own computer.
> 
>     2. Those files have been posted to https://marionettejs.netlify.app so you can view them online too.
> 
> 
> Nothing wrong with the devdocs.io site, but my organization has long been thinking of making internal copies of documentation and repositories. This just seemed like the time to actually make a move.

Thank you! I still use Marionette for active development. A local copy of the documentation helps a  lot!

**Comment by paulfalgout** [comment]
Assuming I can get @jamiebuilds to transfer or reinstate marionettejs.com I'll probably end up redirecting it, but I've moved the site to http://marionette.js.org/

**Comment by paulfalgout** [comment]
I got control of the domain.  I'll keep it going for the indefinite future

**Comment by atl-mk** [comment]
Thanks @paulfalgout, much appreciated !!
