### ISSUE TITLE
emptyViewOptions

### ISSUE THREAD

**Issue by sinel** [marionettejs/backbone.marionette#416]
If I understand correctly, we cannot pass any options to the empty view for a collection. Hence, it is not possible to have a single view with a generic template that could be used for multiple collections, instead we have to have many empty views. Instead, as a simple example, I would like to use one view with a message option, and change this message based on the collection, through a property similar to itemViewOptions.

Albeit somewhat minor, would this be something you would consider adding to prevent clutter and improve maintenance? Or am I missing something?

And thanks for the great framework. I've recently switched to using it and it's been extremely useful in getting my backbone code back in control.

**Comment by joe4mg** [comment]
Just in case someone stumbles upon this as I did, you will need to change 'itemViewOptions' to 'childViewOptions' in the parent composite/collection view to make the above code work (since v2.0).

**Comment by fonji** [comment]
@joe4mg actually, as [emptyViewOptions](http://marionettejs.com/docs/v2.4.1/marionette.collectionview.html#collectionviews-emptyviewoptions) now exists, you'd better update (if you can!) and use it.

**Comment by joe4mg** [comment]
Thanks @fonji - somehow missed that
