### ISSUE TITLE
addInitializer not doing anything

### ISSUE THREAD

**Issue by kojilab** [marionettejs/backbone.marionette#519]
Hi,

I'm assuming I'm doing something wrong but my addInitializer calls are not getting fired apparently.

I'm using underscore.js 1.4.4, backbone.js 0.9.10 and marionette bundled 1.0.0-rc4 all hosted on CDN.js

This is my simple code

var App = new Backbone.Marionette.Application({});

App.addInitializer(function(options) {
  alert('yo')
});

**Comment by VarshaShinde-Edmodo** [comment]
y
