### ISSUE TITLE
Model removed from collection on destroy() despite error from the server

### ISSUE THREAD

**Issue by rodryquintero** [marionettejs/backbone.marionette#596]
I have created a CollectionView and a corresponding ItemView, very much like the ones seen on the examples and documentation.

Everything works as expected except when I try to destroy a model and the operation on the server fails.

I need Marionette to "not" remove the model from the Collection when this happens. I have confirmed that the model detects there has been an error when syncing the server because the "error" function triggers.

Can someone tell me if this is the expected behaviour of the CollectionView or if there is an specific patter to implement this.

If you want to see some code, here is the definition of the CollectionView and ItemView:

``` javascript
window.LOINCDB.Views.LocalMapACNTabItem = Backbone.Marionette.ItemView.extend({
 template: "#tmpl-dia-localmap-acn-item",
  tagName: "li",
  events:
  {
     "click button.close":"del"
  },

  del: function(e)
{
var self = this;
var ok = confirm("Are you sure you want to delete this item?");

 if (ok)
  {
       this.model.destroy({
       success: function(model,response)
            {
                console.log("success");
            },
            error: function(model,response)
            {
                               // this triggers, but the model is always removed from the collection.
                console.log("error");
                console.log(self);
            }
        });
    }
  }
});
   window.LOINCDB.Views.LocalMapACNTabItems = Backbone.Marionette.CollectionView.extend({
    tagName: "ul",
    itemView: LOINCDB.Views.LocalMapACNTabItem
  });
```

And here is an image of the console.log
![image](https://f.cloud.github.com/assets/1271370/462922/a4e08746-b4f5-11e2-97f7-3e78d916e12c.png)

Thanks in advance.

**Comment by rally25rs** [comment]
Is there a way to set `{wait:true}` one place globally for all destroy calls for all models (preferably without overriding Backbone.sync)? IMO, `true` should really be the default.

**Comment by rally25rs** [comment]
For anyone who stumbles across this later and wants to make `wait: true` the default option for a Model destroy(), you can override the existing function like this:

(tested in Backbone v1)

```
  const baseDestroy = Backbone.Model.prototype.destroy;
  Backbone.Model.prototype.destroy = function(options) {
    options = _.extend((options || {}), {
      wait: true
    });
    return baseDestroy.call(this, options);
  };
```
