### ISSUE TITLE
layout.regionType appears to be ignored

### ISSUE THREAD

**Issue by yanfali** [marionettejs/backbone.marionette#674]
I've been trying out layout today. Very cool. However I wanted to override open so I created a custom region with a new open and set this object ref on the layout when I defined it. When I set regionType on the Layout as described in the docs, it never gets picked up.

```
var CustomRegion = Backbone.Marionette.Region.extend({
    open: function(view) {
        this.$el.replaceWith(view.el);
    }
});
return Backbone.Marionette.Layout.extend({
    template: '#mytemplate',
    regionType: CustomRegion,
    regions: {
        usage: '.usage'
    }
});
```

When I return  a structure from regions which contains:

```
return Backbone.Marionette.Layout.extend({
    template: '#mytemplate',
    regions: {
        usage: {
            selector: '.usage',
            regionType: CustomRegion
        }
    }
});
```

It works perfectly. I looked briefly through the code, and I can't see where regionType on layout gets used. Is the documentation wrong or am I just doing something wrong?

**Comment by tamarmot** [comment]
Once again regionType is being ignored, is it supposed to be used?
