### ISSUE TITLE
404 on backbone.marionette.map

### ISSUE THREAD

**Issue by chaitanyav** [marionettejs/backbone.marionette#716]
I am getting 404 not found on backbone.marionette.map when using backbone.marionette. Any suggestions to work around this issue?.

**Comment by LiamKlyneker** [comment]
well, I have this same issue, and I don't know if anyone else too, but I did have the backbone.js NO MINIFIED and the marionette.js MINIFIED in my html,  then the problem happend, but when I change the marionette NO MINIFIED as I have my backbonejs all went well... I wrote this just for help someone in my same situation...

pds. sorry for my bad english
