### ISSUE TITLE
UI hash + Layout

### ISSUE THREAD

**Issue by moimikey** [marionettejs/backbone.marionette#725]
This has been discussed throughout the past year but in several contexts. Might be somewhat similar to #466 

I have a scenario where I don't care for any sub-view instances on the layout, but just the layout itself and the UI hash:

```
@MM.module 'Views', (Views, App, Backbone, Marionette, $, _) ->

  class Views.MediaNavigation extends Marionette.Layout
```

[...]

```
    ui:
      globalBar: '#global-bar'
```

`#global-bar` is not declared in a template, but literally in the page source:

```
  <body>
    <div id="container"></div>
    <div id='global-bar' class='inactive'>
        <a href="#" target="_blank">Terms of Use</a>
        <a href="#" target="_blank">Privacy Policy</a>
    </div>
```

obviously i'd assume then I'd simply be able to do the following on `show`:

```
onShow: ->
  @ui.globalBar.removeClass 'inactive'
```

nope. doesn't work... the context is `undefined`

I added logging to the layout, `onShow`, `onDomRefresh`, and `onRender`. Also in marionette v1.0.4:

```
  bindUIElements: function(){
    console.log('bindUIElements context: ', this);
```

Results:

```
bindUIElements context:  
MediaNavigation {_firstRender: false, regionManager: Marionette.RegionManager.Marionette.Controller.extend.constructor, _listeners: Object, regions: Object, searchRegion: Marionette.Region…}
 backbone.marionette.js:1338
onRender media-navigation.js:55
onDomRefresh media-navigation.js:50
onShow 
```

so bindUIElements() fired before `onRender`, `onDomRefresh`, and `onShow`

Is this normal? Do I need to explicitly call `@bindUIElements()` to remedy this?

---

lemme know if you're anal about having these kind of tickets opened and I can move it elsewhere.

**Comment by bretcj7** [comment]
What was the answer to this question @moimikey ?  We are having a similar issue trying to access the ui hash element off the layout and it being empty.
