### ISSUE TITLE
collectionview get index from item view

### ISSUE THREAD

**Issue by Incubatio** [marionettejs/backbone.marionette#787]
Is there a way to get the index of an item that has been rendered by the item view ?

Right now I'm overriding showCollection method of my CollectionView to add it as a param:

``` coffee
    showCollection: () ->
      for index, item of @collection.models
        item.attributes.theIndex = index
        @addItemView(item, @itemView, index)
```

By checking the code of marionetteJS it seems that index is just not used (but maybe I missed something)

``` js
    appendHtml: function(collectionView, itemView, index){
      collectionView.$el.append(itemView.el);
    },
```

If there is actually no way to get the index property, couldn't we add it in the view using some private naming like <%= _index %>

**Comment by vanquang9387** [comment]
@samccone 
```
CollectionView = Backbone.Marionette.CollectionView({
  itemViewOptions: function(model, index) {
    // do some calculations based on the model
    return {
      foo: "bar",
      itemIndex: index
    }
  }
});
```
But how about adding or removing items?

**Comment by ahumphreys87** [comment]
if an ItemView is rendered by a CollectionView it will be assigned a `_index` property, you could then expose this to your templates with `templateHelpers`.

NOTE: this will only work if the view is rendered by a CollectionView and it will mean you are using an 'internal' property that could be changed in a future release.
