### ISSUE TITLE
collectionView need a emptyViewContainer to render empty view in a different placeholder

### ISSUE THREAD

**Issue by fxxkscript** [marionettejs/backbone.marionette#828]
I have a table to render, if collection's length of table is zero, i don not want to render empty view in `<tr>` node.

So i want to render empty view in a different placeholder.

is there a different way to accomplish this task?

if not, i will add some code to achieve this task.

**Comment by granmoe** [comment]
I ran into this problem and ended up doing the following (hacky) solution:

```
getEmptyView: function() {
  this.$childViewContainer = this.$el // (or whatever you want)
  return yourEmptyView;
}
```

**Comment by khani3s** [comment]
IMHO: CompositeView are useless except for tables. 
This scenario happened a lot: You want add another 'region' to the CompositeView an then you change the CompositeView to a LayoutView and then you move the child code to a CollectionView.

@tonyhb checking the collection length on 'parent' its a hack to solve the problem.

PS: The CompositeView example on docs its a table.

**Comment by paulfalgout** [comment]
@khani3s as such `CompositeView` is deprecated and will likely be removed in `v4`  In `v3`+ you'll be able to replace the el of a region, solving the main use-case for needing a `CompositeView` over a `LayoutView` + `CollectionView`
