### ISSUE TITLE
Composite/Collection Views don't reflect the Collection's order

### ISSUE THREAD

**Issue by husa** [marionettejs/backbone.marionette#896]
If you have a Collection with comparator, or you are manually sorting collection, which has been already rendered, when new items are added(comparator) or manual sort view isn't "re-rendered".
In my case(Composite View), I just overrided 'appendHtml' method from:

```
appendHtml: function(compositeView, itemView, index){
    if (compositeView.isBuffering) {
      compositeView.elBuffer.appendChild(itemView.el);
    }
    else {
      // If we've already rendered the main collection, just
      // append the new items directly into the element.
      var $container = this.getItemViewContainer(compositeView);
      $container.append(itemView.el);
    }
  },
```

where we do have "index" passed but we're not using it, to:

```
appendHtml : function(compositeView, itemView, index) {
            var $container, $nextEl;

            if (compositeView.isBuffering) {
                compositeView.elBuffer.appendChild(itemView.el);
            } else {
                $container = this.getItemViewContainer(compositeView);
                $nextEl    = $container.children().eq(index);

                if ($nextEl.length) {
                    itemView.$el.insertBefore($nextEl);
                } else {
                    $container.append(itemView.el);
                }
            }
        },
```

Of course, I've seen the comment

```
  // Override this method to
  // provide custom logic of how the child item view instances have their
  // HTML appended to the composite view instance.
```

but I think that a similar solution should be included in core

**Comment by cordoval** [comment]
hmm wiki is not up, having problems finding good resources for sort collections

**Comment by cmaher** [comment]
@cordoval: CollectionView defaults to rendering items in their current order, and it additionally supports a custom comparator: http://marionettejs.com/docs/v2.4.1/marionette.collectionview.html#collectionviews-viewcomparator

**Comment by cordoval** [comment]
I have tried that but it does not seem to work, hmm perhaps because i am overriding the constructor. hmmm
