### ISSUE TITLE
Region was added a "display:block" style after show() called.

### ISSUE THREAD

**Issue by JoeHetfield** [marionettejs/backbone.marionette#906]
I got a Layout view and there are several regions on it, like this one:

```
<div class="my-region"></div>
```

I showed some thing in it:

```
myLayout.myRegion.show(anItemView);
```

after inner view was rendered I found the region tag at the dom tree was added an style attribute: "display:block":

```
 <div class="my-region" style="display:block"></div>
```

this messed up the style of the inner view. Is this the behavior of marionette? How can I stop it?

**Comment by YazanRawashdeh** [comment]
Indeed it's Marionette that does this behavior , and it's doing it to make sure the element is shown.
I just did this :
this.getRegion("myRegion").$el.removeAttr("style"); :+1:
