### ISSUE TITLE
Discuss - Removing jQuery as a hard dependency

### ISSUE THREAD

**Issue by jamesplease** [marionettejs/backbone.marionette#980]
This is a place to discuss removing jQuery as a hard dependency. Inspired by a comment @cobbweb made somewhere about doing this for v2.
#### List of jQuery features used by Marionette
- `$.Deferred`
  - _Possible replacement: [ES6-promise polyfill](https://github.com/jakearchibald/es6-promise)_
- `$(selector)`
  - _Possible replacement: Vanilla js_
- `$el.html()`
  - _Possible replacement: Vanilla js_
- `$el.empty()`
  - _Possible replacement: Vanilla js_
- `$el.append()`
  - _Possible replacement: vanilla js_
#### Locations of jQuery in the source

_Will be updated with exact links soon_
- Marionette.Callbacks - `$.Deferred`
- Marionette.Regions - `$.empty()`
- Marionette.TemplateCache - `$.html()`
- BindUIElements - `$(selector)`
  - _Possible replacement: Just return the el if $ is undefined_
- Marionette.ItemView - `$.html()`
- Marionette.CollectionView - `$.append()`
- Marionette.CompositeView - `$.html()` `$.append()`

Seems doable if we wanted to go down this path. I have no opinion on the matter; I'm just fine leaving jQuery the way it is.

**Comment by paulfalgout** [comment]
@marionettejs/marionette-core do we need to readdress this?

**Comment by samccone** [comment]
x-ref
https://github.com/marionettejs/backbone.marionette/issues/2300
